(()=>{
'use strict';
const active=()=>!!window.schoolHubPhase12?.isProduction?.();let ready=false,busy=false;
window.schoolHubServerPersistence.register(['certificates','certificateRequests','certificateCounters']);
const request=(path='',options)=>schoolHubTransport.server.request('/api/v1/certificates'+path,options),permission=name=>{const user=window.__schoolHubPhase7?.getState?.().serverUser;return !!user&&(user.role==='Super Admin'||(user.permissions||[]).includes(name));};
const priorCan=window.can;window.can=function(tab,action='view'){if(!active()||tab!=='certificates')return priorCan.apply(this,arguments);return permission('certificates:'+({add:'create'}[action]||action));};
function paint(){renderCertWorkspace();renderCertHistory();}
async function load(){ready=false;state.certificates=[];state.certificateRequests=[];paint();const data=await request();state.certificates=data.certificates||[];state.certificateRequests=data.requests||[];if(data.students?.length)state.students=data.students;if(data.years?.length)state.academicYears=data.years.map(y=>({...y,status:y.active?'Active':'Archived'}));ready=true;paint();return data;}
async function refreshWorkflows(){if(window.schoolHubWorkflowServer&&permission('workflows:view'))await window.schoolHubWorkflowServer.loadConfig();}
async function run(work,after){if(!ready)return alert('Wait for Certificates to finish loading.');if(busy)return;busy=true;try{const result=await work();await load();await refreshWorkflows();if(after)after(result);return result;}catch(e){alert(e.message);await load().catch(()=>{});}finally{busy=false;}}
function template(type){return typeof f1CertTemplate==='function'?f1CertTemplate(type):null;}
function printRecord(record){const school=window.schoolHubSchoolIdentity(),tokens={...record.snapshot,...record.issueSpecific,academicYear:record.academicYear,issueDate:record.issueDate,certificateNumber:record.certificateNumber,schoolName:school.school||'',schoolAddress:school.address||'',schoolPhone:school.phone||''};printWindow(renderIssuedCertificate(record,tokens));}
function replace(name,fn){const old=window[name];window[name]=function(){return active()?fn.apply(this,arguments):old.apply(this,arguments);};}
replace('issueCertificate',async function(){if(!permission('certificates:create'))return alert('You do not have permission to issue certificates.');const studentId=$('certStudent')?.value,certificateType=$('certType')?.value||'Bonafide',academicYear=$('certYear')?.value||getActiveAcademicYear().name;if(!studentId)return alert('Select a student.');const selected=template(certificateType),payload={studentId,certificateType,academicYear,issueSpecific:collectCertIssueSpecific(certificateType),templateId:selected?.id||'',templateVersion:selected?.version||0,templateSnapshot:selected?f1clone(selected):null};await run(async()=>{const created=await request('/requests',{method:'POST',body:payload,mutation:true}),step=(created.instance.stepsSnapshot||[]).find(s=>s.id===created.instance.currentStepId);if(step?.type==='SYSTEM_ACTION'&&step.systemActionId==='certificate.issue')return request('/requests/'+encodeURIComponent(created.request.id)+'/decision',{method:'POST',body:{version:created.request.version,decision:'Approved',note:''},mutation:true});return created;},result=>{if(result.certificate){printRecord(result.certificate);showToast('Certificate '+result.certificate.certificateNumber+' issued.');}else showToast('Certificate request submitted to the configured approval workflow.');showCertTab('history');});});
replace('advanceCertificateWorkflowInstance',async function(id,decision,note){const row=state.certificateRequests.find(x=>x.id===id);if(!row)return alert('Certificate request not found.');await run(()=>request('/requests/'+encodeURIComponent(id)+'/decision',{method:'POST',body:{version:row.version,decision,note:note||''},mutation:true}),result=>{if(result.certificate){printRecord(result.certificate);showToast('Certificate '+result.certificate.certificateNumber+' issued.');}renderWorkflowTasks();});});
replace('reprintCertificate',async function(id){const row=state.certificates.find(x=>x.id===id);if(!row||!permission('certificates:print'))return alert('You do not have permission to print certificates.');await run(()=>request('/'+encodeURIComponent(id)+'/reprint',{method:'POST',body:{version:row.version},mutation:true}),result=>printRecord(result));});
const priorShow=window.showTab;window.showTab=function(tab){const result=priorShow.apply(this,arguments);if(active()&&tab==='certificates'){$(tab)?.querySelectorAll('.phase7-local-only').forEach(x=>x.remove());Promise.all([load(),refreshWorkflows()]).catch(e=>{if($('certHistRows'))$('certHistRows').textContent=e.message;});}return result;};
window.schoolHubCertificatesServer=Object.freeze({active,handles:tab=>tab==='certificates',load});if(active()){state.certificates=[];state.certificateRequests=[];state.certificateCounters={};}
})();
