(()=>{
'use strict';
const active=()=>!!window.schoolHubPhase12?.isProduction?.();let ready=false,busy=false;
window.schoolHubServerPersistence.register(['fees','feeStructures','feeAssignments','feeCorrectionRequests']);
const request=(path='',options)=>schoolHubTransport.server.request('/api/v1/fees'+path,options);
const permission=name=>{const user=window.__schoolHubPhase7?.getState?.().serverUser;return !!user&&(user.role==='Super Admin'||(user.permissions||[]).includes(name));};
const priorCan=window.can;window.can=function(tab,action='view'){if(!active()||tab!=='fees')return priorCan.apply(this,arguments);return permission('fees:'+({add:'create',edit:'update'}[action]||action));};
function paint(){renderFeeStructures();renderFeeAssignments();renderFees();renderFeeLedger();populateFeeStructureSelects();}
async function load(){ready=false;state.fees=[];state.feeStructures=[];state.feeAssignments=[];state.feeCorrectionRequests=[];paint();const data=await request();state.fees=data.payments||[];state.feeStructures=data.structures||[];state.feeAssignments=data.assignments||[];state.feeCorrectionRequests=data.corrections||[];if(Array.isArray(data.students)&&data.students.length)state.students=data.students;ready=true;paint();return data;}
function replace(name,fn){const old=window[name];window[name]=function(){return active()?fn.apply(this,arguments):old.apply(this,arguments);};}
async function run(work,after){if(!ready)return alert('Wait for Fees to finish loading.');if(busy)return;busy=true;try{const result=await work();await load();if(window.schoolHubWorkflowServer&&permission('workflows:view'))await window.schoolHubWorkflowServer.loadConfig();if(after)after(result);return result;}catch(e){alert(e.message);await load().catch(()=>{});}finally{busy=false;}}
function paymentFromForm(){const studentVal=($('feeStudent').value||'').trim(),student=studentVal.split(' — ')[0],components=typeof collectFeeComponentsFromUI==='function'?collectFeeComponentsFromUI():[],amount=components.length?components.reduce((n,c)=>n+Number(c.paidAmount||0),0):Number($('feeAmount').value);return{receipt:($('feeReceipt').value||'').trim(),date:$('feeDate').value||today,student,head:components.length?'Multiple Fee Components':$('feeHead').value,mode:$('feeMode').value,amount,components:components.length?components:[{component:$('feeHead').value,applicableAmount:amount,paidAmount:amount}]};}
replace('saveFee',async function(){if(!permission('fees:create'))return alert('You do not have permission to record payments.');const payment=paymentFromForm();if(!state.students.some(s=>s.admission===payment.student))return alert('Select a valid student.');if(!Number.isFinite(payment.amount)||payment.amount<=0)return alert('Amount must be greater than zero.');if(payment.date>today&&!confirm('This payment date is in the future. Record it anyway?'))return;await run(()=>request('/payments',{method:'POST',body:{payment,mutationKey:crypto.randomUUID()},mutation:true}),row=>{showToast('Payment saved — receipt '+row.receipt+'.');$('feeReceipt').value='';$('feeAmount').value='';if(typeof f1FeeComponents!=='undefined'){f1FeeComponents.length=0;renderFeeComponentRows();}});});
replace('saveFeeStructure',async function(){const id=$('fsId').value,old=state.feeStructures.find(x=>x.id===id),components=[...document.querySelectorAll('.fs-component-row')].map(row=>({name:(row.querySelector('.fsCompName').value||'').trim(),amount:Number(row.querySelector('.fsCompAmount').value)||0})).filter(c=>c.name),structure={name:($('fsName').value||'').trim(),academicYear:($('fsYear').value||'').trim(),applicableClass:$('fsClass').value,applicableSection:($('fsSection').value||'').trim(),components,dueDate:$('fsDueDate').value,status:$('fsStatus').value};if(!structure.name||!structure.applicableClass||!components.length)return alert('Enter a name, class and at least one fee component.');await run(()=>request('/structures'+(id?'/'+encodeURIComponent(id):''),{method:id?'PATCH':'POST',body:id?{structure,version:old.version}:structure,mutation:true}),()=>closeModal());});
replace('deleteFeeStructure',async function(id){const row=state.feeStructures.find(x=>x.id===id);if(!row||!confirm('Archive fee structure "'+row.name+'"? Its individual assignments will be removed; payments remain.'))return;await run(()=>request('/structures/'+encodeURIComponent(id)+'/remove',{method:'POST',body:{version:row.version},mutation:true}));});
replace('assignFeeStructureToStudent',async function(){const student=($('feeAssignStudent').value||'').trim().split(' — ')[0],feeStructureId=$('feeAssignStructure').value;if(!student||!feeStructureId)return alert('Select a student and fee structure.');await run(()=>request('/assignments',{method:'POST',body:{student,feeStructureId},mutation:true}));});
replace('removeFeeAssignment',async function(id){const row=state.feeAssignments.find(x=>x.id===id);if(!row||!confirm('Remove this individual fee assignment?'))return;await run(()=>request('/assignments/remove',{method:'POST',body:{student:row.student,feeStructureId:row.feeStructureId},mutation:true}));});
replace('deleteFee',async function(i){const row=state.fees[i];if(!row||!confirm('Void receipt "'+row.receipt+'"? It will remain in the audit trail and cannot be reused.'))return;await run(()=>request('/payments/'+encodeURIComponent(row.id)+'/remove',{method:'POST',body:{version:row.version},mutation:true}));});
replace('saveFeeEdit',async function(){const row=state.fees[Number($('feeEditIndex').value)];if(!row)return alert('Fee record not found.');const reason=($('feeEditReason').value||'').trim(),amount=Number($('feeEditAmount').value);if(!reason||!amount||amount<=0)return alert('Enter a valid amount and correction reason.');const payment={...row,receipt:($('feeEditReceipt').value||'').trim(),date:$('feeEditDate').value,head:($('feeEditHead').value||'').trim(),mode:$('feeEditMode').value,amount,components:[{component:($('feeEditHead').value||'').trim(),applicableAmount:amount,paidAmount:amount}]};for(const key of ['id','version'])delete payment[key];await run(()=>request('/payments/'+encodeURIComponent(row.id)+'/corrections',{method:'POST',body:{payment,version:row.version,reason},mutation:true}),()=>{closeModal();showToast('Correction request submitted to the configured workflow.');});});
replace('advanceFeeCorrectionWorkflowInstance',async function(id,decision,note){const row=state.feeCorrectionRequests.find(x=>x.id===id);if(!row)return alert('Correction request not found.');await run(()=>request('/corrections/'+encodeURIComponent(id)+'/decision',{method:'POST',body:{version:row.version,decision,note:note||''},mutation:true}),()=>renderWorkflowTasks());});
const priorShow=window.showTab;window.showTab=function(tab){const result=priorShow.apply(this,arguments);if(active()&&tab==='fees'){$(tab)?.querySelectorAll('.phase7-local-only').forEach(x=>x.remove());load().catch(e=>{if($('feeRows'))$('feeRows').textContent=e.message;});}return result;};
window.schoolHubFeesServer=Object.freeze({active,handles:tab=>tab==='fees',load});if(active()){state.fees=[];state.feeStructures=[];state.feeAssignments=[];state.feeCorrectionRequests=[];}
})();
