/* Personal list preferences. Deliberately independent of Workspace Manager and record writes. */
(function(){
'use strict';
const contexts=new Map(),snapshots=new WeakMap(),memory=new Map();
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults=()=>({version:1,columns:[],hidden:[],join:'all',conditions:[],sort:'',direction:'asc'});
function identity(){const s=window.__schoolHubPhase7?.getState();return s?.serverUser?.id&&s.mode!=='Local'?JSON.stringify([s.baseUrl,s.schoolSlug,s.serverUser.id]):null}
function storageKey(k){const id=identity();return id?'schoolhub_personal_view_v1:'+id+':'+k:null}
function read(k){const key=storageKey(k);if(!key)return defaults();try{const p=JSON.parse(localStorage.getItem(key)||'null');return p?.version===1?{...defaults(),...p,conditions:Array.isArray(p.conditions)?p.conditions.filter(c=>c&&typeof c.field==='string'&&typeof c.op==='string').slice(0,10):[],columns:Array.isArray(p.columns)?p.columns.filter(x=>typeof x==='string'):[],hidden:Array.isArray(p.hidden)?p.hidden.filter(x=>typeof x==='string'):[]}:defaults()}catch{return memory.get(key)||defaults()}}
function write(k,p){const key=storageKey(k);if(!key)throw Error('Sign in before saving a personal view.');localStorage.setItem(key,JSON.stringify(p));memory.set(key,p)}
const textOps=['contains','equals','notEquals','startsWith','endsWith','empty','notEmpty'],orderedOps=['equals','notEquals','greater','less','between','empty','notEmpty'];
function operators(f){return f.type==='number'||f.type==='date'?orderedOps:f.choices?['equals','notEquals','empty','notEmpty']:textOps}
const operatorLabels={contains:'Contains',equals:'Equals',notEquals:'Does not equal',startsWith:'Starts with',endsWith:'Ends with',empty:'Is empty',notEmpty:'Is not empty',greater:'After / greater than',less:'Before / less than',between:'Between (inclusive)'};
function matches(value,c,type){const empty=value==null||value===''||(Array.isArray(value)&&!value.length);if(c.op==='empty')return empty;if(c.op==='notEmpty')return !empty;if(empty)return c.op==='notEquals';if(Array.isArray(value))return c.op==='notEquals'?value.every(v=>matches(v,c,type)):value.some(v=>matches(v,c,type));const normalize=v=>type==='number'?Number(v):type==='date'?String(v).slice(0,10):String(v??'').toLocaleLowerCase(),v=normalize(value),a=normalize(c.value),b=normalize(c.to);switch(c.op){case'equals':return v===a;case'notEquals':return v!==a;case'contains':return String(v).includes(String(a));case'startsWith':return String(v).startsWith(String(a));case'endsWith':return String(v).endsWith(String(a));case'greater':return v>a;case'less':return v<a;case'between':return v>=a&&v<=b;default:return false}}
function catalog(k,m={}){
 const f=(key,label,type='text',get)=>({key,label,type,get:get||((r)=>r[key])});
 const pick=(key,label,list)=>({...f(key,label),choices:(list||[]).map(x=>({value:String(x.id??x.value),label:x.name??x.label??String(x.value)}))});
 const refs=m.refs||m,ref=(key,label,source)=>pick(key,label,refs[source]);
 let fields=[],columns=[];
 switch(k){
 case'students':fields=[f('name','Student'),f('admissionNumber','Admission'),ref('classId','Class','classes'),ref('sectionId','Section','sections'),f('fatherName','Guardian'),f('phone','Phone'),pick('status','Status',[{value:'Active'},{value:'Inactive',label:'Archived'},{value:'Alumni'}])];columns=['name','admissionNumber','classId','fatherName','phone','status','actions'];if(window.__schoolHubPhase7?.getState()?.serverUser?.role==='Teacher')fields=fields.filter(x=>!['fatherName','phone'].includes(x.key));break;
 case'teachers':fields=[f('name','Teacher / Staff'),f('employeeNumber','Employee ID'),f('role','Role'),f('subjectSnapshot','Subject'),f('phone','Phone'),f('email','Email'),pick('status','Status',[{value:'Active'},{value:'Inactive',label:'Archived'}])];columns=['name','employeeNumber','role','subjectSnapshot','phone','status','actions'];break;
 case'homework':fields=[f('assignedDate','Assigned Date','date'),ref('classId','Class','classes'),ref('sectionId','Section','sections'),ref('subjectId','Subject','subjects'),f('title','Homework'),f('dueDate','Due Date','date'),ref('teacherId','Teacher','teachers'),pick('status','Status',m.statuses),f('attachments','Attachments','number',x=>(x.attachments||[]).length)];columns=['assignedDate','classId','subjectId','title','dueDate','teacherId','status','attachments','actions'];break;
 case'teacherlog':fields=[f('date','Date','date'),ref('class','Class','classes'),ref('section','Section','sections'),ref('subject','Subject','subjects'),ref('period','Period','periods'),f('topic','Topic / Lesson Taught'),f('homeworkGiven','Homework Given'),ref('teacherId','Teacher','teachers')];columns=['date','class','subject','period','topic','homeworkGiven','teacherId','actions'];break;
 case'notices':fields=[f('date','Publish Date','date'),f('title','Title'),pick('audience','Audience',m.audiences),f('text','Message'),pick('status','Status',m.statuses)];columns=['date','title','audience','text','status','actions'];break;
 case'classes':fields=[f('name','Class'),f('sections','Sections','text',x=>(x.sections||[]).map(s=>s.name)),f('teachers','Class Teacher','text',x=>(x.assignments||[]).map(a=>m.teachers?.find(t=>t.id===a.teacherId)?.name||'')),f('studentCount','Students','number'),pick('status','Status',m.statuses)];columns=['name','sections','teachers','studentCount','status','actions'];break;
 case'leave':fields=[f('applicant','Applicant'),pick('type','Type',m.types),f('from','From','date'),f('to','To','date'),f('reason','Reason'),pick('status','Status',m.statuses)];columns=['applicant','type','from','to','reason','status','actions'];break;
 case'documents':fields=[f('name','Document Name'),pick('cat','Category',m.categories),pick('audiences','Audience',m.audiences),f('documentVersion','Version'),f('updatedAt','Updated On','date'),pick('status','Status',m.statuses)];columns=['name','cat','audiences','documentVersion','updatedAt','status','actions'];break;
 case'transport':fields=[f('route','Route'),pick('vehicle','Vehicle',m.vehicles),f('driver','Driver'),f('attendant','Attendant'),f('stops','Stops','number',x=>x.stopDetails?.length||String(x.stops||'').split(',').filter(Boolean).length),f('assigned','Assigned','number',x=>(m.assignments||[]).filter(a=>a.busId===x.id).length),f('monthlyFee','Fee (₹)','number'),pick('status','Status',m.statuses)];columns=['route','vehicle','driver','attendant','stops','assigned','monthlyFee','status','actions'];break;
 }
 // These two modules already honor screen-visible field metadata. Never undo that policy.
 if(['homework','teacherlog'].includes(k)&&m.definition){const visible=new Map(m.definition.sections.flatMap(s=>s.fields).map(x=>[x.fieldKey,x]));fields=fields.filter(x=>visible.has(x.key)).map(x=>({...x,label:visible.get(x.key).label||x.label}));if(k==='teacherlog')columns=columns.filter(x=>x==='actions'||visible.has(x));}
 return {fields,columns};
}
function apply(k,rows,m,refresh){if(!identity())return rows;const spec=catalog(k,m),p=read(k),owner=identity(),ctx={...spec,k,refresh,owner};contexts.set(k,ctx);queueMicrotask(()=>decorate(ctx));const conditions=p.conditions.filter(c=>spec.fields.some(f=>f.key===c.field&&operators(f).includes(c.op)));let result=rows.filter(r=>!conditions.length||(p.join==='any'?conditions.some(c=>matches(spec.fields.find(f=>f.key===c.field).get(r),c,spec.fields.find(f=>f.key===c.field).type)):conditions.every(c=>matches(spec.fields.find(f=>f.key===c.field).get(r),c,spec.fields.find(f=>f.key===c.field).type))));const sort=spec.fields.find(f=>f.key===p.sort);if(sort)result=result.slice().sort((a,b)=>{const label=v=>sort.choices?.find(x=>x.value===String(v))?.label??v??'',aVal=label(sort.get(a)),bVal=label(sort.get(b));return(p.direction==='desc'?-1:1)*(sort.type==='number'?Number(aVal)-Number(bVal):String(aVal).localeCompare(String(bVal),undefined,{numeric:true,sensitivity:'base'}))});return result}
function decorate(ctx){if(ctx.owner!==identity())return;const host=document.getElementById(ctx.k);if(!host)return;const table=host.querySelector(ctx.k==='students'?'#studentRows':ctx.k==='teachers'?'#teacherRows':'.hw-table-wrap.main tbody')?.closest('table');if(!table)return;let snapshot=snapshots.get(table);if(!snapshot||snapshot.head!==table.tHead?.rows[0]||snapshot.body!==table.tBodies[0]?.rows[0]){snapshot={head:table.tHead?.rows[0],body:table.tBodies[0]?.rows[0],rows:[...table.rows].map(r=>r===snapshot?.head?snapshot.rows[0]:({r,cells:[...r.cells],hidden:[...r.cells].map(c=>c.hidden)}))};snapshots.set(table,snapshot)}const first=snapshot.rows[0];if(!first||first.cells.length!==ctx.columns.length)return;ctx.available=ctx.columns.filter((k,i)=>k!=='actions'&&!first.hidden[i]&&ctx.fields.some(f=>f.key===k));const p=read(ctx.k),order=[...new Set([...p.columns.filter(k=>ctx.columns.includes(k)&&k!=='actions'),...ctx.columns.filter(k=>k!=='actions'),'actions'])];for(const {r,cells,hidden} of snapshot.rows){if(cells.length!==ctx.columns.length)continue;for(const key of order){const i=ctx.columns.indexOf(key),cell=cells[i];if(!cell)continue;cell.hidden=hidden[i]||(key!=='actions'&&p.hidden.includes(key));r.append(cell)}}let bar=host.querySelector('.pv-toolbar');if(!bar){bar=document.createElement('div');bar.className='pv-toolbar';const anchor=host.querySelector('.hw-table-wrap.main')||table.parentElement;anchor.before(bar)}const count=p.conditions.filter(c=>ctx.fields.some(f=>f.key===c.field)).length;bar.innerHTML='<span>My view'+(count?' · '+count+' advanced filter'+(count===1?'':'s'):'')+(p.sort?' · sorted':'')+'</span><button type="button" class="btn small" data-pv="columns">Columns</button><button type="button" class="btn small" data-pv="filters">Advanced Filter'+(count?' ('+count+')':'')+'</button><button type="button" class="btn small" data-pv="reset">Reset My View</button>';bar.onclick=e=>{const a=e.target.closest('[data-pv]')?.dataset.pv;if(!a)return;if(a==='reset'){if(confirm('Reset only your columns, advanced filters and sort for this workspace? Existing quick filters will remain.')){try{write(ctx.k,defaults());ctx.refresh()}catch(err){alert(err.message)}}}else open(ctx,a)};}
let overlay=null,returnFocus=null;
function close(){overlay?.remove();overlay=null;returnFocus?.focus()}
function open(ctx,tab){close();returnFocus=document.activeElement;let draft=structuredClone(read(ctx.k));const owner=identity();overlay=document.createElement('div');overlay.className='pv-overlay';overlay.innerHTML='<section class="pv-dialog" role="dialog" aria-modal="true" aria-label="Personal workspace view"><header><h2>'+(tab==='columns'?'Columns':'Advanced Filter')+'</h2><button type="button" class="btn" data-close aria-label="Close">×</button></header><p class="pv-note">Only your view of this workspace changes. Saved in this browser for your school and account. Record forms and other users are unaffected.</p><div class="pv-body"></div><p class="pv-error" role="alert"></p><footer><button type="button" class="btn" data-default>Reset to Default</button><button type="button" class="btn" data-close>Cancel</button><button type="button" class="btn primary" data-save>Apply &amp; Save My View</button></footer></section>';document.body.append(overlay);const body=overlay.querySelector('.pv-body'),error=overlay.querySelector('.pv-error');
 const option=(value,label,selected)=>'<option value="'+esc(value)+'" '+(selected===value?'selected':'')+'>'+esc(label)+'</option>';
 function paint(){if(tab==='columns'){const keys=[...new Set([...draft.columns.filter(k=>ctx.available.includes(k)),...ctx.available])];body.innerHTML='<p>Show/hide columns and use the arrows to change their order. Actions always remain available.</p>'+keys.map((key,i)=>'<div class="pv-column"><label><input type="checkbox" data-column="'+esc(key)+'" '+(!draft.hidden.includes(key)?'checked':'')+'> '+esc(ctx.fields.find(f=>f.key===key).label)+'</label><button type="button" class="btn small" data-up="'+i+'" '+(!i?'disabled':'')+' aria-label="Move '+esc(key)+' up">↑</button><button type="button" class="btn small" data-down="'+i+'" '+(i===keys.length-1?'disabled':'')+' aria-label="Move '+esc(key)+' down">↓</button></div>').join('');draft.columns=keys;return}body.innerHTML='<label>Match <select data-join>'+option('all','ALL conditions (AND)',draft.join)+option('any','ANY condition (OR)',draft.join)+'</select></label><div class="pv-conditions">'+draft.conditions.map((c,i)=>{const f=ctx.fields.find(f=>f.key===c.field)||ctx.fields[0];if(!f)return'';const input=(v,attr)=>f.choices?'<select '+attr+'>'+option('','Select a value',v)+f.choices.map(x=>option(x.value,x.label,v)).join('')+'</select>':'<input '+attr+' aria-label="Filter value" type="'+(f.type==='date'?'date':f.type==='number'?'number':'text')+'" maxlength="300" value="'+esc(v||'')+'">';return'<div class="pv-condition" data-index="'+i+'"><select aria-label="Field" data-field>'+ctx.fields.map(x=>option(x.key,x.label,c.field)).join('')+'</select><select aria-label="Operator" data-op>'+operators(f).map(x=>option(x,operatorLabels[x],c.op)).join('')+'</select>'+(!['empty','notEmpty'].includes(c.op)?input(c.value,'data-value')+(c.op==='between'?input(c.to,'data-to'):''):'')+'<button type="button" class="btn" data-remove="'+i+'" aria-label="Remove condition">×</button></div>'}).join('')+'</div><button type="button" class="btn" data-add '+(draft.conditions.length>=10?'disabled':'')+'>+ Add Condition</button><hr><label>Sort by <select data-sort>'+option('','Workspace default',draft.sort)+ctx.fields.map(x=>option(x.key,x.label,draft.sort)).join('')+'</select></label> <select aria-label="Sort direction" data-direction>'+option('asc','Ascending',draft.direction)+option('desc','Descending',draft.direction)+'</select><p>Advanced conditions combine with the existing quick filters. They apply before the list is paginated.</p>';}
 // Discard stale fields after permission/configuration changes, without touching any record.
 draft.conditions=draft.conditions.filter(c=>ctx.fields.some(f=>f.key===c.field&&operators(f).includes(c.op)));paint();
 overlay.onchange=e=>{const t=e.target,i=Number(t.closest('[data-index]')?.dataset.index);if(t.hasAttribute('data-column')){draft.hidden=draft.hidden.filter(k=>k!==t.dataset.column);if(!t.checked)draft.hidden.push(t.dataset.column)}else if(t.hasAttribute('data-field')){draft.conditions[i]={field:t.value,op:'equals',value:''};paint()}else if(t.hasAttribute('data-op')){draft.conditions[i].op=t.value;paint()}else if(t.hasAttribute('data-value'))draft.conditions[i].value=t.value;else if(t.hasAttribute('data-to'))draft.conditions[i].to=t.value;else if(t.hasAttribute('data-join'))draft.join=t.value;else if(t.hasAttribute('data-sort'))draft.sort=t.value;else if(t.hasAttribute('data-direction'))draft.direction=t.value;};
 overlay.oninput=e=>{if(e.target.matches('[data-value],[data-to]'))overlay.onchange(e)};
 overlay.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))return close();if(b.hasAttribute('data-default')){draft=defaults();paint();return}if(b.hasAttribute('data-up')||b.hasAttribute('data-down')){const up=b.hasAttribute('data-up'),i=Number(up?b.dataset.up:b.dataset.down),j=i+(up?-1:1);[draft.columns[i],draft.columns[j]]=[draft.columns[j],draft.columns[i]];paint();return}if(b.hasAttribute('data-remove')){draft.conditions.splice(Number(b.dataset.remove),1);paint();return}if(b.hasAttribute('data-add')){if(ctx.fields.length&&draft.conditions.length<10)draft.conditions.push({field:ctx.fields[0].key,op:'contains',value:''});if(draft.conditions.length){const c=draft.conditions.at(-1),f=ctx.fields.find(f=>f.key===c.field);c.op=operators(f)[0]}paint();return}if(b.hasAttribute('data-save')){try{if(identity()!==owner)throw Error('Your account changed. Close this dialog and reopen it.');if(tab==='columns'&&ctx.available.every(k=>draft.hidden.includes(k)))throw Error('Keep at least one information column visible.');for(const c of draft.conditions){const f=ctx.fields.find(f=>f.key===c.field);if(!f||!operators(f).includes(c.op))throw Error('Select a valid filter field.');if(!['empty','notEmpty'].includes(c.op)&&(c.value==null||c.value===''))throw Error('Complete each filter value.');if(c.op==='between'&&(!c.to||(f.type==='number'?Number(c.value)>Number(c.to):c.value>c.to)))throw Error('Enter a valid inclusive range.')}write(ctx.k,draft);close();ctx.refresh()}catch(err){error.textContent=err.message}}};
 overlay.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const focusable=[...overlay.querySelectorAll('button:not(:disabled),input,select')],first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};overlay.querySelector('button').focus();
}
window.schoolHubPersonalViews=Object.freeze({apply,read,matches});
})();
