(function(){
'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),api=(p='',o={})=>schoolHubTransport.server.request('/api/v1/picklists'+p,o),has=p=>{const u=window.__schoolHubPhase7?.getState()?.serverUser;return u?.role==='Super Admin'||u?.permissions?.includes(p)},active=()=>!!window.schoolHubPhase12?.isProduction();
let model={items:[],workspaceSources:[],sourceFields:{}},workspaces=[],editing=null,rows=[],dirty=false,page=1,loading,returnFocus;
const filters={search:'',source:''},sources={AdminDefined:'Admin-defined',System:'System',Workspace:'Workspace Reference'},btn=(a,id,text,cls='')=>'<button type="button" class="btn small '+cls+'" data-pl-action="'+a+'" data-id="'+esc(id)+'">'+text+'</button>';
const options=(values,current,empty)=> (empty?'<option value="">'+esc(empty)+'</option>':'')+values.map(x=>'<option value="'+esc(x.value)+'" '+(x.value===current?'selected':'')+'>'+esc(x.label)+'</option>').join('');
const style=document.createElement('style');style.textContent='.pl-drawer{width:min(850px,90vw)}.pl-drawer [hidden]{display:none!important}.pl-values{width:100%;border-collapse:collapse;font-size:12px}.pl-values th,.pl-values td{padding:8px 5px;vertical-align:top;text-align:left;border-bottom:1px solid var(--border)}.pl-values input:not([type=checkbox]),.pl-values select{width:100%;min-width:0;padding:8px}.pl-values input[type=checkbox]{width:auto}.pl-values th:nth-child(1),.pl-values th:nth-child(2){width:21%}.pl-values th:nth-child(3){width:17%}.pl-value-actions{display:flex;gap:4px}.pl-value-actions button{padding:5px 7px}.pl-color{display:flex;align-items:center;gap:5px}.pl-swatch{display:inline-block;width:18px;height:18px;border:1px solid var(--border);border-radius:4px;flex-shrink:0}.pl-preview{margin-top:18px;padding:14px;border:1px solid var(--border);border-radius:10px}.pl-value-table{overflow-x:auto}.pl-note{font-size:12px;color:var(--muted);line-height:1.5}.pl-error{color:#d94d60;margin-top:12px}.pl-description{font-size:12px;color:var(--muted);margin-top:5px}.pl-drawer h3{font-size:16px;margin:20px 0 10px}.pl-mobile{display:none}.pl-search{width:100%!important;max-width:300px}.pl-custom-color{height:34px;padding:2px!important;margin-top:5px}.pl-drawer .hw-form textarea{min-height:85px}.pl-table{width:100%;border-collapse:collapse}.pl-table td,.pl-table th{padding:13px 8px;text-align:left;border-bottom:1px solid var(--border);font-size:12px}.pl-table th{background:var(--bg)}.pl-table td code{overflow-wrap:anywhere}.pl-readonly{opacity:.8}@media(max-width:700px){.pl-drawer{width:100%}.pl-desktop{display:none}.pl-mobile{display:block}.pl-values thead{display:none}.pl-values,.pl-values tbody,.pl-values tr,.pl-values td{display:block;width:100%}.pl-values tr{border:1px solid var(--border);border-radius:10px;padding:10px;margin-bottom:12px}.pl-values td{border:0;padding:5px}.pl-values td:before{content:attr(data-label);display:block;font-size:11px;color:var(--muted);margin-bottom:4px}.pl-values .pl-preview-cell{display:inline-block}.pl-drawer .hw-form{grid-template-columns:1fr}.pl-drawer .hw-field{grid-column:1/-1}}';document.head.append(style);
style.textContent+='#plOverlay .btn:not(.primary):not(.danger),#uia1Pane-picklists .btn:not(.primary):not(.danger){background:var(--card);color:var(--text);border:1px solid var(--border)}#uia1Pane-picklists h2{color:var(--text)}#uia1Pane-picklists .hw-filters input,#uia1Pane-picklists .hw-filters select{padding:10px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--text)}.pl-values{min-width:0!important}.pl-preview{overflow-x:auto}.pl-preview .pl-table{min-width:0!important;table-layout:fixed}.pl-drawer .hw-body{min-width:0}.pl-values th{background:var(--bg);color:var(--text)}@media(max-width:700px){.pl-values td{min-width:0!important;max-width:100%}.pl-values tr{box-sizing:border-box}.pl-value-table{overflow-x:hidden}}';
function pane(){let p=$('uia1Pane-picklists');if(!p){p=document.createElement('section');p.id='uia1Pane-picklists';p.className='uia1-pane';$('uia1Content')?.append(p)}return p}
async function load(){if(loading)return loading;loading=(async()=>{const [m,w]=await Promise.all([api(),schoolHubTransport.server.request('/api/v1/workspaces?pageSize=100')]);model=m;workspaces=w.items||[];render()})();try{await loading}catch(e){pane().innerHTML='<div class="card"><p>'+esc(e.message)+'</p>'+btn('reload','','Retry')+'</div>'}finally{loading=null}}
async function navigate(id){showTab('settings');window.uiA1Open('picklists');await load();if(id)open(id)}
function render(){const items=model.items.filter(x=>(!filters.source||x.sourceType===filters.source)&&(!filters.search||(x.name+' '+x.picklistKey+' '+x.description).toLowerCase().includes(filters.search.toLowerCase()))),pages=Math.max(1,Math.ceil(items.length/15));page=Math.min(page,pages);const shown=items.slice((page-1)*15,page*15),action=x=>btn('edit',x.id,has('workspaces:configure')?'Edit':'View');
 pane().innerHTML='<div class="uia1-breadcrumb">Admin Settings &gt; Data &amp; System &gt; Picklist Manager</div><div class="hw-title"><div><h2>Picklist Manager</h2><p class="muted">Manage reusable dropdown values and status colors used across SchoolHub.</p></div>'+(has('workspaces:configure')?btn('new','','+ New Picklist','primary'):'')+'</div><div class="hw-panel"><div class="hw-filters"><label>Search Picklists<input class="pl-search" data-pl-filter="search" value="'+esc(filters.search)+'" placeholder="Search picklists…"></label><label>Source<select data-pl-filter="source">'+options(Object.entries(sources).map(([value,label])=>({value,label})),filters.source,'All Sources')+'</select></label>'+btn('clear','','Clear')+'</div><div class="pl-desktop" style="overflow:auto"><table class="pl-table"><thead><tr>'+['Name','Stable Key','Source','# Values','Updated On','Actions'].map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+shown.map(x=>'<tr><td><b>'+esc(x.name)+'</b><div class="pl-description">'+esc(x.description)+'</div></td><td><code>'+esc(x.picklistKey)+'</code></td><td>'+esc(sources[x.sourceType])+'</td><td>'+(x.sourceType==='Workspace'?'Live records':x.values.length)+'</td><td>'+esc(new Date(x.updatedAt).toLocaleString('en-GB'))+'</td><td>'+action(x)+'</td></tr>').join('')+'</tbody></table></div><div class="pl-mobile">'+shown.map(x=>'<article class="hw-card"><h3>'+esc(x.name)+'</h3><p>'+esc(x.picklistKey)+'</p><p>'+esc(sources[x.sourceType])+' · '+(x.sourceType==='Workspace'?'Live records':x.values.length+' values')+'</p>'+action(x)+'</article>').join('')+'</div>'+(!shown.length?'<div class="hw-empty">No Picklists match these filters.</div>':'')+'<div class="hw-pager"><span>'+items.length+' Picklists · Page '+page+' of '+pages+'</span><div>'+btn('prev','','Previous')+btn('next','','Next')+'</div></div></div>';
}
function close(force=false){if(!force&&dirty&&!confirm('Discard unsaved Picklist changes?'))return false;$('plOverlay')?.remove();editing=null;dirty=false;returnFocus?.focus?.();return true}
function field(title,html,wide=false){return '<label class="hw-field '+(wide?'wide':'')+'">'+title+html+'</label>'}
function open(id){
 const x=model.items.find(x=>x.id===id);returnFocus=document.activeElement;close(true);editing=x||null;rows=(x?.values||[{value:'',label:'',color:'gray',active:true}]).map(v=>({...v}));
 const readonly=!has('workspaces:configure'),source=x?.sourceType||'AdminDefined',el=document.createElement('div');el.id='plOverlay';el.className='hw-overlay';
 el.innerHTML='<section class="hw-drawer pl-drawer" role="dialog" aria-modal="true" aria-label="'+(x?'Edit':'New')+' Picklist"><header><b>'+(x?'Edit':'New')+' Picklist</b>'+btn('close','','×')+'</header><div class="hw-body"><form id="plForm" class="hw-form">'+field('Picklist Name *','<input name="name" required maxlength="120" value="'+esc(x?.name)+'">')+field('Stable Key *','<input name="picklistKey" required pattern="[a-z][A-Za-z0-9]{1,79}" value="'+esc(x?.picklistKey)+'" '+(x?'readonly':'')+'><small class="pl-note">Stable key cannot change after creation.</small>')+field('Description','<textarea name="description" maxlength="500">'+esc(x?.description)+'</textarea>')+field('Source *','<select name="sourceType" '+(x?'disabled':'')+'>'+options([{value:'AdminDefined',label:'Values defined by Admin'},{value:'System',label:'System-defined (built-in)'},{value:'Workspace',label:'Records from Workspace'}],source)+'</select>')+'<div id="plWorkspace" class="hw-field wide"><div class="hw-form">'+field('Source Workspace *','<select name="workspaceId" '+(x?'disabled':'')+'>'+options(workspaces.filter(w=>model.workspaceSources.includes(w.workspaceKey)).map(w=>({value:w.id,label:w.pluralName})),x?.workspaceId,'Select workspace')+'</select>')+field('Display Field *','<select name="labelFieldKey" '+(x?'disabled':'')+'></select>')+field('Stored Value / ID Field','<input name="valueFieldKey" value="'+esc(x?.valueFieldKey||'id')+'" readonly>')+field('Optional Filter Field','<select name="filterFieldKey" '+(x?'disabled':'')+'></select>')+'</div><p class="pl-note">Records are read live from the selected workspace. The optional field supplies a filter value matched by the consuming Workspace field. Stored IDs and existing source mappings are immutable.</p>'+btn('sourcepreview','','Preview source records')+'<div id="plSourcePreview"></div></div></form><div id="plManual"><h3>Picklist Values</h3><p class="pl-note"><b>Value</b> is the stable stored code; <b>Label</b> is what users see. Existing codes stay unchanged. Inactive values remain available for historical display. Required system values cannot be removed or deactivated.</p><div id="plValues" class="pl-value-table"></div>'+(readonly?'':btn('addvalue','','+ Add New Value'))+'<div class="pl-preview"><h3>Usage Preview</h3><p class="pl-note">Illustrative only — these are not real student records.</p><div id="plUsage"></div></div></div><div id="plError" class="pl-error" role="alert"></div></div><footer>'+btn('close','','Cancel')+(readonly?'':btn('save','','Save Picklist','primary'))+'</footer></section>';
 document.body.append(el);if(!x)$('plForm').elements.sourceType.querySelector('[value=System]').disabled=true;
 el.oninput=el.onchange=()=>dirty=true;sourceChanged();renderRows();if(readonly)el.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);el.querySelector('button').focus();
}
function sourceChanged(){const f=$('plForm'),live=f.elements.sourceType.value==='Workspace';$('plWorkspace').hidden=!live;$('plManual').hidden=live;if(!live)return;const workspace=workspaces.find(w=>w.id===f.elements.workspaceId.value),keys=model.sourceFields[workspace?.workspaceKey]||[],labels={id:'Record ID',name:'Name',admissionNumber:'Admission Number',employeeNumber:'Employee Number',status:'Status',classId:'Class ID',sectionId:'Section ID',active:'Active'},choices=keys.map(value=>({value,label:labels[value]||value}));f.elements.labelFieldKey.innerHTML=options(choices,editing?.labelFieldKey||'name','Choose display field');f.elements.filterFieldKey.innerHTML=options(choices,editing?.filterFieldKey||'','No filter')}
function preview(i){const x=rows[i];return schoolHubPicklistDisplay.badge([x],x.value)}
function renderRows(){const can=has('workspaces:configure');$('plValues').innerHTML='<table class="pl-values"><thead><tr>'+['Value *','Label *','Color','Active','Preview','Actions'].map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map((x,i)=>'<tr data-pl-row="'+i+'"><td data-label="Value"><input data-pl-value="value" value="'+esc(x.value)+'" '+(x.id||!can?'readonly':'')+' maxlength="200">'+(x.required?'<small class="pl-note">Required system value</small>':'')+'</td><td data-label="Label"><input data-pl-value="label" value="'+esc(x.label)+'" maxlength="200" '+(!can?'readonly':'')+'></td><td data-label="Color"><div class="pl-color"><span class="pl-swatch" style="background:'+schoolHubPicklistDisplay.hex(x.color)+'"></span><select data-pl-value="color" '+(!can?'disabled':'')+'>'+options([...Object.keys(schoolHubPicklistDisplay.colors).map(value=>({value,label:value[0].toUpperCase()+value.slice(1)})),{value:'custom',label:'Custom'}],String(x.color||'gray').startsWith('#')?'custom':x.color||'gray')+'</select></div>'+(String(x.color).startsWith('#')?'<input class="pl-custom-color" type="color" aria-label="Custom color" data-pl-value="customColor" value="'+esc(x.color)+'" '+(!can?'disabled':'')+'>':'')+'</td><td data-label="Active"><input type="checkbox" data-pl-value="active" '+(x.active!==false?'checked':'')+' '+(x.required||!can?'disabled':'')+'></td><td data-label="Preview" class="pl-preview-cell">'+preview(i)+'</td><td data-label="Actions"><div class="pl-value-actions">'+(can?btn('up',i,'↑')+btn('down',i,'↓')+(!x.required?btn('removevalue',i,x.id?'Deactivate':'Remove'):''):'')+'</div><input data-pl-value="filterValue" placeholder="Optional filter value" value="'+esc(x.filterValue||'')+'" '+(!can?'readonly':'')+'></td></tr>').join('')+'</tbody></table>';usage()}
function usage(){$('plUsage').innerHTML='<table class="pl-table"><thead><tr><th>Example record</th><th>Status / choice</th></tr></thead><tbody>'+rows.slice(0,4).map((x,i)=>'<tr><td>Sample '+(i+1)+'</td><td>'+preview(i)+'</td></tr>').join('')+'</tbody></table>'}
async function save(){const f=$('plForm');if(!f.reportValidity())return;const base={name:f.elements.name.value.trim(),description:f.elements.description.value.trim()},source=f.elements.sourceType.value,values=rows.map(x=>({...(x.id?{id:x.id}:{}),value:x.value.trim(),label:x.label.trim(),color:x.color||'gray',active:x.active!==false,filterValue:x.filterValue||null}));
 if(source!=='Workspace'&&values.some(x=>!x.value||!x.label))throw Error('Each value needs a stable value and label.');
 const body=editing?{...base,version:editing.version,...(source!=='Workspace'?{values}:{})}:{...base,picklistKey:f.elements.picklistKey.value.trim(),sourceType:source,...(source==='Workspace'?{workspaceId:f.elements.workspaceId.value,valueFieldKey:'id',labelFieldKey:f.elements.labelFieldKey.value,filterFieldKey:f.elements.filterFieldKey.value||null}:{values})};
 await api(editing?'/'+encodeURIComponent(editing.id):'',{method:editing?'PATCH':'POST',body,mutation:true});close(true);await load();await schoolHubPicklistDisplay.refresh();window.dispatchEvent(new CustomEvent('schoolhub-picklists-changed'));
}
async function act(a,id){if(a==='close')return close();if(a==='reload')return load();if(a==='new')return open();if(a==='edit')return open(id);if(a==='save')return save();
 if(a==='addvalue'){rows.push({value:'',label:'',color:'gray',active:true});dirty=true;renderRows();return}
 if(a==='removevalue'){const i=Number(id),x=rows[i];if(x.id){x.active=false;dirty=true;renderRows();$('plError').textContent='Value retained as inactive to protect historical records.'}else{rows.splice(i,1);dirty=true;renderRows()}return}
 if(a==='up'||a==='down'){const i=Number(id),j=i+(a==='up'?-1:1);if(j>=0&&j<rows.length){[rows[i],rows[j]]=[rows[j],rows[i]];dirty=true;renderRows()}return}
 if(a==='sourcepreview'){if(!editing)throw Error('Save the source definition before previewing live records.');const r=await api('/'+encodeURIComponent(editing.id)+'/values');$('plSourcePreview').innerHTML='<p class="pl-note">Read-only live values (maximum 1,000).</p>'+r.items.slice(0,20).map(x=>'<div>'+esc(x.label)+'</div>').join('');return}
 if(a==='clear'){filters.search=filters.source='';page=1}if(a==='prev')page=Math.max(1,page-1);if(a==='next')page++;render();
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-pl-action]');if(!b||b.disabled)return;b.disabled=true;try{await act(b.dataset.plAction,b.dataset.id)}catch(error){if($('plError'))$('plError').textContent=error.message;else alert(error.message)}finally{b.disabled=false}});
function valueChanged(e){const el=e.target,k=el.dataset.plValue;if(!k)return;const i=Number(el.closest('[data-pl-row]').dataset.plRow),x=rows[i];x[k==='customColor'?'color':k]=k==='active'?el.checked:k==='color'&&el.value==='custom'?'#2563eb':el.value;dirty=true;if(k==='color'){renderRows();return}el.closest('tr').querySelector('.pl-preview-cell').innerHTML=preview(i);el.closest('tr').querySelector('.pl-swatch').style.background=schoolHubPicklistDisplay.hex(x.color);usage()}
document.addEventListener('input',e=>{if(e.target.dataset.plValue&&e.target.type!=='checkbox'&&e.target.tagName!=='SELECT')valueChanged(e);if(e.target.dataset.plFilter==='search'){const pos=e.target.selectionStart;filters.search=e.target.value;page=1;render();const el=document.querySelector('[data-pl-filter=search]');el.focus();el.setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{if(e.target.dataset.plValue&&(e.target.type==='checkbox'||e.target.tagName==='SELECT'))valueChanged(e);if(e.target.closest('#plForm')&&['sourceType','workspaceId'].includes(e.target.name))sourceChanged();if(e.target.dataset.plFilter==='source'){filters.source=e.target.value;page=1;render()}});
document.addEventListener('keydown',e=>{const el=$('plOverlay');if(!el)return;if(e.key==='Escape')close();if(e.key==='Tab'){const all=[...el.querySelectorAll('button,input,select,textarea')].filter(x=>!x.disabled&&x.getClientRects().length);if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0]?.focus()}}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
const previous=window.uiA1Open;window.uiA1Open=function(k,opts){const result=previous.apply(this,arguments);if(k==='picklists'){if(!active()){pane().innerHTML='<div class="card">Connect to Server Production to manage authoritative Picklists. Local records are unchanged.</div>';return}if(!has('workspaces:view')){pane().innerHTML='<div class="card">You do not have permission to view Picklists.</div>';return}load()}return result};
function fromField(){const id=$('wm2FieldPicklist')?.value;if(!confirm('Leave the field editor and open Picklist Manager? Unsaved field edits will not be saved.'))return;closeModal();return navigate(id)}
window.schoolHubPicklists={navigate,load,open,fromField};
})();
