(()=>{
'use strict';
const active=()=>!!window.schoolHubPhase12?.isProduction?.();let ready=false,loading=null;
const request=(path='',options)=>schoolHubTransport.server.request('/api/v1/reports'+path,options),permission=name=>{const user=window.__schoolHubPhase7?.getState?.().serverUser;return !!user&&(user.role==='Super Admin'||(user.permissions||[]).includes(name));};
const priorCan=window.can;window.can=function(tab,action='view'){if(!active()||tab!=='reports')return priorCan.apply(this,arguments);return permission('reports:'+action);};
function verify(data){const expected=data.verifiedTotals||{},actual={students:data.students.length,attendanceRecords:data.attendance.length,feePayments:data.fees.length,feeCollectedMinor:data.fees.reduce((n,x)=>n+Math.round(Number(x.amount||0)*100),0),feeStructures:data.feeStructures.length,publishedExams:data.exams.length,marks:data.marks.length};for(const key of Object.keys(actual))if(Number(expected[key])!==actual[key])throw Error('Report totals did not reconcile for '+key+'. Refresh and contact an administrator.');}
async function load(){if(loading)return loading;loading=(async()=>{ready=false;const data=await request('/data');verify(data);state.students=data.students;state.attendance=data.attendance;state.fees=data.fees;state.feeStructures=data.feeStructures;state.feeAssignments=data.feeAssignments;state.exams=data.exams;state.marks=data.marks;ready=true;showReportTab('students');return data;})();try{return await loading;}finally{loading=null;}}
const oldShow=window.showReportTab;window.showReportTab=function(tab){if(!active())return oldShow.apply(this,arguments);if(!ready){load().catch(e=>{const host=$('studentReportPreview');if(host)host.innerHTML='<div class="notice">'+esc(e.message)+'</div>';});return;}return oldShow.apply(this,arguments);};
function filters(type){if(type==='students')return getStudentReportFilters();if(type==='fees')return getFeeReportFilters();if(type==='lowattendance')return getLowAttendanceFilters();if(type==='attendance')return{from:$('repAttFrom')?.value||'',to:$('repAttTo')?.value||'',class:$('repAttClass')?.value||'',section:$('repAttSection')?.value||''};return{class:$('repAcClass')?.value||'',section:$('repAcSection')?.value||'',exam:$('repAcExam')?.value||'',subject:$('repAcSubject')?.value||''};}
const oldPrint=window.printReport;window.printReport=function(type){if(!active())return oldPrint.apply(this,arguments);if(!ready)return alert('Wait for Reports to finish loading.');const result=oldPrint.apply(this,arguments);request('/printed',{method:'POST',body:{reportType:type,filters:filters(type)},mutation:true}).catch(e=>alert('The report printed, but its server audit entry failed: '+e.message));return result;};
const priorShow=window.showTab;window.showTab=function(tab){const result=priorShow.apply(this,arguments);if(active()&&tab==='reports'){$(tab)?.querySelectorAll('.phase7-local-only').forEach(x=>x.remove());load().catch(e=>{const host=$('studentReportPreview');if(host)host.innerHTML='<div class="notice">'+esc(e.message)+'</div>';});}return result;};
window.schoolHubReportsServer=Object.freeze({active,handles:tab=>tab==='reports',load,get ready(){return ready;}});
})();
