/* Transport workspace: stable references, recoverable archive, shared picklist display. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const active=()=>!!window.schoolHubPhase12?.isProduction?.(),request=(p='',o)=>schoolHubTransport.server.request('/api/v1/transport'+p,o);
let model,loading,editor,dirty=false,page=1;const filters={search:'',status:'',vehicle:'',shift:'',archived:false};
const has=a=>{const u=window.__schoolHubPhase7?.getState?.().serverUser;return u?.role==='Super Admin'||u?.permissions?.includes('transport:'+a)},admin=()=>window.__schoolHubPhase7?.getState?.().serverUser?.role==='Super Admin';
window.schoolHubServerPersistence.register(['buses','transportAssignments']);
const oldCan=window.can;window.can=function(tab,a='view'){return active()&&tab==='transport'?has({add:'create',edit:'update'}[a]||a):oldCan.apply(this,arguments)};
const btn=(a,id,label,cls='')=>'<button type="button" class="btn small '+cls+'" data-tr="'+a+'" data-id="'+esc(id||'')+'">'+label+'</button>';
const opts=(rows,value,empty='Select')=>'<option value="">'+esc(empty)+'</option>'+rows.map(x=>'<option value="'+esc(x.value??x.id)+'" '+((x.value??x.id)===value?'selected':'')+'>'+esc(x.label??x.name)+'</option>').join('');
const rows=()=>[...(model?.routes||[]),...(model?.archivedRoutes||[])].map(r=>({...r.data,id:r.id,version:r.version,archived:r.archived}));
const vehicleName=x=>model.vehicles.find(v=>v.value===x.vehicle)?.label||x.vehicle||'—';
const get=id=>rows().find(r=>r.id===id),assigned=id=>(model.assignments||[]).filter(a=>a.busId===id);
const field=k=>model?.definition.sections.flatMap(s=>s.fields).find(f=>f.fieldKey===k),label=(k,fallback)=>field(k)?.label||fallback||k;
const stops=x=>x.stopDetails||String(x.stops||'').split(',').map(s=>s.trim()).filter(Boolean).map(name=>({name,pickupTime:'',dropTime:''}));
const allowed=(a)=>model?.definition.behaviorConfiguration?.[a]!==false;
const actions=x=>btn('view',x.id,'View')+(!x.archived&&has('update')?btn('edit',x.id,'Edit'):'')+(has('print')&&allowed('print')?btn('print',x.id,'Print'):'')+(!x.archived&&has('delete')&&allowed('archive')?btn('archive',x.id,'Archive','danger'):'')+(x.archived&&admin()?btn('restore',x.id,'Restore'):'');
const style=document.createElement('style');style.textContent='.tr-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:18px 0}.tr-summary>div{padding:18px;border:1px solid var(--line);border-radius:12px;background:var(--card)}.tr-summary b{display:block;font-size:24px;margin-top:8px}.tr-drawer{width:min(560px,100%)}.tr-drawer .btn:not(.primary):not(.danger){background:var(--card);color:var(--text);border:1px solid var(--line)}.tr-drawer [hidden]{display:none!important}.tr-stop{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:6px;margin:8px 0}.tr-stop input{min-width:0;width:100%}.tr-detail dd{margin:4px 0 15px;white-space:pre-wrap;overflow-wrap:anywhere}.tr-detail dt{font-weight:600}.tr-students{max-height:260px;overflow:auto}.tr-error{color:#ec6470}.tr-drawer select[multiple]{min-height:110px}.tr-note{font-size:12px;color:var(--muted)}@media(max-width:700px){.tr-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.tr-stop{grid-template-columns:1fr 1fr}.tr-stop input:first-child{grid-column:1/-1}}';document.head.append(style);
async function load(){
 if(loading)return loading;
 loading=(async()=>{model=await request();state.buses=rows().map(x=>({...x,status:x.archived?'Inactive':x.status}));state.transportAssignments=model.assignments.filter(a=>a.busId);render()})();
 try{return await loading}catch(e){$('transport').innerHTML='<div class="card"><p>'+esc(e.message)+'</p>'+btn('reload','','Retry')+'</div>'}finally{loading=null}
}
function render(){
 if(!model)return;const all=rows(),live=all.filter(x=>!x.archived),filtered=schoolHubPersonalViews.apply('transport',all,model,render).filter(x=>!!x.archived===filters.archived&&(!filters.status||x.status===filters.status)&&(!filters.vehicle||x.vehicle===filters.vehicle)&&(!filters.shift||x.shift===filters.shift)&&(!filters.search||[x.route,x.routeCode,x.vehicle,x.driver].join(' ').toLowerCase().includes(filters.search.toLowerCase()))),pages=Math.max(1,Math.ceil(filtered.length/10));page=Math.min(page,pages);const shown=filtered.slice((page-1)*10,page*10);
 const counts=[['Total Routes',live.length],['Vehicles',new Set(live.map(x=>x.vehicle).filter(Boolean)).size],['Drivers',new Set(live.map(x=>x.driverId||x.driver).filter(Boolean)).size],['Students Assigned',model.assignments.filter(a=>live.some(r=>r.id===a.busId)).length],['Active Routes',live.filter(x=>x.status==='Active').length]];
 $('transport').innerHTML='<div class="hw-shell"><div class="hw-title"><div><h2>Transport</h2><p class="muted">Manage routes, vehicles, drivers, attendants and student assignments.</p></div>'+(has('create')?btn('add','','+ Add Route','primary'):'')+'</div><div class="tr-summary">'+counts.map(([name,n])=>'<div>'+name+'<b>'+n+'</b></div>').join('')+'</div><div class="hw-panel"><div class="hw-filters" style="padding:16px"><label>Search<input data-tr-search placeholder="Route, vehicle or driver" value="'+esc(filters.search)+'"></label>'+[['status',model.statuses,'All Status'],['vehicle',model.vehicles,'All Vehicles'],['shift',model.shifts,'All Shifts']].map(([k,list,empty])=>'<label>'+esc(label(k))+'<select data-tr-filter="'+k+'">'+opts(list,filters[k],empty)+'</select></label>').join('')+'<label>Records<select data-tr-filter="archived"><option value="false">Current routes</option><option value="true" '+(filters.archived?'selected':'')+'>Archived routes</option></select></label>'+btn('clear','','Clear Filters')+'</div><div class="hw-table-wrap main"><table class="hw-table"><thead><tr>'+['Route','Vehicle','Driver','Attendant','Stops','Assigned','Fee (₹)','Status','Actions'].map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+shown.map(x=>'<tr><td><b>'+esc(x.route)+'</b><div class="muted">'+esc(x.routeCode||'')+'</div></td><td>'+esc(vehicleName(x))+'</td><td>'+esc(x.driver||'—')+'</td><td>'+esc(x.attendant||'—')+'</td><td>'+stops(x).length+'</td><td>'+assigned(x.id).length+'</td><td>'+esc(x.monthlyFee??'—')+'</td><td>'+schoolHubPicklistDisplay.badge(model.statuses,x.status)+'</td><td><div class="hw-actions">'+actions(x)+'</div></td></tr>').join('')+'</tbody></table></div><div class="hw-mobile">'+shown.map(x=>'<article class="hw-card"><h3>'+esc(x.route)+'</h3><p>'+esc(vehicleName(x))+' · '+esc(x.driver)+'</p><p>'+assigned(x.id).length+' students · '+stops(x).length+' stops</p>'+schoolHubPicklistDisplay.badge(model.statuses,x.status)+'<div class="hw-actions">'+actions(x)+'</div></article>').join('')+'</div>'+(!shown.length?'<div class="hw-empty">No matching routes. Use Add Route to get started.</div>':'')+'<div class="hw-pager"><span>'+filtered.length+' routes · Page '+page+' of '+pages+'</span><div>'+btn('prev','','Previous')+btn('next','','Next')+'</div></div></div></div>';
}
function close(force=false){if(!force&&dirty&&!confirm('Discard unsaved route changes?'))return false;$('trOverlay')?.remove();editor=null;dirty=false;return true}
function drawer(title,body,footer){if(!close())return false;const el=document.createElement('div');el.id='trOverlay';el.className='hw-overlay';el.innerHTML='<section class="hw-drawer tr-drawer" role="dialog" aria-modal="true" aria-label="'+esc(title)+'"><header><b>'+esc(title)+'</b>'+btn('close','','×')+'</header><div class="hw-body">'+body+'<div id="trError" class="tr-error" role="alert"></div></div><footer>'+footer+'</footer></section>';document.body.append(el);el.querySelector('button').focus();el.oninput=()=>dirty=true;el.onchange=()=>dirty=true;return true}
function stopRow(x={name:'',pickupTime:'',dropTime:''}){return '<div class="tr-stop"><input aria-label="Stop name" data-stop="name" required maxlength="240" placeholder="Stop name" value="'+esc(x.name)+'"><input aria-label="Pickup time" data-stop="pickupTime" type="time" value="'+esc(x.pickupTime)+'"><input aria-label="Drop time" data-stop="dropTime" type="time" value="'+esc(x.dropTime)+'">'+btn('stop-remove','','Remove')+'</div>'}
function open(id){
 if(!has(id?'update':'create'))return;const x=id?get(id):{status:'Active',classIds:[],sectionIds:[]};
 const text=(k,title,type='text',required=false)=>'<label class="hw-field">'+esc(label(k,title))+(required?' *':'')+'<input name="'+k+'" type="'+type+'" '+(required?'required':'')+' '+(type==='number'?'min="'+(k==='capacity'?1:0)+'" step="'+(k==='capacity'?1:'0.01')+'"':'maxlength="'+(k==='routeCode'?80:160)+'"')+' value="'+esc(x[k]??'')+'"></label>';
 const select=(k,title,list,required=false)=>'<label class="hw-field">'+esc(label(k,title))+(required?' *':'')+'<select name="'+k+'" '+(required?'required':'')+'>'+opts(list.filter(v=>v.active!==false||(v.value??v.id)===x[k]),x[k])+'</select></label>';
 const staff=model.staff.map(s=>({...s,name:s.name+' ('+s.role+')'}));
 let body=text('route','Route Name','text',true)+text('routeCode','Route Code','text',true)+select('vehicle','Vehicle',model.vehicles,true)+select('driverId','Driver',staff,!x.driver)+select('attendantId','Attendant',staff);
 if(x.driver&&!x.driverId)body+='<p class="tr-note wide">Existing driver: '+esc(x.driver)+'. Retained until linked to a staff record.</p>';
 if(x.attendant&&!x.attendantId)body+='<p class="tr-note wide">Existing attendant: '+esc(x.attendant)+'. Retained until linked to a staff record.</p>';
 body+='<div class="hw-field wide"><label>'+esc(label('stops','Stops / Pickup Points'))+' *</label><p class="tr-note">Ordered stops · optional pickup and drop times.</p><div id="trStops">'+(stops(x).length?stops(x):[{name:'',pickupTime:'',dropTime:''}]).map(stopRow).join('')+'</div>'+btn('stop-add','','+ Add Stop')+'</div>'+text('startTime','Start Time','time',true)+select('shift','Shift',model.shifts,true)+text('monthlyFee','Monthly Fee (₹)','number')+text('capacity','Capacity','number');
 for(const [k,title,list]of [['classIds','Assigned Classes',model.classes],['sectionIds','Assigned Sections',model.sections.map(s=>({...s,name:(model.classes.find(c=>c.id===s.classId)?.name||'Class')+' — '+s.name}))]])body+='<label class="hw-field">'+esc(label(k,title))+'<select name="'+k+'" multiple>'+list.filter(v=>v.active!==false||(x[k]||[]).includes(v.id)).map(v=>'<option value="'+esc(v.id)+'" '+((x[k]||[]).includes(v.id)?'selected':'')+'>'+esc(v.name)+'</option>').join('')+'</select></label>';
 body+=select('status','Status',model.statuses,true)+'<label class="hw-field wide">'+esc(label('notes','Notes'))+'<textarea name="notes" rows="4" maxlength="8000">'+esc(x.notes||'')+'</textarea></label><p class="tr-note wide">Vehicle and Shift values are managed in Picklist Manager. Drivers and attendants reference Teachers & Staff; no staff records are created here.</p>';
 if(!drawer(id?'Edit Route':'Add Route','<form id="trForm" class="hw-form">'+body+'</form>',btn('close','','Cancel')+btn('save','','Save Route','primary')))return;editor=x;
 for(const input of $('trForm').querySelectorAll('[name]')){const f=field(input.name);if(!f)continue;if(f.screenVisible===false||f.archived){input.closest('label').hidden=true;input.required=false}if(f.configuration?.readOnly)input.disabled=true}
 sectionFilter();
}
function sectionFilter(){const f=$('trForm');if(!f)return;const ids=[...f.elements.classIds.selectedOptions].map(x=>x.value);for(const o of f.elements.sectionIds.options){const s=model.sections.find(x=>x.id===o.value);o.hidden=!ids.includes(s.classId);o.disabled=o.hidden;if(o.hidden)o.selected=false}}
async function save(){const f=$('trForm');if(!f.reportValidity())return;const x=editor,data={route:f.elements.route.value.trim(),routeCode:f.elements.routeCode.value.trim(),vehicle:f.elements.vehicle.value,driver:x.driver||'',attendant:x.attendant||'',driverId:f.elements.driverId.value||null,attendantId:f.elements.attendantId.value||null,stops:'',stopDetails:[...f.querySelectorAll('.tr-stop')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-stop]')].map(el=>[el.dataset.stop,el.value.trim()]))),startTime:f.elements.startTime.value,shift:f.elements.shift.value,monthlyFee:f.elements.monthlyFee.value===''?null:Number(f.elements.monthlyFee.value),capacity:f.elements.capacity.value===''?null:Number(f.elements.capacity.value),classIds:[...f.elements.classIds.selectedOptions].map(x=>x.value),sectionIds:[...f.elements.sectionIds.selectedOptions].map(x=>x.value),status:f.elements.status.value,notes:f.elements.notes.value};
 await request('/routes'+(x.id?'/'+encodeURIComponent(x.id):''),{method:x.id?'PATCH':'POST',body:x.id?{data,version:x.version}:data,mutation:true});close(true);await load();
}
function details(x,printing=false){const values={route:x.route,routeCode:x.routeCode||'Not recorded',vehicle:vehicleName(x),driverId:x.driver,attendantId:x.attendant,stops:stops(x).map((s,i)=>(i+1)+'. '+s.name+(s.pickupTime?' · Pickup '+s.pickupTime:'')+(s.dropTime?' · Drop '+s.dropTime:'')).join('\n'),startTime:x.startTime,shift:model.shifts.find(v=>v.value===x.shift)?.label||x.shift,monthlyFee:x.monthlyFee,capacity:x.capacity,classIds:(x.classIds||[]).map(id=>model.classes.find(c=>c.id===id)?.name||'Unavailable class').join(', '),sectionIds:(x.sectionIds||[]).map(id=>{const s=model.sections.find(c=>c.id===id);return s?(model.classes.find(c=>c.id===s.classId)?.name||'Class')+' — '+s.name:'Unavailable section'}).join(', '),status:(x.archived?'Archived · ':'')+(model.statuses.find(v=>v.value===x.status)?.label||x.status),notes:x.notes};
 return '<h3>'+esc(x.route)+'</h3><dl class="tr-detail">'+Object.entries(values).filter(([k])=>!printing||field(k)?.printVisible!==false).map(([k,v])=>'<dt>'+esc(label(k))+'</dt><dd>'+esc(v??'—')+'</dd>').join('')+'</dl><h4>Assigned Students ('+assigned(x.id).length+')</h4>'+assigned(x.id).map(a=>{const s=model.students.find(s=>s.id===a.studentId);return '<p>'+esc(s?.name||'Unavailable student')+' · '+esc(s?.admission||'')+' · '+esc(a.pickupStop)+' / '+esc(a.dropStop)+(!printing&&has('update')?btn('unassign',a.studentId,'Unassign'):'')+'</p>'}).join('');
}
function view(id){const x=get(id);if(!x)return;let body=details(x);if(!x.archived&&has('update'))body+='<div class="hw-form"><label class="hw-field wide">Student<select id="trStudent">'+opts(model.students.filter(s=>s.status==='Active'&&!model.assignments.some(a=>a.studentId===s.id&&a.busId)).map(s=>({...s,name:s.name+' — '+s.admission})),null)+'</select></label><label class="hw-field">Pickup<select id="trPickup">'+opts(stops(x).map(s=>({value:s.name,label:s.name})),null,'None')+'</select></label><label class="hw-field">Drop<select id="trDrop">'+opts(stops(x).map(s=>({value:s.name,label:s.name})),null,'None')+'</select></label>'+btn('assign',x.id,'Assign Student','primary')+'</div>';if(drawer('Route Details',body,btn('close','','Close')+(has('print')?btn('print',id,'Print'):'')))editor=x;}
async function act(a,id){
 if(a==='reload')return load();if(a==='close')return close();if(a==='add')return open();if(a==='edit')return open(id);if(a==='save')return save();if(a==='view')return view(id);
 if(a==='print'){if(!has('print')||!allowed('print'))return;return printWindow(details(get(id),true))}
 if(a==='stop-add'){$('trStops').insertAdjacentHTML('beforeend',stopRow());dirty=true;return}
 if(a==='archive'||a==='restore'){const x=get(id);if(!confirm(a==='archive'?'Archive this route? Student assignments and history will be retained.':'Restore this route?'))return;await request('/routes/'+encodeURIComponent(id)+(a==='archive'?'/remove':'/restore'),{method:'POST',body:{version:x.version},mutation:true});close(true);return load()}
 if(a==='assign'||a==='unassign'){const sid=a==='assign'?$('trStudent').value:id;if(!sid)throw Error('Select a student.');const route=editor.id,old=model.assignments.find(x=>x.studentId===sid);if(a==='unassign'&&!confirm('Unassign this student?'))return;await request('/assignments/'+encodeURIComponent(sid),{method:'PUT',body:{busId:a==='assign'?route:null,pickupStop:a==='assign'?$('trPickup').value:'',dropStop:a==='assign'?$('trDrop').value:'',version:old?.version||0},mutation:true});close(true);await load();return view(route)}
 if(a==='clear'){Object.assign(filters,{search:'',status:'',vehicle:'',shift:'',archived:false});page=1}if(a==='prev')page=Math.max(1,page-1);if(a==='next')page++;render();
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-tr]');if(!b||b.disabled)return;if(b.dataset.tr==='stop-remove'){b.closest('.tr-stop').remove();dirty=true;return}b.disabled=true;try{await act(b.dataset.tr,b.dataset.id)}catch(error){if($('trError'))$('trError').textContent=error.message;else alert(error.message)}finally{b.disabled=false}});
document.addEventListener('change',e=>{if(e.target.dataset.trFilter){const k=e.target.dataset.trFilter;filters[k]=k==='archived'?e.target.value==='true':e.target.value;page=1;render()}if(e.target.name==='classIds')sectionFilter()});
document.addEventListener('input',e=>{if(!e.target.matches('[data-tr-search]'))return;const pos=e.target.selectionStart;filters.search=e.target.value;page=1;render();const el=document.querySelector('[data-tr-search]');el.focus();el.setSelectionRange(pos,pos)});
document.addEventListener('keydown',e=>{const o=$('trOverlay');if(!o)return;if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...o.querySelectorAll('button,input,select,textarea')].filter(x=>!x.disabled&&x.getClientRects().length);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus()}}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
for(const [name,fn]of Object.entries({renderBuses:()=>model?render():load(),addBus:()=>open(),openEditBus:open,viewBus:view,printBus:id=>act('print',id),deleteBus:id=>act('archive',id)})){const old=window[name];window[name]=function(){return active()?fn.apply(this,arguments):old.apply(this,arguments)}}
const oldShow=window.showTab;window.showTab=function(tab){const r=oldShow.apply(this,arguments);if(active()&&tab==='transport')load();return r};
window.schoolHubTransportOperations={handles:tab=>tab==='transport',load};
})();
