/* Preserve the existing work-log editor and files while moving authority to PostgreSQL. */
(()=>{
'use strict';
const active=()=>!!window.schoolHubPhase12?.isProduction?.();let ready=false,busy=false,reference={teachers:[],classes:[],periods:[],years:[],timetable:[]};
window.schoolHubServerPersistence.register(['teacherWorkLogs','teacherLogs']);
const request=(path='',options)=>schoolHubTransport.server.request('/api/v1/work-logs'+path,options);
const priorCan=window.can;window.can=function(tab,action='view'){if(!active()||tab!=='teacherlog')return priorCan.apply(this,arguments);const user=window.__schoolHubPhase7?.getState?.().serverUser;return !!user&&(user.role==='Super Admin'||(user.permissions||[]).includes('teacherlog:'+({add:'create',edit:'update'}[action]||action)));};
async function load(){ready=false;state.teacherWorkLogs=[];state.teacherLogs=[];const data=await request();state.teacherWorkLogs=data.items;state.teacherLogs=state.teacherWorkLogs;reference={teachers:data.staff,classes:data.classes.map(c=>({...c,sections:data.sections.filter(s=>s.classId===c.id).map(s=>s.name)})),years:data.years,timetable:data.timetable.map(t=>({...t,sectionName:data.sections.find(s=>s.id===t.sectionId)?.name})),periods:[...new Set(data.timetable.map(t=>t.period))].map(name=>({id:name,name}))};ready=true;window.twrRebuild();}
function suggestion(){const cls=reference.classes.find(c=>c.name===$('twrClass')?.value),day=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][new Date(($('twrDate')?.value||'')+'T12:00:00').getDay()],teacher=$('twrTeacher')?.value,year=reference.years.find(y=>y.name===$('twrYear')?.textContent);return reference.timetable.filter(t=>t.classId===cls?.id&&t.teacherId===teacher&&t.day===day&&t.period===$('twrPeriod')?.value&&t.academicYearId===year?.id&&(!t.sectionId||t.sectionName===$('twrSection')?.value)).map(t=>t.subject).filter(Boolean);}
async function save(pending,removed){
 if(!ready||busy){alert('Wait for Work Logs to finish loading or saving.');return false;}busy=true;
 try{
  const id=$('twrId').value,old=state.teacherWorkLogs.find(r=>r.id===id);if(id&&!old)throw Error('Refresh the work-log list first.');
  const record={teacherId:$('twrTeacher').value,class:$('twrClass').value,section:$('twrSection').value,academicYear:$('twrYear').textContent,date:$('twrDate').value,subject:$('twrSubject').value.trim(),period:$('twrPeriod').value.trim(),topic:$('twrTopic').value.trim(),details:$('twrDetails').value.trim(),homeworkGiven:$('twrHomework').value.trim(),remarks:$('twrRemarks').value.trim()};
  const newFiles=[];for(const f of pending){if(f.size>10*1024*1024)throw Error('Each attachment must be 10 MB or smaller.');const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read '+f.name));reader.readAsDataURL(f);});newFiles.push({name:f.name,content});}
  await request(id?'/'+encodeURIComponent(id):'',{method:id?'PATCH':'POST',body:{record,retainIds:(old?.attachments||[]).filter(f=>!removed.includes(f.id)).map(f=>f.id),newFiles,version:old?.version||0},mutation:true});await load();showToast(id?'Work log updated.':'Work log saved.');return true;
 }catch(e){alert(e.message);return false;}finally{busy=false;}
}
const priorDelete=window.deleteTeacherWorkLogRepair;window.deleteTeacherWorkLogRepair=async function(id){if(!active())return priorDelete.apply(this,arguments);const row=state.teacherWorkLogs.find(r=>r.id===id);if(!row||busy||!ready)return;if(!confirm('Delete this work log and its attachments?'))return;busy=true;try{await request('/'+encodeURIComponent(id)+'/remove',{method:'POST',body:{version:row.version},mutation:true});await load();}catch(e){alert(e.message);}finally{busy=false;}};
for(const name of ['downloadAttachment','previewAttachment']){const old=window[name];window[name]=async function(id,module='homework'){if(!active()||module!=='teacherlog')return old.apply(this,arguments);try{const f=await schoolHubTransport.server.request('/api/v1/work-log-files/'+encodeURIComponent(id)),bytes=Uint8Array.from(atob(f.content),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:f.type}));if(name==='previewAttachment'&&(f.type.startsWith('image/')||f.type==='application/pdf')){const tag=f.type==='application/pdf'?'iframe':'img';openModal(esc(f.name),'<'+tag+' src="'+url+'" style="width:100%;height:70vh;object-fit:contain;border:0"></'+tag+'>');setTimeout(()=>URL.revokeObjectURL(url),60000);}else{const a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){alert(e.message);}};}
const priorShow=window.showTab;window.showTab=function(tab){const result=priorShow.apply(this,arguments);if(active()&&tab==='teacherlog')load().catch(e=>{if($('teacherlog'))$('teacherlog').textContent=e.message;});return result;};
window.schoolHubWorkLogServer=Object.freeze({handles:tab=>tab==='teacherlog',active,load,save,refs:()=>reference,year:()=>reference.years[0]?.name||'',suggestion:()=>{const a=[...new Set(suggestion())];return a.length===1?a[0]:'';}});
if(active()){state.teacherWorkLogs=[];state.teacherLogs=[];}
})();
