import { randomUUID } from 'node:crypto';
import type { Queryable } from '../database/types.js';
import type { Principal } from './service.js';
import { ApiError } from '../errors/api-error.js';
import { serverPermissionKeysForGrant,workspaceManifest,type AuthorizationAction } from './policy-registry.js';
import { getCapabilities,type RecordSecurityContext } from './policy-engine.js';
export const ACCESS_ROLES=['View Records','Add Records','Edit Records','Delete Records','Permanent Delete Records','Print Records','View Attachments','Add Attachments','View Change Log','Run Imports','Setup Administration','View Own Records','View Assigned Records','View Group Records','View Class Records','View Section Records','View Audience Records','View All Workspace Records'] as const;
export type AccessRole=typeof ACCESS_ROLES[number]; export type AccessMode='Off'|'Preview'|'Audit'|'Enforced'|'Rollback';
export const AUDIENCE_TYPES=['Private','Selected groups','Selected individuals','Class','Section','Entire workspace','Global'] as const;
export async function accessMode(db:Queryable,schoolId:string):Promise<AccessMode>{return (await db.query<any>('SELECT mode FROM access_control_settings WHERE school_id=$1',[schoolId])).rows[0]?.mode||'Off'}
export async function effectiveRoles(db:Queryable,schoolId:string,userId:string,workspaceId:string){
 const rows=(await db.query<any>(`SELECT DISTINCT arg.action_key AS action,arg.scope_key AS scope,g.id AS "groupId",g.name AS "groupName",ar.id AS "namedRoleId",ar.name AS "namedRoleName"
  FROM access_group_memberships gm
  JOIN access_groups g ON g.id=gm.group_id AND g.school_id=gm.school_id AND g.active=true
  JOIN access_group_roles agr ON agr.group_id=g.id AND agr.school_id=g.school_id
  JOIN access_roles ar ON ar.id=agr.role_id AND ar.school_id=g.school_id AND ar.status='Active'
  JOIN access_role_grants arg ON arg.role_id=ar.id AND arg.school_id=ar.school_id
  WHERE gm.school_id=$1 AND gm.user_id=$2 AND ar.workspace_id=$3`,[schoolId,userId,workspaceId])).rows;
 const actionRoles:Record<string,AccessRole>={'record.view':'View Records','record.create':'Add Records','record.update':'Edit Records','record.archive':'Delete Records','record.permanent_delete':'Permanent Delete Records','record.print':'Print Records','attachment.view':'View Attachments','attachment.download':'View Attachments','attachment.upload':'Add Attachments','audit.view':'View Change Log'};
 const scopeRoles:Record<string,AccessRole>={OWNED:'View Own Records',DIRECT_ASSIGNED:'View Assigned Records',GROUP:'View Group Records',CLASS:'View Class Records',SECTION:'View Section Records',AUDIENCE:'View Audience Records',ALL_WORKSPACE:'View All Workspace Records'};
 const out=new Map<string,any>();
 for(const row of rows)for(const roleKey of [actionRoles[row.action],scopeRoles[row.scope]].filter(Boolean) as AccessRole[])out.set(roleKey+'|'+row.groupId+'|'+row.namedRoleId,{...row,roleKey});
 return [...out.values()].sort((a,b)=>String(a.roleKey).localeCompare(String(b.roleKey))||String(a.groupName).localeCompare(String(b.groupName)));
}
export async function hasSetupAdministration(db:Queryable,p:Principal){return !!(await db.query('SELECT 1 FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id JOIN access_group_global_roles ggr ON ggr.group_id=g.id AND ggr.school_id=g.school_id WHERE gm.school_id=$1 AND gm.user_id=$2 AND g.active=true AND ggr.role_key=$3 LIMIT 1',[p.schoolId,p.userId,'Setup Administration'])).rows[0]}
export async function requireSetupAdministration(db:Queryable,p:Principal){if(p.systemRecovery===true)return;if(await hasSetupAdministration(db,p))return;throw new ApiError('SETUP_ADMINISTRATION_REQUIRED','Setup Administration is required.',403)}export async function ensureLegacyMigration():Promise<never>{throw new ApiError('LEGACY_AUTHORIZATION_DISABLED','Legacy permission migration is disabled. Use Groups, named Workspace Roles, and normalized grants.',409)}
export type AudienceInput={audienceType:typeof AUDIENCE_TYPES[number];ownerUserId?:string|null;assignedUserId?:string|null;classId?:string|null;sectionId?:string|null;groupIds?:string[];userIds?:string[]};
export async function saveRecordAudience(db:Queryable,p:Principal,workspaceId:string,recordId:string,input:AudienceInput){if(!(await db.query('SELECT id FROM workspace_definitions WHERE id=$1 AND school_id=$2',[workspaceId,p.schoolId])).rows[0])throw new ApiError('WORKSPACE_NOT_FOUND','Workspace not found.',404);if(input.audienceType==='Class'&&!input.classId||input.audienceType==='Section'&&(!input.classId||!input.sectionId)||input.audienceType==='Selected groups'&&!input.groupIds?.length||input.audienceType==='Selected individuals'&&!input.userIds?.length)throw new ApiError('AUDIENCE_REFERENCE_REQUIRED','The selected audience requires its related scope.',422);if(input.classId&&!(await db.query('SELECT id FROM classes WHERE id=$1 AND school_id=$2',[input.classId,p.schoolId])).rows[0])throw new ApiError('INVALID_AUDIENCE_REFERENCE','Class is outside this school.',422);if(input.sectionId&&!(await db.query('SELECT id FROM sections WHERE id=$1 AND school_id=$2 AND class_id=$3',[input.sectionId,p.schoolId,input.classId])).rows[0])throw new ApiError('INVALID_AUDIENCE_REFERENCE','Section is outside the selected class.',422);for(const groupId of new Set(input.groupIds||[]))if(!(await db.query('SELECT id FROM access_groups WHERE id=$1 AND school_id=$2 AND active=true',[groupId,p.schoolId])).rows[0])throw new ApiError('INVALID_AUDIENCE_REFERENCE','A selected group is unavailable.',422);for(const userId of new Set(input.userIds||[]))if(!(await db.query("SELECT id FROM users WHERE id=$1 AND school_id=$2 AND status='Active'",[userId,p.schoolId])).rows[0])throw new ApiError('INVALID_AUDIENCE_REFERENCE','A selected user is unavailable.',422);await db.query('INSERT INTO record_access_controls(school_id,workspace_id,record_id,owner_user_id,assigned_user_id,audience_type,class_id,section_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(school_id,workspace_id,record_id) DO UPDATE SET owner_user_id=$4,assigned_user_id=$5,audience_type=$6,class_id=$7,section_id=$8,updated_at=CURRENT_TIMESTAMP,version=record_access_controls.version+1',[p.schoolId,workspaceId,recordId,input.ownerUserId||p.userId,input.assignedUserId||null,input.audienceType,input.classId||null,input.sectionId||null,p.userId]);await db.query('DELETE FROM record_audience_groups WHERE school_id=$1 AND workspace_id=$2 AND record_id=$3',[p.schoolId,workspaceId,recordId]);await db.query('DELETE FROM record_audience_users WHERE school_id=$1 AND workspace_id=$2 AND record_id=$3',[p.schoolId,workspaceId,recordId]);for(const groupId of new Set(input.groupIds||[]))await db.query('INSERT INTO record_audience_groups(school_id,workspace_id,record_id,group_id) VALUES($1,$2,$3,$4)',[p.schoolId,workspaceId,recordId,groupId]);for(const userId of new Set(input.userIds||[]))await db.query('INSERT INTO record_audience_users(school_id,workspace_id,record_id,user_id) VALUES($1,$2,$3,$4)',[p.schoolId,workspaceId,recordId,userId])}
async function scopes(db:Queryable,p:Principal){const classes=new Set<string>(),sections=new Set<string>();if(p.teacherId)for(const x of (await db.query<any>('SELECT class_id,section_id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$2 AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)',[p.schoolId,p.teacherId])).rows){classes.add(x.class_id);if(x.section_id)sections.add(x.section_id)}if(p.studentId){const x=(await db.query<any>("SELECT class_id,section_id FROM students WHERE id=$1 AND school_id=$2 AND status='Active'",[p.studentId,p.schoolId])).rows[0];if(x){classes.add(x.class_id);if(x.section_id)sections.add(x.section_id)}}if(p.guardianId)for(const x of (await db.query<any>("SELECT s.class_id,s.section_id FROM guardian_student_links gsl JOIN students s ON s.id=gsl.student_id AND s.school_id=gsl.school_id WHERE gsl.school_id=$1 AND gsl.guardian_id=$2 AND gsl.active=true AND s.status='Active'",[p.schoolId,p.guardianId])).rows){classes.add(x.class_id);if(x.section_id)sections.add(x.section_id)}return{classes,sections}}
export async function previewRecordAccess(db:Queryable,p:Principal,workspaceId:string,recordId:string){
 if(p.systemRecovery===true)return{allowed:true,reason:'SYSTEM_RECOVERY_AUTHORITY',matchedRoles:['System Administrator'],grants:[],audienceType:'System recovery'};
 const workspace=(await db.query<any>("SELECT workspace_key AS \"workspaceKey\" FROM workspace_definitions WHERE id=$1 AND school_id=$2 AND status<>'Archived'",[workspaceId,p.schoolId])).rows[0],policy=workspace?workspaceManifest(workspace.workspaceKey)[0]:null;
 if(!workspace||!policy)return{allowed:false,reason:'CENTRAL_POLICY_NOT_REGISTERED',matchedRoles:[],grants:[],audienceType:null};
 const record=(await db.query<any>('SELECT * FROM record_access_controls WHERE school_id=$1 AND workspace_id=$2 AND record_id=$3 AND archived=false',[p.schoolId,workspaceId,recordId])).rows[0];
 if(!record)return{allowed:false,reason:'CENTRAL_SECURITY_METADATA_REQUIRED',matchedRoles:[],grants:[],audienceType:null};
 const [groups,users]=await Promise.all([db.query<any>('SELECT group_id AS id FROM record_audience_groups WHERE school_id=$1 AND workspace_id=$2 AND record_id=$3',[p.schoolId,workspaceId,recordId]),db.query<any>('SELECT user_id AS id FROM record_audience_users WHERE school_id=$1 AND workspace_id=$2 AND record_id=$3',[p.schoolId,workspaceId,recordId])]);
 const audience=String(record.audience_type||''),audienceType=audience==='Selected groups'?'GROUP':audience==='Class'?'CLASS':audience==='Section'?'SECTION':audience==='Entire workspace'||audience==='Global'?'SCHOOL_PUBLISHED':'AUDIENCE';
 const context:RecordSecurityContext={schoolId:p.schoolId,workspaceKey:workspace.workspaceKey,resourceType:policy.resourceType,recordId,ownerUserId:record.owner_user_id||null,createdByUserId:record.created_by||null,assignedUserIds:record.assigned_user_id?[record.assigned_user_id]:[],recipientUserIds:users.rows.map((x:any)=>x.id),audienceGroupIds:groups.rows.map((x:any)=>x.id),audienceType,classId:record.class_id||null,sectionId:record.section_id||null,published:audienceType==='SCHOOL_PUBLISHED'};
 const allowed=(await getCapabilities(db,p,context,['record.view']))['record.view']===true;
 return{allowed,reason:allowed?'CENTRAL_GRANT_MATCHED':'NO_COMPLETE_GRANT',matchedRoles:[],grants:[],audienceType:record.audience_type};
}export async function assertRecordAccess(db:Queryable,p:Principal,workspaceId:string,recordId:string){const result=await previewRecordAccess(db,p,workspaceId,recordId);if(!result.allowed)throw new ApiError(result.reason,'Record access is denied.',403,result);return result}
export async function permissionsForUser(db:Queryable,p:Pick<Principal,'schoolId'|'userId'|'roleName'|'systemRecovery'|'permissions'>){
 const mode=await accessMode(db,p.schoolId),system=p.systemRecovery===true;
 if(system){const out=new Set<string>(),workspaces=(await db.query<any>("SELECT workspace_key AS key FROM workspace_definitions WHERE school_id=$1 AND status<>'Archived'",[p.schoolId])).rows;for(const {key} of workspaces)for(const action of ['view','create','update','delete','manage','print','permanent-delete'])out.add(key+':'+action);for(const permission of ['school:read','school:manage','core:manage','users:view','users:manage','imports:manage','audit:view','diagnostics:view','diagnostics:export','portal:manage','portal:admin','workspaces:view','workspaces:configure','workspaces:create','workspaces:archive','workspaces:reset'])out.add(permission);return{mode,permissions:[...out].sort(),authority:'SYSTEM_RECOVERY_ROLE' as const}}
 const grants=(await db.query<any>(`SELECT w.workspace_key AS "workspaceKey",arg.resource_type AS "resourceType",arg.action_key AS action,arg.scope_key AS scope
   FROM access_group_memberships gm
   JOIN access_groups g ON g.id=gm.group_id AND g.school_id=gm.school_id AND g.active=true
   JOIN access_group_roles agr ON agr.group_id=g.id AND agr.school_id=g.school_id
   JOIN access_roles ar ON ar.id=agr.role_id AND ar.school_id=g.school_id AND ar.status='Active'
   JOIN workspace_definitions w ON w.id=ar.workspace_id AND w.school_id=ar.school_id AND w.status<>'Archived'
   JOIN access_role_grants arg ON arg.role_id=ar.id AND arg.school_id=ar.school_id
   WHERE gm.school_id=$1 AND gm.user_id=$2`,[p.schoolId,p.userId])).rows;
 const out=new Set<string>();for(const grant of grants)for(const permission of serverPermissionKeysForGrant(grant.workspaceKey,grant.resourceType,grant.action as AuthorizationAction))out.add(permission);
 const setup=!!(await db.query("SELECT 1 FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id AND g.active=true JOIN access_group_global_roles ggr ON ggr.group_id=g.id AND ggr.school_id=g.school_id WHERE gm.school_id=$1 AND gm.user_id=$2 AND ggr.role_key='Setup Administration' LIMIT 1",[p.schoolId,p.userId])).rows[0];
 if(setup)for(const permission of ['users:view','users:manage','audit:view','diagnostics:view','diagnostics:export','portal:manage','school:read','school:manage','reports:view','reports:print','workflows:view','workflows:manage','workspaces:view','workspaces:configure','workspaces:create','workspaces:archive','workspaces:reset'])out.add(permission);
 return{mode,permissions:[...out].sort(),authority:'GROUP_ROLE_GRANT' as const};
}export async function enforceRecordPayload(db:Queryable,p:Principal,workspaceKey:string,payload:any){
 const workspace=(await db.query<any>('SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key=$2 AND status<>$3',[p.schoolId,workspaceKey,'Archived'])).rows[0];
 if(!workspace)throw new ApiError('WORKSPACE_ACCESS_NOT_CONFIGURED','Centralized access is not configured for this workspace.',403);
 const data=payload?.data;if(!data||typeof data!=='object')return payload;
 if(Array.isArray(data.items)){const allowed=[];for(const item of data.items){const id=String(item?.id||item?.recordId||'');if(id&&(await previewRecordAccess(db,p,workspace.id,id)).allowed)allowed.push(item)}return{...payload,data:{...data,items:allowed,total:allowed.length,hasNext:false}}}
 const id=String(data.id||data.recordId||'');if(id){const result=await previewRecordAccess(db,p,workspace.id,id);if(!result.allowed)throw new ApiError(result.reason,'Record access is denied.',403,result)}
 return payload;
}export function newAccessGroupId(){return randomUUID()}



