import { randomUUID } from 'node:crypto';
import type { Queryable } from '../database/types.js';
import type { Principal } from '../authorization/service.js';
import { ApiError } from '../errors/api-error.js';
import {authorizeArchivedLifecycle,resolveEffectiveGrants} from '../authorization/policy-engine.js';

type CoreKind='staff'|'classes'|'sections'|'subjects'|'academic_years'|'teacher_assignments';
const selects:Record<CoreKind,string>={
 staff:'id,employee_number AS "employeeNumber",name,role_name AS role,subject_snapshot AS "subjectSnapshot",phone,email,status,extra,created_at AS "createdAt",updated_at AS "updatedAt",version',
 classes:'id,name,active,created_at AS "createdAt",updated_at AS "updatedAt",version',
 sections:'id,class_id AS "classId",name,active,sort_order AS "sortOrder",created_at AS "createdAt",updated_at AS "updatedAt",version',
 subjects:'id,name,code,active,created_at AS "createdAt",updated_at AS "updatedAt",version',
 academic_years:'id,name,start_date AS "startDate",end_date AS "endDate",active,created_at AS "createdAt",updated_at AS "updatedAt",version',
 teacher_assignments:'id,teacher_id AS "teacherId",academic_year_id AS "academicYearId",class_id AS "classId",section_id AS "sectionId",subject_id AS "subjectId",assignment_type AS "assignmentType",valid_from AS "validFrom",valid_until AS "validUntil",active,created_at AS "createdAt",updated_at AS "updatedAt",version'
};
const labels:Record<CoreKind,string>={staff:'Staff record',classes:'Class',sections:'Section',subjects:'Subject',academic_years:'Academic year',teacher_assignments:'Teacher assignment'};
function conflict(label:string){return new ApiError('RECORD_VERSION_CONFLICT',label+' changed on another device. Refresh and review before saving.',409)}

export class CoreRelationshipRepository{
 constructor(private db:Queryable){}
 async list(p:Principal,kind:CoreKind){
  const mapping:Record<CoreKind,{workspace:string;resource:string}>={staff:{workspace:'staff',resource:'staff'},classes:{workspace:'classes',resource:'class'},sections:{workspace:'sections',resource:'section'},subjects:{workspace:'subjects',resource:'subject'},academic_years:{workspace:'academic-years',resource:'academic-year'},teacher_assignments:{workspace:'staff',resource:'teaching-assignment'}};
  const values:unknown[]=[p.schoolId],config=mapping[kind],grants=p.systemRecovery===true?[]:(await resolveEffectiveGrants(this.db,p,config.workspace,config.resource)).filter(grant=>grant.action==='record.view'),clauses:string[]=[];
  if(p.systemRecovery===true)clauses.push('TRUE');
  for(const grant of grants){if(grant.scope==='ALL_WORKSPACE')clauses.push('TRUE');else if(kind==='staff'&&grant.scope==='SELF'&&p.teacherId){values.push(p.teacherId);clauses.push(`id=$${values.length}`)}else if(kind==='classes'&&['ASSIGNED_CLASS','ASSIGNED_TEACHING_CONTEXT'].includes(grant.scope)&&p.teacherId){values.push(p.teacherId);clauses.push(`id IN (SELECT class_id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$${values.length} AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE))`)}else if(kind==='sections'&&['ASSIGNED_SECTION','ASSIGNED_TEACHING_CONTEXT'].includes(grant.scope)&&p.teacherId){values.push(p.teacherId);clauses.push(`(id IN (SELECT section_id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$${values.length} AND section_id IS NOT NULL AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)) OR class_id IN (SELECT class_id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$${values.length} AND section_id IS NULL AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)))`)}else if(kind==='subjects'&&grant.scope==='ASSIGNED_TEACHING_CONTEXT'&&p.teacherId){values.push(p.teacherId);clauses.push(`id IN (SELECT subject_id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$${values.length} AND subject_id IS NOT NULL AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE))`)}else if(kind==='academic_years'&&grant.scope==='ASSIGNED_TEACHING_CONTEXT'&&p.teacherId){values.push(p.teacherId);clauses.push(`id IN (SELECT academic_year_id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$${values.length} AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE))`)}else if(kind==='teacher_assignments'&&grant.scope==='SELF'&&p.teacherId){values.push(p.teacherId);clauses.push(`teacher_id=$${values.length}`)}}
  const lifecycle=kind==='staff'?"status='Active'":kind==='teacher_assignments'||kind==='classes'||kind==='sections'||kind==='subjects'||kind==='academic_years'?'active=true':'TRUE',where=`school_id=$1 AND (${clauses.length?clauses.join(' OR '):'FALSE'}) AND (${grants.some(grant=>grant.constraints.viewArchived===true)||p.systemRecovery===true?'TRUE':lifecycle})`,r=await this.db.query<any>(`SELECT ${selects[kind]} FROM ${kind} WHERE ${where} ORDER BY 1`,values);return{items:r.rows};
 }
 private async current(db:Queryable,p:Principal,kind:CoreKind,id:string){const r=await db.query<any>(`SELECT * FROM ${kind} WHERE id=$1 AND school_id=$2`,[id,p.schoolId]);if(!r.rows[0])throw new ApiError('RECORD_NOT_FOUND',labels[kind]+' not found.',404);return r.rows[0]}
 private async activeRef(db:Queryable,p:Principal,table:'staff'|'classes'|'sections'|'subjects'|'academic_years',id:string|null|undefined){if(!id)return null;const active=table==='staff'?"status='Active'":'active=true',r=await db.query<any>(`SELECT * FROM ${table} WHERE id=$1 AND school_id=$2 AND ${active}`,[id,p.schoolId]);if(!r.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','A selected '+labels[table].toLowerCase()+' is unavailable.',422);return r.rows[0]}
 async createStaff(db:Queryable,p:Principal,x:any){const id=randomUUID(),r=await db.query<any>(`INSERT INTO staff(id,school_id,employee_number,name,role_name,subject_snapshot,phone,email,status,extra) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING ${selects.staff}`,[id,p.schoolId,x.employeeNumber||null,x.name,x.role||'Teacher',x.subjectSnapshot||null,x.phone||null,x.email||null,x.status||'Active',JSON.stringify(x.extra||{})]);return r.rows[0]}
 async updateStaff(db:Queryable,p:Principal,id:string,x:any){const old=await this.current(db,p,'staff',id);if(old.version!==x.version)throw conflict('Staff record');const r=await db.query<any>(`UPDATE staff SET employee_number=$1,name=$2,role_name=$3,subject_snapshot=$4,phone=$5,email=$6,status=$7,extra=$8,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$9 AND school_id=$10 AND version=$11 RETURNING ${selects.staff}`,[x.employeeNumber===undefined?old.employee_number:x.employeeNumber,x.name??old.name,x.role??old.role_name,x.subjectSnapshot===undefined?old.subject_snapshot:x.subjectSnapshot,x.phone===undefined?old.phone:x.phone,x.email===undefined?old.email:x.email,x.status??old.status,JSON.stringify(x.extra??old.extra??{}),id,p.schoolId,x.version]);if(!r.rows[0])throw conflict('Staff record');return r.rows[0]}
 async deactivateStaff(db:Queryable,p:Principal,id:string,version:number){return this.deactivate(db,p,'staff',id,version)}
 async restoreStaff(db:Queryable,p:Principal,id:string,version:number){return this.restore(db,p,'staff',id,version)}
 async createClass(db:Queryable,p:Principal,x:any){const id=randomUUID(),r=await db.query<any>(`INSERT INTO classes(id,school_id,name,active) VALUES($1,$2,$3,$4) RETURNING ${selects.classes}`,[id,p.schoolId,x.name,x.active!==false]);return r.rows[0]}
 async updateClass(db:Queryable,p:Principal,id:string,x:any){return this.namedUpdate(db,p,'classes',id,x)}
 async deactivateClass(db:Queryable,p:Principal,id:string,version:number){return this.deactivate(db,p,'classes',id,version)}
 async restoreClass(db:Queryable,p:Principal,id:string,version:number){return this.restore(db,p,'classes',id,version)}
 async createSection(db:Queryable,p:Principal,x:any){await this.activeRef(db,p,'classes',x.classId);const id=randomUUID(),r=await db.query<any>(`INSERT INTO sections(id,school_id,class_id,name,active,sort_order) VALUES($1,$2,$3,$4,$5,$6) RETURNING ${selects.sections}`,[id,p.schoolId,x.classId,x.name,x.active!==false,x.sortOrder||0]);return r.rows[0]}
 async updateSection(db:Queryable,p:Principal,id:string,x:any){const old=await this.current(db,p,'sections',id);if(old.version!==x.version)throw conflict('Section');const classId=x.classId??old.class_id;await this.activeRef(db,p,'classes',classId);const r=await db.query<any>(`UPDATE sections SET class_id=$1,name=$2,active=$3,sort_order=$4,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$5 AND school_id=$6 AND version=$7 RETURNING ${selects.sections}`,[classId,x.name??old.name,x.active??old.active,x.sortOrder??old.sort_order,id,p.schoolId,x.version]);if(!r.rows[0])throw conflict('Section');return r.rows[0]}
 async reorderSections(db:Queryable,p:Principal,classId:string,items:{id:string;sortOrder:number;version:number}[]){await this.activeRef(db,p,'classes',classId);const rows=[];for(const x of items){const old=await this.current(db,p,'sections',x.id);if(old.class_id!==classId)throw new ApiError('INVALID_RECORD_REFERENCE','Every reordered section must belong to the selected class.',422);if(old.version!==x.version)throw conflict('Section');const r=await db.query<any>(`UPDATE sections SET sort_order=$1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND school_id=$3 AND class_id=$4 AND version=$5 RETURNING ${selects.sections}`,[x.sortOrder,x.id,p.schoolId,classId,x.version]);if(!r.rows[0])throw conflict('Section');rows.push(r.rows[0])}return rows}
 async deactivateSection(db:Queryable,p:Principal,id:string,version:number){return this.deactivate(db,p,'sections',id,version)}
 async restoreSection(db:Queryable,p:Principal,id:string,version:number){return this.restore(db,p,'sections',id,version)}
 async createSubject(db:Queryable,p:Principal,x:any){const id=randomUUID(),r=await db.query<any>(`INSERT INTO subjects(id,school_id,name,code,active) VALUES($1,$2,$3,$4,$5) RETURNING ${selects.subjects}`,[id,p.schoolId,x.name,x.code||null,x.active!==false]);return r.rows[0]}
 async updateSubject(db:Queryable,p:Principal,id:string,x:any){return this.namedUpdate(db,p,'subjects',id,x)}
 async deactivateSubject(db:Queryable,p:Principal,id:string,version:number){return this.deactivate(db,p,'subjects',id,version)}
 async createAcademicYear(db:Queryable,p:Principal,x:any){if(x.startDate&&x.endDate&&x.endDate<x.startDate)throw new ApiError('VALIDATION_FAILED','Academic year end date cannot be before its start date.',422);const id=randomUUID(),r=await db.query<any>(`INSERT INTO academic_years(id,school_id,name,start_date,end_date,active) VALUES($1,$2,$3,$4,$5,$6) RETURNING ${selects.academic_years}`,[id,p.schoolId,x.name,x.startDate||null,x.endDate||null,x.active!==false]);return r.rows[0]}
 async updateAcademicYear(db:Queryable,p:Principal,id:string,x:any){const old=await this.current(db,p,'academic_years',id);if(old.version!==x.version)throw conflict('Academic year');const start=x.startDate===undefined?old.start_date:x.startDate,end=x.endDate===undefined?old.end_date:x.endDate;if(start&&end&&String(end)<String(start))throw new ApiError('VALIDATION_FAILED','Academic year end date cannot be before its start date.',422);const r=await db.query<any>(`UPDATE academic_years SET name=$1,start_date=$2,end_date=$3,active=$4,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$5 AND school_id=$6 AND version=$7 RETURNING ${selects.academic_years}`,[x.name??old.name,start,end,x.active??old.active,id,p.schoolId,x.version]);if(!r.rows[0])throw conflict('Academic year');return r.rows[0]}
 async validateAssignment(db:Queryable,p:Principal,x:any){await this.activeRef(db,p,'staff',x.teacherId);await this.activeRef(db,p,'academic_years',x.academicYearId);await this.activeRef(db,p,'classes',x.classId);const section=await this.activeRef(db,p,'sections',x.sectionId);if(section&&section.class_id!==x.classId)throw new ApiError('INVALID_RECORD_REFERENCE','The selected section does not belong to the selected class.',422);await this.activeRef(db,p,'subjects',x.subjectId);if(x.validFrom&&x.validUntil&&x.validUntil<x.validFrom)throw new ApiError('VALIDATION_FAILED','Assignment end date cannot be before its start date.',422)}
 async createAssignment(db:Queryable,p:Principal,x:any){await this.validateAssignment(db,p,x);const id=randomUUID(),r=await db.query<any>(`INSERT INTO teacher_assignments(id,school_id,teacher_id,academic_year_id,class_id,section_id,subject_id,assignment_type,valid_from,valid_until,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING ${selects.teacher_assignments}`,[id,p.schoolId,x.teacherId,x.academicYearId,x.classId,x.sectionId||null,x.subjectId||null,x.assignmentType,x.validFrom||null,x.validUntil||null,x.active!==false]);return r.rows[0]}
 async updateAssignment(db:Queryable,p:Principal,id:string,x:any){const old=await this.current(db,p,'teacher_assignments',id);if(old.version!==x.version)throw conflict('Teacher assignment');const n={teacherId:x.teacherId??old.teacher_id,academicYearId:x.academicYearId??old.academic_year_id,classId:x.classId??old.class_id,sectionId:x.sectionId===undefined?old.section_id:x.sectionId,subjectId:x.subjectId===undefined?old.subject_id:x.subjectId,assignmentType:x.assignmentType??old.assignment_type,validFrom:x.validFrom===undefined?old.valid_from:x.validFrom,validUntil:x.validUntil===undefined?old.valid_until:x.validUntil,active:x.active??old.active};await this.validateAssignment(db,p,n);const r=await db.query<any>(`UPDATE teacher_assignments SET teacher_id=$1,academic_year_id=$2,class_id=$3,section_id=$4,subject_id=$5,assignment_type=$6,valid_from=$7,valid_until=$8,active=$9,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$10 AND school_id=$11 AND version=$12 RETURNING ${selects.teacher_assignments}`,[n.teacherId,n.academicYearId,n.classId,n.sectionId,n.subjectId,n.assignmentType,n.validFrom,n.validUntil,n.active,id,p.schoolId,x.version]);if(!r.rows[0])throw conflict('Teacher assignment');return r.rows[0]}
 async deactivateAssignment(db:Queryable,p:Principal,id:string,version:number){return this.deactivate(db,p,'teacher_assignments',id,version)}
 async restoreAssignment(db:Queryable,p:Principal,id:string,version:number){return this.restore(db,p,'teacher_assignments',id,version)}
 async linkUser(db:Queryable,p:Principal,userId:string,x:any){const u=await db.query<any>('SELECT id,teacher_id,status,version FROM users WHERE id=$1 AND school_id=$2',[userId,p.schoolId]);if(!u.rows[0])throw new ApiError('USER_NOT_FOUND','User not found.',404);if(u.rows[0].version!==x.version)throw conflict('User');if(x.teacherId)await this.activeRef(db,p,'staff',x.teacherId);if(x.teacherId){const duplicate=await db.query<any>("SELECT id,username FROM users WHERE school_id=$1 AND teacher_id=$2 AND id<>$3 AND status='Active'",[p.schoolId,x.teacherId,userId]);if(duplicate.rows.length&&!x.allowDuplicate)throw new ApiError('DUPLICATE_TEACHER_LINK','This staff record is already linked to another active user.',409,{username:duplicate.rows[0].username});if(duplicate.rows.length&&!String(x.reason||'').trim())throw new ApiError('OVERRIDE_REASON_REQUIRED','Enter a reason for the duplicate link decision.',422)}const r=await db.query<any>('UPDATE users SET teacher_id=$1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND school_id=$3 AND version=$4 RETURNING id,role_id AS "roleId",teacher_id AS "teacherId",username,status,version',[x.teacherId||null,userId,p.schoolId,x.version]);if(!r.rows[0])throw conflict('User');return{row:r.rows[0],beforeTeacherId:u.rows[0].teacher_id||null}}
 private async namedUpdate(db:Queryable,p:Principal,kind:'classes'|'subjects',id:string,x:any){const old=await this.current(db,p,kind,id);if(old.version!==x.version)throw conflict(labels[kind]);const code=kind==='subjects'?(x.code===undefined?old.code:x.code):undefined;const r=await db.query<any>(kind==='subjects'?`UPDATE subjects SET name=$1,code=$2,active=$3,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND school_id=$5 AND version=$6 RETURNING ${selects.subjects}`:`UPDATE classes SET name=$1,active=$2,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$3 AND school_id=$4 AND version=$5 RETURNING ${selects.classes}`,kind==='subjects'?[x.name??old.name,code,x.active??old.active,id,p.schoolId,x.version]:[x.name??old.name,x.active??old.active,id,p.schoolId,x.version]);if(!r.rows[0])throw conflict(labels[kind]);return r.rows[0]}
 private async deactivate(db:Queryable,p:Principal,kind:CoreKind,id:string,version:number){const old=await this.current(db,p,kind,id);if(old.version!==version)throw conflict(labels[kind]);const status=kind==='staff'?"status='Inactive'":'active=false',r=await db.query<any>(`UPDATE ${kind} SET ${status},version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING ${selects[kind]}`,[id,p.schoolId,version]);if(!r.rows[0])throw conflict(labels[kind]);return r.rows[0]}
 private async restore(db:Queryable,p:Principal,kind:'staff'|'classes'|'sections'|'teacher_assignments',id:string,version:number){const old=await this.current(db,p,kind,id);const workspaceKey=kind==='teacher_assignments'?'staff':kind,resourceType=kind==='teacher_assignments'?'teaching-assignment':kind==='classes'?'class':kind==='sections'?'section':'staff';await authorizeArchivedLifecycle(db,p,'record.restore',{schoolId:p.schoolId,workspaceKey,resourceType,recordId:id,lifecycle:(kind==='staff'?old.status==='Inactive':old.active===false)?'Archived':'Active',subjectStaffIds:kind==='staff'?[id]:old.teacher_id?[old.teacher_id]:[],classId:kind==='classes'?id:old.class_id||null,sectionId:kind==='sections'?id:old.section_id||null,academicYearId:old.academic_year_id||null});if(old.version!==version)throw conflict(labels[kind]);const status=kind==='staff'?"status='Active'":'active=true',r=await db.query<any>(`UPDATE ${kind} SET ${status},version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING ${selects[kind]}`,[id,p.schoolId,version]);if(!r.rows[0])throw conflict(labels[kind]);return r.rows[0]}
}
