import { randomUUID } from 'node:crypto';
import type { Queryable } from '../database/types.js';
import type { Principal } from '../authorization/service.js';
import { ApiError } from '../errors/api-error.js';
import {resolveEffectiveGrants,type EffectiveGrant,type WorkspaceTabKey} from '../authorization/policy-engine.js';

export type StudentInput={admissionNumber:string;name:string;classId:string;sectionId?:string|null;academicYearId?:string|null;status?:'Active'|'Inactive'|'Alumni';fatherName?:string|null;email?:string|null;phone?:string|null;address?:string|null;dateOfBirth?:string|null;extra?:Record<string,unknown>};
const select=`s.id,s.admission_number AS "admissionNumber",s.name,s.class_id AS "classId",s.section_id AS "sectionId",s.academic_year_id AS "academicYearId",s.status,s.father_name AS "fatherName",s.email,s.phone,s.address,s.date_of_birth AS "dateOfBirth",s.extra,s.created_at AS "createdAt",s.updated_at AS "updatedAt",s.version`;
function visible(row:any,p:Principal,grants:readonly EffectiveGrant[]=[]){const extra=row?.extra&&typeof row.extra==='object'?Object.fromEntries(Object.entries(row.extra).filter(([key])=>key!=='workspaceCustomFields')):row?.extra,clean={...row,extra};if(p.systemRecovery===true||grants.some(grant=>grant.constraints.viewConfidential===true))return clean;const {fatherName,email,phone,address,dateOfBirth,...safe}=clean;return safe;}
export class StudentRepository{
 constructor(private db:Queryable){}
 private async authorizationScope(p:Principal,action:'record.view'|'record.print',values:unknown[],tabKey:WorkspaceTabKey='MAIN'){
  if(p.systemRecovery===true)return{where:'TRUE',grants:[] as EffectiveGrant[]};
  const grants=(await resolveEffectiveGrants(this.db,p,'students','student',tabKey)).filter(grant=>grant.action===action),clauses:string[]=[];
  for(const grant of grants){let relationship='FALSE';if(grant.scope==='ALL_WORKSPACE')relationship='TRUE';else if(grant.scope==='SELF'&&p.studentId){values.push(p.studentId);relationship=`s.id=$${values.length}`}else if(grant.scope==='CHILD_PERSONAL'&&p.guardianId){values.push(p.guardianId);relationship=`EXISTS(SELECT 1 FROM guardian_student_links gsl WHERE gsl.school_id=s.school_id AND gsl.student_id=s.id AND gsl.guardian_id=$${values.length} AND gsl.active=true)`}else if(grant.scope==='ASSIGNED_STUDENT'&&p.teacherId){values.push(p.teacherId);relationship=`EXISTS(SELECT 1 FROM teacher_assignments ta WHERE ta.school_id=s.school_id AND ta.teacher_id=$${values.length} AND ta.active=true AND ta.class_id=s.class_id AND (ta.section_id IS NULL OR ta.section_id=s.section_id) AND (ta.academic_year_id IS NULL OR s.academic_year_id IS NULL OR ta.academic_year_id=s.academic_year_id) AND (ta.valid_from IS NULL OR ta.valid_from<=CURRENT_DATE) AND (ta.valid_until IS NULL OR ta.valid_until>=CURRENT_DATE))`}if(relationship!=='FALSE')clauses.push(`(${relationship} AND (${grant.constraints.viewArchived===true?'TRUE':"s.status='Active'"}))`)}
  return{where:clauses.length?'('+clauses.join(' OR ')+')':'FALSE',grants};
 }
 async list(p:Principal,q:{search?:string;classId?:string;sectionId?:string;status?:string;page:number;pageSize:number},tabKey:WorkspaceTabKey='MAIN'){const values:unknown[]=[p.schoolId],scope=await this.authorizationScope(p,'record.view',values,tabKey);let where=`s.school_id=$1 AND ${scope.where}`;if(q.search){values.push('%'+q.search.replace(/[%_]/g,'\\$&')+'%');where+=` AND (s.name ILIKE $${values.length} ESCAPE '\\' OR s.admission_number ILIKE $${values.length} ESCAPE '\\')`;}if(q.classId){values.push(q.classId);where+=` AND s.class_id=$${values.length}`;}if(q.sectionId){values.push(q.sectionId);where+=` AND s.section_id=$${values.length}`;}if(q.status){values.push(q.status);where+=` AND s.status=$${values.length}`;}const count=await this.db.query<{count:string}>(`SELECT count(DISTINCT s.id)::text count FROM students s WHERE ${where}`,values);values.push(q.pageSize,(q.page-1)*q.pageSize);const rows=await this.db.query<any>(`SELECT DISTINCT ${select} FROM students s WHERE ${where} ORDER BY s.name,s.id LIMIT $${values.length-1} OFFSET $${values.length}`,values);return{items:rows.rows.map(x=>visible(x,p,scope.grants)),page:q.page,pageSize:q.pageSize,total:Number(count.rows[0]?.count||0)};}
 async get(p:Principal,id:string,tabKey:WorkspaceTabKey='MAIN'){const values:unknown[]=[p.schoolId,id],scope=await this.authorizationScope(p,'record.view',values,tabKey);const r=await this.db.query<any>(`SELECT ${select} FROM students s WHERE s.school_id=$1 AND s.id=$2 AND ${scope.where}`,values);if(!r.rows[0])throw new ApiError('STUDENT_NOT_FOUND','Student not found or outside your access.',404);return visible(r.rows[0],p,scope.grants);}
 async validateRefs(p:Principal,input:StudentInput){const c=await this.db.query('SELECT id FROM classes WHERE id=$1 AND school_id=$2 AND active=true',[input.classId,p.schoolId]);if(!c.rows.length)throw new ApiError('INVALID_RECORD_REFERENCE','Select a valid class.',422);if(input.sectionId){const s=await this.db.query('SELECT id FROM sections WHERE id=$1 AND class_id=$2 AND school_id=$3 AND active=true',[input.sectionId,input.classId,p.schoolId]);if(!s.rows.length)throw new ApiError('INVALID_RECORD_REFERENCE','Select a valid section for this class.',422);}if(input.academicYearId){const y=await this.db.query('SELECT id FROM academic_years WHERE id=$1 AND school_id=$2',[input.academicYearId,p.schoolId]);if(!y.rows.length)throw new ApiError('INVALID_RECORD_REFERENCE','Select a valid academic year.',422);}}
 async create(db:Queryable,p:Principal,input:StudentInput){const id=randomUUID();const r=await db.query<any>(`INSERT INTO students(id,school_id,admission_number,name,class_id,section_id,academic_year_id,status,father_name,email,phone,address,date_of_birth,extra) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING ${select.replaceAll('s.','')}`,[id,p.schoolId,input.admissionNumber,input.name,input.classId,input.sectionId||null,input.academicYearId||null,input.status||'Active',input.fatherName||null,input.email||null,input.phone||null,input.address||null,input.dateOfBirth||null,JSON.stringify(input.extra||{})]);return visible(r.rows[0],p);}
 async update(db:Queryable,p:Principal,id:string,input:Partial<StudentInput>,version:number){const current=await db.query<any>('SELECT * FROM students WHERE id=$1 AND school_id=$2',[id,p.schoolId]);if(!current.rows[0])throw new ApiError('STUDENT_NOT_FOUND','Student not found.',404);if(current.rows[0].version!==version)throw new ApiError('RECORD_VERSION_CONFLICT','This student changed on another device. Refresh and review before saving.',409);const x=current.rows[0],next={admissionNumber:input.admissionNumber??x.admission_number,name:input.name??x.name,classId:input.classId??x.class_id,sectionId:input.sectionId===undefined?x.section_id:input.sectionId,academicYearId:input.academicYearId===undefined?x.academic_year_id:input.academicYearId,status:input.status??x.status,fatherName:input.fatherName===undefined?x.father_name:input.fatherName,email:input.email===undefined?x.email:input.email,phone:input.phone===undefined?x.phone:input.phone,address:input.address===undefined?x.address:input.address,dateOfBirth:input.dateOfBirth===undefined?x.date_of_birth:input.dateOfBirth,extra:input.extra??x.extra};const r=await db.query<any>(`UPDATE students SET admission_number=$1,name=$2,class_id=$3,section_id=$4,academic_year_id=$5,status=$6,father_name=$7,email=$8,phone=$9,address=$10,date_of_birth=$11,extra=$12,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$13 AND school_id=$14 AND version=$15 RETURNING ${select.replaceAll('s.','')}`,[next.admissionNumber,next.name,next.classId,next.sectionId,next.academicYearId,next.status,next.fatherName,next.email,next.phone,next.address,next.dateOfBirth,JSON.stringify(next.extra||{}),id,p.schoolId,version]);if(!r.rows[0])throw new ApiError('RECORD_VERSION_CONFLICT','This student changed on another device. Refresh and review before saving.',409);return visible(r.rows[0],p);}
 async deactivate(db:Queryable,p:Principal,id:string,version:number){const r=await db.query<any>(`UPDATE students SET status='Inactive',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING ${select.replaceAll('s.','')}`,[id,p.schoolId,version]);if(!r.rows[0])throw new ApiError('RECORD_VERSION_CONFLICT','This student changed on another device. Refresh and review before saving.',409);return visible(r.rows[0],p);}
 async restore(db:Queryable,p:Principal,id:string,version:number){const r=await db.query<any>(`UPDATE students SET status='Active',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND status='Inactive' AND version=$3 RETURNING ${select.replaceAll('s.','')}`,[id,p.schoolId,version]);if(!r.rows[0])throw new ApiError('RECORD_VERSION_CONFLICT','This archived student changed or is already active. Refresh and review before restoring.',409);return visible(r.rows[0],p);}
}
