import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AppConfig } from '../config/index.js';
import type { Database, Queryable } from '../database/types.js';
import { ApiError } from '../errors/api-error.js';
import { authenticate } from '../auth/security.js';
import {requirePermission,type Principal} from '../authorization/service.js';
import {authorizeWorkspaceAction} from '../authorization/policy-engine.js';
import { writeAudit } from '../audit/service.js';
import { AcademicService } from '../services/academic-service.js';

const id=z.string().min(1).max(120),nullableId=id.nullable().optional(),version=z.number().int().positive();
const date=z.string().date(),time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/);
const attachment=z.object({name:z.string().min(1).max(240),size:z.number().int().min(0).max(25*1024*1024),type:z.string().max(120).optional()}).strict();
const attendance=z.object({date,period:z.string().min(1).max(80).default('Full Day'),rows:z.array(z.object({studentId:id,status:z.string().trim().min(1).max(200),arrivalTime:time.nullable().optional(),remark:z.string().max(500).optional(),version:version.optional()}).strict()).min(1).max(500)}).strict();
const homework=z.object({academicYearId:nullableId,classId:id,sectionId:nullableId,subjectId:nullableId,teacherId:nullableId,title:z.string().trim().min(1).max(200),instructions:z.string().max(4000).default(''),assignedDate:date,dueDate:date.nullable().optional(),attachmentMetadata:z.array(attachment).max(10).default([])}).strict();
const homeworkUpdate=z.object({title:z.string().trim().min(1).max(200).optional(),instructions:z.string().max(4000).optional(),dueDate:date.nullable().optional(),attachmentMetadata:z.array(attachment).max(10).optional(),version}).strict();
const timetable=z.object({academicYearId:id,classId:id,sectionId:nullableId,subjectId:id,teacherId:id,day:z.enum(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']),periodKey:z.string().trim().min(1).max(120),room:z.string().trim().max(80).nullable().optional(),notes:z.string().trim().max(1000).nullable().optional(),startTime:time.nullable().optional(),endTime:time.nullable().optional()}).strict();
const timetableUpdate=timetable.partial().extend({version}).strict();
const period=z.object({name:z.string().trim().min(1).max(80),periodType:z.enum(['Teaching Period','Assembly','Short Break','Lunch','Activity']),startTime:time,endTime:time.optional(),durationMinutes:z.number().int().min(1).max(600).optional(),sortOrder:z.number().int().min(0).max(1000)}).strict();
const periodUpdate=period.partial().extend({version}).strict();
const exam=z.object({academicYearId:id,classId:id,sectionId:nullableId,subjectId:nullableId,name:z.string().trim().min(1).max(200),examDate:date.nullable().optional(),maxMarks:z.number().positive().max(100000),passingMarks:z.number().min(0).max(100000).nullable().optional()}).strict();
const examUpdate=exam.partial().extend({version}).strict();
const marks=z.object({examId:id,examVersion:version.optional(),rows:z.array(z.object({studentId:id,marks:z.number().min(0).nullable().optional(),absent:z.boolean().default(false),version:version.optional()}).strict()).min(1).max(500)}).strict();
const promotionRow=z.object({studentId:id,outcome:z.enum(['Promoted','Retained','Transferred','Inactive']).optional(),destinationClassId:nullableId,destinationSectionId:nullableId}).strict();
const promotion=z.object({sourceAcademicYearId:id,destinationAcademicYearId:id,classId:id.optional(),rows:z.array(promotionRow).max(2000).optional()}).strict();
const promotionCommit=promotion.extend({previewHash:z.string().length(64),operationKey:z.string().regex(/^[A-Za-z0-9._:-]{8,120}$/),confirmed:z.literal(true)}).strict();
function parsed<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApiError('VALIDATION_FAILED','The request contains invalid or protected fields.',422,{fields:result.error.issues.map(x=>x.path.join('.'))});return result.data}
function auth(db:Database,config:AppConfig,csrf=false){return async(req:FastifyRequest)=>authenticate(req,db,config,csrf)}
function principal(req:FastifyRequest){if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
async function audited<T>(db:Database,req:FastifyRequest,p:Principal,action:string,entityType:string,work:(tx:Queryable)=>Promise<T>,summary:Record<string,unknown>={}):Promise<T>{return db.transaction(async tx=>{const result=await work(tx);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action,entityType,outcome:'SUCCESS',correlationId:req.correlationId,summary});return result})}

export async function registerAcademicRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const service=new AcademicService(db);
 app.get('/api/v1/academic/attendance-options',{preHandler:auth(db,config)},async req=>({data:await service.attendanceOptions(principal(req))}));
 app.get('/api/v1/academic/attendance',{preHandler:auth(db,config)},async req=>({data:await service.attendance(principal(req),req.query as any)}));
 app.put('/api/v1/academic/attendance',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(attendance,req.body),items=await audited(db,req,p,'ATTENDANCE_BULK_SAVED','Attendance',tx=>service.saveAttendance(tx,p,input),{date:input.date,period:input.period,count:input.rows.length});return{data:{items}}});
 app.post('/api/v1/academic/attendance/print-event',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'attendance','attendance-entry','record.print');await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'ATTENDANCE_REPORT_PRINTED',entityType:'Attendance',outcome:'SUCCESS',correlationId:req.correlationId,summary:req.body&&typeof req.body==='object'?req.body as Record<string,unknown>:{}});return{data:{recorded:true}}});

 app.get('/api/v1/academic/homework',{preHandler:auth(db,config)},async req=>({data:await service.homework(principal(req),req.query as any)}));
 app.post('/api/v1/academic/homework',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req),input=parsed(homework,req.body),row=await audited(db,req,p,'HOMEWORK_CREATED','Homework',tx=>service.createHomework(tx,p,input),{classId:input.classId});return reply.code(201).send({data:row})});
 app.patch('/api/v1/academic/homework/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(homeworkUpdate,req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'HOMEWORK_UPDATED','Homework',tx=>service.updateHomework(tx,p,recordId,input),{recordId})}});
 app.post('/api/v1/academic/homework/:id/publish',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'HOMEWORK_PUBLISHED','Homework',tx=>service.publishHomework(tx,p,recordId,input.version),{recordId})}});
 app.post('/api/v1/academic/homework/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'HOMEWORK_DEACTIVATED','Homework',tx=>service.deactivateHomework(tx,p,recordId,input.version),{recordId})}});

 app.get('/api/v1/academic/timetable',{preHandler:auth(db,config)},async req=>({data:await service.timetable(principal(req),req.query as any)}));
 app.get('/api/v1/academic/timetable-options',{preHandler:auth(db,config)},async req=>({data:await service.timetableOptions(principal(req))}));
 app.get('/api/v1/academic/timetable-periods',{preHandler:auth(db,config)},async req=>({data:await service.periods(principal(req))}));
 app.post('/api/v1/academic/timetable-periods',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req),input=parsed(period,req.body),row=await audited(db,req,p,'TIMETABLE_PERIOD_CREATED','Timetable Period',tx=>service.createPeriod(tx,p,input),{name:input.name,periodType:input.periodType});return reply.code(201).send({data:row})});
 app.patch('/api/v1/academic/timetable-periods/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(periodUpdate,req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'TIMETABLE_PERIOD_UPDATED','Timetable Period',tx=>service.updatePeriod(tx,p,recordId,input),{recordId})}});
 app.post('/api/v1/academic/timetable-periods/:id/move',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({direction:z.enum(['up','down']),version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'TIMETABLE_PERIOD_MOVED','Timetable Period',tx=>service.movePeriod(tx,p,recordId,input.direction,input.version),{recordId,direction:input.direction})}});
 app.post('/api/v1/academic/timetable-periods/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'TIMETABLE_PERIOD_DEACTIVATED','Timetable Period',tx=>service.deactivatePeriod(tx,p,recordId,input.version),{recordId})}});
 app.post('/api/v1/academic/timetable',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req),input=parsed(timetable,req.body),row=await audited(db,req,p,'TIMETABLE_ENTRY_CREATED','Timetable',tx=>service.createTimetable(tx,p,input),{day:input.day,periodKey:input.periodKey});return reply.code(201).send({data:row})});
 app.patch('/api/v1/academic/timetable/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(timetableUpdate,req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'TIMETABLE_ENTRY_UPDATED','Timetable',tx=>service.updateTimetable(tx,p,recordId,input),{recordId})}});
 app.post('/api/v1/academic/timetable/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'TIMETABLE_ENTRY_DEACTIVATED','Timetable',tx=>service.deactivateTimetable(tx,p,recordId,input.version),{recordId})}});
 app.post('/api/v1/academic/timetable/print-event',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'timetable','timetable-entry','record.print');await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'TIMETABLE_PRINTED',entityType:'Timetable',outcome:'SUCCESS',correlationId:req.correlationId,summary:req.body&&typeof req.body==='object'?req.body as Record<string,unknown>:{}});return{data:{recorded:true}}});

 app.get('/api/v1/academic/exams',{preHandler:auth(db,config)},async req=>({data:await service.exams(principal(req),req.query as any)}));
 app.post('/api/v1/academic/exams',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req),input=parsed(exam,req.body),row=await audited(db,req,p,'EXAM_CREATED','Exam',tx=>service.createExam(tx,p,input),{name:input.name});return reply.code(201).send({data:row})});
 app.patch('/api/v1/academic/exams/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(examUpdate,req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'EXAM_UPDATED','Exam',tx=>service.updateExam(tx,p,recordId,input),{recordId})}});
 app.post('/api/v1/academic/exams/:id/publish',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'EXAM_RESULTS_PUBLISHED','Exam',tx=>service.publishExam(tx,p,recordId,input.version),{recordId})}});
 app.post('/api/v1/academic/exams/:id/correction',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version,reason:z.string().trim().min(10).max(500)}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'EXAM_CORRECTION_OPENED','Exam',tx=>service.openCorrection(tx,p,recordId,input.version,input.reason),{recordId,reason:input.reason})}});
 app.post('/api/v1/academic/exams/:id/archive',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({version}).strict(),req.body),recordId=String((req.params as any).id);return{data:await audited(db,req,p,'EXAM_ARCHIVED','Exam',tx=>service.archiveExam(tx,p,recordId,input.version),{recordId})}});
 app.put('/api/v1/academic/marks',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(marks,req.body),items=await audited(db,req,p,'MARKS_BULK_SAVED','Mark',tx=>service.saveMarks(tx,p,input),{examId:input.examId,count:input.rows.length});return{data:{items}}});

 app.get('/api/v1/academic/report-cards/:studentId',{preHandler:auth(db,config)},async req=>{const q=req.query as any;if(!q.academicYearId)throw new ApiError('ACADEMIC_YEAR_REQUIRED','Select an academic year.',422);return{data:await service.reportCard(principal(req),String((req.params as any).studentId),String(q.academicYearId))}});
 app.post('/api/v1/academic/report-cards/:studentId/publish',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(z.object({academicYearId:id,confirmed:z.literal(true)}).strict(),req.body),studentId=String((req.params as any).studentId);return{data:await audited(db,req,p,'REPORT_CARD_PUBLISHED','Report Card',tx=>service.publishReport(tx,p,studentId,input.academicYearId),{studentId,academicYearId:input.academicYearId})}});

 app.post('/api/v1/academic/promotions/preview',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(promotion,req.body),preview=await service.promotionPreview(p,input);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'PROMOTION_PREVIEWED',entityType:'Promotion',outcome:'SUCCESS',correlationId:req.correlationId,summary:{sourceAcademicYearId:input.sourceAcademicYearId,destinationAcademicYearId:input.destinationAcademicYearId,count:preview.count}});return{data:preview}});
 app.post('/api/v1/academic/promotions/commit',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(promotionCommit,req.body);return{data:await service.commitPromotion(p,input,req.correlationId)}});
}
