import { randomUUID } from 'node:crypto';
import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AppConfig } from '../config/index.js';
import type { Database } from '../database/types.js';
import { authenticate } from '../auth/security.js';
import { ApiError } from '../errors/api-error.js';
import { writeAudit } from '../audit/service.js';
import { ACCESS_ROLES,AUDIENCE_TYPES,accessMode,effectiveRoles,newAccessGroupId,previewRecordAccess,requireSetupAdministration,saveRecordAudience,type AccessMode } from '../authorization/access-control.js';
import type { Principal } from '../authorization/service.js';
import {OPERATIONAL_WORKSPACE_KEYS} from '../services/workspace-service.js';
const modes=['Off','Preview','Audit','Enforced','Rollback'] as const,role=z.enum(ACCESS_ROLES),audience=z.enum(AUDIENCE_TYPES);
const groupCreate=z.object({name:z.string().trim().min(2).max(120),description:z.string().max(500).default(''),groupKind:z.enum(['Custom','Teachers','Students','Parents','Staff','Finance','Class','Section']).default('Custom'),managedScopeType:z.enum(['Class','Section','Student','Parent','Teacher','Staff']).nullable().optional(),managedScopeId:z.string().max(120).nullable().optional(),memberIds:z.array(z.string().max(120)).max(2000).default([])}).strict();
const assignment=z.object({roles:z.array(role).max(ACCESS_ROLES.length)}).strict();
const audienceInput=z.object({audienceType:audience,ownerUserId:z.string().max(120).nullable().optional(),assignedUserId:z.string().max(120).nullable().optional(),classId:z.string().max(120).nullable().optional(),sectionId:z.string().max(120).nullable().optional(),groupIds:z.array(z.string().max(120)).max(200).default([]),userIds:z.array(z.string().max(120)).max(200).default([])}).strict();
function auth(db:Database,c:AppConfig,csrf=false){return(req:FastifyRequest)=>authenticate(req,db,c,csrf)}
function principal(req:FastifyRequest){if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function parsed<T>(schema:z.ZodType<T>,value:unknown){const r=schema.safeParse(value);if(!r.success)throw new ApiError('VALIDATION_FAILED','Check the access-management fields.',422,{fields:r.error.issues.map(x=>x.path.join('.'))});return r.data}
async function workspace(db:Database,p:Principal,id:string){const row=(await db.query<any>('SELECT id,workspace_key AS "workspaceKey",name,status FROM workspace_definitions WHERE id=$1 AND school_id=$2',[id,p.schoolId])).rows[0];if(!row)throw new ApiError('WORKSPACE_NOT_FOUND','Workspace not found.',404);return row}
export async function registerAccessManagementRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 app.get('/api/v1/access-management',{preHandler:auth(db,config)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);const mode=await accessMode(db,p.schoolId),groups=(await db.query<any>('SELECT id,name,description,group_kind AS "groupKind",managed_scope_type AS "managedScopeType",managed_scope_id AS "managedScopeId",system,active,version FROM access_groups WHERE school_id=$1 ORDER BY system DESC,name',[p.schoolId])).rows,workspaces=(await db.query<any>('SELECT id,workspace_key AS "workspaceKey",name,status FROM workspace_definitions WHERE school_id=$1 AND (system=false OR workspace_key=ANY($2::text[])) ORDER BY name',[p.schoolId,[...OPERATIONAL_WORKSPACE_KEYS]])).rows,memberships=(await db.query<any>('SELECT group_id AS "groupId",user_id AS "userId" FROM access_group_memberships WHERE school_id=$1',[p.schoolId])).rows,workspaceAssignments=[] as any[],globalAssignments=(await db.query<any>('SELECT group_id AS "groupId",role_key AS "roleKey" FROM access_group_global_roles WHERE school_id=$1 ORDER BY role_key',[p.schoolId])).rows,assignments=[...workspaceAssignments,...globalAssignments.map(x=>({...x,workspaceId:null}))];return{data:{mode,availableModes:modes,roles:ACCESS_ROLES,visibilityRoles:ACCESS_ROLES.slice(10),groups,workspaces,memberships,assignments,legacyAuthorizationEnabled:false,authority:'Groups -> Workspace Roles -> normalized grants'}}});
 app.get('/api/v1/access-management/users',{preHandler:auth(db,config)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);const users=(await db.query<any>('SELECT id,username,status,teacher_id AS "teacherId",student_id AS "studentId",version FROM users WHERE school_id=$1 ORDER BY username',[p.schoolId])).rows,memberships=(await db.query<any>('SELECT gm.user_id AS "userId",g.id AS "groupId",g.name AS "groupName" FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id WHERE gm.school_id=$1 ORDER BY g.name',[p.schoolId])).rows,workspaceGrants=(await db.query<any>('SELECT gm.user_id AS "userId",g.id AS "groupId",g.name AS "groupName",w.id AS "workspaceId",w.name AS "workspaceName",ar.name AS "roleKey",ar.id AS "roleId" FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id JOIN access_group_roles agr ON agr.group_id=g.id AND agr.school_id=g.school_id JOIN access_roles ar ON ar.id=agr.role_id AND ar.school_id=agr.school_id JOIN workspace_definitions w ON w.id=ar.workspace_id AND w.school_id=ar.school_id WHERE gm.school_id=$1 AND g.active=true AND ar.status=$2 ORDER BY w.name,ar.name,g.name',[p.schoolId,'Active'])).rows,globalGrants=(await db.query<any>('SELECT gm.user_id AS "userId",g.id AS "groupId",g.name AS "groupName",ggr.role_key AS "roleKey" FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id JOIN access_group_global_roles ggr ON ggr.group_id=g.id WHERE gm.school_id=$1 AND g.active=true ORDER BY ggr.role_key,g.name',[p.schoolId])).rows,grants=[...workspaceGrants,...globalGrants.map(x=>({...x,workspaceId:null,workspaceName:'Global'}))];return{data:{items:users.map(u=>({...u,groups:memberships.filter(x=>x.userId===u.id),effectiveRoles:grants.filter(x=>x.userId===u.id)}))}}});
 app.post('/api/v1/access-management/groups',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await requireSetupAdministration(db,p);const input=parsed(groupCreate,req.body),id=newAccessGroupId();await db.transaction(async tx=>{await tx.query('INSERT INTO access_groups(id,school_id,name,description,group_kind,managed_scope_type,managed_scope_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,p.schoolId,input.name,input.description,input.groupKind,input.managedScopeType||null,input.managedScopeId||null,p.userId]);for(const userId of new Set(input.memberIds)){const user=(await tx.query("SELECT id FROM users WHERE id=$1 AND school_id=$2 AND status<>'Inactive'",[userId,p.schoolId])).rows[0];if(!user)throw new ApiError('INVALID_GROUP_MEMBER','A selected member is unavailable.',422);await tx.query('INSERT INTO access_group_memberships(school_id,group_id,user_id,created_by) VALUES($1,$2,$3,$4)',[p.schoolId,id,userId,p.userId])}await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'ACCESS_GROUP_CREATED',entityType:'Access Group',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{name:input.name,memberCount:new Set(input.memberIds).size}})});return reply.code(201).send({data:{id}})});
 app.put('/api/v1/access-management/groups/:id/members',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);const id=String((req.params as any).id),input=parsed(z.object({memberIds:z.array(z.string().max(120)).max(2000)}).strict(),req.body);await db.transaction(async tx=>{const group=(await tx.query<any>('SELECT id,system FROM access_groups WHERE id=$1 AND school_id=$2 AND active=true',[id,p.schoolId])).rows[0];if(!group)throw new ApiError('GROUP_NOT_FOUND','Group not found.',404);if(group.system)throw new ApiError('SYSTEM_GROUP_PROTECTED','Migrated and administration groups are maintained by the system.',409);if(input.memberIds.includes(p.userId)&&(await tx.query("SELECT 1 FROM access_group_global_roles WHERE school_id=$1 AND group_id=$2 AND role_key='Setup Administration' LIMIT 1",[p.schoolId,id])).rows[0])throw new ApiError('SELF_SETUP_ADMINISTRATION_GRANT_DENIED','You cannot add yourself to a group that grants Setup Administration.',403);await tx.query('DELETE FROM access_group_memberships WHERE group_id=$1 AND school_id=$2',[id,p.schoolId]);for(const userId of new Set(input.memberIds)){if(!(await tx.query("SELECT id FROM users WHERE id=$1 AND school_id=$2 AND status<>'Inactive'",[userId,p.schoolId])).rows[0])throw new ApiError('INVALID_GROUP_MEMBER','A selected member is unavailable.',422);await tx.query('INSERT INTO access_group_memberships(school_id,group_id,user_id,created_by) VALUES($1,$2,$3,$4)',[p.schoolId,id,userId,p.userId])}await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'ACCESS_GROUP_MEMBERS_CHANGED',entityType:'Access Group',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{memberCount:new Set(input.memberIds).size}})});return{data:{updated:true}}});
 app.put('/api/v1/access-management/groups/:groupId/workspaces/:workspaceId/roles',{preHandler:auth(db,config,true)},async()=>{throw new ApiError('LEGACY_AUTHORIZATION_DISABLED','Direct workspace-role assignments are disabled. Use Groups with named Workspace Roles and normalized grants.',410)});
 app.patch('/api/v1/access-management/rollout',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);const input=parsed(z.object({mode:z.enum(modes),version:z.number().int().positive().optional()}).strict(),req.body);const current=(await db.query<any>('SELECT mode,version FROM access_control_settings WHERE school_id=$1',[p.schoolId])).rows[0]||{mode:'Off',version:0};if(input.version!==undefined&&input.version!==current.version)throw new ApiError('RECORD_VERSION_CONFLICT','Access rollout changed on another device.',409);await db.transaction(async tx=>{await tx.query('INSERT INTO access_control_settings(school_id,mode,previous_mode,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(school_id) DO UPDATE SET previous_mode=access_control_settings.mode,mode=$2,updated_by=$4,updated_at=CURRENT_TIMESTAMP,version=access_control_settings.version+1',[p.schoolId,input.mode,current.mode,p.userId]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'ACCESS_ROLLOUT_MODE_CHANGED',entityType:'School',entityId:p.schoolId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{from:current.mode,to:input.mode}})});return{data:{mode:input.mode}}});
 app.put('/api/v1/access-management/workspaces/:workspaceId/records/:recordId/audience',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),workspaceId=String((req.params as any).workspaceId),recordId=String((req.params as any).recordId),input=parsed(audienceInput,req.body);const roles=await effectiveRoles(db,p.schoolId,p.userId,workspaceId);if(!roles.some(x=>x.roleKey==='Add Records'||x.roleKey==='Edit Records')&&!await hasSetup(db,p))throw new ApiError('RECORD_AUDIENCE_CHANGE_DENIED','Add Records or Edit Records is required.',403);await db.transaction(async tx=>{await saveRecordAudience(tx,p,workspaceId,recordId,input);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'RECORD_AUDIENCE_CHANGED',entityType:'Record Audience',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{workspaceId,audienceType:input.audienceType,groupCount:input.groupIds.length,userCount:input.userIds.length}})});return{data:{saved:true}}});
 app.get('/api/v1/access-management/workspaces/:workspaceId/records/:recordId/preview',{preHandler:auth(db,config)},async req=>{const p=principal(req),workspaceId=String((req.params as any).workspaceId),recordId=String((req.params as any).recordId),result=await previewRecordAccess(db,p,workspaceId,recordId),mode=await accessMode(db,p.schoolId);if(mode==='Audit')await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'RECORD_ACCESS_AUDITED',entityType:'Record',entityId:recordId,outcome:result.allowed?'SUCCESS':'DENIED',reasonCode:result.reason,correlationId:req.correlationId,summary:{workspaceId,matchedRoles:result.matchedRoles}});return{data:{...result,mode,enforced:mode==='Enforced'}}}); app.get('/api/v1/access-management/workspaces/:workspaceId/records/:recordId/access',{preHandler:auth(db,config)},async req=>{const p=principal(req),workspaceId=String((req.params as any).workspaceId),recordId=String((req.params as any).recordId),mode=await accessMode(db,p.schoolId),result=await previewRecordAccess(db,p,workspaceId,recordId);if(mode==='Audit')await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'RECORD_ACCESS_AUDITED',entityType:'Record',entityId:recordId,outcome:result.allowed?'SUCCESS':'DENIED',reasonCode:result.reason,correlationId:req.correlationId,summary:{workspaceId,matchedRoles:result.matchedRoles}});if(!result.allowed)throw new ApiError(result.reason,'Record access is denied.',403,result);return{data:{allowed:result.allowed,centralDecision:result.allowed,mode,reason:result.reason,matchedRoles:result.matchedRoles,legacyAuthorizationEnabled:false}}});
}
async function hasSetup(db:Database,p:Principal){try{await requireSetupAdministration(db,p);return true}catch{return false}}
