import {registerWorkspaceLayoutRoutes} from './workspace-layouts.js';
import { randomBytes, randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AppConfig } from '../config/index.js';
import type { Database, Queryable } from '../database/types.js';
import { ApiError } from '../errors/api-error.js';
import { hashPassword, validatePassword, verifyPassword } from '../auth/password.js';
import { authenticate, clearSessionCookie, setSessionCookie } from '../auth/security.js';
import { createSession, digest, revokeOtherSessions, revokeSession, rotateCsrf } from '../auth/sessions.js';
import { assertTeacherStudentScope, requirePermission, type Principal } from '../authorization/service.js';
import {enforceRecordPayload,permissionsForUser,requireSetupAdministration} from '../authorization/access-control.js';
import {authorizeArchivedLifecycle,authorizeCreate,authorizeRecord,authorizeUpdate,authorizeWorkspaceAction} from '../authorization/policy-engine.js';
import { writeAudit } from '../audit/service.js';
import { StudentRepository, type StudentInput } from '../repositories/student-repository.js';
import { CoreRelationshipRepository } from '../repositories/core-relationship-repository.js';
import { ImportService } from '../services/import-service.js';
import { logMetadata, redactDiagnostic } from '../logging/service.js';
import { PortalService } from '../services/portal-service.js';
import { registerProductionAuthorityRoutes } from './production-authority.js';
import { registerAcademicRoutes } from './academic.js';
import {registerExamWorkspaceRoutes} from './exam-workspace.js';
import {registerStandardWorkspaceRoutes} from './standard-workspaces.js';
import { registerHomeworkWorkspaceRoutes } from './homework-workspace.js';
import { registerWorkspaceRoutes } from './workspaces.js';
import { registerPicklistRoutes } from './picklists.js';
import { registerOperationalWorkspaceRoutes,validateOperationalCustomValues,validateStudentCustomValues } from './operational-workspaces.js';
import { registerCommunicationRoutes } from './communications.js';
import {registerCalendarWorkspaceRoutes} from './calendar-workspace.js';
import { registerCalendarRoutes } from './calendar-events.js';
import {registerDocumentWorkspaceRoutes} from './document-workspace.js';
import { registerSchoolContentRoutes } from './school-content.js';
import { registerResourceCatalogRoutes } from './resource-catalogs.js';
import { registerTransportRoutes } from './transport.js';
import { registerWorkLogRoutes } from './work-logs.js';
import {registerWorkLogWorkspaceRoutes} from './work-log-workspace.js';
import {registerLeaveWorkspaceRoutes} from './leave-workspace.js';
import { registerLeaveWorkflowRoutes } from './leave-workflows.js';
import { registerWorkflowTaskRoutes } from './workflow-tasks.js';
import { registerFeeRoutes } from './fees.js';
import { registerCertificateRoutes } from './certificates.js';
import { registerReportRoutes } from './reports.js';
import {nextWorkspaceNumber} from '../services/workspace-numbering.js';
import {registerPortalConfigurationRoutes} from './portal-configuration.js';
import {registerExperimentalFeatureRoutes} from './experimental-features.js';
import {effectivePortalMode,portalConfiguration} from '../services/portal-configuration.js';
import {registerExamLogisticsRoutes} from './exam-logistics.js';
import {registerCommunicationDeliveryRoutes} from './communication-delivery.js';
import {registerSpecialistOperationsRoutes} from './specialist-operations.js';
import {registerAccessManagementRoutes} from './access-management.js';
import {registerStandardAccessRoutes} from './access-management-standard.js';

const credentials=z.object({schoolSlug:z.string().min(1).max(80),username:z.string().min(1).max(120),password:z.string().min(1).max(256)}).strict();
const setup=z.object({schoolName:z.string().min(2).max(160),schoolSlug:z.string().regex(/^[a-z0-9-]{2,80}$/),username:z.string().min(3).max(120),password:z.string().max(256)}).strict();
const student=z.object({admissionNumber:z.string().min(1).max(80).optional(),name:z.string().min(1).max(180),classId:z.string().min(1).max(120),sectionId:z.string().max(120).nullable().optional(),academicYearId:z.string().max(120).nullable().optional(),status:z.enum(['Active','Inactive','Alumni']).optional(),fatherName:z.string().max(180).nullable().optional(),email:z.string().email().max(180).nullable().optional(),phone:z.string().max(40).nullable().optional(),address:z.string().max(500).nullable().optional(),dateOfBirth:z.string().date().nullable().optional(),extra:z.record(z.string(),z.unknown()).optional(),customValues:z.record(z.string().max(120),z.unknown()).optional()}).strict();
const updateStudent=student.partial().extend({version:z.number().int().positive()}).strict();
const versionOnly=z.object({version:z.number().int().positive()}).strict();
const staff=z.object({employeeNumber:z.string().max(80).nullable().optional(),name:z.string().min(1).max(180),role:z.string().min(1).max(80).optional(),subjectSnapshot:z.string().max(180).nullable().optional(),phone:z.string().max(40).nullable().optional(),email:z.string().email().max(180).nullable().optional(),status:z.enum(['Active','Inactive']).optional(),extra:z.record(z.string(),z.unknown()).optional(),customValues:z.record(z.string().max(120),z.unknown()).optional()}).strict();
const classRecord=z.object({name:z.string().min(1).max(120),active:z.boolean().optional()}).strict();
const section=z.object({classId:z.string().min(1).max(120),name:z.string().min(1).max(120),active:z.boolean().optional(),sortOrder:z.number().int().min(0).max(10000).optional()}).strict();
const subject=z.object({name:z.string().min(1).max(180),code:z.string().max(80).nullable().optional(),active:z.boolean().optional()}).strict();
const academicYear=z.object({name:z.string().min(1).max(80),startDate:z.string().date().nullable().optional(),endDate:z.string().date().nullable().optional(),active:z.boolean().optional()}).strict();
const assignment=z.object({teacherId:z.string().min(1).max(120),academicYearId:z.string().min(1).max(120),classId:z.string().min(1).max(120),sectionId:z.string().max(120).nullable().optional(),subjectId:z.string().max(120).nullable().optional(),assignmentType:z.enum(['ClassTeacher','SubjectTeacher','Substitute','Coordinator']),validFrom:z.string().date().nullable().optional(),validUntil:z.string().date().nullable().optional(),active:z.boolean().optional()}).strict();
const guardian=z.object({name:z.string().min(1).max(180),email:z.string().email().max(180).nullable().optional(),phone:z.string().max(40).nullable().optional()}).strict();
const portalUser=z.object({username:z.string().min(3).max(120),roleName:z.string().min(1).max(120),teacherId:z.string().max(120).nullable().optional(),studentId:z.string().max(120).nullable().optional(),guardianId:z.string().max(120).nullable().optional()}).strict();
const portalAttendance=z.object({date:z.string().date(),period:z.string().min(1).max(80).default('Full Day'),rows:z.array(z.object({studentId:z.string().min(1).max(120),status:z.enum(['Present','Absent','Late','Excused']),remark:z.string().max(500).optional()}).strict()).min(1).max(200)}).strict();
const portalHomework=z.object({classId:z.string().min(1).max(120),sectionId:z.string().max(120).nullable().optional(),subjectId:z.string().max(120).nullable().optional(),academicYearId:z.string().max(120).nullable().optional(),title:z.string().min(1).max(200),instructions:z.string().max(4000).default(''),assignedDate:z.string().date(),dueDate:z.string().date().nullable().optional()}).strict();
const portalMark=z.object({examId:z.string().min(1).max(120),studentId:z.string().min(1).max(120),marks:z.number().min(0).nullable().optional(),absent:z.boolean().default(false),version:z.number().int().positive().optional()}).strict();
const APPLICATION_VERSION='14.0.0-wm2';
function studentSecurityContext(p:Principal,row:any,tabKey?:'MAIN'|'GRID_1'|'GRID_2'|'GRID_3'){return{schoolId:p.schoolId,workspaceKey:'students',resourceType:'student',recordId:row.id?String(row.id):undefined,subjectStudentIds:row.id?[String(row.id)]:undefined,classId:row.classId||null,sectionId:row.sectionId||null,academicYearId:row.academicYearId||null,lifecycle:row.status==='Active'?'Active':'Archived',tabKey} as const}
async function coreSecurityContext(db:Queryable,p:Principal,workspaceKey:string,resourceType:string,table:'staff'|'classes'|'sections'|'subjects'|'academic_years'|'teacher_assignments',id?:string){
 if(!id)return{schoolId:p.schoolId,workspaceKey,resourceType} as const;
 const row=(await db.query<any>(`SELECT * FROM ${table} WHERE id=$1 AND school_id=$2`,[id,p.schoolId])).rows[0];if(!row)throw new ApiError('RECORD_NOT_FOUND','Record not found.',404);return{schoolId:p.schoolId,workspaceKey,resourceType,recordId:id,subjectStaffIds:table==='staff'?[id]:table==='teacher_assignments'?[row.teacher_id]:undefined,classId:table==='classes'?id:row.class_id||null,sectionId:table==='sections'?id:row.section_id||null,subjectId:table==='subjects'?id:row.subject_id||null,academicYearId:table==='academic_years'?id:row.academic_year_id||null,lifecycle:(table==='staff'?row.status==='Active':row.active===true)?'Active':'Archived'} as const;
}
const loginAttempts=new Map<string,{count:number;since:number}>();
const sensitive=new Set(['fatherName','email','phone','address','dateOfBirth']);
function parsed<T>(schema:z.ZodType<T>,value:unknown):T{const r=schema.safeParse(value);if(!r.success)throw new ApiError('VALIDATION_FAILED','The request contains invalid or protected fields.',422,{fields:r.error.issues.map(x=>x.path.join('.'))});return r.data;}
function auth(db:Database,config:AppConfig,csrf=false){return async(req:FastifyRequest)=>{await authenticate(req,db,config,csrf)};}
function principal(req:FastifyRequest){if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal;}
function pageQuery(q:any){const page=Math.max(1,Math.min(100000,Number(q?.page)||1)),pageSize=Math.max(1,Math.min(100,Number(q?.pageSize)||25));return{page,pageSize,search:String(q?.search||'').slice(0,120)};}
function studentQuery(q:any){return{...pageQuery(q),classId:String(q?.classId||'').slice(0,120),sectionId:String(q?.sectionId||'').slice(0,120),status:['Active','Inactive','Alumni'].includes(String(q?.status||''))?String(q.status):''};}
async function entityList(db:Queryable,p:Principal,table:string,columns:string){requirePermission(p,table==='users'?'users:view':'school:read');const r=await db.query<any>(`SELECT ${columns} FROM ${table} WHERE school_id=$1 ORDER BY 1 LIMIT 500`,[p.schoolId]);return{items:r.rows};}

export async function registerApi(app:FastifyInstance,db:Database,config:AppConfig){
 const imports=new ImportService(db),students=new StudentRepository(db),core=new CoreRelationshipRepository(db),portal=new PortalService(db);
 await registerProductionAuthorityRoutes(app,db,config);
 await registerAccessManagementRoutes(app,db,config);
 await registerStandardAccessRoutes(app,db,config);
 await registerPortalConfigurationRoutes(app,db,config);
 await registerExperimentalFeatureRoutes(app,db,config);
 await registerAcademicRoutes(app,db,config);
 await registerExamWorkspaceRoutes(app,db,config);
 await registerExamLogisticsRoutes(app,db,config);
 await registerStandardWorkspaceRoutes(app,db,config);
 await registerWorkLogWorkspaceRoutes(app,db,config);
 await registerHomeworkWorkspaceRoutes(app,db,config);
 await registerWorkspaceRoutes(app,db,config);
 await registerWorkspaceLayoutRoutes(app,db,config);
 await registerPicklistRoutes(app,db,config);
 await registerOperationalWorkspaceRoutes(app,db,config);
 await registerCommunicationRoutes(app,db,config);
 await registerCommunicationDeliveryRoutes(app,db,config);
 await registerSpecialistOperationsRoutes(app,db,config);
 await registerCalendarRoutes(app,db,config);
 await registerCalendarWorkspaceRoutes(app,db,config);
 await registerSchoolContentRoutes(app,db,config);
 await registerDocumentWorkspaceRoutes(app,db,config);
 await registerResourceCatalogRoutes(app,db,config);
 await registerTransportRoutes(app,db,config);
 await registerWorkLogRoutes(app,db,config);
 await registerLeaveWorkflowRoutes(app,db,config);
 await registerLeaveWorkspaceRoutes(app,db,config);
 await registerWorkflowTaskRoutes(app,db,config);
 await registerFeeRoutes(app,db,config);
 await registerCertificateRoutes(app,db,config);
 await registerReportRoutes(app,db,config);
 async function coreMutation(req:FastifyRequest,p:Principal,action:string,entityType:string,work:(tx:Queryable)=>Promise<any>,summary:Record<string,unknown>={}){return db.transaction(async tx=>{const row=await work(tx);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action,entityType,entityId:row.id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{...summary,version:row.version}});return row})}
 app.get('/health',async()=>({status:'ok',apiVersion:'v1'}));
 app.post('/api/v1/setup',async(req,reply)=>{const input=parsed(setup,req.body);if(!validatePassword(input.password))throw new ApiError('WEAK_PASSWORD','Use at least 12 characters with upper, lower, number, and symbol.',422);const count=await db.query<{count:string}>('SELECT count(*)::text count FROM schools');if(Number(count.rows[0]?.count||0)>0)throw new ApiError('SETUP_ALREADY_COMPLETED','Initial administrator setup is already complete.',409);const ids={school:randomUUID(),role:randomUUID(),user:randomUUID()};await db.transaction(async tx=>{await tx.query('INSERT INTO schools(id,name,slug) VALUES($1,$2,$3)',[ids.school,input.schoolName,input.schoolSlug]);await tx.query('INSERT INTO roles(id,school_id,name,system,active) VALUES($1,$2,$3,true,true)',[ids.role,ids.school,'System Administrator']);await tx.query('INSERT INTO users(id,school_id,role_id,username,password_hash) VALUES($1,$2,$3,$4,$5)',[ids.user,ids.school,ids.role,input.username,await hashPassword(input.password)]);await writeAudit(tx,{schoolId:ids.school,actorUserId:ids.user,action:'FIRST_ADMIN_CREATED',entityType:'User',entityId:ids.user,outcome:'SUCCESS',correlationId:req.correlationId});});return reply.code(201).send({data:{schoolId:ids.school,userId:ids.user}});});
 app.post('/api/v1/auth/login',async(req,reply)=>{const input=parsed(credentials,req.body),key=req.ip+'|'+input.schoolSlug+'|'+input.username.toLowerCase(),now=Date.now(),attempt=loginAttempts.get(key);if(attempt&&now-attempt.since<600000&&attempt.count>=5)throw new ApiError('LOGIN_RATE_LIMITED','Sign-in is temporarily unavailable. Try again later.',429);const found=await db.query<any>('SELECT u.*,r.name role_name FROM users u JOIN schools s ON s.id=u.school_id JOIN roles r ON r.id=u.role_id WHERE s.slug=$1 AND lower(u.username)=lower($2)',[input.schoolSlug,input.username]);const u=found.rows[0],valid=!!u&&await verifyPassword(u.password_hash,input.password).catch(()=>false);if(!valid){loginAttempts.set(key,{count:(attempt?.count||0)+1,since:attempt?.since||now});await writeAudit(db,{schoolId:u?.school_id||null,actorUserId:u?.id||null,action:'LOGIN_FAILURE',entityType:'User',entityId:u?.id,outcome:'FAILED',reasonCode:'INVALID_CREDENTIALS',correlationId:req.correlationId});throw new ApiError('INVALID_CREDENTIALS','Invalid school, username, or password.',401);}if(u.status!=='Active')throw new ApiError('ACCOUNT_DISABLED','This account is disabled.',403);loginAttempts.delete(key);const session=await createSession(db,u,config.sessionTtlMinutes,{ip:req.ip,userAgent:req.headers['user-agent']});setSessionCookie(reply,config,session.token,session.expiresAt);await writeAudit(db,{schoolId:u.school_id,actorUserId:u.id,action:'LOGIN_SUCCESS',entityType:'User',entityId:u.id,outcome:'SUCCESS',correlationId:req.correlationId});return{data:{user:{id:u.id,username:u.username,role:u.role_name,mustChangePassword:u.must_change_password,teacherId:u.teacher_id||null,studentId:u.student_id||null,guardianId:(await db.query<any>('SELECT guardian_id FROM user_guardian_links WHERE user_id=$1 AND school_id=$2',[u.id,u.school_id])).rows[0]?.guardian_id||null,permissions:(await permissionsForUser(db,{schoolId:u.school_id,userId:u.id,roleName:u.role_name,permissions:[]})).permissions},csrfToken:session.csrf,expiresAt:session.expiresAt.toISOString()}};});
 app.get('/api/v1/auth/session',{preHandler:auth(db,config)},async req=>{const p=principal(req),csrfToken=await rotateCsrf(db,req.sessionToken!);return{data:{user:{id:p.userId,username:p.username,role:p.roleName,teacherId:p.teacherId,studentId:p.studentId,guardianId:p.guardianId,permissions:p.permissions},authenticated:true,csrfToken}};});
 app.post('/api/v1/auth/logout',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await revokeSession(db,req.sessionToken!);clearSessionCookie(reply,config);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'LOGOUT',entityType:'User',entityId:p.userId,outcome:'SUCCESS',correlationId:req.correlationId});return{data:{loggedOut:true}};});
 app.post('/api/v1/auth/change-password',{preHandler:auth(db,config,true)},async(req)=>{const p=principal(req),input=parsed(z.object({currentPassword:z.string().min(1),newPassword:z.string().max(256)}).strict(),req.body);if(!validatePassword(input.newPassword))throw new ApiError('WEAK_PASSWORD','Use at least 12 characters with upper, lower, number, and symbol.',422);const row=await db.query<any>('SELECT password_hash FROM users WHERE id=$1 AND school_id=$2',[p.userId,p.schoolId]);if(!await verifyPassword(row.rows[0].password_hash,input.currentPassword))throw new ApiError('INVALID_CREDENTIALS','The current password is incorrect.',401);await db.transaction(async tx=>{await tx.query('UPDATE users SET password_hash=$1,must_change_password=false,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=$2',[await hashPassword(input.newPassword),p.userId]);await revokeOtherSessions(tx,p.userId,req.sessionToken!);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'PASSWORD_CHANGED',entityType:'User',entityId:p.userId,outcome:'SUCCESS',correlationId:req.correlationId});});return{data:{changed:true}};});
 app.post('/api/v1/auth/accept-invitation',async req=>{const input=parsed(z.object({token:z.string().min(32).max(256),newPassword:z.string().max(256)}).strict(),req.body);if(!validatePassword(input.newPassword))throw new ApiError('WEAK_PASSWORD','Use at least 12 characters with upper, lower, number, and symbol.',422);const invitation=await db.query<any>('SELECT * FROM password_invitations WHERE id_hash=$1 AND used_at IS NULL AND expires_at>now()',[digest(input.token)]);const invite=invitation.rows[0];if(!invite)throw new ApiError('INVITATION_INVALID','This password invitation is invalid or expired.',400);await db.transaction(async tx=>{await tx.query("UPDATE users SET password_hash=$1,must_change_password=false,status='Active',updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=$2 AND school_id=$3",[await hashPassword(input.newPassword),invite.user_id,invite.school_id]);await tx.query('UPDATE password_invitations SET used_at=CURRENT_TIMESTAMP WHERE id_hash=$1',[invite.id_hash]);await tx.query('DELETE FROM sessions WHERE user_id=$1',[invite.user_id]);await writeAudit(tx,{schoolId:invite.school_id,actorUserId:invite.user_id,action:'PASSWORD_INVITATION_ACCEPTED',entityType:'User',entityId:invite.user_id,outcome:'SUCCESS',correlationId:req.correlationId});});return{data:{passwordSet:true}};});

 app.get('/api/v1/users',{preHandler:auth(db,config)},async req=>({data:await entityList(db,principal(req),'users','id,role_id AS "roleId",teacher_id AS "teacherId",username,status,created_at AS "createdAt",updated_at AS "updatedAt",version')}));
 app.post('/api/v1/users/:id/password-invitation',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'users:manage');const userId=String((req.params as any).id),found=await db.query<any>('SELECT id FROM users WHERE id=$1 AND school_id=$2',[userId,p.schoolId]);if(!found.rows[0])throw new ApiError('USER_NOT_FOUND','User not found.',404);const token=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+24*60*60_000);await db.transaction(async tx=>{await tx.query('DELETE FROM password_invitations WHERE user_id=$1 AND used_at IS NULL',[userId]);await tx.query('INSERT INTO password_invitations(id_hash,user_id,school_id,expires_at,created_by) VALUES($1,$2,$3,$4,$5)',[digest(token),userId,p.schoolId,expiresAt,p.userId]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'PASSWORD_INVITATION_CREATED',entityType:'User',entityId:userId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{expiresAt:expiresAt.toISOString()}});});return reply.code(201).send({data:{token,expiresAt:expiresAt.toISOString()}});});
 app.get('/api/v1/staff',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'staff','staff','record.view');return{data:await core.list(p,'staff')}});
 app.post('/api/v1/staff',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeCreate(db,p,await coreSecurityContext(db,p,'staff','staff','staff'));const input=parsed(staff,req.body),row=await coreMutation(req,p,'STAFF_CREATED','Staff',async tx=>{if(!input.employeeNumber){const school=(await tx.query<any>('SELECT settings FROM schools WHERE id=$1',[p.schoolId])).rows[0],prefix=String(school?.settings?.employeePrefix||'EMP').slice(0,20);do{input.employeeNumber=await nextWorkspaceNumber(tx,p.schoolId,'staff',prefix+'{000}')}while((await tx.query('SELECT id FROM staff WHERE school_id=$1 AND employee_number=$2',[p.schoolId,input.employeeNumber])).rows.length)}const custom=await validateOperationalCustomValues(tx,p,'staff',input.customValues||{},input,'create');return core.createStaff(tx,p,{...input,extra:{...(input.extra||{}),workspaceCustomFields:custom}})},{employeeNumber:input.employeeNumber||null});return reply.code(201).send({data:row})});
 app.patch('/api/v1/staff/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(staff.partial().extend({version:z.number().int().positive()}).strict(),req.body),id=String((req.params as any).id),context=await coreSecurityContext(db,p,'staff','staff','staff',id);await authorizeUpdate(db,p,context,context);return{data:await coreMutation(req,p,'STAFF_UPDATED','Staff',async tx=>{if(input.customValues!==undefined){const old=(await tx.query<any>('SELECT extra FROM staff WHERE id=$1 AND school_id=$2',[id,p.schoolId])).rows[0]?.extra||{},custom=await validateOperationalCustomValues(tx,p,'staff',input.customValues,{...input,id},'edit');input.extra={...old,workspaceCustomFields:{...(old.workspaceCustomFields||{}),...custom}}}return core.updateStaff(tx,p,id,input)})}});
 app.post('/api/v1/staff/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.archive',await coreSecurityContext(db,p,'staff','staff','staff',id));const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'STAFF_DEACTIVATED','Staff',tx=>core.deactivateStaff(tx,p,id,input.version))}});
 app.post('/api/v1/staff/:id/restore',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.restore',await coreSecurityContext(db,p,'staff','staff','staff',id));const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'STAFF_RESTORED','Staff',tx=>core.restoreStaff(tx,p,id,input.version))}});
 app.post('/api/v1/staff/:id/print-event',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.print',await coreSecurityContext(db,p,'staff','staff','staff',id));const found=await db.query('SELECT id FROM staff WHERE id=$1 AND school_id=$2',[id,p.schoolId]);if(!found.rows[0])throw new ApiError('RECORD_NOT_FOUND','Staff record not found.',404);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'STAFF_PRINTED',entityType:'Staff',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});return{data:{recorded:true}}});

 app.get('/api/v1/classes',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'classes','class','record.view');return{data:await core.list(p,'classes')}});
 app.post('/api/v1/classes',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeCreate(db,p,await coreSecurityContext(db,p,'classes','class','classes'));const input=parsed(classRecord,req.body),row=await coreMutation(req,p,'CLASS_CREATED','Class',tx=>core.createClass(tx,p,input));return reply.code(201).send({data:row})});
 app.post('/api/v1/classes/bundle',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'core:manage');const input=parsed(z.object({name:z.string().min(1).max(120),sections:z.array(z.string().min(1).max(120)).max(100)}).strict(),req.body);const result=await db.transaction(async tx=>{const cls=await core.createClass(tx,p,{name:input.name}),sections=[];for(let i=0;i<input.sections.length;i++)sections.push(await core.createSection(tx,p,{classId:cls.id,name:input.sections[i],sortOrder:i}));await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'CLASS_WITH_SECTIONS_CREATED',entityType:'Class',entityId:cls.id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{sectionIds:sections.map(x=>x.id)}});return{...cls,sections}});return reply.code(201).send({data:result})});
 app.patch('/api/v1/classes/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'classes','class','record.update');const input=parsed(classRecord.partial().extend({version:z.number().int().positive()}).strict(),req.body);return{data:await coreMutation(req,p,'CLASS_UPDATED','Class',tx=>core.updateClass(tx,p,String((req.params as any).id),input))}});
 app.patch('/api/v1/classes/:id/bundle',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'classes','class','record.update');await authorizeWorkspaceAction(db,p,'sections','section','record.update');await authorizeWorkspaceAction(db,p,'sections','section','record.create');await authorizeWorkspaceAction(db,p,'sections','section','record.archive');const input=parsed(z.object({name:z.string().min(1).max(120),version:z.number().int().positive(),sections:z.array(z.string().min(1).max(120)).max(100)}).strict(),req.body),id=String((req.params as any).id);const result=await db.transaction(async tx=>{const cls=await core.updateClass(tx,p,id,{name:input.name,version:input.version}),found=await tx.query<any>('SELECT id,name,version FROM sections WHERE school_id=$1 AND class_id=$2',[p.schoolId,id]),used=new Set<string>(),sections=[];for(let i=0;i<input.sections.length;i++){const name=input.sections[i],same=found.rows.find(x=>!used.has(x.id)&&String(x.name).trim().toLowerCase()===name.trim().toLowerCase());if(same){used.add(same.id);sections.push(await core.updateSection(tx,p,same.id,{name,sortOrder:i,active:true,version:same.version}))}else sections.push(await core.createSection(tx,p,{classId:id,name,sortOrder:i}))}for(const old of found.rows.filter(x=>!used.has(x.id)))await core.deactivateSection(tx,p,old.id,old.version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'CLASS_SECTIONS_UPDATED',entityType:'Class',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{sectionIds:sections.map(x=>x.id)}});return{...cls,sections}});return{data:result}});
 app.post('/api/v1/classes/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'classes','class','record.archive');const input=parsed(versionOnly,req.body),id=String((req.params as any).id),deps=await Promise.all([db.query<{count:string}>("SELECT count(*)::text count FROM students WHERE school_id=$1 AND class_id=$2 AND status='Active'",[p.schoolId,id]),db.query<{count:string}>('SELECT count(*)::text count FROM teacher_assignments WHERE school_id=$1 AND class_id=$2 AND active=true',[p.schoolId,id]),db.query<{count:string}>('SELECT count(*)::text count FROM timetable_entries WHERE school_id=$1 AND class_id=$2 AND active=true',[p.schoolId,id]),db.query<{count:string}>("SELECT count(*)::text count FROM homework_records WHERE school_id=$1 AND class_id=$2 AND status<>'Inactive'",[p.schoolId,id]),db.query<{count:string}>("SELECT count(*)::text count FROM exam_records WHERE school_id=$1 AND class_id=$2 AND state<>'Inactive'",[p.schoolId,id])]),counts={students:Number(deps[0].rows[0]?.count||0),assignments:Number(deps[1].rows[0]?.count||0),timetable:Number(deps[2].rows[0]?.count||0),homework:Number(deps[3].rows[0]?.count||0),exams:Number(deps[4].rows[0]?.count||0)};if(Object.values(counts).some(Boolean))throw new ApiError('CLASS_HAS_ACTIVE_DEPENDENCIES','Archive or reassign active class dependencies first.',409,counts);return{data:await coreMutation(req,p,'CLASS_DEACTIVATED','Class',tx=>core.deactivateClass(tx,p,id,input.version))}});
 app.post('/api/v1/classes/:id/restore',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'classes','class','record.restore');const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'CLASS_RESTORED','Class',tx=>core.restoreClass(tx,p,String((req.params as any).id),input.version))}});

 app.get('/api/v1/sections',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'sections','section','record.view');return{data:await core.list(p,'sections')}});
 app.post('/api/v1/sections',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeCreate(db,p,await coreSecurityContext(db,p,'sections','section','sections'));const input=parsed(section,req.body),row=await coreMutation(req,p,'SECTION_CREATED','Section',tx=>core.createSection(tx,p,input));return reply.code(201).send({data:row})});
 app.patch('/api/v1/sections/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'sections','section','record.update');const input=parsed(section.partial().extend({version:z.number().int().positive()}).strict(),req.body),id=String((req.params as any).id),before=await db.query<any>('SELECT name FROM sections WHERE id=$1 AND school_id=$2',[id,p.schoolId]);return{data:await coreMutation(req,p,before.rows[0]?.name!==input.name&&input.name!==undefined?'SECTION_RENAMED':'SECTION_UPDATED','Section',tx=>core.updateSection(tx,p,id,input),{beforeName:before.rows[0]?.name||null,afterName:input.name||before.rows[0]?.name||null})}});
 app.post('/api/v1/sections/reorder',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'sections','section','record.update');const input=parsed(z.object({classId:z.string().min(1),items:z.array(z.object({id:z.string().min(1),sortOrder:z.number().int().min(0),version:z.number().int().positive()}).strict()).min(1)}).strict(),req.body);const rows=await db.transaction(async tx=>{const result=await core.reorderSections(tx,p,input.classId,input.items);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'SECTIONS_REORDERED',entityType:'Class',entityId:input.classId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{sectionIds:input.items.map(x=>x.id)}});return result});return{data:{items:rows}}});
 app.post('/api/v1/sections/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'sections','section','record.archive');const input=parsed(versionOnly,req.body),id=String((req.params as any).id),deps=await Promise.all([db.query<{count:string}>("SELECT count(*)::text count FROM students WHERE school_id=$1 AND section_id=$2 AND status='Active'",[p.schoolId,id]),db.query<{count:string}>('SELECT count(*)::text count FROM teacher_assignments WHERE school_id=$1 AND section_id=$2 AND active=true',[p.schoolId,id]),db.query<{count:string}>('SELECT count(*)::text count FROM timetable_entries WHERE school_id=$1 AND section_id=$2 AND active=true',[p.schoolId,id])]),counts={students:Number(deps[0].rows[0]?.count||0),assignments:Number(deps[1].rows[0]?.count||0),timetable:Number(deps[2].rows[0]?.count||0)};if(Object.values(counts).some(Boolean))throw new ApiError('SECTION_HAS_ACTIVE_DEPENDENCIES','Archive or reassign active section dependencies first.',409,counts);return{data:await coreMutation(req,p,'SECTION_DEACTIVATED','Section',tx=>core.deactivateSection(tx,p,id,input.version))}});
 app.post('/api/v1/sections/:id/restore',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'sections','section','record.restore');const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'SECTION_RESTORED','Section',tx=>core.restoreSection(tx,p,String((req.params as any).id),input.version))}});

 app.get('/api/v1/subjects',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'subjects','subject','record.view');return{data:await core.list(p,'subjects')}});
 app.post('/api/v1/subjects',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeCreate(db,p,{schoolId:p.schoolId,workspaceKey:'subjects',resourceType:'subject'});const input=parsed(subject,req.body),row=await coreMutation(req,p,'SUBJECT_CREATED','Subject',tx=>core.createSubject(tx,p,input));return reply.code(201).send({data:row})});
 app.patch('/api/v1/subjects/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.update',{schoolId:p.schoolId,workspaceKey:'subjects',resourceType:'subject',recordId:id});const input=parsed(subject.partial().extend({version:z.number().int().positive()}).strict(),req.body);return{data:await coreMutation(req,p,'SUBJECT_UPDATED','Subject',tx=>core.updateSubject(tx,p,id,input))}});
 app.post('/api/v1/subjects/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.archive',{schoolId:p.schoolId,workspaceKey:'subjects',resourceType:'subject',recordId:id});const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'SUBJECT_DEACTIVATED','Subject',tx=>core.deactivateSubject(tx,p,id,input.version))}});

 app.get('/api/v1/academic-years',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'academic-years','academic-year','record.view');return{data:await core.list(p,'academic_years')}});
 app.post('/api/v1/academic-years',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeCreate(db,p,{schoolId:p.schoolId,workspaceKey:'academic-years',resourceType:'academic-year'});const input=parsed(academicYear,req.body),row=await coreMutation(req,p,'ACADEMIC_YEAR_CREATED','Academic Year',tx=>core.createAcademicYear(tx,p,input));return reply.code(201).send({data:row})});
 app.patch('/api/v1/academic-years/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.update',{schoolId:p.schoolId,workspaceKey:'academic-years',resourceType:'academic-year',recordId:id});const input=parsed(academicYear.partial().extend({version:z.number().int().positive()}).strict(),req.body);return{data:await coreMutation(req,p,'ACADEMIC_YEAR_UPDATED','Academic Year',tx=>core.updateAcademicYear(tx,p,id,input))}});
 app.post('/api/v1/academic-years/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id);await authorizeRecord(db,p,'record.archive',{schoolId:p.schoolId,workspaceKey:'academic-years',resourceType:'academic-year',recordId:id});const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'ACADEMIC_YEAR_ARCHIVED','Academic Year',async tx=>{const school=(await tx.query<any>('SELECT active_academic_year_id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId])).rows[0];if(school?.active_academic_year_id===id)throw new ApiError('CURRENT_ACADEMIC_YEAR','Choose another current Academic Year before archiving this one.',409);return core.updateAcademicYear(tx,p,id,{active:false,version:input.version})})}});

 app.patch('/api/v1/users/:id/teacher-link',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(z.object({teacherId:z.string().max(120).nullable(),version:z.number().int().positive(),allowDuplicate:z.boolean().optional(),reason:z.string().max(500).optional()}).strict(),req.body),id=String((req.params as any).id);const result=await db.transaction(async tx=>{const linked=await core.linkUser(tx,p,id,input);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:input.teacherId?(linked.beforeTeacherId?'USER_TEACHER_LINK_CHANGED':'USER_TEACHER_LINK_CREATED'):'USER_TEACHER_LINK_CLEARED',entityType:'User',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{beforeTeacherId:linked.beforeTeacherId,afterTeacherId:input.teacherId||null,duplicateOverride:!!input.allowDuplicate,reason:input.reason||''}});return linked.row});return{data:result}});

 app.get('/api/v1/teacher-assignments',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'staff','teaching-assignment','record.view');return{data:await core.list(p,'teacher_assignments')}});
 app.post('/api/v1/teacher-assignments',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeCreate(db,p,await coreSecurityContext(db,p,'staff','teaching-assignment','teacher_assignments'));const input=parsed(assignment,req.body),row=await coreMutation(req,p,'TEACHER_ASSIGNMENT_CREATED','Teacher Assignment',tx=>core.createAssignment(tx,p,input));return reply.code(201).send({data:row})});
 app.patch('/api/v1/teacher-assignments/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'staff','teaching-assignment','record.update');const input=parsed(assignment.partial().extend({version:z.number().int().positive()}).strict(),req.body);return{data:await coreMutation(req,p,'TEACHER_ASSIGNMENT_UPDATED','Teacher Assignment',tx=>core.updateAssignment(tx,p,String((req.params as any).id),input))}});
 app.post('/api/v1/teacher-assignments/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'staff','teaching-assignment','record.archive');const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'TEACHER_ASSIGNMENT_DEACTIVATED','Teacher Assignment',tx=>core.deactivateAssignment(tx,p,String((req.params as any).id),input.version))}});
 app.post('/api/v1/teacher-assignments/:id/restore',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'staff','teaching-assignment','record.restore');const input=parsed(versionOnly,req.body);return{data:await coreMutation(req,p,'TEACHER_ASSIGNMENT_RESTORED','Teacher Assignment',tx=>core.restoreAssignment(tx,p,String((req.params as any).id),input.version))}});

 app.get('/api/v1/students',{preHandler:auth(db,config)},async req=>{const p=principal(req);return{data:await students.list(p,studentQuery(req.query))}});
 app.get('/api/v1/students/:id',{preHandler:auth(db,config)},async req=>{const p=principal(req);return{data:await students.get(p,(req.params as any).id)}});
 app.post('/api/v1/students',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req),input=parsed(student,req.body),tabKey=z.enum(['MAIN','GRID_1','GRID_2','GRID_3']).optional().default('MAIN').parse((req.query as any)?.tabKey);if(!!p.teacherId&&Object.keys(input).some(k=>sensitive.has(k)))throw new ApiError('FIELD_ACCESS_DENIED','Sensitive fields require an explicit disclosure grant.',403);const result=await db.transaction(async tx=>{const repo=new StudentRepository(tx);await repo.validateRefs(p,input as StudentInput);await authorizeCreate(tx,p,studentSecurityContext(p,input,tabKey));if(!input.admissionNumber){const school=(await tx.query<any>('SELECT settings FROM schools WHERE id=$1',[p.schoolId])).rows[0],prefix=String(school?.settings?.studentPrefix||'STU').slice(0,20);do{input.admissionNumber=await nextWorkspaceNumber(tx,p.schoolId,'students',prefix+'{000}')}while((await tx.query('SELECT id FROM students WHERE school_id=$1 AND admission_number=$2',[p.schoolId,input.admissionNumber])).rows.length)}const customValues=await validateStudentCustomValues(tx,p,input.customValues||{},input,'create',tabKey),studentInput={...input,extra:{...(input.extra||{}),workspaceCustomFields:customValues}},row=await repo.create(tx,p,studentInput as StudentInput);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'STUDENT_CREATED',entityType:'Student',entityId:row.id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{admissionNumber:row.admissionNumber,tabKey}});return row});return reply.code(201).send({data:result})});
 app.patch('/api/v1/students/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(updateStudent,req.body),id=String((req.params as any).id);if(!!p.teacherId&&Object.keys(input).some(k=>sensitive.has(k)))throw new ApiError('FIELD_ACCESS_DENIED','Sensitive fields require an explicit disclosure grant.',403);const result=await db.transaction(async tx=>{const repo=new StudentRepository(tx),current=await repo.get(p,id),candidate={...current,classId:input.classId||current.classId,sectionId:input.sectionId===undefined?current.sectionId:input.sectionId,academicYearId:input.academicYearId===undefined?current.academicYearId:input.academicYearId,admissionNumber:input.admissionNumber||current.admissionNumber,name:input.name||current.name};await authorizeUpdate(tx,p,studentSecurityContext(p,current),studentSecurityContext(p,candidate));if(input.customValues!==undefined){const raw=(await tx.query<any>('SELECT extra FROM students WHERE id=$1 AND school_id=$2',[id,p.schoolId])).rows[0]?.extra||{},customValues=await validateStudentCustomValues(tx,p,input.customValues,{...current,...candidate},'edit');input.extra={...raw,workspaceCustomFields:{...(raw.workspaceCustomFields||{}),...customValues}}}await repo.validateRefs(p,candidate as StudentInput);const row=await repo.update(tx,p,id,input,input.version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'STUDENT_UPDATED',entityType:'Student',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{version:row.version}});return row});return{data:result}});
 app.post('/api/v1/students/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),{version,reason}=parsed(z.object({version:z.number().int().positive(),reason:z.string().trim().max(500).optional()}).strict(),req.body),id=String((req.params as any).id);const result=await db.transaction(async tx=>{const repo=new StudentRepository(tx),current=await repo.get(p,id);await authorizeRecord(tx,p,'record.archive',studentSecurityContext(p,current));const row=await repo.deactivate(tx,p,id,version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'STUDENT_DEACTIVATED',entityType:'Student',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{reason:reason||null}});return row});return{data:result}});
 app.post('/api/v1/students/:id/restore',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),{version}=parsed(versionOnly,req.body),id=String((req.params as any).id);const result=await db.transaction(async tx=>{const repo=new StudentRepository(tx),current=await repo.get(p,id);await authorizeArchivedLifecycle(tx,p,'record.restore',studentSecurityContext(p,current));const row=await repo.restore(tx,p,id,version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'STUDENT_RESTORED',entityType:'Student',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});return row});return{data:result}});
 app.post('/api/v1/students/:id/print-event',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),id=String((req.params as any).id),current=await students.get(p,id);await authorizeRecord(db,p,'record.print',studentSecurityContext(p,current));await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'STUDENT_PRINTED',entityType:'Student',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});return{data:{recorded:true}}});

 app.post('/api/v1/imports/preview',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'imports:manage');const body=parsed(z.object({backup:z.unknown()}).strict(),req.body),preview=imports.preview(body.backup);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'IMPORT_PREVIEW',entityType:'Import',outcome:preview.valid?'SUCCESS':'FAILED',reasonCode:preview.valid?undefined:'VALIDATION_FAILED',correlationId:req.correlationId,summary:{hash:preview.hash,counts:preview.counts}});return{data:preview};});
 app.post('/api/v1/imports/commit',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'imports:manage');const body=parsed(z.object({backup:z.unknown(),previewHash:z.string().length(64),confirmed:z.literal(true)}).strict(),req.body);return{data:await imports.commit(p,body.backup,body.previewHash,req.correlationId)};});
 app.get('/api/v1/imports/:id',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'imports:manage');const r=await db.query<any>('SELECT id,backup_hash AS "backupHash",status,counts,created_at AS "createdAt",completed_at AS "completedAt" FROM import_jobs WHERE id=$1 AND school_id=$2',[(req.params as any).id,p.schoolId]);if(!r.rows[0])throw new ApiError('IMPORT_NOT_FOUND','Import not found.',404);return{data:r.rows[0]};});
 app.get('/api/v1/portal/me',{preHandler:auth(db,config)},async req=>{const p=principal(req);const configuration=await portalConfiguration(db,p.schoolId),rolloutMode=effectivePortalMode(config.portalRolloutMode,configuration);if(rolloutMode==='Off')throw new ApiError('PORTAL_DISABLED','Role portals are disabled in Admin Settings.',403);return{data:{...(await portal.dashboard(p,configuration.modules)),rolloutMode,capabilities:{modules:configuration.modules,teacher:configuration.teacher,pwa:configuration.pwa}}}});
 app.post('/api/v1/portal-users',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await requireSetupAdministration(db,p);requirePermission(p,'portal:manage');const input=parsed(portalUser,req.body),userId=randomUUID(),expiresAt=new Date(Date.now()+24*60*60_000),token=randomBytes(32).toString('base64url');const result=await db.transaction(async tx=>{let roleRow=await tx.query<any>('SELECT id FROM roles WHERE school_id=$1 AND name=$2',[p.schoolId,input.roleName]),roleId=roleRow.rows[0]?.id;if(!roleId){roleId=randomUUID();await tx.query('INSERT INTO roles(id,school_id,name) VALUES($1,$2,$3)',[roleId,p.schoolId,input.roleName])}if(input.teacherId){const found=await tx.query('SELECT id FROM staff WHERE id=$1 AND school_id=$2 AND status=$3',[input.teacherId,p.schoolId,'Active']);if(!found.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','The selected staff record is invalid.',422)}if(input.studentId){const found=await tx.query('SELECT id FROM students WHERE id=$1 AND school_id=$2 AND status=$3',[input.studentId,p.schoolId,'Active']);if(!found.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','The selected student record is invalid.',422)}if(input.guardianId){const found=await tx.query('SELECT id FROM guardian_profiles WHERE id=$1 AND school_id=$2 AND status=$3',[input.guardianId,p.schoolId,'Active']);if(!found.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','The selected guardian record is invalid.',422)}await tx.query('INSERT INTO users(id,school_id,role_id,teacher_id,student_id,username,password_hash,must_change_password,status) VALUES($1,$2,$3,$4,$5,$6,$7,true,$8)',[userId,p.schoolId,roleId,input.teacherId||null,input.studentId||null,input.username,await hashPassword(randomBytes(32).toString('hex')),'PendingPassword']);if(input.guardianId)await tx.query('INSERT INTO user_guardian_links(user_id,guardian_id,school_id) VALUES($1,$2,$3)',[userId,input.guardianId,p.schoolId]);await tx.query('INSERT INTO password_invitations(id_hash,user_id,school_id,expires_at,created_by) VALUES($1,$2,$3,$4,$5)',[digest(token),userId,p.schoolId,expiresAt,p.userId]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'PORTAL_USER_INVITED',entityType:'User',entityId:userId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{roleName:input.roleName,expiresAt:expiresAt.toISOString()}});return{id:userId,username:input.username,roleName:input.roleName,status:'PendingPassword',invitationToken:token,expiresAt:expiresAt.toISOString()}});return reply.code(201).send({data:result})});
 app.get('/api/v1/guardians',{preHandler:auth(db,config)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);requirePermission(p,'portal:manage');const r=await db.query<any>('SELECT id,name,email,phone,status,version FROM guardian_profiles WHERE school_id=$1 ORDER BY name LIMIT 500',[p.schoolId]);return{data:{items:r.rows}}});
 app.post('/api/v1/guardians',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await requireSetupAdministration(db,p);const input=parsed(guardian,req.body),result=await portal.createGuardian(p,input);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'GUARDIAN_CREATED',entityType:'Guardian',entityId:result.id,outcome:'SUCCESS',correlationId:req.correlationId});return reply.code(201).send({data:result})});
 app.patch('/api/v1/users/:id/student-link',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);const input=parsed(z.object({studentId:z.string().max(120).nullable(),version:z.number().int().positive()}).strict(),req.body),id=String((req.params as any).id);const result=await db.transaction(async tx=>{const linked=await portal.linkUserStudent(tx,p,id,input.studentId,input.version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:input.studentId?'USER_STUDENT_LINKED':'USER_STUDENT_UNLINKED',entityType:'User',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{studentId:input.studentId}});return linked});return{data:result}});
 app.patch('/api/v1/users/:id/guardian-link',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);const input=parsed(z.object({guardianId:z.string().max(120).nullable()}).strict(),req.body),id=String((req.params as any).id);const result=await db.transaction(async tx=>{const linked=await portal.linkUserGuardian(tx,p,id,input.guardianId);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:input.guardianId?'USER_GUARDIAN_LINKED':'USER_GUARDIAN_UNLINKED',entityType:'User',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{guardianId:input.guardianId}});return linked});return{data:result}});
 app.post('/api/v1/guardians/:id/students',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await requireSetupAdministration(db,p);const input=parsed(z.object({studentId:z.string().min(1).max(120),relationship:z.string().min(1).max(80).default('Guardian')}).strict(),req.body),guardianId=String((req.params as any).id),result=await portal.linkGuardianStudent(p,guardianId,input.studentId,input.relationship);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'GUARDIAN_STUDENT_LINKED',entityType:'Guardian',entityId:guardianId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{studentId:input.studentId,relationship:input.relationship}});return reply.code(201).send({data:result})});
 app.post('/api/v1/portal/teacher/attendance',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);const configuration=await portalConfiguration(db,p.schoolId);if(effectivePortalMode(config.portalRolloutMode,configuration)!=='Pilot'||!configuration.teacher.attendance)throw new ApiError('PORTAL_READ_ONLY','Teacher attendance is disabled in Admin Settings.',403);const input=parsed(portalAttendance,req.body);const result=await db.transaction(async tx=>{const saved=await portal.saveAttendance(tx,p,input);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'PORTAL_ATTENDANCE_SAVED',entityType:'Attendance',outcome:'SUCCESS',correlationId:req.correlationId,summary:{date:input.date,period:input.period,count:saved.length}});return saved});return{data:{items:result}}});
 app.post('/api/v1/portal/teacher/homework',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);const configuration=await portalConfiguration(db,p.schoolId);if(effectivePortalMode(config.portalRolloutMode,configuration)!=='Pilot'||!configuration.teacher.homework)throw new ApiError('PORTAL_READ_ONLY','Teacher homework publishing is disabled in Admin Settings.',403);const input=parsed(portalHomework,req.body),result=await portal.createHomework(p,input);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'PORTAL_HOMEWORK_PUBLISHED',entityType:'Homework',entityId:result.id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{classId:input.classId,sectionId:input.sectionId||null,subjectId:input.subjectId||null}});return reply.code(201).send({data:result})});
 app.post('/api/v1/portal/teacher/marks',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);const configuration=await portalConfiguration(db,p.schoolId);if(effectivePortalMode(config.portalRolloutMode,configuration)!=='Pilot'||!configuration.teacher.marks)throw new ApiError('PORTAL_READ_ONLY','Teacher marks entry is disabled in Admin Settings.',403);const input=parsed(portalMark,req.body);const result=await db.transaction(async tx=>{const saved=await portal.saveMark(tx,p,input);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'PORTAL_MARK_SAVED',entityType:'Mark',entityId:saved.id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{examId:input.examId,studentId:input.studentId}});return saved});return{data:result}});
 app.get('/api/v1/diagnostics/health',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'diagnostics:view');const check=await db.query<{now:string}>('SELECT CURRENT_TIMESTAMP::text AS now');return{data:{status:'ok',applicationVersion:APPLICATION_VERSION,apiVersion:'v1',database:'reachable',databaseTime:check.rows[0]?.now||null,logging:logMetadata(config),correlationId:req.correlationId}}});
 app.get('/api/v1/diagnostics/support-bundle-preview',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'diagnostics:view');return{data:{applicationVersion:APPLICATION_VERSION,schemaVersion:14,mode:'ServerProduction',generatedAt:new Date().toISOString(),logging:logMetadata(config),included:['version metadata','backend health','logging configuration','migration status'],excluded:['passwords','tokens','cookies','authorization headers','database URL','student and staff records','attachments']}}});
 app.post('/api/v1/diagnostics/support-bundle',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'diagnostics:export');const input=parsed(z.object({client:z.unknown().optional(),confirmed:z.literal(true)}).strict(),req.body);const bundle=redactDiagnostic({applicationVersion:APPLICATION_VERSION,schemaVersion:14,mode:'ServerProduction',generatedAt:new Date().toISOString(),logging:logMetadata(config),client:input.client||null});await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'DIAGNOSTICS_EXPORTED',entityType:'Diagnostics',outcome:'SUCCESS',correlationId:req.correlationId,summary:{applicationVersion:APPLICATION_VERSION}});return{data:bundle}});
 app.get('/api/v1/audit-events',{preHandler:auth(db,config)},async req=>{const p=principal(req);await requireSetupAdministration(db,p);requirePermission(p,'audit:view');const q=pageQuery(req.query),offset=(q.page-1)*q.pageSize,[r,total]=await Promise.all([db.query<any>('SELECT id,action,entity_type AS "entityType",entity_id AS "entityId",occurred_at AS "occurredAt",outcome,reason_code AS "reasonCode",correlation_id AS "correlationId",summary FROM audit_events WHERE school_id=$1 ORDER BY occurred_at DESC,id DESC LIMIT $2 OFFSET $3',[p.schoolId,q.pageSize,offset]),db.query<{count:string}>('SELECT count(*)::text count FROM audit_events WHERE school_id=$1',[p.schoolId])]);const count=Number(total.rows[0]?.count||0);return{data:{items:r.rows,page:q.page,pageSize:q.pageSize,total:count,hasNext:offset+r.rows.length<count}};});
}


