import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Database} from '../database/types.js';
import type {AppConfig} from '../config/index.js';
import {authenticate} from '../auth/security.js';
import {requirePermission,assertTeacherStudentScope} from '../authorization/service.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';
import {WorkspaceService} from '../services/workspace-service.js';
import {CoreRelationshipRepository} from '../repositories/core-relationship-repository.js';
import {readHomeworkPicklist} from '../services/homework-picklists.js';
import {existing} from './calendar-events.js';
import {validateAttachmentFile} from './work-logs.js';
const id=z.string().min(1).max(120),ref=id.nullable(),time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable();
const record=z.object({title:z.string().trim().min(1).max(240),type:z.string().min(1).max(80),category:z.string().max(120),from:z.string().date(),to:z.string().date(),startTime:time,endTime:time,allDay:z.boolean(),description:z.string().max(10000),audiences:z.array(z.string().min(1).max(120)).min(1).max(20),classId:ref,sectionId:ref,teacherId:ref,studentId:ref,status:z.enum(['Active','Inactive','Cancelled']),isHoliday:z.boolean(),holidayType:z.string().max(120),tentative:z.boolean().optional(),lunar:z.boolean().optional()}).strict();
const schema=z.object({record,version:z.number().int().nonnegative(),retainIds:z.array(id).max(5),newFiles:z.array(z.object({name:z.string().min(1).max(240),content:z.string().max(14*1024*1024)}).strict()).max(5)}).strict();
export async function registerCalendarWorkspaceRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const auth=(write=false)=>async(req:FastifyRequest)=>authenticate(req,db,config,write),core=new CoreRelationshipRepository(db);
 app.get('/api/v1/calendar-workspace',{preHandler:auth()},async req=>{
  const p=req.principal!;requirePermission(p,'calendar:view');const ws=new WorkspaceService(db);await ws.syncFactories(p,'calendar-workspace');
  const w=(await db.query<any>("SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key='calendar-holidays'",[p.schoolId])).rows[0];
  const items=(await db.query<any>('SELECT id,data,hidden,notice_id AS "noticeId",version FROM school_calendar_events WHERE school_id=$1',[p.schoolId])).rows,files=(await db.query<any>('SELECT id,event_id,name,type,size FROM calendar_files WHERE school_id=$1 AND archived=false',[p.schoolId])).rows;
  const [classes,sections,staff,years]=await Promise.all([core.list(p,'classes'),core.list(p,'sections'),core.list(p,'staff'),core.list(p,'academic_years')]);
  const students:any[]=[];for(const s of (await db.query<any>("SELECT id,name,admission_number,class_id,section_id,academic_year_id FROM students WHERE school_id=$1 AND status='Active'",[p.schoolId])).rows){try{await assertTeacherStudentScope(db,p,s);students.push({id:s.id,name:s.name,classId:s.class_id,sectionId:s.section_id,admissionNumber:s.admission_number})}catch(e){if(!(e instanceof ApiError&&e.status===403))throw e}}
  const notices=(await db.query<any>('SELECT id FROM school_communications WHERE school_id=$1 AND archived=false',[p.schoolId])).rows;
  for(const [key,field]of [['calendarEventType','type'],['calendarCategory','category']]){const list=(await db.query<any>('SELECT id FROM picklist_definitions WHERE school_id=$1 AND picklist_key=$2',[p.schoolId,key])).rows[0];if(list)for(const value of new Set<string>(items.map(x=>x.data[field]).filter(x=>typeof x==='string'&&x.length>0&&x.length<=120)))await db.query('INSERT INTO picklist_values(id,school_id,picklist_id,value,label,sort_order) VALUES($1,$2,$3,$4,$4,100) ON CONFLICT(picklist_id,value) DO NOTHING',[randomUUID(),p.schoolId,list.id,value]);}
  return{data:{items:items.map(x=>({...x,noticeActive:notices.some(n=>n.id===x.noticeId),attachments:files.filter(f=>f.event_id===x.id)})),definition:await ws.definition(db,p,w.id),classes:classes.items.filter(x=>x.active),sections:sections.items.filter(x=>x.active),teachers:staff.items.filter(x=>x.status==='Active').map(x=>({id:x.id,name:x.name})),students,academicYear:years.items.find(x=>x.active)?.name||'Not selected',types:await readHomeworkPicklist(db,p.schoolId,'calendarEventType'),categories:await readHomeworkPicklist(db,p.schoolId,'calendarCategory'),statuses:await readHomeworkPicklist(db,p.schoolId,'calendarStatus'),audiences:await readHomeworkPicklist(db,p.schoolId,'calendarAudience'),holidayTypes:await readHomeworkPicklist(db,p.schoolId,'calendarHolidayType')}};
 });
 for(const method of ['POST','PATCH'] as const)app.route({method,url:'/api/v1/calendar-workspace'+(method==='PATCH'?'/:id':''),preHandler:auth(true),bodyLimit:72*1024*1024,handler:async(req,reply)=>{
  const p=req.principal!,editing=method==='PATCH';requirePermission(p,editing?'calendar:update':'calendar:create');const parsed=schema.safeParse(req.body);if(!parsed.success)throw new ApiError('VALIDATION_FAILED','Check event fields, dates and times.',422);const input=parsed.data,r=input.record,eventId=editing?String((req.params as any).id):randomUUID();
  if(!r.allDay&&!r.startTime)throw new ApiError('START_TIME_REQUIRED','Enter a start time or select All Day.',422);
  if(r.to<r.from||(!r.allDay&&r.from===r.to&&r.startTime&&r.endTime&&r.endTime<r.startTime))throw new ApiError('INVALID_DATE_RANGE','End must not be before start.',422);
  if(new Set(r.audiences).size!==r.audiences.length||(r.audiences.includes('All')&&r.audiences.length>1))throw new ApiError('INVALID_AUDIENCE','Choose All alone or select specific audiences.',422);
  if(r.sectionId&&!r.classId||r.audiences.includes('Class')&&!r.classId||r.audiences.includes('Section')&&!r.sectionId||r.audiences.includes('Individual')&&!r.teacherId&&!r.studentId)throw new ApiError('AUDIENCE_REFERENCE_REQUIRED','Select the related class, section or individual for this audience.',422);
  if(input.retainIds.length+input.newFiles.length>5||new Set(input.retainIds).size!==input.retainIds.length||(!editing&&input.retainIds.length))throw new ApiError('INVALID_ATTACHMENTS','Choose up to five files.',422);
  const uploads=input.newFiles.map(validateAttachmentFile);
  await db.transaction(async tx=>{
   const old=editing?await existing(tx,p,eventId,input.version):null;if(old?.hidden)throw new ApiError('NOT_FOUND','Restore the hidden holiday before editing.',404);
   for(const [key,values,prior]of [['calendarEventType',[r.type],[old?.data.type]],['calendarCategory',[r.category],[old?.data.category]],['calendarStatus',[r.status],[old?.data.status]],['calendarAudience',r.audiences,old?.data.audiences||[old?.data.audience]],['calendarHolidayType',[r.holidayType],[old?.data.holidayType]]] as [string,string[],string[]][]){const list=await readHomeworkPicklist(tx,p.schoolId,key);for(const value of values)if(value&&!prior.includes(value)&&!list.some(x=>x.active&&x.value===value))throw new ApiError('INVALID_PICKLIST','Choose active event options from Picklist Manager.',422);}
   for(const [table,rid]of [['classes',r.classId],['sections',r.sectionId],['staff',r.teacherId],['students',r.studentId]])if(rid){const target=(await tx.query<any>('SELECT * FROM '+table+' WHERE school_id=$1 AND id=$2',[p.schoolId,rid])).rows[0];if(!target||(table==='classes'||table==='sections'?target.active!==true:target.status!=='Active'))throw new ApiError('INVALID_REFERENCE','Choose active related records from this school.',422);if(table==='sections'&&target.class_id!==r.classId)throw new ApiError('INVALID_REFERENCE','Section must belong to the selected class.',422);if(table==='students'){await assertTeacherStudentScope(tx,p,target);if(r.classId&&target.class_id!==r.classId||r.sectionId&&target.section_id!==r.sectionId)throw new ApiError('INVALID_REFERENCE','Student does not belong to the selected class/section.',422);}if(!!p.teacherId&&table==='staff'&&rid!==p.teacherId)throw new ApiError('FORBIDDEN','Staff reference is outside your scope.',403);}
   if(!!p.teacherId&&r.classId){const allowed=(await core.list(p,'classes')).items;if(!allowed.some(x=>x.id===r.classId))throw new ApiError('FORBIDDEN','Class is outside your teaching scope.',403);}
   const priorFiles=(await tx.query<any>('SELECT id FROM calendar_files WHERE school_id=$1 AND event_id=$2 AND archived=false',[p.schoolId,eventId])).rows;if(input.retainIds.some(fid=>!priorFiles.some(f=>f.id===fid)))throw new ApiError('INVALID_ATTACHMENTS','Attachment does not belong to this event.',422);
   const now=new Date().toISOString(),data={...(old?.data||{}),...r,audience:r.audiences.join(', '),startTime:r.allDay?null:r.startTime,endTime:r.allDay?null:r.endTime,tentative:old?.data.tentative??r.tentative??false,lunar:old?.data.lunar??r.lunar??false,createdBy:old?.data.createdBy||p.userId,createdByName:old?.data.createdByName||p.username,createdAt:old?.data.createdAt||now,updatedAt:now};
   if(editing)await tx.query('UPDATE school_calendar_events SET data=$1,version=version+1 WHERE school_id=$2 AND id=$3',[JSON.stringify(data),p.schoolId,eventId]);else await tx.query('INSERT INTO school_calendar_events(school_id,id,data,version) VALUES($1,$2,$3,1)',[p.schoolId,eventId,JSON.stringify(data)]);
   for(const f of priorFiles)if(!input.retainIds.includes(f.id))await tx.query('UPDATE calendar_files SET archived=true WHERE id=$1 AND school_id=$2',[f.id,p.schoolId]);for(const f of uploads)await tx.query('INSERT INTO calendar_files(id,school_id,event_id,name,type,size,content) VALUES($1,$2,$3,$4,$5,$6,$7)',[f.id,p.schoolId,eventId,f.name,f.type,f.size,f.content]);
   await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:editing?'CALENDAR_UPDATED':'CALENDAR_CREATED',entityType:'Calendar',entityId:eventId,outcome:'SUCCESS',correlationId:req.correlationId});
  });return reply.code(editing?200:201).send({data:{id:eventId}});
 }});
 app.get('/api/v1/calendar-files/:id',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'calendar:view');const f=(await db.query<any>('SELECT f.name,f.type,f.content FROM calendar_files f JOIN school_calendar_events e ON e.school_id=f.school_id AND e.id=f.event_id WHERE f.school_id=$1 AND f.id=$2 AND f.archived=false AND e.hidden=false',[p.schoolId,String((req.params as any).id)])).rows[0];if(!f)throw new ApiError('NOT_FOUND','Attachment not found.',404);return{data:f}});
}
