import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Database,Queryable} from '../database/types.js';
import type {AppConfig} from '../config/index.js';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {authenticate} from '../auth/security.js';
import {requirePermission} from '../authorization/service.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';
import {startWorkflow,advanceOperation} from '../services/operations-workflows.js';
const type=z.enum(['Bonafide','Study','Character','Transfer']);
const create=z.object({studentId:z.string().min(1).max(120),certificateType:type,academicYear:z.string().trim().min(1).max(100),issueSpecific:z.record(z.string(),z.string().max(1000)).default({}),templateId:z.string().max(120).default(''),templateVersion:z.number().int().min(0).default(0),templateSnapshot:z.json().nullable().default(null)}).strict();
const decision=z.object({version:z.number().int().positive(),decision:z.enum(['Approved','Rejected']),note:z.string().max(10000)}).strict();
const version=z.object({version:z.number().int().positive()}).strict();
const prefixes:Record<string,string>={Bonafide:'BON',Study:'STU',Character:'CHAR',Transfer:'TC'};
function parsed<T>(schema:z.ZodType<T>,body:unknown):T{const r=schema.safeParse(body);if(!r.success)throw new ApiError('VALIDATION_FAILED','Check the certificate fields.',422,{fields:r.error.issues.map(i=>i.path.join('.'))});return r.data;}
const conflict=()=>new ApiError('RECORD_VERSION_CONFLICT','The certificate request changed. Refresh before continuing.',409);
async function studentSnapshot(db:Queryable,schoolId:string,studentId:string,academicYear:string){
 const row=(await db.query<any>(`SELECT s.id,s.admission_number AS "admissionNo",s.name AS "studentName",s.father_name AS "fatherName",s.date_of_birth AS dob,s.extra,c.name AS "currentClass",se.name AS "currentSection",ay.name AS "currentYear",hc.name AS "historyClass",hs.name AS "historySection"
 FROM students s JOIN classes c ON c.id=s.class_id AND c.school_id=s.school_id LEFT JOIN sections se ON se.id=s.section_id AND se.school_id=s.school_id LEFT JOIN academic_years ay ON ay.id=s.academic_year_id AND ay.school_id=s.school_id LEFT JOIN academic_years target ON target.school_id=s.school_id AND target.name=$3 LEFT JOIN student_academic_history h ON h.school_id=s.school_id AND h.student_id=s.id AND h.academic_year_id=target.id LEFT JOIN classes hc ON hc.id=h.class_id AND hc.school_id=h.school_id LEFT JOIN sections hs ON hs.id=h.section_id AND hs.school_id=h.school_id WHERE s.school_id=$1 AND s.id=$2 AND s.status IN ('Active','Alumni')`,[schoolId,studentId,academicYear])).rows[0];
 if(!row)throw new ApiError('INVALID_RECORD_REFERENCE','Select an active or alumni student belonging to this school.',422);const historical=!!row.historyClass,current=row.currentYear===academicYear;if(!historical&&!current)throw new ApiError('ACADEMIC_HISTORY_NOT_FOUND','No academic record exists for this student in the selected year.',422);
 return {studentName:row.studentName,admissionNo:row.admissionNo,rollNo:String(row.extra?.roll||''),class:row.historyClass||row.currentClass,section:row.historySection||row.currentSection||'',fatherName:row.fatherName||row.extra?.father||'',motherName:String(row.extra?.mother||''),dob:row.dob?String(row.dob).slice(0,10):String(row.extra?.dob||'')};
}
export async function registerCertificateRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const auth=(write=false)=>async(req:FastifyRequest)=>authenticate(req,db,config,write),audit=(tx:Queryable,req:FastifyRequest,action:string,id:string,summary:Record<string,unknown>={})=>writeAudit(tx,{schoolId:req.principal!.schoolId,actorUserId:req.principal!.userId,action,entityType:'Certificate',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary});
 app.get('/api/v1/certificates',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'certificates:view');const requests=await db.query<any>('SELECT id,data,version FROM school_certificate_requests WHERE school_id=$1 ORDER BY created_at DESC,id',[p.schoolId]),certificates=await db.query<any>('SELECT id,data,reprint_count AS "reprintCount",version FROM school_certificates WHERE school_id=$1 ORDER BY created_at,id',[p.schoolId]),students=await db.query<any>(`SELECT s.id,s.admission_number AS admission,s.name,s.status,c.name AS class,se.name AS section FROM students s JOIN classes c ON c.id=s.class_id AND c.school_id=s.school_id LEFT JOIN sections se ON se.id=s.section_id AND se.school_id=s.school_id WHERE s.school_id=$1 AND s.status='Active' ORDER BY s.name`,[p.schoolId]),years=await db.query<any>('SELECT id,name,active FROM academic_years WHERE school_id=$1 ORDER BY name DESC',[p.schoolId]);return{data:{requests:requests.rows.map(r=>({...r.data,id:r.id,version:r.version})),certificates:certificates.rows.map(r=>({...r.data,id:r.id,version:r.version,reprintCount:r.reprintCount})),students:students.rows,years:years.rows}};});
 app.post('/api/v1/certificates/requests',{preHandler:auth(true)},async(req,reply)=>{const p=req.principal!;requirePermission(p,'certificates:create');const input=parsed(create,req.body),snapshot=await studentSnapshot(db,p.schoolId,input.studentId,input.academicYear),id=randomUUID(),data={...input,snapshot,status:'Pending',createdBy:p.username,createdDate:new Date().toISOString().slice(0,10),decisionNote:''};const result=await db.transaction(async tx=>{await tx.query('INSERT INTO school_certificate_requests(id,school_id,student_id,data) VALUES($1,$2,$3,$4)',[id,p.schoolId,input.studentId,JSON.stringify(data)]);const instance=await startWorkflow(tx,p,'certificates',id,input.certificateType+' Certificate — '+snapshot.studentName,{certificateType:input.certificateType});await audit(tx,req,'CERTIFICATE_REQUESTED',id,{certificateType:input.certificateType,studentId:input.studentId});return{request:{...data,id,version:1},instance};});return reply.code(201).send({data:result});});
 app.post('/api/v1/certificates/requests/:id/decision',{preHandler:auth(true)},async req=>{const p=req.principal!;requirePermission(p,'certificates:create');const id=String((req.params as any).id),input=parsed(decision,req.body);return{data:await db.transaction(async tx=>{const row=(await tx.query<any>('SELECT data,version,student_id FROM school_certificate_requests WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,id])).rows[0];if(!row||row.version!==input.version||row.data.status!=='Pending')throw conflict();const result=await advanceOperation(tx,p,'certificates',id,input.decision,input.note);let certificate=null;if(result.rejected){row.data.status='Rejected';row.data.decisionNote=input.note;}else if(result.final){const existing=(await tx.query<any>('SELECT id,data,reprint_count AS "reprintCount",version FROM school_certificates WHERE school_id=$1 AND request_id=$2',[p.schoolId,id])).rows[0];if(existing)certificate={...existing.data,id:existing.id,version:existing.version,reprintCount:existing.reprintCount};else{await tx.query('INSERT INTO school_certificate_counters(school_id,certificate_type) VALUES($1,$2) ON CONFLICT(school_id,certificate_type) DO NOTHING',[p.schoolId,row.data.certificateType]);const counter=(await tx.query<any>('SELECT next_number FROM school_certificate_counters WHERE school_id=$1 AND certificate_type=$2 FOR UPDATE',[p.schoolId,row.data.certificateType])).rows[0],number=BigInt(counter.next_number),certificateNumber=prefixes[row.data.certificateType]+'-'+new Date().getFullYear()+'-'+String(number).padStart(6,'0'),certificateId=randomUUID(),certificateData={certificateNumber,certificateType:row.data.certificateType,studentId:row.student_id,issueDate:new Date().toISOString().slice(0,10),academicYear:row.data.academicYear,snapshot:row.data.snapshot,issueSpecific:row.data.issueSpecific,issuedBy:p.username,templateId:row.data.templateId,templateVersion:row.data.templateVersion,templateSnapshot:row.data.templateSnapshot};await tx.query('UPDATE school_certificate_counters SET next_number=$1 WHERE school_id=$2 AND certificate_type=$3',[(number+1n).toString(),p.schoolId,row.data.certificateType]);await tx.query('INSERT INTO school_certificates(id,school_id,request_id,student_id,certificate_number,data) VALUES($1,$2,$3,$4,$5,$6)',[certificateId,p.schoolId,id,row.student_id,certificateNumber,JSON.stringify(certificateData)]);row.data.status='Issued';certificate={...certificateData,id:certificateId,version:1,reprintCount:0};await audit(tx,req,'CERTIFICATE_ISSUED',certificateNumber,{requestId:id,studentId:row.student_id});}}await tx.query('UPDATE school_certificate_requests SET data=$1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3',[JSON.stringify(row.data),p.schoolId,id]);await audit(tx,req,'CERTIFICATE_WORKFLOW_STEP_DECIDED',id,{decision:input.decision,final:result.final});return{request:{...row.data,id,version:row.version+1},certificate};})};});
 app.post('/api/v1/certificates/:id/reprint',{preHandler:auth(true)},async req=>{const p=req.principal!;requirePermission(p,'certificates:print');const id=String((req.params as any).id),input=parsed(version,req.body);return{data:await db.transaction(async tx=>{const row=await tx.query<any>('UPDATE school_certificates SET reprint_count=reprint_count+1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$1 AND id=$2 AND version=$3 RETURNING data,reprint_count AS "reprintCount",version',[p.schoolId,id,input.version]);if(!row.rows[0])throw conflict();await audit(tx,req,'CERTIFICATE_REPRINTED',row.rows[0].data.certificateNumber,{reprintCount:row.rows[0].reprintCount});return{...row.rows[0].data,id,version:row.rows[0].version,reprintCount:row.rows[0].reprintCount};})};});
}
