import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {AppConfig} from '../config/index.js';
import type {Database,Queryable} from '../database/types.js';
import {authenticate} from '../auth/security.js';
import {requirePermission,type Principal} from '../authorization/service.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';

const id=z.string().min(1).max(120),version=z.number().int().nonnegative(),channel=z.enum(['InApp','Email','SMS','WhatsApp','WebPush']);
const flags=z.object({enabled:z.boolean(),inApp:z.boolean(),email:z.boolean(),sms:z.boolean(),whatsapp:z.boolean(),webPush:z.boolean(),scheduledDispatch:z.boolean(),acknowledgements:z.boolean(),retries:z.boolean()}).strict();
const templateInput=z.object({name:z.string().trim().min(1).max(160),subject:z.string().trim().min(1).max(240),body:z.string().trim().min(1).max(10000),audience:z.enum(['All','Students','Parents','Teachers']),active:z.boolean(),version:version.optional()}).strict();
const campaignInput=z.object({templateId:id.nullable().optional(),noticeId:id.nullable().optional(),title:z.string().trim().min(1).max(240),body:z.string().trim().min(1).max(10000),audience:z.enum(['All','Students','Parents','Teachers']),channels:z.array(channel).min(1).max(5),scheduledAt:z.string().datetime({offset:true}).nullable().optional(),requiresAcknowledgement:z.boolean().default(false)}).strict();
const DEFAULT={enabled:false,inApp:false,email:false,sms:false,whatsapp:false,webPush:false,scheduledDispatch:false,acknowledgements:false,retries:false};
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApiError('VALIDATION_FAILED','Check the communication delivery fields.',422,{fields:result.error.issues.map(x=>x.path.join('.'))});return result.data}
function principal(req:FastifyRequest):Principal{if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function auth(db:Database,config:AppConfig,write=false){return async(req:FastifyRequest)=>authenticate(req,db,config,write)}
async function configuration(db:Queryable,schoolId:string){const row=(await db.query<any>('SELECT configuration,version FROM communication_delivery_configuration WHERE school_id=$1',[schoolId])).rows[0];return row?{...DEFAULT,...row.configuration,version:row.version}:{...DEFAULT,version:0}}
async function requireEnabled(db:Queryable,p:Principal){const c=await configuration(db,p.schoolId);if(!c.enabled)throw new ApiError('COMMUNICATION_DELIVERY_DISABLED','Communication delivery is disabled in Admin Settings.',403);return c}
async function audit(tx:Queryable,req:FastifyRequest,action:string,entityId?:string,summary?:Record<string,unknown>){const p=principal(req);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action,entityType:'Communication Delivery',entityId,outcome:'SUCCESS',correlationId:req.correlationId,summary})}
function keyForChannel(value:string){return({InApp:'inApp',Email:'email',SMS:'sms',WhatsApp:'whatsapp',WebPush:'webPush'} as Record<string,string>)[value]}
async function recipients(tx:Queryable,schoolId:string,audience:string){const rows=(await tx.query<any>(`SELECT u.id,u.username,u.teacher_id AS "teacherId",u.student_id AS "studentId",ug.guardian_id AS "guardianId" FROM users u LEFT JOIN user_guardian_links ug ON ug.user_id=u.id AND ug.school_id=u.school_id WHERE u.school_id=$1 AND u.status='Active' ORDER BY u.username`,[schoolId])).rows;return rows.filter(row=>audience==='All'||audience==='Teachers'&&!!row.teacherId||audience==='Students'&&!!row.studentId||audience==='Parents'&&!!row.guardianId)}
async function dispatch(tx:Queryable,p:Principal,campaignId:string,force=false){const cfg=await requireEnabled(tx,p),campaign=(await tx.query<any>('SELECT * FROM communication_campaigns WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,campaignId])).rows[0];if(!campaign)throw new ApiError('CAMPAIGN_NOT_FOUND','Communication campaign not found.',404);if(!['Draft','Scheduled','CompletedWithErrors'].includes(campaign.status))throw new ApiError('CAMPAIGN_LOCKED','This campaign cannot be dispatched again.',409);if(!force&&campaign.scheduled_at&&new Date(campaign.scheduled_at).getTime()>Date.now())throw new ApiError('CAMPAIGN_NOT_DUE','This campaign is scheduled for a later time.',409);const channels=Array.isArray(campaign.channels)?campaign.channels:JSON.parse(campaign.channels||'[]'),users=await recipients(tx,p.schoolId,campaign.audience);if(!users.length)throw new ApiError('NO_RECIPIENTS','No active portal users match this audience.',409);for(const selected of channels){const setting=keyForChannel(selected);if(!cfg[setting])throw new ApiError('CHANNEL_DISABLED',selected+' is disabled in Admin Settings.',403)}await tx.query("UPDATE communication_campaigns SET status='Processing',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$1 AND id=$2",[p.schoolId,campaignId]);let delivered=0,blocked=0;for(const user of users)for(const selected of channels){const existing=(await tx.query('SELECT id FROM communication_deliveries WHERE school_id=$1 AND campaign_id=$2 AND user_id=$3 AND channel=$4',[p.schoolId,campaignId,user.id,selected])).rows[0];if(existing)continue;const isInApp=selected==='InApp',status=isInApp?'Delivered':'Blocked',error=isInApp?null:'PROVIDER_NOT_CONFIGURED';await tx.query('INSERT INTO communication_deliveries(id,school_id,campaign_id,user_id,channel,status,destination_snapshot,attempts,error_code,delivered_at) VALUES($1,$2,$3,$4,$5,$6,$7,1,$8,$9)',[randomUUID(),p.schoolId,campaignId,user.id,selected,status,user.username,error,isInApp?new Date().toISOString():null]);if(isInApp)delivered++;else blocked++}const status=blocked?'CompletedWithErrors':'Completed';await tx.query('UPDATE communication_campaigns SET status=$1,dispatched_at=CURRENT_TIMESTAMP,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3',[status,p.schoolId,campaignId]);return{recipients:users.length,delivered,blocked,status}}

export async function registerCommunicationDeliveryRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 app.get('/api/v1/communication-delivery/configuration',{preHandler:auth(db,config)},async req=>{const p=principal(req);return{data:{...(await configuration(db,p.schoolId)),providers:{Email:'NotConfigured',SMS:'NotConfigured',WhatsApp:'NotConfigured',WebPush:'NotConfigured'}}}});
 app.patch('/api/v1/communication-delivery/configuration',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'school:manage');requirePermission(p,'notices:update');const input=parse(flags.extend({version}),req.body);if(!input.enabled&&Object.entries(input).some(([key,value])=>!['enabled','version'].includes(key)&&value===true))throw new ApiError('VALIDATION_FAILED','Disable all delivery options before disabling the feature.',422);if(input.acknowledgements&&!input.inApp)throw new ApiError('VALIDATION_FAILED','In-app delivery is required for acknowledgements.',422);if(input.retries&&!input.enabled)throw new ApiError('VALIDATION_FAILED','Enable communication delivery before retries.',422);const data=await db.transaction(async tx=>{await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);const old=await configuration(tx,p.schoolId);if(old.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Communication settings changed. Reload before saving.',409);const value={enabled:input.enabled,inApp:input.inApp,email:input.email,sms:input.sms,whatsapp:input.whatsapp,webPush:input.webPush,scheduledDispatch:input.scheduledDispatch,acknowledgements:input.acknowledgements,retries:input.retries};if(old.version)await tx.query('UPDATE communication_delivery_configuration SET configuration=$1,version=version+1,updated_by=$2,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3',[JSON.stringify(value),p.userId,p.schoolId]);else await tx.query('INSERT INTO communication_delivery_configuration(school_id,configuration,updated_by) VALUES($1,$2,$3)',[p.schoolId,JSON.stringify(value),p.userId]);await audit(tx,req,'COMMUNICATION_DELIVERY_CONFIGURATION_UPDATED',p.schoolId,{enabled:value.enabled});return configuration(tx,p.schoolId)});return{data}});
 app.get('/api/v1/communication-delivery/templates',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'notices:view');await requireEnabled(db,p);const rows=await db.query<any>('SELECT id,name,subject,body,audience,active,version FROM communication_templates WHERE school_id=$1 ORDER BY active DESC,name',[p.schoolId]);return{data:{items:rows.rows}}});
 app.post('/api/v1/communication-delivery/templates',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'notices:create');await requireEnabled(db,p);const input=parse(templateInput.omit({version:true}),req.body);const row=await db.transaction(async tx=>{const created=(await tx.query<any>('INSERT INTO communication_templates(id,school_id,name,subject,body,audience,active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING id,name,subject,body,audience,active,version',[randomUUID(),p.schoolId,input.name,input.subject,input.body,input.audience,input.active,p.userId])).rows[0];await audit(tx,req,'COMMUNICATION_TEMPLATE_CREATED',created.id,{name:created.name});return created});return reply.code(201).send({data:row})});
 app.patch('/api/v1/communication-delivery/templates/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'notices:update');await requireEnabled(db,p);const input=parse(templateInput.required({version:true}),req.body),templateId=String((req.params as any).id);const row=await db.transaction(async tx=>{const updated=(await tx.query<any>('UPDATE communication_templates SET name=$1,subject=$2,body=$3,audience=$4,active=$5,version=version+1,updated_by=$6,updated_at=CURRENT_TIMESTAMP WHERE school_id=$7 AND id=$8 AND version=$9 RETURNING id,name,subject,body,audience,active,version',[input.name,input.subject,input.body,input.audience,input.active,p.userId,p.schoolId,templateId,input.version])).rows[0];if(!updated)throw new ApiError('RECORD_VERSION_CONFLICT','Template changed. Reload before saving.',409);await audit(tx,req,'COMMUNICATION_TEMPLATE_UPDATED',templateId);return updated});return{data:row}});
 app.get('/api/v1/communication-delivery/campaigns',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'notices:view');await requireEnabled(db,p);const campaigns=await db.query<any>(`SELECT c.id,c.template_id AS "templateId",c.notice_id AS "noticeId",c.title,c.body,c.audience,c.channels,c.scheduled_at AS "scheduledAt",c.dispatched_at AS "dispatchedAt",c.status,c.requires_acknowledgement AS "requiresAcknowledgement",c.version,(SELECT count(*)::int FROM communication_deliveries d WHERE d.school_id=c.school_id AND d.campaign_id=c.id) AS "deliveryCount" FROM communication_campaigns c WHERE c.school_id=$1 ORDER BY c.created_at DESC`,[p.schoolId]);return{data:{items:campaigns.rows}}});
 app.post('/api/v1/communication-delivery/campaigns',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'notices:create');const cfg=await requireEnabled(db,p),input=parse(campaignInput,req.body);if(new Set(input.channels).size!==input.channels.length)throw new ApiError('VALIDATION_FAILED','Select each delivery channel once.',422);if(input.requiresAcknowledgement&&!cfg.acknowledgements)throw new ApiError('ACKNOWLEDGEMENTS_DISABLED','Acknowledgements are disabled in Admin Settings.',403);if(input.scheduledAt&&!cfg.scheduledDispatch)throw new ApiError('SCHEDULED_DELIVERY_DISABLED','Scheduled delivery is disabled in Admin Settings.',403);for(const selected of input.channels)if(!cfg[keyForChannel(selected)])throw new ApiError('CHANNEL_DISABLED',selected+' is disabled in Admin Settings.',403);const row=await db.transaction(async tx=>{if(input.templateId&&!((await tx.query('SELECT id FROM communication_templates WHERE school_id=$1 AND id=$2 AND active=true',[p.schoolId,input.templateId])).rows[0]))throw new ApiError('INVALID_RECORD_REFERENCE','Select an active communication template.',422);if(input.noticeId&&!((await tx.query("SELECT id FROM school_communications WHERE school_id=$1 AND id=$2 AND archived=false AND publication_state='Published'",[p.schoolId,input.noticeId])).rows[0]))throw new ApiError('INVALID_RECORD_REFERENCE','Select a published notice.',422);const status=input.scheduledAt?'Scheduled':'Draft',created=(await tx.query<any>('INSERT INTO communication_campaigns(id,school_id,template_id,notice_id,title,body,audience,channels,scheduled_at,status,requires_acknowledgement,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,title,audience,channels,scheduled_at AS "scheduledAt",status,requires_acknowledgement AS "requiresAcknowledgement",version',[randomUUID(),p.schoolId,input.templateId||null,input.noticeId||null,input.title,input.body,input.audience,JSON.stringify(input.channels),input.scheduledAt||null,status,input.requiresAcknowledgement,p.userId])).rows[0];await audit(tx,req,'COMMUNICATION_CAMPAIGN_CREATED',created.id,{channels:input.channels,scheduled:!!input.scheduledAt});return created});return reply.code(201).send({data:row})});
 app.post('/api/v1/communication-delivery/campaigns/:id/dispatch',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'notices:update');const campaignId=String((req.params as any).id),input=parse(z.object({confirmed:z.literal(true),force:z.boolean().default(false)}).strict(),req.body);const result=await db.transaction(async tx=>{const value=await dispatch(tx,p,campaignId,input.force);await audit(tx,req,'COMMUNICATION_CAMPAIGN_DISPATCHED',campaignId,value);return value});return{data:result}});
 app.post('/api/v1/communication-delivery/dispatch-due',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'notices:update');const cfg=await requireEnabled(db,p);if(!cfg.scheduledDispatch)throw new ApiError('SCHEDULED_DELIVERY_DISABLED','Scheduled delivery is disabled in Admin Settings.',403);const ids=(await db.query<any>("SELECT id FROM communication_campaigns WHERE school_id=$1 AND status='Scheduled' AND scheduled_at<=now() ORDER BY scheduled_at LIMIT 100",[p.schoolId])).rows;const results=[];for(const row of ids)results.push({id:row.id,...await db.transaction(tx=>dispatch(tx,p,row.id,false))});if(results.length)await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'COMMUNICATION_DUE_QUEUE_DISPATCHED',entityType:'Communication Delivery',outcome:'SUCCESS',correlationId:req.correlationId,summary:{count:results.length}});return{data:{items:results}}});
 app.get('/api/v1/communication-delivery/inbox',{preHandler:auth(db,config)},async req=>{const p=principal(req);const cfg=await requireEnabled(db,p);if(!cfg.inApp)throw new ApiError('CHANNEL_DISABLED','In-app delivery is disabled in Admin Settings.',403);const rows=await db.query<any>(`SELECT d.id,d.status,d.delivered_at AS "deliveredAt",d.read_at AS "readAt",d.acknowledged_at AS "acknowledgedAt",d.version,c.title,c.body,c.requires_acknowledgement AS "requiresAcknowledgement" FROM communication_deliveries d JOIN communication_campaigns c ON c.id=d.campaign_id AND c.school_id=d.school_id WHERE d.school_id=$1 AND d.user_id=$2 AND d.channel='InApp' ORDER BY d.created_at DESC`,[p.schoolId,p.userId]);return{data:{items:rows.rows}}});
 app.post('/api/v1/communication-delivery/inbox/:id/read',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);const cfg=await requireEnabled(db,p);if(!cfg.inApp)throw new ApiError('CHANNEL_DISABLED','In-app delivery is disabled.',403);const deliveryId=String((req.params as any).id),input=parse(z.object({version}).strict(),req.body),row=(await db.query<any>("UPDATE communication_deliveries SET status=CASE WHEN status='Acknowledged' THEN status ELSE 'Read' END,read_at=COALESCE(read_at,CURRENT_TIMESTAMP),version=version+1 WHERE school_id=$1 AND id=$2 AND user_id=$3 AND channel='InApp' AND version=$4 RETURNING id,status,version",[p.schoolId,deliveryId,p.userId,input.version])).rows[0];if(!row)throw new ApiError('RECORD_VERSION_CONFLICT','Message changed. Reload before marking it read.',409);return{data:row}});
 app.post('/api/v1/communication-delivery/inbox/:id/acknowledge',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),cfg=await requireEnabled(db,p);if(!cfg.acknowledgements)throw new ApiError('ACKNOWLEDGEMENTS_DISABLED','Acknowledgements are disabled.',403);const deliveryId=String((req.params as any).id),input=parse(z.object({version}).strict(),req.body);const row=await db.transaction(async tx=>{const found=(await tx.query<any>(`SELECT d.id,d.version,c.requires_acknowledgement AS "requiresAcknowledgement" FROM communication_deliveries d JOIN communication_campaigns c ON c.id=d.campaign_id AND c.school_id=d.school_id WHERE d.school_id=$1 AND d.id=$2 AND d.user_id=$3 AND d.channel='InApp'`,[p.schoolId,deliveryId,p.userId])).rows[0];if(!found||!found.requiresAcknowledgement||found.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Message changed or does not require acknowledgement.',409);return(await tx.query<any>("UPDATE communication_deliveries SET status='Acknowledged',read_at=COALESCE(read_at,CURRENT_TIMESTAMP),acknowledged_at=CURRENT_TIMESTAMP,version=version+1 WHERE school_id=$1 AND id=$2 AND user_id=$3 AND version=$4 RETURNING id,status,version",[p.schoolId,deliveryId,p.userId,input.version])).rows[0]});return{data:row}});
 app.get('/api/v1/communication-delivery/campaigns/:id/deliveries',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'notices:view');await requireEnabled(db,p);const campaignId=String((req.params as any).id),rows=await db.query<any>(`SELECT d.id,d.user_id AS "userId",u.username,d.channel,d.status,d.attempts,d.error_code AS "errorCode",d.delivered_at AS "deliveredAt",d.read_at AS "readAt",d.acknowledged_at AS "acknowledgedAt",d.version FROM communication_deliveries d JOIN users u ON u.id=d.user_id AND u.school_id=d.school_id WHERE d.school_id=$1 AND d.campaign_id=$2 ORDER BY u.username,d.channel`,[p.schoolId,campaignId]);return{data:{items:rows.rows}}});
 app.post('/api/v1/communication-delivery/campaigns/:id/retry',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),cfg=await requireEnabled(db,p);requirePermission(p,'notices:update');if(!cfg.retries)throw new ApiError('RETRIES_DISABLED','Delivery retries are disabled in Admin Settings.',403);const campaignId=String((req.params as any).id),changed=await db.query<any>("UPDATE communication_deliveries SET attempts=attempts+1,status='Blocked',error_code='PROVIDER_NOT_CONFIGURED',version=version+1 WHERE school_id=$1 AND campaign_id=$2 AND channel<>'InApp' AND status IN ('Blocked','Failed') RETURNING id",[p.schoolId,campaignId]);await writeAudit(db,{schoolId:p.schoolId,actorUserId:p.userId,action:'COMMUNICATION_DELIVERY_RETRY_REQUESTED',entityType:'Communication Delivery',entityId:campaignId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{count:changed.rows.length}});return{data:{retried:changed.rows.length,providerStatus:'NotConfigured'}}});
}
