import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {AppConfig} from '../config/index.js';
import type {Database,Queryable} from '../database/types.js';
import {authenticate} from '../auth/security.js';
import {requirePermission,type Principal} from '../authorization/service.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';

const id=z.string().min(1).max(120),version=z.number().int().nonnegative(),time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const flags=z.object({enabled:z.boolean(),roomManagement:z.boolean(),clashValidation:z.boolean(),seatAllocation:z.boolean(),invigilation:z.boolean(),hallTickets:z.boolean()}).strict();
const roomInput=z.object({name:z.string().trim().min(1).max(160),code:z.string().trim().min(1).max(40),building:z.string().trim().max(160).default(''),rows:z.number().int().min(1).max(100),columns:z.number().int().min(1).max(100),capacity:z.number().int().min(1).max(10000),active:z.boolean().default(true),version:version.optional()}).strict();
const sessionInput=z.object({examId:id,roomId:id,sessionDate:z.string().date(),startsAt:time,endsAt:time,version:version.optional()}).strict();
const DEFAULT={enabled:false,roomManagement:false,clashValidation:false,seatAllocation:false,invigilation:false,hallTickets:false};
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApiError('VALIDATION_FAILED','Check the examination logistics fields.',422,{fields:result.error.issues.map(x=>x.path.join('.'))});return result.data}
function principal(req:FastifyRequest):Principal{if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function auth(db:Database,config:AppConfig,write=false){return async(req:FastifyRequest)=>authenticate(req,db,config,write)}
async function configuration(db:Queryable,schoolId:string){const row=(await db.query<any>('SELECT configuration,version FROM exam_logistics_configuration WHERE school_id=$1',[schoolId])).rows[0];return row?{...DEFAULT,...row.configuration,version:row.version}:{...DEFAULT,version:0}}
async function requireFeature(db:Queryable,p:Principal,key:keyof typeof DEFAULT){const c=await configuration(db,p.schoolId);if(!c.enabled||key!=='enabled'&&!c[key])throw new ApiError('EXAM_LOGISTICS_DISABLED','This examination logistics capability is disabled in Admin Settings.',403);return c}
async function exam(db:Queryable,p:Principal,examId:string){const row=(await db.query<any>('SELECT id,name,academic_year_id AS "academicYearId",class_id AS "classId",section_id AS "sectionId",subject_id AS "subjectId",exam_date AS "examDate",state FROM exam_records WHERE school_id=$1 AND id=$2 AND state<>\'Archived\'',[p.schoolId,examId])).rows[0];if(!row)throw new ApiError('EXAM_NOT_FOUND','Assessment not found.',404);return row}
async function roster(db:Queryable,p:Principal,e:any){const [students,history]=await Promise.all([db.query<any>(`SELECT id,name,admission_number AS "admissionNumber",academic_year_id AS "academicYearId",class_id AS "classId",section_id AS "sectionId" FROM students WHERE school_id=$1 AND status='Active' ORDER BY admission_number,name`,[p.schoolId]),db.query<any>('SELECT student_id AS "studentId",class_id AS "classId",section_id AS "sectionId" FROM student_academic_history WHERE school_id=$1 AND academic_year_id=$2',[p.schoolId,e.academicYearId])]);return students.rows.filter(student=>{const enrollment=student.academicYearId===e.academicYearId?student:history.rows.find(row=>row.studentId===student.id);return enrollment?.classId===e.classId&&(!e.sectionId||enrollment.sectionId===e.sectionId)}).map(({id,name,admissionNumber})=>({id,name,admissionNumber}))}
async function audit(tx:Queryable,req:FastifyRequest,action:string,entityId?:string,summary?:Record<string,unknown>){const p=principal(req);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action,entityType:'Exam Logistics',entityId,outcome:'SUCCESS',correlationId:req.correlationId,summary})}

export async function registerExamLogisticsRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 app.get('/api/v1/exam-logistics/configuration',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'exams:view');return{data:await configuration(db,p.schoolId)}});
 app.patch('/api/v1/exam-logistics/configuration',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'school:manage');requirePermission(p,'exams:manage');const input=parse(flags.extend({version}),req.body);if(!input.enabled&&Object.entries(input).some(([k,v])=>!['enabled','version'].includes(k)&&v===true))throw new ApiError('VALIDATION_FAILED','Disable all examination logistics options before disabling the feature.',422);if(!input.roomManagement&&(input.clashValidation||input.seatAllocation||input.invigilation||input.hallTickets))throw new ApiError('VALIDATION_FAILED','Enable rooms and session scheduling before its dependent examination workflows.',422);if(input.hallTickets&&!input.seatAllocation)throw new ApiError('VALIDATION_FAILED','Enable seat allocation before hall tickets.',422);const data=await db.transaction(async tx=>{await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);const old=await configuration(tx,p.schoolId);if(old.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Examination logistics settings changed. Reload before saving.',409);const value={enabled:input.enabled,roomManagement:input.roomManagement,clashValidation:input.clashValidation,seatAllocation:input.seatAllocation,invigilation:input.invigilation,hallTickets:input.hallTickets};if(old.version)await tx.query('UPDATE exam_logistics_configuration SET configuration=$1,version=version+1,updated_by=$2,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3',[JSON.stringify(value),p.userId,p.schoolId]);else await tx.query('INSERT INTO exam_logistics_configuration(school_id,configuration,updated_by) VALUES($1,$2,$3)',[p.schoolId,JSON.stringify(value),p.userId]);await audit(tx,req,'EXAM_LOGISTICS_CONFIGURATION_UPDATED',p.schoolId,{enabled:value.enabled});return configuration(tx,p.schoolId)});return{data}});
 app.get('/api/v1/exam-logistics',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'exams:view');const cfg=await requireFeature(db,p,'enabled');const [rooms,sessions,exams,staff]=await Promise.all([
  db.query<any>('SELECT id,name,code,building,room_rows AS rows,room_columns AS columns,capacity,active,version FROM exam_logistics_rooms WHERE school_id=$1 ORDER BY active DESC,name',[p.schoolId]),
  db.query<any>(`SELECT s.id,s.exam_id AS "examId",s.room_id AS "roomId",s.session_date AS "sessionDate",s.starts_at AS "startsAt",s.ends_at AS "endsAt",s.state,s.version,(SELECT count(*)::int FROM exam_logistics_seats x WHERE x.school_id=s.school_id AND x.session_id=s.id) AS "seatCount",(SELECT count(*)::int FROM exam_logistics_invigilators i WHERE i.school_id=s.school_id AND i.session_id=s.id) AS "invigilatorCount" FROM exam_logistics_sessions s WHERE s.school_id=$1 ORDER BY s.session_date,s.starts_at`,[p.schoolId]),
  db.query<any>(`SELECT id,name,academic_year_id AS "academicYearId",class_id AS "classId",section_id AS "sectionId",subject_id AS "subjectId",exam_date AS "examDate",state FROM exam_records WHERE school_id=$1 AND state<>'Archived' ORDER BY exam_date,name`,[p.schoolId]),
  db.query<any>("SELECT id,name,employee_number AS \"employeeNumber\" FROM staff WHERE school_id=$1 AND status='Active' ORDER BY name",[p.schoolId])]);return{data:{configuration:cfg,rooms:rooms.rows,sessions:sessions.rows,exams:exams.rows,staff:staff.rows}}});
 app.post('/api/v1/exam-logistics/rooms',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'exams:manage');await requireFeature(db,p,'roomManagement');const input=parse(roomInput.omit({version:true}),req.body);if(input.capacity>input.rows*input.columns)throw new ApiError('INVALID_ROOM_CAPACITY','Capacity cannot exceed the configured seat grid.',422);const row=await db.transaction(async tx=>{const duplicate=await tx.query('SELECT id FROM exam_logistics_rooms WHERE school_id=$1 AND lower(code)=lower($2)',[p.schoolId,input.code]);if(duplicate.rows[0])throw new ApiError('DUPLICATE_ROOM','A room with this code already exists.',409);const created=(await tx.query<any>('INSERT INTO exam_logistics_rooms(id,school_id,name,code,building,room_rows,room_columns,capacity,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,name,code,building,room_rows AS rows,room_columns AS columns,capacity,active,version',[randomUUID(),p.schoolId,input.name,input.code,input.building,input.rows,input.columns,input.capacity,input.active])).rows[0];await audit(tx,req,'EXAM_ROOM_CREATED',created.id,{code:created.code});return created});return reply.code(201).send({data:row})});
 app.patch('/api/v1/exam-logistics/rooms/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'exams:manage');await requireFeature(db,p,'roomManagement');const input=parse(roomInput.required({version:true}),req.body),roomId=String((req.params as any).id);if(input.capacity>input.rows*input.columns)throw new ApiError('INVALID_ROOM_CAPACITY','Capacity cannot exceed the configured seat grid.',422);const row=await db.transaction(async tx=>{const updated=(await tx.query<any>('UPDATE exam_logistics_rooms SET name=$1,code=$2,building=$3,room_rows=$4,room_columns=$5,capacity=$6,active=$7,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$8 AND id=$9 AND version=$10 RETURNING id,name,code,building,room_rows AS rows,room_columns AS columns,capacity,active,version',[input.name,input.code,input.building,input.rows,input.columns,input.capacity,input.active,p.schoolId,roomId,input.version])).rows[0];if(!updated)throw new ApiError('RECORD_VERSION_CONFLICT','Room changed. Reload before saving.',409);await audit(tx,req,'EXAM_ROOM_UPDATED',roomId);return updated});return{data:row}});
 app.post('/api/v1/exam-logistics/sessions',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'exams:manage');const cfg=await requireFeature(db,p,'roomManagement'),input=parse(sessionInput.omit({version:true}),req.body);if(input.startsAt>=input.endsAt)throw new ApiError('INVALID_SESSION_TIME','End time must be later than start time.',422);const row=await db.transaction(async tx=>{const e=await exam(tx,p,input.examId),room=(await tx.query<any>('SELECT * FROM exam_logistics_rooms WHERE school_id=$1 AND id=$2 AND active=true',[p.schoolId,input.roomId])).rows[0];if(!room)throw new ApiError('INVALID_RECORD_REFERENCE','Select an active examination room.',422);const students=await roster(tx,p,e);if(students.length>room.capacity)throw new ApiError('ROOM_CAPACITY_EXCEEDED','The room is too small for this assessment roster.',409,{required:students.length,capacity:room.capacity});if(cfg.clashValidation){const roomClash=(await tx.query('SELECT id FROM exam_logistics_sessions WHERE school_id=$1 AND room_id=$2 AND session_date=$3 AND state<>\'Cancelled\' AND starts_at<$5 AND ends_at>$4 LIMIT 1',[p.schoolId,input.roomId,input.sessionDate,input.startsAt,input.endsAt])).rows[0];if(roomClash)throw new ApiError('EXAM_ROOM_CLASH','This room is already used during the selected time.',409);const classClash=(await tx.query(`SELECT s.id FROM exam_logistics_sessions s JOIN exam_records x ON x.id=s.exam_id AND x.school_id=s.school_id WHERE s.school_id=$1 AND s.session_date=$2 AND s.state<>'Cancelled' AND s.starts_at<$4 AND s.ends_at>$3 AND x.class_id=$5 AND (x.section_id IS NULL OR $6::text IS NULL OR x.section_id=$6) LIMIT 1`,[p.schoolId,input.sessionDate,input.startsAt,input.endsAt,e.classId,e.sectionId||null])).rows[0];if(classClash)throw new ApiError('EXAM_CLASS_CLASH','This class or section already has an examination during the selected time.',409)}const created=(await tx.query<any>('INSERT INTO exam_logistics_sessions(id,school_id,exam_id,room_id,session_date,starts_at,ends_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING id,exam_id AS "examId",room_id AS "roomId",session_date AS "sessionDate",starts_at AS "startsAt",ends_at AS "endsAt",state,version',[randomUUID(),p.schoolId,input.examId,input.roomId,input.sessionDate,input.startsAt,input.endsAt,p.userId])).rows[0];await audit(tx,req,'EXAM_SESSION_CREATED',created.id,{rosterSize:students.length});return created});return reply.code(201).send({data:row})});
 app.post('/api/v1/exam-logistics/sessions/:id/allocate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'exams:manage');await requireFeature(db,p,'seatAllocation');const sessionId=String((req.params as any).id),input=parse(z.object({version}).strict(),req.body);const result=await db.transaction(async tx=>{const s=(await tx.query<any>('SELECT * FROM exam_logistics_sessions WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,sessionId])).rows[0];if(!s)throw new ApiError('EXAM_SESSION_NOT_FOUND','Examination session not found.',404);if(s.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Session changed. Reload before allocating seats.',409);if(s.state!=='Draft')throw new ApiError('EXAM_SESSION_LOCKED','Published sessions cannot be reallocated.',409);const e=await exam(tx,p,s.exam_id),students=await roster(tx,p,e),room=(await tx.query<any>('SELECT * FROM exam_logistics_rooms WHERE school_id=$1 AND id=$2',[p.schoolId,s.room_id])).rows[0];if(students.length>room.capacity)throw new ApiError('ROOM_CAPACITY_EXCEEDED','The room is too small for this roster.',409);await tx.query('DELETE FROM exam_logistics_seats WHERE school_id=$1 AND session_id=$2',[p.schoolId,sessionId]);for(let index=0;index<students.length;index++){const row=Math.floor(index/room.room_columns),column=index%room.room_columns+1,rowLabel=String.fromCharCode(65+Math.floor(row/26))+String.fromCharCode(65+row%26);await tx.query('INSERT INTO exam_logistics_seats(id,school_id,session_id,student_id,seat_number,row_label,column_number) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),p.schoolId,sessionId,students[index].id,rowLabel+'-'+column,rowLabel,column])}const updated=(await tx.query<any>('UPDATE exam_logistics_sessions SET version=version+1,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3 RETURNING version',[p.userId,p.schoolId,sessionId])).rows[0];await audit(tx,req,'EXAM_SEATS_ALLOCATED',sessionId,{count:students.length});return{count:students.length,version:updated.version}});return{data:result}});
 app.put('/api/v1/exam-logistics/sessions/:id/invigilators',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'exams:manage');const cfg=await requireFeature(db,p,'invigilation'),sessionId=String((req.params as any).id),input=parse(z.object({staffIds:z.array(id).min(1).max(20),version}).strict(),req.body);if(new Set(input.staffIds).size!==input.staffIds.length)throw new ApiError('VALIDATION_FAILED','Select each invigilator once.',422);const result=await db.transaction(async tx=>{const s=(await tx.query<any>('SELECT * FROM exam_logistics_sessions WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,sessionId])).rows[0];if(!s)throw new ApiError('EXAM_SESSION_NOT_FOUND','Examination session not found.',404);if(s.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Session changed. Reload before assigning invigilators.',409);if(s.state!=='Draft')throw new ApiError('EXAM_SESSION_LOCKED','Published sessions cannot change invigilators.',409);for(const staffId of input.staffIds){const staff=(await tx.query("SELECT id FROM staff WHERE school_id=$1 AND id=$2 AND status='Active'",[p.schoolId,staffId])).rows[0];if(!staff)throw new ApiError('INVALID_RECORD_REFERENCE','Select active staff only.',422);if(cfg.clashValidation){const clash=(await tx.query(`SELECT i.id FROM exam_logistics_invigilators i JOIN exam_logistics_sessions x ON x.id=i.session_id AND x.school_id=i.school_id WHERE i.school_id=$1 AND i.staff_id=$2 AND x.id<>$3 AND x.session_date=$4 AND x.state<>'Cancelled' AND x.starts_at<$6 AND x.ends_at>$5 LIMIT 1`,[p.schoolId,staffId,sessionId,s.session_date,s.starts_at,s.ends_at])).rows[0];if(clash)throw new ApiError('INVIGILATOR_CLASH','A selected invigilator is already assigned during this time.',409)}}await tx.query('DELETE FROM exam_logistics_invigilators WHERE school_id=$1 AND session_id=$2',[p.schoolId,sessionId]);for(const staffId of input.staffIds)await tx.query('INSERT INTO exam_logistics_invigilators(id,school_id,session_id,staff_id,role) VALUES($1,$2,$3,$4,$5)',[randomUUID(),p.schoolId,sessionId,staffId,'Invigilator']);const updated=(await tx.query<any>('UPDATE exam_logistics_sessions SET version=version+1,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3 RETURNING version',[p.userId,p.schoolId,sessionId])).rows[0];await audit(tx,req,'EXAM_INVIGILATORS_ASSIGNED',sessionId,{count:input.staffIds.length});return{count:input.staffIds.length,version:updated.version}});return{data:result}});
 app.post('/api/v1/exam-logistics/sessions/:id/publish',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'exams:manage');const cfg=await requireFeature(db,p,'enabled'),sessionId=String((req.params as any).id),input=parse(z.object({version,confirmed:z.literal(true)}).strict(),req.body);const result=await db.transaction(async tx=>{const s=(await tx.query<any>('SELECT * FROM exam_logistics_sessions WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,sessionId])).rows[0];if(!s)throw new ApiError('EXAM_SESSION_NOT_FOUND','Examination session not found.',404);if(s.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Session changed. Reload before publishing.',409);if(s.state!=='Draft')throw new ApiError('EXAM_SESSION_LOCKED','Only draft sessions can be published.',409);const e=await exam(tx,p,s.exam_id),students=await roster(tx,p,e);if(cfg.seatAllocation){const count=Number((await tx.query<any>('SELECT count(*)::int AS count FROM exam_logistics_seats WHERE school_id=$1 AND session_id=$2',[p.schoolId,sessionId])).rows[0]?.count||0);if(count!==students.length)throw new ApiError('SEAT_ALLOCATION_INCOMPLETE','Allocate a seat to every student before publishing.',409)}if(cfg.invigilation){const count=Number((await tx.query<any>('SELECT count(*)::int AS count FROM exam_logistics_invigilators WHERE school_id=$1 AND session_id=$2',[p.schoolId,sessionId])).rows[0]?.count||0);if(!count)throw new ApiError('INVIGILATOR_REQUIRED','Assign at least one invigilator before publishing.',409)}const updated=(await tx.query<any>("UPDATE exam_logistics_sessions SET state='Published',version=version+1,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3 RETURNING state,version",[p.userId,p.schoolId,sessionId])).rows[0];await audit(tx,req,'EXAM_SESSION_PUBLISHED',sessionId,{rosterSize:students.length});return updated});return{data:result}});
 app.get('/api/v1/exam-logistics/sessions/:id/hall-tickets',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'exams:view');await requireFeature(db,p,'hallTickets');const sessionId=String((req.params as any).id),s=(await db.query<any>(`SELECT s.*,e.name AS "examName",r.name AS "roomName",r.code AS "roomCode" FROM exam_logistics_sessions s JOIN exam_records e ON e.id=s.exam_id AND e.school_id=s.school_id JOIN exam_logistics_rooms r ON r.id=s.room_id AND r.school_id=s.school_id WHERE s.school_id=$1 AND s.id=$2`,[p.schoolId,sessionId])).rows[0];if(!s)throw new ApiError('EXAM_SESSION_NOT_FOUND','Examination session not found.',404);if(s.state!=='Published')throw new ApiError('EXAM_SESSION_NOT_PUBLISHED','Publish the session before printing hall tickets.',409);const tickets=(await db.query<any>(`SELECT st.id AS "studentId",st.name,st.admission_number AS "admissionNumber",x.seat_number AS "seatNumber" FROM exam_logistics_seats x JOIN students st ON st.id=x.student_id AND st.school_id=x.school_id WHERE x.school_id=$1 AND x.session_id=$2 ORDER BY x.seat_number`,[p.schoolId,sessionId])).rows;return{data:{session:{id:s.id,examName:s.examName,roomName:s.roomName,roomCode:s.roomCode,sessionDate:s.session_date,startsAt:s.starts_at,endsAt:s.ends_at},tickets}}});
}
