import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Database,Queryable} from '../database/types.js';
import type {AppConfig} from '../config/index.js';
import {authenticate} from '../auth/security.js';
import {requirePermission} from '../authorization/service.js';
import {authorizeCreate,authorizeRecord,authorizeWorkspaceAction,resolveEffectiveGrants,type RecordSecurityContext} from '../authorization/policy-engine.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {workflowSettings,workflowSettingsSchema,validateWorkflows,startWorkflow,advanceOperation} from '../services/operations-workflows.js';
function parse<T>(s:z.ZodType<T>,v:unknown):T{const r=s.safeParse(v);if(!r.success)throw new ApiError('VALIDATION_FAILED','Check the supplied workflow or leave fields.',422,{fields:r.error.issues.map(i=>i.path.join('.'))});return r.data;}
const leaveSchema=z.object({applicant:z.string().trim().min(1).max(200),type:z.string().min(1).max(100),from:z.string().date(),to:z.string().date(),reason:z.string().max(10000)}).strict().refine(x=>x.to>=x.from);
function leaveContext(p:any,row:any):RecordSecurityContext{const data=row?.data||row||{};return{schoolId:p.schoolId,workspaceKey:'leave-requests',resourceType:'leave-request',recordId:row?.id,ownerUserId:data.submittedBy||null,createdByUserId:data.submittedBy||null,subjectStudentIds:data.studentId?[String(data.studentId)]:[],subjectStaffIds:data.staffId?[String(data.staffId)]:[],lifecycle:data.status||'Pending'}}
async function leavePredicate(db:Queryable,p:any,alias:string){await authorizeWorkspaceAction(db,p,'leave-requests','leave-request','record.view');const grants=(await resolveEffectiveGrants(db,p,'leave-requests','leave-request')).filter(grant=>grant.action==='record.view'),values:any[]=[p.schoolId],clauses:string[]=[];for(const grant of grants){if(grant.scope==='ALL_WORKSPACE')clauses.push('TRUE');else if(grant.scope==='OWNED'||grant.scope==='CREATED_BY'){values.push(p.userId);clauses.push(alias+".data->>'submittedBy'=$"+values.length)}else if(grant.scope==='SELF'){const own:string[]=[];if(p.studentId){values.push(p.studentId);own.push(alias+".data->>'studentId'=$"+values.length)}if(p.teacherId){values.push(p.teacherId);own.push(alias+".data->>'staffId'=$"+values.length)}if(own.length)clauses.push('('+own.join(' OR ')+')')}else if(grant.scope==='CHILD_PERSONAL'&&p.guardianId){values.push(p.guardianId);clauses.push("EXISTS(SELECT 1 FROM guardian_student_links gsl WHERE gsl.school_id=$1 AND gsl.guardian_id=$"+values.length+" AND gsl.student_id="+alias+".data->>'studentId' AND gsl.active=true)")}}return{sql:clauses.length?'('+clauses.join(' OR ')+')':'FALSE',values}}
export async function registerLeaveWorkflowRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const auth=(write=false)=>async(req:FastifyRequest)=>authenticate(req,db,config,write);
 app.get('/api/v1/operation-workflows',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'workflows:view');const settings=await workflowSettings(db,p.schoolId),instances=(await db.query<any>('SELECT data,version FROM operation_workflow_instances WHERE school_id=$1 ORDER BY created_at DESC',[p.schoolId])).rows,roles=(await db.query('SELECT id,name FROM roles WHERE school_id=$1 ORDER BY name',[p.schoolId])).rows;return {data:{...settings,roles,instances:instances.map(i=>({...i.data,version:i.version}))}};});
 app.put('/api/v1/operation-workflows',{preHandler:auth(true)},async req=>{
  const p=req.principal!;requirePermission(p,'workflows:manage');const input=parse(workflowSettingsSchema,req.body);
  const result=await db.transaction(async tx=>{const old=await workflowSettings(tx,p.schoolId,true);if(input.version!==old.version)throw new ApiError('RECORD_VERSION_CONFLICT','Workflow settings changed. Refresh before editing.',409);await validateWorkflows(tx,p,input,old);const r=await tx.query('UPDATE operation_workflow_settings SET definitions=$1,policies=$2,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3 RETURNING version',[JSON.stringify(input.definitions),JSON.stringify(input.policies),p.schoolId]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'WORKFLOW_SETTINGS_UPDATED',entityType:'Workflow',outcome:'SUCCESS',correlationId:req.correlationId});return r.rows[0];});return {data:result};
 });
 app.get('/api/v1/leaves',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'leave:view');const filter=await leavePredicate(db,p,'l'),rows=(await db.query<any>('SELECT l.id,l.data,l.version FROM school_leave_requests l WHERE l.school_id=$1 AND l.archived=false AND '+filter.sql+' ORDER BY l.created_at,l.id',filter.values)).rows,visibleIds=rows.map(r=>r.id),instances=visibleIds.length?(await db.query<any>("SELECT data,version FROM operation_workflow_instances WHERE school_id=$1 AND subject_type='leave' AND subject_id=ANY($2::text[])",[p.schoolId,visibleIds])).rows:[],settings=await workflowSettings(db,p.schoolId);return {data:{items:rows.map(r=>({...r.data,id:r.id,version:r.version})),instances:instances.map(r=>({...r.data,version:r.version})),requireRejectionReason:settings.policies['leave.requireRejectionReason']!==false}};});
 app.post('/api/v1/leaves',{preHandler:auth(true)},async(req,reply)=>{const p=req.principal!;requirePermission(p,'leave:create');const input=parse(leaveSchema,req.body),id=randomUUID(),data={...input,status:'Pending',decisionNote:'',submittedBy:p.userId,submittedByName:p.username};await db.transaction(async tx=>{await authorizeCreate(tx,p,leaveContext(p,{id,data}));await startWorkflow(tx,p,'leave',id,'Leave — '+data.applicant,{leaveDuration:Math.round((Date.parse(data.to)-Date.parse(data.from))/86400000)+1,leaveType:data.type});await tx.query('INSERT INTO school_leave_requests(id,school_id,data) VALUES($1,$2,$3)',[id,p.schoolId,JSON.stringify(data)]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'LEAVE_CREATED',entityType:'Leave',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});});return reply.code(201).send({data:{id}});});
 app.post('/api/v1/leaves/:id/decision',{preHandler:auth(true)},async req=>{const p=req.principal!,id=String((req.params as any).id);const input=parse(z.object({version:z.number().int().positive(),decision:z.enum(['Approved','Rejected']),note:z.string().max(10000)}).strict(),req.body);await db.transaction(async tx=>{
  const r=(await tx.query<any>('SELECT data,version FROM school_leave_requests WHERE school_id=$1 AND id=$2 AND archived=false FOR UPDATE',[p.schoolId,id])).rows[0];if(!r)throw new ApiError('NOT_FOUND','Leave not found.',404);if(r.version!==input.version||r.data.status!=='Pending')throw new ApiError('RECORD_VERSION_CONFLICT','This leave changed or was already decided.',409);const context=leaveContext(p,{id,data:r.data});if(input.decision==='Approved')await authorizeRecord(tx,p,'workflow.approve',context);else await authorizeRecord(tx,p,'workflow.reject',context);
  const result=await advanceOperation(tx,p,'leave',id,input.decision,input.note);if(result.rejected){r.data.status='Rejected';r.data.decisionNote=input.note;}else if(result.final){r.data.status='Approved';r.data.decisionNote=input.note;}
  if(result.rejected||result.final){r.data.decisionBy=p.userId;r.data.decisionByName=p.username;r.data.decisionAt=new Date().toISOString();}
  await tx.query('UPDATE school_leave_requests SET data=$1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3',[JSON.stringify(r.data),p.schoolId,id]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'LEAVE_STEP_DECIDED',entityType:'Leave',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{decision:input.decision,status:r.data.status}});
 });return {data:{saved:true}};});
 app.post('/api/v1/leaves/:id/remove',{preHandler:auth(true)},async req=>{const p=req.principal!,id=String((req.params as any).id);requirePermission(p,'leave:delete');const {version}=parse(z.object({version:z.number().int().positive()}).strict(),req.body);await db.transaction(async tx=>{const current=(await tx.query<any>('SELECT data,version FROM school_leave_requests WHERE school_id=$1 AND id=$2 AND archived=false FOR UPDATE',[p.schoolId,id])).rows[0];if(!current)throw new ApiError('NOT_FOUND','Leave not found.',404);await authorizeRecord(tx,p,'record.archive',leaveContext(p,{id,data:current.data}));const r=await tx.query('UPDATE school_leave_requests SET archived=true,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$1 AND id=$2 AND version=$3 AND archived=false RETURNING id',[p.schoolId,id,version]);if(!r.rows.length)throw new ApiError('RECORD_VERSION_CONFLICT','Leave changed. Refresh before deleting.',409);const rows=(await tx.query<any>("SELECT id,data FROM operation_workflow_instances WHERE school_id=$1 AND subject_type='leave' AND subject_id=$2 FOR UPDATE",[p.schoolId,id])).rows;for(const w of rows)if(w.data.status==='In Progress'){w.data.status='Cancelled';w.data.completedDate=new Date().toISOString().slice(0,10);await tx.query('UPDATE operation_workflow_instances SET data=$1,version=version+1 WHERE school_id=$2 AND id=$3',[JSON.stringify(w.data),p.schoolId,w.id]);}await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'LEAVE_REMOVED',entityType:'Leave',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});});return {data:{removed:true}};});
}
