import {requireLifecycleSelections} from '../authorization/lifecycle-permissions.js';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import type {AppConfig} from '../config/index.js';
import type {Database,Queryable} from '../database/types.js';
import {authenticate} from '../auth/security.js';
import {type Principal} from '../authorization/service.js';
import {authorizeRecord,authorizeUpdate,resolveEffectiveGrants,type RecordSecurityContext,type WorkspaceTabKey} from '../authorization/policy-engine.js';
import {ApiError} from '../errors/api-error.js';
import {WorkspaceService,isOperationalWorkspaceDefinition} from '../services/workspace-service.js';
import {StudentRepository} from '../repositories/student-repository.js';
import {workspaceValues} from './picklists.js';
import {defaultWorkspaceTabs,UNIVERSAL_SPECIAL_PERMISSIONS,UNIVERSAL_TAB_KEYS} from '../authorization/universal-workspace-permissions.js';
import {workspaceManifest,type AuthorizationAction} from '../authorization/policy-registry.js';
import {writeAudit} from '../audit/service.js';
import {experimentalFeatures,gridTabAvailable} from '../services/experimental-features.js';

type OperationalView='create'|'edit'|'record'|'print';
const selectable=new Set(['radio','singleSelect','multiSelect']);
const empty=(value:any)=>value===undefined||value===null||value===''||(Array.isArray(value)&&value.length===0);
function configuredValidationError(field:any,rule:any,fallback:string):never{throw new ApiError('CUSTOM_FIELD_VALIDATION_FAILED',String(rule?.errorMessage||fallback),422,{fieldKey:field.fieldKey,rule:rule?.type||null})}
function validateConfiguredValue(field:any,value:any){
 const cfg=field.configuration||{},text=typeof value==='string'?value:null;
 if(text!==null&&cfg.fieldLength!==undefined&&text.length>Number(cfg.fieldLength))configuredValidationError(field,null,field.label+' must contain at most '+cfg.fieldLength+' characters.');
 for(const rule of Array.isArray(cfg.validationRules)?cfg.validationRules:[]){
  const parameters=String(rule.parameters||'').trim();
  if(rule.type==='minLength'&&text!==null&&text.length<Number(parameters))configuredValidationError(field,rule,field.label+' must contain at least '+parameters+' characters.');
  if(rule.type==='maxLength'&&text!==null&&text.length>Number(parameters))configuredValidationError(field,rule,field.label+' must contain at most '+parameters+' characters.');
  if((rule.type==='pattern'||rule.type==='custom')&&text!==null&&!new RegExp(parameters).test(text))configuredValidationError(field,rule,field.label+' does not match the required format.');
  if(rule.type==='email'&&text!==null&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text))configuredValidationError(field,rule,field.label+' must be a valid email address.');
  if(rule.type==='url'&&text!==null){try{new URL(text)}catch{configuredValidationError(field,rule,field.label+' must be a valid URL.')}}
  if(rule.type==='numberRange'){const range=parameters.split(/\s*(?:,|to)\s*/i).map(Number),number=Number(value);if(!Number.isFinite(number)||number<range[0]||number>range[1])configuredValidationError(field,rule,field.label+' must be from '+range[0]+' to '+range[1]+'.')}
 }
}
function principal(req:FastifyRequest):Principal{if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function viewAction(view:OperationalView){return view==='create'?'record.create':view==='edit'?'record.update':view==='print'?'record.print':'record.view'}

async function picklistValues(db:Queryable,p:Principal,picklistId:string,includeInactive=false){
 const row=(await db.query<any>('SELECT source_type AS "sourceType",workspace_id AS "workspaceId",value_field_key AS "valueFieldKey",label_field_key AS "labelFieldKey",filter_field_key AS "filterFieldKey" FROM picklist_definitions WHERE id=$1 AND school_id=$2 AND active=true',[picklistId,p.schoolId])).rows[0];
 if(!row)throw new ApiError('INVALID_PICKLIST_REFERENCE','The configured Picklist is unavailable.',409);
 if(row.sourceType==='AdminDefined')return(await db.query<any>('SELECT value,label,color,filter_value AS "filterValue" FROM picklist_values WHERE picklist_id=$1 AND school_id=$2 '+(includeInactive?'':'AND active=true ')+'ORDER BY sort_order,id',[picklistId,p.schoolId])).rows;
 return workspaceValues(db,p,row);
}

function tabResource(workspaceKey:string,tabKey:WorkspaceTabKey){const manifest=workspaceManifest(workspaceKey),index=UNIVERSAL_TAB_KEYS.indexOf(tabKey);return manifest[index]||manifest[0]||null}
async function permittedTabs(db:Queryable,p:Principal,workspaceKey:string,action:AuthorizationAction){
 if(p.systemRecovery===true)return[...UNIVERSAL_TAB_KEYS] as WorkspaceTabKey[];
 const tabs:WorkspaceTabKey[]=[];
 for(const tabKey of UNIVERSAL_TAB_KEYS){const resource=tabResource(workspaceKey,tabKey);if(!resource||!resource.actions.includes(action))continue;const grants=await resolveEffectiveGrants(db,p,workspaceKey,resource.resourceType,tabKey);if(grants.some(grant=>grant.action===action))tabs.push(tabKey)}
 return tabs
}

const permissionForView:Record<OperationalView,string>={create:'ADD',edit:'EDIT',record:'VIEW',print:'PRINT'};
async function universalSelections(db:Queryable,p:Principal,workspaceId:string){
 if(p.systemRecovery===true)return{administrator:true,items:new Set<string>()};
 const rows=(await db.query<any>(`SELECT up.tab_key AS "tabKey",up.permission_key AS "permissionKey" FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id AND g.school_id=gm.school_id AND g.active=true JOIN access_group_roles agr ON agr.group_id=g.id AND agr.school_id=g.school_id JOIN access_roles ar ON ar.id=agr.role_id AND ar.school_id=g.school_id AND ar.status='Active' AND ar.workspace_id=$3 JOIN access_role_universal_permissions up ON up.role_id=ar.id AND up.school_id=ar.school_id WHERE gm.school_id=$1 AND gm.user_id=$2`,[p.schoolId,p.userId,workspaceId])).rows,items=new Set<string>(rows.map((row:any)=>row.tabKey+'|'+row.permissionKey));
 return{administrator:items.has('SPECIAL|WORKSPACE_ADMINISTRATOR'),items}
}
function selectedTabs(selection:{administrator:boolean;items:Set<string>},permission:string){return UNIVERSAL_TAB_KEYS.filter(tabKey=>selection.administrator||selection.items.has(tabKey+'|'+permission)) as WorkspaceTabKey[]}
async function requireSelectedPermission(db:Queryable,p:Principal,workspaceId:string,workspaceKey:string,tabKey:WorkspaceTabKey,permission:string){const selection=await universalSelections(db,p,workspaceId);if(selection.administrator||selection.items.has(tabKey+'|'+permission))return selection;throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403,{workspaceKey,tabKey,permission,reason:'TAB_PERMISSION_REQUIRED'})}
function canAccessGridRecord(p:Principal,selection:{administrator:boolean;items:Set<string>},row:any){if(p.systemRecovery===true||selection.administrator||selection.items.has('SPECIAL|VIEW_RECORDS_OWNED_BY_OTHERS'))return true;if(row.owner_user_id===p.userId)return true;return selection.items.has('SPECIAL|VIEW_ASSIGNED_RECORDS')&&Array.isArray(row.assigned_user_ids)&&row.assigned_user_ids.includes(p.userId)}

export async function operationalDefinition(db:Queryable,p:Principal,workspaceKey:string,view:OperationalView,requestedTabKey?:WorkspaceTabKey){
 const service=new WorkspaceService(db as Database),features=await experimentalFeatures(db,p.schoolId),availableTabs=UNIVERSAL_TAB_KEYS.filter(tab=>gridTabAvailable(features,tab)) as WorkspaceTabKey[];
 if(requestedTabKey&&!gridTabAvailable(features,requestedTabKey))
  throw new ApiError('EXPERIMENTAL_FEATURE_DISABLED','Grid tabs are disabled in Admin Settings.',403,{workspaceKey,tabKey:requestedTabKey,feature:'gridTabs'});
 let workspace=(await db.query<any>('SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key=$2 AND status=$3',[p.schoolId,workspaceKey,'Active'])).rows[0];
 if(!workspace&&typeof (db as any).transaction==='function'){await service.syncFactories(p,'operational-fields');workspace=(await db.query<any>('SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key=$2 AND status=$3',[p.schoolId,workspaceKey,'Active'])).rows[0]}
 if(!workspace)return{id:null,workspaceKey,definitionVersion:0,view,tabConfiguration:defaultWorkspaceTabs(workspaceKey),visibleTabKeys:p.systemRecovery===true?[...availableTabs]:[],editableTabKeys:p.systemRecovery===true?[...availableTabs]:[],addableTabKeys:p.systemRecovery===true?[...availableTabs]:[],deletableTabKeys:p.systemRecovery===true?[...availableTabs]:[],printableTabKeys:p.systemRecovery===true?[...availableTabs]:[],specialPermissionKeys:p.systemRecovery===true?[...UNIVERSAL_SPECIAL_PERMISSIONS]:[],sections:[]};
 const definition=await service.definition(db,p,workspace.id),selection=await universalSelections(db,p,workspace.id),visibleTabKeys=(p.systemRecovery===true?[...UNIVERSAL_TAB_KEYS] as WorkspaceTabKey[]:selectedTabs(selection,'VIEW')).filter(tab=>availableTabs.includes(tab)),editableTabKeys=(p.systemRecovery===true?[...UNIVERSAL_TAB_KEYS] as WorkspaceTabKey[]:selectedTabs(selection,'EDIT')).filter(tab=>availableTabs.includes(tab)),addableTabKeys=(p.systemRecovery===true?[...UNIVERSAL_TAB_KEYS] as WorkspaceTabKey[]:selectedTabs(selection,'ADD')).filter(tab=>availableTabs.includes(tab)),deletableTabKeys=(p.systemRecovery===true?[...UNIVERSAL_TAB_KEYS] as WorkspaceTabKey[]:selectedTabs(selection,'DELETE')).filter(tab=>availableTabs.includes(tab)),printableTabKeys=(p.systemRecovery===true?[...UNIVERSAL_TAB_KEYS] as WorkspaceTabKey[]:selectedTabs(selection,'PRINT')).filter(tab=>availableTabs.includes(tab));
 if(!visibleTabKeys.length)throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403,{workspaceKey,action:'record.view',reason:'NO_VISIBLE_WORKSPACE_TAB'});
 const action=viewAction(view),actionTabs=view==='record'?visibleTabKeys:({create:addableTabKeys,edit:editableTabKeys,print:printableTabKeys} as any)[view]||[],allowedTabs=actionTabs.filter((tab:WorkspaceTabKey)=>visibleTabKeys.includes(tab));
 if(requestedTabKey&&(!visibleTabKeys.includes(requestedTabKey)||!allowedTabs.includes(requestedTabKey)))throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403,{workspaceKey,tabKey:requestedTabKey,action,reason:'TAB_PERMISSION_REQUIRED'});
 const includedTabs=new Set<WorkspaceTabKey>(requestedTabKey?[requestedTabKey]:allowedTabs),sections=[];
 for(const section of definition.sections){
  const tabKey=(section.tabKey||'MAIN') as WorkspaceTabKey;if(!includedTabs.has(tabKey))continue;
  const rule=(section.roleVisibility||[]).find((x:any)=>x.roleId===p.roleId);
  const layout=section.layouts?.[view]||{};
  const sectionVisible=view==='print'?(section.printVisible!==false&&rule?.printVisible!==false):(section.screenVisible!==false&&rule?.screenVisible!==false&&(view!=='edit'||rule?.editVisible!==false));
  if(!sectionVisible||layout.visible===false)continue;
  const fields=[];
  for(const field of section.fields){
   if(field.system||field.archived)continue;
   if(field.configuration?.visibility==='hidden')continue;
   if((view==='create'||view==='edit')&&field.configuration?.readOnly===true)continue;
   if(view==='print'?field.printVisible===false:field.screenVisible===false)continue;
   const item={...field,choices:[] as any[]};
   if(selectable.has(field.fieldType)&&field.configuration?.picklistId)item.choices=await picklistValues(db,p,field.configuration.picklistId,view==='record'||view==='print');
   else if(selectable.has(field.fieldType))item.choices=(field.options||[]).filter((x:any)=>x.active!==false).map((x:any)=>({value:x.value,label:x.label,filterValue:null}));
   fields.push(item);
  }
  if(fields.length)sections.push({...section,fields});
 }
 const specialPermissionKeys=selection.administrator?UNIVERSAL_SPECIAL_PERMISSIONS.filter(key=>p.systemRecovery===true||!['PERMANENT_DELETE','RESTORE_ARCHIVED_RECORDS'].includes(key)||selection.items.has('SPECIAL|'+key)):[...selection.items].filter(item=>item.startsWith('SPECIAL|')).map(item=>item.slice(8));
 return{id:definition.id,workspaceKey,name:definition.name,pluralName:definition.pluralName,definitionVersion:definition.definitionVersion,view,tabConfiguration:definition.tabConfiguration,visibleTabKeys,editableTabKeys,addableTabKeys,deletableTabKeys,printableTabKeys,specialPermissionKeys,sections};
}
export function assertWritableOperationalFieldKeys(values:Record<string,any>,fields:readonly any[]){
 const allowed=new Set(fields.filter(field=>field.configuration?.readOnly!==true).map(field=>field.fieldKey));
 for(const key of Object.keys(values))if(!allowed.has(key))throw new ApiError('CUSTOM_FIELD_NOT_WRITABLE','A custom field is unavailable, read-only, or hidden for your role.',422,{fieldKey:key});
}
export async function validateOperationalCustomValues(db:Queryable,p:Principal,workspaceKey:string,values:Record<string,any>,context:Record<string,any>,view:'create'|'edit',tabKey?:WorkspaceTabKey){
 const definition=await operationalDefinition(db,p,workspaceKey,view,tabKey),fields=definition.sections.flatMap((x:any)=>x.fields);
 assertWritableOperationalFieldKeys(values,fields);
 const normalized:Record<string,any>={};
 for(const field of fields){
  const supplied=Object.prototype.hasOwnProperty.call(values,field.fieldKey);
  if(view==='edit'&&!supplied)continue;
  let value=supplied?values[field.fieldKey]:field.defaultValue;
  if(empty(value)){if(field.required)throw new ApiError('CUSTOM_FIELD_REQUIRED',field.label+' is required.',422,{fieldKey:field.fieldKey});if(supplied)normalized[field.fieldKey]=null;continue}
  if(['integer','decimal','currency'].includes(field.fieldType)){const number=Number(value);if(!Number.isFinite(number)||(field.fieldType==='integer'&&!Number.isInteger(number)))throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be a valid number.',422,{fieldKey:field.fieldKey});value=number}
  else if(['boolean','checkbox'].includes(field.fieldType)){if(typeof value!=='boolean')throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be true or false.',422,{fieldKey:field.fieldKey})}
  else if(field.fieldType==='matrix'){
   if(!value||typeof value!=='object'||Array.isArray(value))throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must contain Matrix values.',422,{fieldKey:field.fieldKey});
   const rows=new Set((field.configuration?.rows||[]).map((x:any)=>x.key)),columns=new Set((field.configuration?.columns||[]).map((x:any)=>x.key));
   for(const [row,cells] of Object.entries(value)){if(!rows.has(row)||!cells||typeof cells!=='object'||Array.isArray(cells))throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' contains an invalid Matrix row.',422,{fieldKey:field.fieldKey});for(const column of Object.keys(cells as object))if(!columns.has(column))throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' contains an invalid Matrix column.',422,{fieldKey:field.fieldKey})}
  }else if(field.fieldType==='image'){
   if(typeof value!=='string')throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be an image attachment.',422,{fieldKey:field.fieldKey});
   const match=value.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be a JPEG, PNG, or WebP image.',422,{fieldKey:field.fieldKey});
   const maxMb=Math.max(1,Math.min(10,Number(field.configuration?.maxSizeMb)||5));if(Buffer.from(match[2],'base64').byteLength>maxMb*1024*1024)throw new ApiError('CUSTOM_FIELD_TOO_LARGE',field.label+' must be '+maxMb+' MB or smaller.',422,{fieldKey:field.fieldKey,maxSizeMb:maxMb});
  }else if(field.fieldType==='pdf'){
   if(typeof value!=='string')throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be a PDF document.',422,{fieldKey:field.fieldKey});
   const match=value.match(/^data:application\/pdf;base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be a PDF document.',422,{fieldKey:field.fieldKey});
   const maxMb=Math.max(1,Math.min(10,Number(field.configuration?.maxSizeMb)||10));if(Buffer.from(match[1],'base64').byteLength>maxMb*1024*1024)throw new ApiError('CUSTOM_FIELD_TOO_LARGE',field.label+' must be '+maxMb+' MB or smaller.',422,{fieldKey:field.fieldKey,maxSizeMb:maxMb});
  }else if(selectable.has(field.fieldType)){
   const selected=field.fieldType==='multiSelect'?(Array.isArray(value)?value:[value]):[value],choices=field.choices||[],choiceMap=new Map(choices.map((x:any)=>[String(x.value),x]));
   for(const selectedValue of selected){const choice:any=choiceMap.get(String(selectedValue));if(!choice)throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' contains a value outside its Picklist.',422,{fieldKey:field.fieldKey});if(field.configuration?.picklistMode==='filtered'){const controller=values[field.configuration.picklistFilterFieldKey]??context[field.configuration.picklistFilterFieldKey];if(String(choice.filterValue??'')!==String(controller??''))throw new ApiError('CUSTOM_FIELD_FILTER_MISMATCH',field.label+' does not match its controlling field.',422,{fieldKey:field.fieldKey})}}
   value=field.fieldType==='multiSelect'?selected.map(String):String(selected[0]);
  }else{value=String(value);if(value.length>10000)throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' is too long.',422,{fieldKey:field.fieldKey});if(field.fieldType==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be a valid email address.',422,{fieldKey:field.fieldKey});if(field.fieldType==='url'){try{new URL(value)}catch{throw new ApiError('CUSTOM_FIELD_INVALID',field.label+' must be a valid URL.',422,{fieldKey:field.fieldKey})}}}
  validateConfiguredValue(field,value);
  if(field.configuration?.unique===true){
   const serialized=typeof value==='string'?value:JSON.stringify(value),recordId=String(context.id||context.recordId||'');let duplicate:any;
   if(workspaceKey==='students'||workspaceKey==='staff'){const table=workspaceKey==='students'?'students':'staff',query="SELECT id FROM "+table+" WHERE school_id=$1 AND extra->'workspaceCustomFields'->>$2=$3"+(recordId?' AND id<>$4':'')+" LIMIT 1",params=recordId?[p.schoolId,field.fieldKey,serialized,recordId]:[p.schoolId,field.fieldKey,serialized];duplicate=(await db.query(query,params)).rows[0]}
   else{const query="SELECT r.id FROM workspace_grid_records r JOIN workspace_definitions w ON w.id=r.workspace_id WHERE r.school_id=$1 AND w.workspace_key=$2 AND r.field_values->>$3=$4 AND r.status='Active'"+(recordId?' AND r.id<>$5':'')+" LIMIT 1",params=recordId?[p.schoolId,workspaceKey,field.fieldKey,serialized,recordId]:[p.schoolId,workspaceKey,field.fieldKey,serialized];duplicate=(await db.query(query,params)).rows[0]}
   if(duplicate)throw new ApiError('CUSTOM_FIELD_NOT_UNIQUE',field.label+' must be unique.',422,{fieldKey:field.fieldKey});
  }
  normalized[field.fieldKey]=value;
 }
 return normalized;
}
export async function validateStudentCustomValues(db:Queryable,p:Principal,values:Record<string,any>,context:Record<string,any>,view:'create'|'edit',tabKey:WorkspaceTabKey='MAIN'){return validateOperationalCustomValues(db,p,'students',values,context,view,tabKey)}

export async function registerOperationalWorkspaceRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const auth=async(req:FastifyRequest)=>authenticate(req,db,config);
 app.get('/api/v1/operational-workspaces',{preHandler:auth},async req=>{const p=principal(req),rows=(await db.query<any>('SELECT id,workspace_key AS "workspaceKey",name,plural_name AS "pluralName",category,system,navigation_configuration AS "navigationConfiguration" FROM workspace_definitions WHERE school_id=$1 AND status=\'Active\' ORDER BY category,plural_name',[p.schoolId])).rows,items=[];for(const row of rows){if(!isOperationalWorkspaceDefinition(row))continue;const selection=await universalSelections(db,p,row.id);if(p.systemRecovery!==true&&!selection.items.has('DASHBOARD|VIEW'))continue;items.push({id:row.id,workspaceKey:row.workspaceKey,name:row.name,pluralName:row.pluralName,category:row.category,system:row.system,navigationConfiguration:row.navigationConfiguration||{}})}return{data:{items}}});
 app.get('/api/v1/operational-workspaces/:workspaceKey',{preHandler:auth},async req=>{const p=principal(req),view=String((req.query as any)?.view||'record') as OperationalView,rawTab=String((req.query as any)?.tabKey||''),tabKey=rawTab?(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null:undefined;if(rawTab&&!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);if(!['create','edit','record','print'].includes(view))throw new ApiError('VALIDATION_FAILED','Choose create, edit, record, or print view.',422);return{data:await operationalDefinition(db,p,String((req.params as any).workspaceKey),view,tabKey||undefined)}});
 app.get('/api/v1/operational-workspaces/:workspaceKey/tabs/:tabKey/grid-records',{preHandler:auth},async req=>{const p=principal(req),workspaceKey=String((req.params as any).workspaceKey),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,workspaceKey,'record',tabKey),selection=await universalSelections(db,p,definition.id),viewOthers=p.systemRecovery===true||selection.administrator||selection.items.has('SPECIAL|VIEW_RECORDS_OWNED_BY_OTHERS'),viewAssigned=selection.administrator||selection.items.has('SPECIAL|VIEW_ASSIGNED_RECORDS'),viewArchived=p.systemRecovery===true||selection.administrator||selection.items.has('SPECIAL|VIEW_ARCHIVED_RECORDS'),values:any[]=[p.schoolId,definition.id,tabKey],clauses:string[]=[];if(viewOthers)clauses.push('TRUE');else{values.push(p.userId);clauses.push('owner_user_id=$'+values.length);if(viewAssigned){values.push(JSON.stringify([p.userId]));clauses.push('assigned_user_ids @> $'+values.length+'::jsonb')}}const rows=(await db.query<any>("SELECT id,field_values AS values,owner_user_id AS \"ownerUserId\",assigned_user_ids AS \"assignedUserIds\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\",version FROM workspace_grid_records WHERE school_id=$1 AND workspace_id=$2 AND tab_key=$3 AND status "+(viewArchived?"IN ('Active','Archived')":"='Active'")+' AND ('+clauses.join(' OR ')+') ORDER BY status,created_at DESC LIMIT 500',values)).rows;return{data:{items:rows,tabKey}}});
 app.post('/api/v1/operational-workspaces/:workspaceKey/tabs/:tabKey/grid-records',{preHandler:auth},async(req,reply)=>{const p=principal(req),workspaceKey=String((req.params as any).workspaceKey),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,workspaceKey,'create',tabKey),body=z.object({values:z.record(z.string().max(120),z.unknown())}).strict().parse(req.body),recordId=randomUUID(),row=await db.transaction(async tx=>{const values=await validateOperationalCustomValues(tx,p,workspaceKey,body.values,{recordId},'create',tabKey),created=(await tx.query<any>('INSERT INTO workspace_grid_records(id,school_id,workspace_id,tab_key,field_values,owner_user_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$6) RETURNING id,field_values AS values,owner_user_id AS "ownerUserId",assigned_user_ids AS "assignedUserIds",status,created_at AS "createdAt",updated_at AS "updatedAt",version',[recordId,p.schoolId,definition.id,tabKey,JSON.stringify(values),p.userId])).rows[0];await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'WORKSPACE_GRID_RECORD_CREATED',entityType:'Workspace Grid Record',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{workspaceKey,tabKey}});return created});return reply.code(201).send({data:row})});
 app.patch('/api/v1/operational-workspaces/:workspaceKey/tabs/:tabKey/grid-records/:recordId',{preHandler:auth},async req=>{const p=principal(req),workspaceKey=String((req.params as any).workspaceKey),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,workspaceKey,'edit',tabKey),recordId=String((req.params as any).recordId),body=z.object({version:z.number().int().positive(),values:z.record(z.string().max(120),z.unknown())}).strict().parse(req.body),row=await db.transaction(async tx=>{const old=(await tx.query<any>('SELECT * FROM workspace_grid_records WHERE id=$1 AND school_id=$2 AND workspace_id=$3 AND tab_key=$4 AND status=\'Active\' FOR UPDATE',[recordId,p.schoolId,definition.id,tabKey])).rows[0];if(!old)throw new ApiError('RECORD_NOT_FOUND','Grid record not found.',404);const selection=await requireSelectedPermission(tx,p,definition.id,workspaceKey,tabKey,'EDIT'),canOthers=p.systemRecovery===true||selection.administrator||selection.items.has('SPECIAL|VIEW_RECORDS_OWNED_BY_OTHERS'),canAssigned=selection.administrator||selection.items.has('SPECIAL|VIEW_ASSIGNED_RECORDS');if(!canOthers&&old.owner_user_id!==p.userId&&!(canAssigned&&Array.isArray(old.assigned_user_ids)&&old.assigned_user_ids.includes(p.userId)))throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403);if(old.version!==body.version)throw new ApiError('RECORD_VERSION_CONFLICT','Grid record changed. Reload before saving.',409);const values=await validateOperationalCustomValues(tx,p,workspaceKey,body.values,{recordId},'edit',tabKey),updated=(await tx.query<any>('UPDATE workspace_grid_records SET field_values=$1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND school_id=$3 AND version=$4 RETURNING id,field_values AS values,owner_user_id AS "ownerUserId",assigned_user_ids AS "assignedUserIds",status,created_at AS "createdAt",updated_at AS "updatedAt",version',[JSON.stringify({...old.field_values,...values}),recordId,p.schoolId,body.version])).rows[0];await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'WORKSPACE_GRID_RECORD_UPDATED',entityType:'Workspace Grid Record',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{workspaceKey,tabKey,fields:Object.keys(values)}});return updated});return{data:row}});
 app.post('/api/v1/operational-workspaces/:workspaceKey/tabs/:tabKey/grid-records/:recordId/archive',{preHandler:auth},async req=>{const p=principal(req),workspaceKey=String((req.params as any).workspaceKey),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,workspaceKey,'record',tabKey),selection=await requireSelectedPermission(db,p,definition.id,workspaceKey,tabKey,'DELETE'),recordId=String((req.params as any).recordId),body=z.object({version:z.number().int().positive()}).strict().parse(req.body),row=await db.transaction(async tx=>{const old=(await tx.query<any>("SELECT * FROM workspace_grid_records WHERE id=$1 AND school_id=$2 AND workspace_id=$3 AND tab_key=$4 AND status='Active' FOR UPDATE",[recordId,p.schoolId,definition.id,tabKey])).rows[0];if(!old)throw new ApiError('RECORD_NOT_FOUND','Grid record not found.',404);if(!canAccessGridRecord(p,selection,old))throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403);if(old.version!==body.version)throw new ApiError('RECORD_VERSION_CONFLICT','Grid record changed. Reload before deleting.',409);const updated=(await tx.query<any>("UPDATE workspace_grid_records SET status='Archived',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING id,status,version",[recordId,p.schoolId,body.version])).rows[0];await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'WORKSPACE_GRID_RECORD_ARCHIVED',entityType:'Workspace Grid Record',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{workspaceKey,tabKey}});return updated});return{data:row}});
 app.post('/api/v1/operational-workspaces/:workspaceKey/tabs/:tabKey/grid-records/:recordId/restore',{preHandler:auth},async req=>{const p=principal(req),workspaceKey=String((req.params as any).workspaceKey),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,workspaceKey,'record',tabKey),lifecycleRoles=await requireLifecycleSelections(db,p,workspaceKey,tabKey,'restore');const recordId=String((req.params as any).recordId),body=z.object({version:z.number().int().positive()}).strict().parse(req.body),updated=await db.transaction(async tx=>{const old=(await tx.query<any>("SELECT * FROM workspace_grid_records WHERE id=$1 AND school_id=$2 AND workspace_id=$3 AND tab_key=$4 AND status='Archived' FOR UPDATE",[recordId,p.schoolId,definition.id,tabKey])).rows[0];if(!old)throw new ApiError('RECORD_NOT_FOUND','Archived record not found.',404);if(p.systemRecovery!==true&&!lifecycleRoles.some(role=>canAccessGridRecord(p,{administrator:role.items.has('SPECIAL|WORKSPACE_ADMINISTRATOR'),items:role.items},old)))throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403);if(old.version!==body.version)throw new ApiError('RECORD_VERSION_CONFLICT','Archived record changed. Reload before restoring.',409);const row=(await tx.query<any>("UPDATE workspace_grid_records SET status='Active',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING id,status,version",[recordId,p.schoolId,body.version])).rows[0];await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'WORKSPACE_GRID_RECORD_RESTORED',entityType:'Workspace Grid Record',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{workspaceKey,tabKey}});return row});return{data:updated}});
 app.delete('/api/v1/operational-workspaces/:workspaceKey/tabs/:tabKey/grid-records/:recordId',{preHandler:auth},async req=>{const p=principal(req),workspaceKey=String((req.params as any).workspaceKey),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,workspaceKey,'record',tabKey),lifecycleRoles=await requireLifecycleSelections(db,p,workspaceKey,tabKey,'permanentDelete');const recordId=String((req.params as any).recordId),body=z.object({version:z.number().int().positive(),confirmation:z.literal('DELETE')}).strict().parse(req.body);await db.transaction(async tx=>{const old=(await tx.query<any>("SELECT * FROM workspace_grid_records WHERE id=$1 AND school_id=$2 AND workspace_id=$3 AND tab_key=$4 AND status='Archived' FOR UPDATE",[recordId,p.schoolId,definition.id,tabKey])).rows[0];if(!old)throw new ApiError('RECORD_NOT_FOUND','Archived record not found.',404);if(p.systemRecovery!==true&&!lifecycleRoles.some(role=>canAccessGridRecord(p,{administrator:role.items.has('SPECIAL|WORKSPACE_ADMINISTRATOR'),items:role.items},old)))throw new ApiError('AUTHORIZATION_DENIED','Access is denied.',403);if(old.version!==body.version)throw new ApiError('RECORD_VERSION_CONFLICT','Archived record changed. Reload before permanent deletion.',409);await tx.query('DELETE FROM workspace_grid_records WHERE id=$1 AND school_id=$2',[recordId,p.schoolId]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'WORKSPACE_GRID_RECORD_PERMANENTLY_DELETED',entityType:'Workspace Grid Record',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{workspaceKey,tabKey}})});return{data:{deleted:true}}});
 app.get('/api/v1/operational-workspaces/students/tabs/:tabKey/records',{preHandler:auth},async req=>{const p=principal(req),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const definition=await operationalDefinition(db,p,'students','record',tabKey),query=req.query as any,page=Math.max(1,Number(query?.page)||1),pageSize=Math.max(1,Math.min(100,Number(query?.pageSize)||100)),model=await new StudentRepository(db).list(p,{search:String(query?.search||''),classId:String(query?.classId||''),sectionId:String(query?.sectionId||''),status:String(query?.status||''),page,pageSize},tabKey),keys=new Set(definition.sections.flatMap((section:any)=>section.fields.map((field:any)=>field.fieldKey))),items=[];for(const student of model.items){const raw=(await db.query<any>('SELECT extra FROM students WHERE id=$1 AND school_id=$2',[student.id,p.schoolId])).rows[0]?.extra?.workspaceCustomFields||{},customValues=Object.fromEntries(Object.entries(raw).filter(([key])=>keys.has(key)));items.push({...student,customValues})}return{data:{...model,items,tabKey}}});
 app.patch('/api/v1/operational-workspaces/students/tabs/:tabKey/records/:recordId',{preHandler:auth},async req=>{const p=principal(req),rawTab=String((req.params as any).tabKey),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);const input=z.object({version:z.number().int().positive(),customValues:z.record(z.string().max(120),z.unknown())}).strict().parse(req.body),recordId=String((req.params as any).recordId);const result=await db.transaction(async tx=>{await operationalDefinition(tx,p,'students','edit',tabKey);const repo=new StudentRepository(tx),current=await repo.get(p,recordId,tabKey),context:RecordSecurityContext={schoolId:p.schoolId,workspaceKey:'students',resourceType:'student',recordId,subjectStudentIds:[recordId],classId:current.classId||null,sectionId:current.sectionId||null,academicYearId:current.academicYearId||null,lifecycle:current.status==='Active'?'Active':'Archived',tabKey};await authorizeUpdate(tx,p,context,context);const customValues=await validateOperationalCustomValues(tx,p,'students',input.customValues,{...current,id:recordId},'edit',tabKey),raw=(await tx.query<any>('SELECT extra FROM students WHERE id=$1 AND school_id=$2',[recordId,p.schoolId])).rows[0]?.extra||{},row=await repo.update(tx,p,recordId,{extra:{...raw,workspaceCustomFields:{...(raw.workspaceCustomFields||{}),...customValues}}},input.version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'STUDENT_GRID_UPDATED',entityType:'Student',entityId:recordId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{tabKey,fields:Object.keys(customValues),version:row.version}});return row});return{data:result}});
 app.get('/api/v1/operational-workspaces/students/records/:recordId',{preHandler:auth},async req=>{const p=principal(req),view=String((req.query as any)?.view||'record') as OperationalView,rawTab=String((req.query as any)?.tabKey||'MAIN'),tabKey=(UNIVERSAL_TAB_KEYS as readonly string[]).includes(rawTab)?rawTab as WorkspaceTabKey:null;if(!tabKey)throw new ApiError('VALIDATION_FAILED','Choose Main Tab or Grid Tab 1–3.',422);if(!['edit','record','print'].includes(view))throw new ApiError('VALIDATION_FAILED','Choose edit, record, or print view.',422);const recordId=String((req.params as any).recordId);await new StudentRepository(db).get(p,recordId,tabKey);const definition=await operationalDefinition(db,p,'students',view,tabKey),keys=new Set(definition.sections.flatMap((section:any)=>section.fields.map((field:any)=>field.fieldKey))),raw=(await db.query<any>('SELECT extra FROM students WHERE id=$1 AND school_id=$2',[recordId,p.schoolId])).rows[0]?.extra?.workspaceCustomFields||{},values=Object.fromEntries(Object.entries(raw).filter(([key])=>keys.has(key)));return{data:{recordId,view,tabKey,values}}});
 app.get('/api/v1/operational-workspaces/staff/records/:recordId',{preHandler:auth},async req=>{const p=principal(req),view=String((req.query as any)?.view||'record') as OperationalView;if(!['edit','record','print'].includes(view))throw new ApiError('VALIDATION_FAILED','Choose edit, record, or print view.',422);const recordId=String((req.params as any).recordId),found=await db.query<any>('SELECT id,extra,status FROM staff WHERE id=$1 AND school_id=$2',[recordId,p.schoolId]);if(!found.rows[0])throw new ApiError('RECORD_NOT_FOUND','Staff record not found or outside your access.',404);const context:RecordSecurityContext={schoolId:p.schoolId,workspaceKey:'staff',resourceType:'staff',recordId,subjectStaffIds:[recordId],lifecycle:found.rows[0].status};await authorizeRecord(db,p,viewAction(view),context);const definition=await operationalDefinition(db,p,'staff',view),keys=new Set(definition.sections.flatMap((section:any)=>section.fields.map((field:any)=>field.fieldKey))),raw=found.rows[0].extra?.workspaceCustomFields||{},values=Object.fromEntries(Object.entries(raw).filter(([key])=>keys.has(key)));return{data:{recordId,view,values}}});
}
