import { randomBytes, randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AppConfig } from '../config/index.js';
import type { Database, Queryable } from '../database/types.js';
import { ApiError } from '../errors/api-error.js';
import { authenticate } from '../auth/security.js';
import { digest } from '../auth/sessions.js';
import { hashPassword } from '../auth/password.js';
import { requirePermission, type Principal } from '../authorization/service.js';
import {authorizeRecord} from '../authorization/policy-engine.js';
import { writeAudit } from '../audit/service.js';

export const SERVER_PERMISSIONS = [
  'assets:view','assets:manage','idcards:view','idcards:manage','idcards:print',
  'workflows:view','workflows:manage','leave:view','leave:create','leave:update','leave:delete','leave:print',
  'fees:view','fees:create','fees:update','fees:delete','fees:print',
  'certificates:view','certificates:create','certificates:print',
  'reports:view','reports:print',
  'teacherlog:view','teacherlog:create','teacherlog:update','teacherlog:delete','teacherlog:print',
  'transport:view','transport:create','transport:update','transport:delete','transport:print',
  'uniform:view','uniform:create','uniform:update','uniform:delete','uniform:print',
  'curriculum:view','curriculum:create','curriculum:update','curriculum:delete','curriculum:print',
  'documents:view','documents:create','documents:update','documents:delete','documents:print',
  'rules:view','rules:update','rules:print',
  'notices:view','notices:create','notices:update','notices:delete','notices:print',
  'calendar:view','calendar:create','calendar:update','calendar:delete','calendar:print',
  'school:read','school:manage','core:manage','users:view','users:manage',
  'students:view','students:create','students:update','students:print','students:deactivate','students:restore',
  'imports:manage','audit:view','diagnostics:view','diagnostics:export',
  'portal:manage','portal:self',
  'attendance:view','attendance:manage','homework:view','homework:manage','homework:publish',
  'timetable:view','timetable:manage','exams:view','exams:manage','marks:manage','marks:publish','marks:correct',
  'reportcards:view','reportcards:publish','promotion:manage',
  'workspaces:view','workspaces:configure','workspaces:create','workspaces:archive','workspaces:reset'
] as const;

export const PRODUCTION_AUTHORITY = Object.freeze({
  authoritative:['school','users','roles','permissions','staff','students','classes','sections','subjects','teacherAssignments','academicYears','guardians','portalIdentityLinks','coreDashboard','audit','attendance','homework','timetable','exams','marks','reportCards','promotion','studentAcademicHistory','workspaceMetadata','notices','calendar','documents','rules','uniform','curriculum','transport','teacherWorkLog','leave','workflows','fees','certificates','reports','assets','digitalIdCards'],
  unavailable:[],
  localPreferences:['personalTheme','sidebar','personalDashboardLayout','lastSelectedView']
});

const permission = z.enum(SERVER_PERMISSIONS);
const roleCreate = z.object({name:z.string().trim().min(2).max(80),permissions:z.array(permission).max(SERVER_PERMISSIONS.length).default([])}).strict();
const roleUpdate = roleCreate.partial().extend({version:z.number().int().positive()}).strict();
const userCreate = z.object({firstName:z.string().trim().max(80).default(''),lastName:z.string().trim().max(80).default(''),email:z.union([z.string().trim().email().max(180),z.literal('')]).default(''),username:z.string().trim().min(3).max(120),password:z.string().min(8).max(200).optional(),status:z.enum(['Active','Inactive','Deleted']).default('Active'),roleId:z.string().min(1).max(120).optional(),groupIds:z.array(z.string().min(1).max(120)).max(500).default([]),teacherId:z.string().max(120).nullable().optional(),studentId:z.string().max(120).nullable().optional(),guardianId:z.string().max(120).nullable().optional()}).strict();
const userUpdate = z.object({firstName:z.string().trim().min(1).max(80).optional(),lastName:z.string().trim().min(1).max(80).optional(),email:z.string().trim().email().max(180).optional(),username:z.string().trim().min(3).max(120).optional(),password:z.string().min(8).max(200).optional(),roleId:z.string().min(1).max(120).optional(),status:z.enum(['Active','Inactive','Deleted']).optional(),version:z.number().int().positive()}).strict();
const schoolLogo = z.union([z.string().max(8_000_000).regex(/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=\r\n]+$/),z.literal('')]).nullable();
const printTextStyle = z.object({family:z.string().max(80).optional(),size:z.number().min(6).max(72).optional(),bold:z.boolean().optional(),italic:z.boolean().optional(),letterSpacing:z.number().min(0).max(12).optional(),textCase:z.enum(['none','uppercase','lowercase','capitalize']).optional()}).strict();
const printHeaderSettings = z.object({tagline:z.string().max(240).optional(),extra:z.record(z.string().max(80),z.string().max(500)).optional(),layout:z.enum(['logoLeft','logoRight','centered']).optional(),align:z.record(z.string().max(40),z.enum(['left','center','right'])).optional(),logoSize:z.number().min(16).max(160).optional(),fontFamily:z.string().max(80).optional(),typography:z.object({schoolName:printTextStyle.optional(),tagline:printTextStyle.optional(),address:printTextStyle.optional(),contact:printTextStyle.optional(),customFields:printTextStyle.optional()}).strict().optional(),divider:z.enum(['none','thin','medium','thick','double']).optional(),spacing:z.object({top:z.number().min(0).max(80).optional(),logoGap:z.number().min(0).max(80).optional(),nameGap:z.number().min(0).max(40).optional(),infoGap:z.number().min(0).max(40).optional(),bottom:z.number().min(0).max(80).optional()}).strict().optional(),elements:z.object({logo:z.boolean().optional(),schoolName:z.boolean().optional(),tagline:z.boolean().optional(),customFields:z.boolean().optional()}).strict().optional(),contactItems:z.array(z.object({id:z.string().max(80),label:z.string().max(120),enabled:z.boolean()}).strict()).max(40).optional(),customFields:z.array(z.object({id:z.string().max(80).optional(),label:z.string().max(120),value:z.string().max(500),enabled:z.boolean().optional()}).strict()).max(40).optional()}).strict();
const watermarkSettings = z.object({enabled:z.boolean(),type:z.enum(['text','logo']),text:z.string().max(120),opacity:z.number().min(3).max(50),position:z.enum(['center','top','bottom']),rotation:z.number().min(-90).max(90),size:z.number().min(20).max(90)}).strict();
const dashboardRoleDefaults = z.record(z.string().min(1).max(120),z.array(z.string().min(1).max(120)).max(50)).refine(value=>Object.keys(value).length<=200,'Too many role dashboard defaults.');
const schoolUpdate = z.object({name:z.string().trim().min(2).max(160).optional(),contactPhone:z.string().max(40).nullable().optional(),email:z.string().email().max(180).nullable().optional(),website:z.string().url().max(240).nullable().optional(),address:z.string().max(500).nullable().optional(),principalName:z.string().max(160).nullable().optional(),logo:schoolLogo.optional(),brandColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),theme:z.enum(['light','dark','system']).optional(),loginBg:schoolLogo.optional(),loginBgPosition:z.enum(['center','top','bottom','left','right']).optional(),loginBgOpacity:z.number().min(0).max(100).optional(),loginOverlay:z.number().min(0).max(80).optional(),loginSubtitle:z.string().max(240).optional(),printHeaderSettings:printHeaderSettings.optional(),watermarkSettings:watermarkSettings.optional(),dashboardRoleDefaults:dashboardRoleDefaults.optional(),studentPrefix:z.string().max(20).nullable().optional(),employeePrefix:z.string().max(20).nullable().optional(),receiptPrefix:z.string().max(20).nullable().optional(),currency:z.string().regex(/^[A-Z]{3}$/).optional(),activeAcademicYearId:z.string().max(120).nullable().optional(),version:z.number().int().positive()}).strict();
const versionOnly = z.object({version:z.number().int().positive()}).strict();

function parsed<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApiError('VALIDATION_FAILED','The request contains invalid or protected fields.',422,{fields:result.error.issues.map(x=>x.path.join('.'))});return result.data}
function principal(req:FastifyRequest){if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function auth(db:Database,config:AppConfig,csrf=false){return async(req:FastifyRequest)=>authenticate(req,db,config,csrf)}
function conflict(label:string){return new ApiError('RECORD_VERSION_CONFLICT',label+' changed on another device. Refresh and review before saving.',409)}
const SCHOOL_SETTING_KEYS=['contactPhone','email','website','address','principalName','logo','brandColor','theme','loginBg','loginBgPosition','loginBgOpacity','loginOverlay','loginSubtitle','printHeaderSettings','watermarkSettings','dashboardRoleDefaults','studentPrefix','employeePrefix','receiptPrefix','currency'] as const;
function safeSettings(value:any){const source=value&&typeof value==='object'?value:{};return Object.fromEntries(SCHOOL_SETTING_KEYS.filter(k=>Object.prototype.hasOwnProperty.call(source,k)).map(k=>[k,source[k]]))}
async function activeRole(db:Queryable,p:Principal,id:string){const r=await db.query<any>('SELECT id,name,system,active,version FROM roles WHERE id=$1 AND school_id=$2 AND active=true',[id,p.schoolId]);if(!r.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','The selected role is unavailable.',422);return r.rows[0]}
async function activeReference(db:Queryable,p:Principal,table:'staff'|'students'|'guardian_profiles',id:string|null|undefined){if(!id)return null;const active=table==='students'||table==='staff'?"status='Active'":"status='Active'",r=await db.query<any>(`SELECT id FROM ${table} WHERE id=$1 AND school_id=$2 AND ${active}`,[id,p.schoolId]);if(!r.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','A selected identity link is unavailable.',422);return id}
async function accountRoleForCreate(db:Queryable,p:Principal,input:z.infer<typeof userCreate>){
  if(input.roleId)return activeRole(db,p,input.roleId);
  const existing=await db.query<any>("SELECT id,name,system,active,version FROM roles WHERE school_id=$1 AND name='Group Managed User'",[p.schoolId]);
  if(existing.rows[0])return existing.rows[0];
  const id=randomUUID(),created=await db.query<any>("INSERT INTO roles(id,school_id,name,system,active) VALUES($1,$2,'Group Managed User',true,false) RETURNING id,name,system,active,version",[id,p.schoolId]);
  return created.rows[0]
}
async function assignInitialGroups(db:Queryable,p:Principal,userId:string,groupIds:string[]){
  const selected=[...new Set(groupIds)];
  for(const groupId of selected){
    const group=(await db.query<any>('SELECT id,system,active FROM access_groups WHERE id=$1 AND school_id=$2',[groupId,p.schoolId])).rows[0];
    if(!group||!group.active)throw new ApiError('GROUP_NOT_FOUND','A selected group is unavailable or inactive.',422);
    if(group.system)throw new ApiError('SYSTEM_GROUP_PROTECTED','System-managed groups cannot be assigned manually.',409);
  }
  for(const groupId of selected)await db.query('INSERT INTO access_group_memberships(school_id,group_id,user_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,user_id) DO NOTHING',[p.schoolId,groupId,userId,p.userId]);
  return selected
}
async function listRoles(db:Queryable,p:Principal){const roles=await db.query<any>('SELECT id,name,system,active,created_at AS "createdAt",updated_at AS "updatedAt",version FROM roles WHERE school_id=$1 ORDER BY name',[p.schoolId]);return roles.rows.map(role=>({...role,permissions:[],legacyPermissionsDisabled:true}))}
async function ensureLastSuperAdmin(db:Queryable,p:Principal,userId:string,nextRoleId:string,nextStatus:string){const current=await db.query<any>('SELECT r.system,u.status FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=$1 AND u.school_id=$2',[userId,p.schoolId]);if(!current.rows[0])throw new ApiError('USER_NOT_FOUND','User not found.',404);if(current.rows[0].system!==true||(nextRoleId===p.roleId&&nextStatus==='Active'))return;const next=await db.query<any>('SELECT system FROM roles WHERE id=$1 AND school_id=$2',[nextRoleId,p.schoolId]);if(next.rows[0]?.system===true&&nextStatus==='Active')return;const count=await db.query<{count:string}>("SELECT count(*)::text count FROM users u JOIN roles r ON r.id=u.role_id WHERE u.school_id=$1 AND u.id<>$2 AND u.status='Active' AND r.system=true",[p.schoolId,userId]);if(Number(count.rows[0]?.count||0)<1)throw new ApiError('LAST_SUPER_ADMIN','At least one active System Administratoristrator must remain.',409)}

export async function registerProductionAuthorityRoutes(app:FastifyInstance,db:Database,config:AppConfig){
  app.get('/api/v1/production/capabilities',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'school:read');return{data:{mode:'ServerProduction',schemaVersion:16,...PRODUCTION_AUTHORITY}}});

  app.get('/api/v1/school-settings',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'school:read');const r=await db.query<any>('SELECT id,name,slug,settings,active_academic_year_id AS "activeAcademicYearId",version FROM schools WHERE id=$1',[p.schoolId]);const row=r.rows[0];return{data:{id:row.id,name:row.name,slug:row.slug,...safeSettings(row.settings),activeAcademicYearId:row.activeAcademicYearId||null,version:row.version}}});
  app.patch('/api/v1/school-settings',{preHandler:auth(db,config,true)},async req=>{const p=principal(req),input=parsed(schoolUpdate,req.body),changed=Object.keys(input).filter(key=>key!=='version');if(changed.length===1&&changed[0]==='activeAcademicYearId'&&input.activeAcademicYearId)await authorizeRecord(db,p,'record.update',{schoolId:p.schoolId,workspaceKey:'academic-years',resourceType:'academic-year',recordId:input.activeAcademicYearId,lifecycle:'Active'});else requirePermission(p,'school:manage');const result=await db.transaction(async tx=>{const found=await tx.query<any>('SELECT * FROM schools WHERE id=$1',[p.schoolId]),old=found.rows[0];if(!old)throw new ApiError('SCHOOL_NOT_FOUND','School not found.',404);if(old.version!==input.version)throw conflict('School settings');if(input.activeAcademicYearId){const year=await tx.query('SELECT id FROM academic_years WHERE id=$1 AND school_id=$2 AND active=true',[input.activeAcademicYearId,p.schoolId]);if(!year.rows[0])throw new ApiError('INVALID_RECORD_REFERENCE','The selected academic year is unavailable or archived.',422)}const nextSettings={...safeSettings(old.settings)} as Record<string,unknown>;for(const key of SCHOOL_SETTING_KEYS)if(input[key]!==undefined)nextSettings[key]=input[key];const activeId=input.activeAcademicYearId===undefined?old.active_academic_year_id:input.activeAcademicYearId;const updated=await tx.query<any>('UPDATE schools SET name=$1,settings=$2,active_academic_year_id=$3,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$4 AND version=$5 RETURNING id,name,slug,settings,active_academic_year_id AS "activeAcademicYearId",version',[input.name??old.name,JSON.stringify(nextSettings),activeId,p.schoolId,input.version]);if(!updated.rows[0])throw conflict('School settings');await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'SCHOOL_SETTINGS_UPDATED',entityType:'School',entityId:p.schoolId,outcome:'SUCCESS',correlationId:req.correlationId,summary:{changedFields:Object.keys(input).filter(x=>x!=='version')}});return updated.rows[0]});return{data:{...result,...safeSettings(result.settings),settings:undefined}}});

  app.get('/api/v1/roles',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'users:view');return{data:{items:await listRoles(db,p),availablePermissions:[],legacyPermissionsDisabled:true,authority:'Groups -> Workspace Roles -> normalized grants'}}});
  app.post('/api/v1/roles',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(roleCreate,req.body);if(input.permissions.length)throw new ApiError('LEGACY_AUTHORIZATION_DISABLED','Account-role permissions are disabled. Assign normalized grants through Groups and Workspace Roles.',409);const row=await db.transaction(async tx=>{const duplicate=await tx.query('SELECT id FROM roles WHERE school_id=$1 AND lower(name)=lower($2)',[p.schoolId,input.name]);if(duplicate.rows[0])throw new ApiError('DUPLICATE_ROLE','A role with this name already exists.',409);const id=randomUUID(),created=await tx.query<any>('INSERT INTO roles(id,school_id,name,system,active) VALUES($1,$2,$3,false,true) RETURNING id,name,system,active,version',[id,p.schoolId,input.name]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'ROLE_CREATED',entityType:'Role',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{name:input.name,permissions:input.permissions}});return created.rows[0]});return reply.code(201).send({data:row})});
  app.patch('/api/v1/roles/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(roleUpdate,req.body),id=String((req.params as any).id);if(input.permissions?.length)throw new ApiError('LEGACY_AUTHORIZATION_DISABLED','Account-role permissions are disabled. Assign normalized grants through Groups and Workspace Roles.',409);const row=await db.transaction(async tx=>{const found=await tx.query<any>('SELECT * FROM roles WHERE id=$1 AND school_id=$2',[id,p.schoolId]),old=found.rows[0];if(!old)throw new ApiError('ROLE_NOT_FOUND','Role not found.',404);if(old.version!==input.version)throw conflict('Role');if(old.system)throw new ApiError('SYSTEM_ROLE_PROTECTED','Protected system roles cannot be modified.',409);if(input.name&&input.name.toLowerCase()!==String(old.name).toLowerCase()){const duplicate=await tx.query('SELECT id FROM roles WHERE school_id=$1 AND lower(name)=lower($2) AND id<>$3',[p.schoolId,input.name,id]);if(duplicate.rows[0])throw new ApiError('DUPLICATE_ROLE','A role with this name already exists.',409)}const updated=await tx.query<any>('UPDATE roles SET name=$1,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND school_id=$3 AND version=$4 RETURNING id,name,system,active,version',[input.name??old.name,id,p.schoolId,input.version]);if(!updated.rows[0])throw conflict('Role');await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'ROLE_UPDATED',entityType:'Role',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{name:input.name??old.name,permissionsChanged:!!input.permissions}});return updated.rows[0]});return{data:row}});
  app.post('/api/v1/roles/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(versionOnly,req.body),id=String((req.params as any).id);const row=await db.transaction(async tx=>{const found=await tx.query<any>('SELECT * FROM roles WHERE id=$1 AND school_id=$2',[id,p.schoolId]),old=found.rows[0];if(!old)throw new ApiError('ROLE_NOT_FOUND','Role not found.',404);if(old.version!==input.version)throw conflict('Role');if(old.system)throw new ApiError('SYSTEM_ROLE_PROTECTED','Protected system roles cannot be deactivated.',409);const used=await tx.query<{count:string}>("SELECT count(*)::text count FROM users WHERE school_id=$1 AND role_id=$2 AND status<>'Inactive'",[p.schoolId,id]);if(Number(used.rows[0]?.count||0)>0)throw new ApiError('ROLE_IN_USE','Reassign active users before deactivating this role.',409);const updated=await tx.query<any>('UPDATE roles SET active=false,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING id,name,system,active,version',[id,p.schoolId,input.version]);if(!updated.rows[0])throw conflict('Role');await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'ROLE_DEACTIVATED',entityType:'Role',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});return updated.rows[0]});return{data:row}});

  app.get('/api/v1/production-users',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'users:view');const users=await db.query<any>('SELECT u.id,u.first_name AS "firstName",u.last_name AS "lastName",u.email,u.username,u.status,u.role_id AS "roleId",r.name AS "roleName",u.teacher_id AS "teacherId",u.student_id AS "studentId",ugl.guardian_id AS "guardianId",u.created_at AS "createdAt",u.updated_at AS "updatedAt",u.version FROM users u JOIN roles r ON r.id=u.role_id LEFT JOIN user_guardian_links ugl ON ugl.user_id=u.id AND ugl.school_id=u.school_id WHERE u.school_id=$1 ORDER BY u.username',[p.schoolId]);return{data:{items:users.rows}}});
  app.post('/api/v1/production-users',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(userCreate,req.body);if(!input.roleId&&!input.groupIds.length)throw new ApiError('GROUP_REQUIRED','Select at least one active Group for this user.',422);const token=input.password?null:randomBytes(32).toString('base64url'),expiresAt=token?new Date(Date.now()+24*60*60_000):null;const row=await db.transaction(async tx=>{const role=await accountRoleForCreate(tx,p,input);const duplicate=await tx.query('SELECT id FROM users WHERE school_id=$1 AND lower(username)=lower($2)',[p.schoolId,input.username]);if(duplicate.rows[0])throw new ApiError('DUPLICATE_USERNAME','This username is already in use.',409);await activeReference(tx,p,'staff',input.teacherId);await activeReference(tx,p,'students',input.studentId);await activeReference(tx,p,'guardian_profiles',input.guardianId);const id=randomUUID(),status=!input.password&&input.status==='Active'?'PendingPassword':input.status,created=await tx.query<any>('INSERT INTO users(id,school_id,role_id,teacher_id,student_id,first_name,last_name,email,username,password_hash,must_change_password,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,$11) RETURNING id,first_name AS "firstName",last_name AS "lastName",email,username,status,role_id AS "roleId",teacher_id AS "teacherId",student_id AS "studentId",version',[id,p.schoolId,role.id,input.teacherId||null,input.studentId||null,input.firstName,input.lastName,input.email,input.username,await hashPassword(input.password||randomBytes(32).toString('hex')),status]);const assignedGroups=await assignInitialGroups(tx,p,id,input.groupIds);if(input.guardianId)await tx.query('INSERT INTO user_guardian_links(user_id,guardian_id,school_id) VALUES($1,$2,$3)',[id,input.guardianId,p.schoolId]);if(token&&expiresAt)await tx.query('INSERT INTO password_invitations(id_hash,user_id,school_id,expires_at,created_by) VALUES($1,$2,$3,$4,$5)',[digest(token),id,p.schoolId,expiresAt,p.userId]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'USER_CREATED',entityType:'User',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{username:input.username,accountType:role.name,groupIds:assignedGroups,linkedTeacher:!!input.teacherId,linkedStudent:!!input.studentId,linkedGuardian:!!input.guardianId,temporaryPasswordSet:!!input.password}});return created.rows[0]});return reply.code(201).send({data:{...row,invitationToken:token,expiresAt:expiresAt?.toISOString()||null}})});
  app.patch('/api/v1/production-users/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(userUpdate,req.body),id=String((req.params as any).id);if(id===p.userId&&input.status&&input.status!=='Active')throw new ApiError('CURRENT_USER_PROTECTED','The signed-in administrator cannot deactivate or delete their own account.',409);const row=await db.transaction(async tx=>{const found=await tx.query<any>('SELECT * FROM users WHERE id=$1 AND school_id=$2',[id,p.schoolId]),old=found.rows[0];if(!old)throw new ApiError('USER_NOT_FOUND','User not found.',404);if(old.version!==input.version)throw conflict('User');const roleId=input.roleId??old.role_id,status=input.status??old.status,passwordHash=input.password?await hashPassword(input.password):old.password_hash;if(input.roleId)await activeRole(tx,p,input.roleId);await ensureLastSuperAdmin(tx,p,id,roleId,status);if(input.username&&input.username.toLowerCase()!==String(old.username).toLowerCase()){const duplicate=await tx.query('SELECT id FROM users WHERE school_id=$1 AND lower(username)=lower($2) AND id<>$3',[p.schoolId,input.username,id]);if(duplicate.rows[0])throw new ApiError('DUPLICATE_USERNAME','This username is already in use.',409)}const updated=await tx.query<any>('UPDATE users SET first_name=$1,last_name=$2,email=$3,username=$4,role_id=$5,status=$6,password_hash=$7,must_change_password=CASE WHEN $8 THEN true ELSE must_change_password END,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$9 AND school_id=$10 AND version=$11 RETURNING id,first_name AS "firstName",last_name AS "lastName",email,username,status,role_id AS "roleId",teacher_id AS "teacherId",student_id AS "studentId",version',[input.firstName??old.first_name,input.lastName??old.last_name,input.email??old.email,input.username??old.username,roleId,status,passwordHash,!!input.password,id,p.schoolId,input.version]);if(!updated.rows[0])throw conflict('User');if(roleId!==old.role_id||status!=='Active'||input.password)await tx.query('DELETE FROM sessions WHERE user_id=$1',[id]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'USER_UPDATED',entityType:'User',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId,summary:{username:input.username??old.username,roleChanged:roleId!==old.role_id,status,passwordReset:!!input.password}});return updated.rows[0]});return{data:row}});
  app.post('/api/v1/production-users/:id/deactivate',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'users:manage');const input=parsed(versionOnly,req.body),id=String((req.params as any).id);if(id===p.userId)throw new ApiError('CURRENT_USER_PROTECTED','The signed-in administrator cannot deactivate their own account.',409);const row=await db.transaction(async tx=>{const found=await tx.query<any>('SELECT * FROM users WHERE id=$1 AND school_id=$2',[id,p.schoolId]),old=found.rows[0];if(!old)throw new ApiError('USER_NOT_FOUND','User not found.',404);if(old.version!==input.version)throw conflict('User');await ensureLastSuperAdmin(tx,p,id,old.role_id,'Inactive');const updated=await tx.query<any>("UPDATE users SET status='Inactive',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND school_id=$2 AND version=$3 RETURNING id,username,status,role_id AS \"roleId\",version",[id,p.schoolId,input.version]);if(!updated.rows[0])throw conflict('User');await tx.query('DELETE FROM sessions WHERE user_id=$1',[id]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'USER_DEACTIVATED',entityType:'User',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});return updated.rows[0]});return{data:row}});

  app.get('/api/v1/production/dashboard',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'school:read');if(!!p.teacherId){if(!p.teacherId)throw new ApiError('TEACHER_NOT_LINKED','The teacher account is not linked.',403);const result=await db.query<any>(`SELECT
 (SELECT count(*)::int FROM staff WHERE school_id=$1 AND id=$2 AND status='Active') AS staff,
 (SELECT count(DISTINCT class_id)::int FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$2 AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)) AS classes,
 (SELECT count(DISTINCT section_id)::int FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$2 AND active=true AND section_id IS NOT NULL AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)) AS sections,
 (SELECT count(*)::int FROM students s WHERE s.school_id=$1 AND s.status='Active' AND EXISTS(SELECT 1 FROM teacher_assignments a WHERE a.school_id=s.school_id AND a.teacher_id=$2 AND a.class_id=s.class_id AND (a.section_id IS NULL OR a.section_id=s.section_id) AND a.active=true AND (a.valid_from IS NULL OR a.valid_from<=CURRENT_DATE) AND (a.valid_until IS NULL OR a.valid_until>=CURRENT_DATE))) AS students`,[p.schoolId,p.teacherId]);return{data:{counts:{...result.rows[0],users:0,roles:0,subjects:0,academicYears:0,guardians:0},authoritative:true}}}const tables=['students','staff','classes','sections','subjects','academic_years','users','roles','guardian_profiles'] as const,counts:Record<string,number>={};for(const table of tables){const status=table==='students'||table==='staff'||table==='users'||table==='guardian_profiles'?" AND status='Active'":table==='classes'||table==='sections'||table==='subjects'||table==='academic_years'||table==='roles'?' AND active=true':'';const r=await db.query<{count:string}>(`SELECT count(*)::text count FROM ${table} WHERE school_id=$1${status}`,[p.schoolId]);counts[table==='academic_years'?'academicYears':table==='guardian_profiles'?'guardians':table]=Number(r.rows[0]?.count||0)}return{data:{counts,authoritative:true}}});
}





