import {randomBytes,randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {AppConfig} from '../config/index.js';
import type {Database,Queryable} from '../database/types.js';
import {authenticate} from '../auth/security.js';
import {digest} from '../auth/sessions.js';
import {requirePermission,type Principal} from '../authorization/service.js';
import {authorizeWorkspaceAction,resolveEffectiveGrants} from '../authorization/policy-engine.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';

const id=z.string().min(1).max(120),version=z.number().int().positive(),date=z.string().date(),money=z.number().int().min(0).max(9_000_000_000);
const flags=z.object({enabled:z.boolean(),assetRegister:z.boolean(),assignments:z.boolean(),maintenance:z.boolean(),idCards:z.boolean(),bulkIssue:z.boolean(),replacementCards:z.boolean(),verification:z.boolean()}).strict();
const DEFAULT={enabled:false,assetRegister:false,assignments:false,maintenance:false,idCards:false,bulkIssue:false,replacementCards:false,verification:false};
const condition=z.enum(['New','Good','Fair','Poor','Damaged','Disposed']);
const categoryInput=z.object({name:z.string().trim().min(1).max(120),code:z.string().trim().min(1).max(30),active:z.boolean().default(true)}).strict();
const assetInput=z.object({assetNumber:z.string().trim().min(1).max(60),name:z.string().trim().min(1).max(180),categoryId:id,serialNumber:z.string().trim().max(120).nullable().optional(),acquiredOn:date.nullable().optional(),purchaseCostMinor:money.default(0),condition,location:z.string().trim().max(180).default(''),notes:z.string().trim().max(2000).default('')}).strict();
const assignmentInput=z.object({assetId:id,holderType:z.enum(['Student','Staff']),holderId:id,assignedOn:date,dueOn:date.nullable().optional(),conditionOut:condition,notes:z.string().trim().max(1000).default('')}).strict();
const maintenanceInput=z.object({assetId:id,openedOn:date,vendor:z.string().trim().max(180).default(''),costMinor:money.default(0),description:z.string().trim().min(1).max(2000)}).strict();
const design=z.object({title:z.string().trim().min(1).max(120),primaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),secondaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),showPhoto:z.boolean(),showValidity:z.boolean(),orientation:z.enum(['Portrait','Landscape'])}).strict();
const templateInput=z.object({name:z.string().trim().min(1).max(120),holderType:z.enum(['Student','Staff']),design,active:z.boolean().default(true)}).strict();
const issueInput=z.object({holderType:z.enum(['Student','Staff']),holderId:id,templateId:id,issuedOn:date,expiresOn:date.nullable().optional()}).strict();
const bulkInput=z.object({templateId:id,holderType:z.enum(['Student','Staff']),classId:id.nullable().optional(),sectionId:id.nullable().optional(),issuedOn:date,expiresOn:date.nullable().optional(),confirmed:z.literal(true)}).strict();

function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApiError('VALIDATION_FAILED','Check the asset and I-card fields.',422,{fields:result.error.issues.map(x=>x.path.join('.'))});return result.data}
function principal(req:FastifyRequest):Principal{if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function requireOperationsView(p:Principal){if(p.systemRecovery===true||p.permissions.includes('assets:view')||p.permissions.includes('idcards:view'))return;throw new ApiError('ROLE_PERMISSION_DENIED','The role does not allow access to Phase 20 operations.',403)}
function auth(db:Database,config:AppConfig,write=false){return async(req:FastifyRequest)=>authenticate(req,db,config,write)}
async function configuration(db:Queryable,schoolId:string){const row=(await db.query<any>('SELECT configuration,version FROM specialist_operations_configuration WHERE school_id=$1',[schoolId])).rows[0];return row?{...DEFAULT,...row.configuration,version:row.version}:{...DEFAULT,version:0}}
async function requireFeature(db:Queryable,p:Principal,key:keyof typeof DEFAULT){const cfg=await configuration(db,p.schoolId);if(!cfg.enabled||key!=='enabled'&&!cfg[key])throw new ApiError('SPECIALIST_OPERATIONS_DISABLED','This asset or I-card capability is disabled in Admin Settings.',403);return cfg}
async function audit(tx:Queryable,req:FastifyRequest,action:string,entityType:string,entityId?:string,summary?:Record<string,unknown>){const p=principal(req);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action,entityType,entityId,outcome:'SUCCESS',correlationId:req.correlationId,summary})}
function dates(start:string,end?:string|null){if(!/^\d{4}-\d{2}-\d{2}$/.test(start))return;if(end&&end<start)throw new ApiError('INVALID_DATE_RANGE','The end date cannot be earlier than the start date.',422)}
async function holder(tx:Queryable,p:Principal,type:'Student'|'Staff',holderId:string){const table=type==='Student'?'students':'staff',number=type==='Student'?'admission_number':'employee_number',query='SELECT id,name,'+number+' AS number FROM '+table+" WHERE school_id=$1 AND id=$2 AND status='Active'";const row=(await tx.query<any>(query,[p.schoolId,holderId])).rows[0];if(!row)throw new ApiError('INVALID_RECORD_REFERENCE','Select an active '+type.toLowerCase()+'.',422);return row}
async function nextCardNumber(tx:Queryable,p:Principal){await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);const found=(await tx.query<any>('SELECT next_number FROM id_card_number_counters WHERE school_id=$1',[p.schoolId])).rows[0];const number=Number(found?.next_number||1);if(found)await tx.query('UPDATE id_card_number_counters SET next_number=next_number+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$1',[p.schoolId]);else await tx.query('INSERT INTO id_card_number_counters(school_id,next_number) VALUES($1,2)',[p.schoolId]);return 'ID-'+String(number).padStart(6,'0')}
async function issueCard(tx:Queryable,p:Principal,input:z.infer<typeof issueInput>,replacementForId:string|null=null){dates(input.issuedOn,input.expiresOn);const template=(await tx.query<any>('SELECT id,name,holder_type,design FROM id_card_templates WHERE school_id=$1 AND id=$2 AND active=true',[p.schoolId,input.templateId])).rows[0];if(!template||template.holder_type!==input.holderType)throw new ApiError('INVALID_CARD_TEMPLATE','Select an active template for this holder type.',422);const person=await holder(tx,p,input.holderType,input.holderId),token=randomBytes(32).toString('base64url'),cardNumber=await nextCardNumber(tx,p),cardId=randomUUID();const snapshot={name:person.name,number:person.number,templateName:template.name,design:template.design};await tx.query('INSERT INTO id_card_issues(id,school_id,holder_type,student_id,staff_id,template_id,card_number,issued_on,expires_on,replacement_for_id,holder_snapshot,verification_token_hash,issued_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[cardId,p.schoolId,input.holderType,input.holderType==='Student'?input.holderId:null,input.holderType==='Staff'?input.holderId:null,input.templateId,cardNumber,input.issuedOn,input.expiresOn||null,replacementForId,JSON.stringify(snapshot),digest(token),p.userId]);return{id:cardId,cardNumber,holderType:input.holderType,holderId:input.holderId,templateId:input.templateId,issuedOn:input.issuedOn,expiresOn:input.expiresOn||null,status:'Active',holderSnapshot:snapshot,verificationToken:token,version:1}}

export async function registerSpecialistOperationsRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 app.get('/api/v1/specialist-operations/configuration',{preHandler:auth(db,config)},async req=>({data:await configuration(db,principal(req).schoolId)}));
 app.patch('/api/v1/specialist-operations/configuration',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);requirePermission(p,'school:manage');const input=parse(flags.extend({version:z.number().int().nonnegative()}),req.body);if(!input.enabled&&Object.entries(input).some(([key,value])=>!['enabled','version'].includes(key)&&value===true))throw new ApiError('VALIDATION_FAILED','Disable every Phase 20 capability before disabling the module.',422);if(!input.assetRegister&&(input.assignments||input.maintenance))throw new ApiError('VALIDATION_FAILED','Enable the asset register before assignment or maintenance workflows.',422);if(!input.idCards&&(input.bulkIssue||input.replacementCards||input.verification))throw new ApiError('VALIDATION_FAILED','Enable digital I-cards before dependent card workflows.',422);const data=await db.transaction(async tx=>{await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);const old=await configuration(tx,p.schoolId);if(old.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Phase 20 settings changed. Reload before saving.',409);const value={enabled:input.enabled,assetRegister:input.assetRegister,assignments:input.assignments,maintenance:input.maintenance,idCards:input.idCards,bulkIssue:input.bulkIssue,replacementCards:input.replacementCards,verification:input.verification};if(old.version)await tx.query('UPDATE specialist_operations_configuration SET configuration=$1,version=version+1,updated_by=$2,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3',[JSON.stringify(value),p.userId,p.schoolId]);else await tx.query('INSERT INTO specialist_operations_configuration(school_id,configuration,updated_by) VALUES($1,$2,$3)',[p.schoolId,JSON.stringify(value),p.userId]);await audit(tx,req,'SPECIALIST_OPERATIONS_CONFIGURATION_UPDATED','Phase 20',p.schoolId,{enabled:value.enabled});return configuration(tx,p.schoolId)});return{data}});
 app.get('/api/v1/specialist-operations',{preHandler:auth(db,config)},async req=>{
  const p=principal(req),assetGrants=await resolveEffectiveGrants(db,p,'assets','asset'),cardGrants=await resolveEffectiveGrants(db,p,'idcards','digital-id-card'),systemAdministrator=p.systemRecovery===true;
  const canViewAssets=systemAdministrator||assetGrants.some(x=>x.action==='record.view'),canViewCards=systemAdministrator||cardGrants.some(x=>x.action==='record.view'),allCards=systemAdministrator||cardGrants.some(x=>x.action==='record.view'&&x.scope==='ALL_WORKSPACE'),selfCards=cardGrants.some(x=>x.action==='record.view'&&x.scope==='SELF');
  if(!canViewAssets&&!canViewCards)throw new ApiError('ROLE_PERMISSION_DENIED','The assigned roles do not allow access to Assets or ID Cards.',403);
  const cfg=await configuration(db,p.schoolId),cardClauses:string[]=[],cardParams:any[]=[p.schoolId],empty=()=>Promise.resolve({rows:[]} as any);
  if(!cfg.enabled)return{data:{configuration:cfg,categories:[],assets:[],assignments:[],maintenance:[],templates:[],cards:[],students:[],staff:[]}};
  if(allCards)cardClauses.push('TRUE');else if(selfCards){if(p.studentId){cardParams.push(p.studentId);cardClauses.push('student_id=$'+cardParams.length)}if(p.teacherId){cardParams.push(p.teacherId);cardClauses.push('staff_id=$'+cardParams.length)}}
  const cardWhere=cardClauses.length?'('+cardClauses.join(' OR ')+')':'FALSE';
  const [categories,assets,assignments,maintenance,templates,cards,students,staff]=await Promise.all([
   canViewAssets?db.query<any>('SELECT id,name,code,active,version FROM asset_categories WHERE school_id=$1 ORDER BY active DESC,name',[p.schoolId]):empty(),
   canViewAssets?db.query<any>('SELECT id,asset_number AS "assetNumber",name,category_id AS "categoryId",serial_number AS "serialNumber",acquired_on AS "acquiredOn",purchase_cost_minor AS "purchaseCostMinor",condition,status,location,notes,version FROM school_assets WHERE school_id=$1 AND archived=false ORDER BY asset_number',[p.schoolId]):empty(),
   canViewAssets?db.query<any>('SELECT id,asset_id AS "assetId",holder_type AS "holderType",student_id AS "studentId",staff_id AS "staffId",assigned_on AS "assignedOn",due_on AS "dueOn",returned_on AS "returnedOn",condition_out AS "conditionOut",condition_in AS "conditionIn",notes,version FROM asset_assignments WHERE school_id=$1 ORDER BY created_at DESC',[p.schoolId]):empty(),
   canViewAssets?db.query<any>('SELECT id,asset_id AS "assetId",opened_on AS "openedOn",completed_on AS "completedOn",vendor,cost_minor AS "costMinor",description,status,version FROM asset_maintenance_records WHERE school_id=$1 ORDER BY created_at DESC',[p.schoolId]):empty(),
   allCards?db.query<any>('SELECT id,name,holder_type AS "holderType",design,active,version FROM id_card_templates WHERE school_id=$1 ORDER BY active DESC,name',[p.schoolId]):empty(),
   canViewCards?db.query<any>('SELECT id,holder_type AS "holderType",student_id AS "studentId",staff_id AS "staffId",template_id AS "templateId",card_number AS "cardNumber",issued_on AS "issuedOn",expires_on AS "expiresOn",status,replacement_for_id AS "replacementForId",holder_snapshot AS "holderSnapshot",version FROM id_card_issues WHERE school_id=$1 AND '+cardWhere+' ORDER BY created_at DESC LIMIT 1000',cardParams):empty(),
   (canViewAssets||allCards)?db.query<any>("SELECT id,name,admission_number AS number,class_id AS \"classId\",section_id AS \"sectionId\" FROM students WHERE school_id=$1 AND status='Active' ORDER BY name",[p.schoolId]):empty(),
   (canViewAssets||allCards)?db.query<any>("SELECT id,name,employee_number AS number FROM staff WHERE school_id=$1 AND status='Active' ORDER BY name",[p.schoolId]):empty()
  ]);
  return{data:{configuration:cfg,categories:categories.rows,assets:assets.rows,assignments:assignments.rows,maintenance:maintenance.rows,templates:templates.rows,cards:cards.rows,students:students.rows,staff:staff.rows}};
 });
 app.post('/api/v1/specialist-operations/categories',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset-category','record.create');await requireFeature(db,p,'assetRegister');const input=parse(categoryInput,req.body),row=await db.transaction(async tx=>{const created=(await tx.query<any>('INSERT INTO asset_categories(id,school_id,name,code,active) VALUES($1,$2,$3,$4,$5) RETURNING id,name,code,active,version',[randomUUID(),p.schoolId,input.name,input.code,input.active])).rows[0];await audit(tx,req,'ASSET_CATEGORY_CREATED','Asset Category',created.id);return created});return reply.code(201).send({data:row})});
 app.post('/api/v1/specialist-operations/assets',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset','record.create');await requireFeature(db,p,'assetRegister');const input=parse(assetInput,req.body),row=await db.transaction(async tx=>{const category=(await tx.query('SELECT id FROM asset_categories WHERE school_id=$1 AND id=$2 AND active=true',[p.schoolId,input.categoryId])).rows[0];if(!category)throw new ApiError('INVALID_RECORD_REFERENCE','Select an active asset category.',422);const created=(await tx.query<any>('INSERT INTO school_assets(id,school_id,asset_number,name,category_id,serial_number,acquired_on,purchase_cost_minor,condition,location,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING id,asset_number AS "assetNumber",name,category_id AS "categoryId",serial_number AS "serialNumber",acquired_on AS "acquiredOn",purchase_cost_minor AS "purchaseCostMinor",condition,status,location,notes,version',[randomUUID(),p.schoolId,input.assetNumber,input.name,input.categoryId,input.serialNumber||null,input.acquiredOn||null,input.purchaseCostMinor,input.condition,input.location,input.notes,p.userId])).rows[0];await audit(tx,req,'ASSET_CREATED','Asset',created.id,{assetNumber:created.assetNumber});return created});return reply.code(201).send({data:row})});
 app.patch('/api/v1/specialist-operations/assets/:id',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset','record.update');await requireFeature(db,p,'assetRegister');const input=parse(assetInput.extend({version}),req.body),assetId=String((req.params as any).id),row=await db.transaction(async tx=>{const updated=(await tx.query<any>('UPDATE school_assets SET asset_number=$1,name=$2,category_id=$3,serial_number=$4,acquired_on=$5,purchase_cost_minor=$6,condition=$7,location=$8,notes=$9,version=version+1,updated_by=$10,updated_at=CURRENT_TIMESTAMP WHERE school_id=$11 AND id=$12 AND version=$13 AND archived=false RETURNING id,asset_number AS "assetNumber",name,category_id AS "categoryId",serial_number AS "serialNumber",acquired_on AS "acquiredOn",purchase_cost_minor AS "purchaseCostMinor",condition,status,location,notes,version',[input.assetNumber,input.name,input.categoryId,input.serialNumber||null,input.acquiredOn||null,input.purchaseCostMinor,input.condition,input.location,input.notes,p.userId,p.schoolId,assetId,input.version])).rows[0];if(!updated)throw new ApiError('RECORD_VERSION_CONFLICT','Asset changed. Reload before saving.',409);await audit(tx,req,'ASSET_UPDATED','Asset',assetId);return updated});return{data:row}});
 app.post('/api/v1/specialist-operations/assignments',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset-assignment','record.create');await requireFeature(db,p,'assignments');const input=parse(assignmentInput,req.body);dates(input.assignedOn,input.dueOn);const row=await db.transaction(async tx=>{await holder(tx,p,input.holderType,input.holderId);const asset=(await tx.query<any>('SELECT id,status FROM school_assets WHERE school_id=$1 AND id=$2 AND archived=false FOR UPDATE',[p.schoolId,input.assetId])).rows[0];if(!asset)throw new ApiError('ASSET_NOT_FOUND','Asset not found.',404);if(asset.status!=='Available')throw new ApiError('ASSET_NOT_AVAILABLE','Only available assets can be assigned.',409);const created=(await tx.query<any>('INSERT INTO asset_assignments(id,school_id,asset_id,holder_type,student_id,staff_id,assigned_on,due_on,condition_out,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,asset_id AS "assetId",holder_type AS "holderType",student_id AS "studentId",staff_id AS "staffId",assigned_on AS "assignedOn",due_on AS "dueOn",returned_on AS "returnedOn",condition_out AS "conditionOut",condition_in AS "conditionIn",notes,version',[randomUUID(),p.schoolId,input.assetId,input.holderType,input.holderType==='Student'?input.holderId:null,input.holderType==='Staff'?input.holderId:null,input.assignedOn,input.dueOn||null,input.conditionOut,input.notes,p.userId])).rows[0];await tx.query("UPDATE school_assets SET status='Assigned',version=version+1,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3",[p.userId,p.schoolId,input.assetId]);await audit(tx,req,'ASSET_ASSIGNED','Asset Assignment',created.id,{assetId:input.assetId,holderType:input.holderType});return created});return reply.code(201).send({data:row})});
 app.post('/api/v1/specialist-operations/assignments/:id/return',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset-assignment','record.update');await requireFeature(db,p,'assignments');const assignmentId=String((req.params as any).id),input=parse(z.object({returnedOn:date,conditionIn:condition,version}).strict(),req.body),row=await db.transaction(async tx=>{const assignment=(await tx.query<any>('SELECT * FROM asset_assignments WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,assignmentId])).rows[0];if(!assignment)throw new ApiError('ASSET_ASSIGNMENT_NOT_FOUND','Asset assignment not found.',404);if(assignment.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Assignment changed. Reload before returning it.',409);if(assignment.returned_on)throw new ApiError('ASSET_ALREADY_RETURNED','This asset was already returned.',409);dates(String(assignment.assigned_on).slice(0,10),input.returnedOn);const updated=(await tx.query<any>('UPDATE asset_assignments SET returned_on=$1,condition_in=$2,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3 AND id=$4 RETURNING id,asset_id AS "assetId",returned_on AS "returnedOn",condition_in AS "conditionIn",version',[input.returnedOn,input.conditionIn,p.schoolId,assignmentId])).rows[0];await tx.query("UPDATE school_assets SET status='Available',condition=$1,version=version+1,updated_by=$2,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3 AND id=$4",[input.conditionIn,p.userId,p.schoolId,assignment.asset_id]);await audit(tx,req,'ASSET_RETURNED','Asset Assignment',assignmentId,{assetId:assignment.asset_id});return updated});return{data:row}});
 app.post('/api/v1/specialist-operations/maintenance',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset-maintenance','record.create');await requireFeature(db,p,'maintenance');const input=parse(maintenanceInput,req.body),row=await db.transaction(async tx=>{const asset=(await tx.query<any>('SELECT status FROM school_assets WHERE school_id=$1 AND id=$2 AND archived=false FOR UPDATE',[p.schoolId,input.assetId])).rows[0];if(!asset)throw new ApiError('ASSET_NOT_FOUND','Asset not found.',404);if(asset.status!=='Available')throw new ApiError('ASSET_NOT_AVAILABLE','Only available assets can enter maintenance.',409);const created=(await tx.query<any>('INSERT INTO asset_maintenance_records(id,school_id,asset_id,opened_on,vendor,cost_minor,description,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,asset_id AS "assetId",opened_on AS "openedOn",completed_on AS "completedOn",vendor,cost_minor AS "costMinor",description,status,version',[randomUUID(),p.schoolId,input.assetId,input.openedOn,input.vendor,input.costMinor,input.description,p.userId])).rows[0];await tx.query("UPDATE school_assets SET status='Maintenance',version=version+1,updated_by=$1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3",[p.userId,p.schoolId,input.assetId]);await audit(tx,req,'ASSET_MAINTENANCE_OPENED','Asset Maintenance',created.id,{assetId:input.assetId});return created});return reply.code(201).send({data:row})});
 app.post('/api/v1/specialist-operations/maintenance/:id/complete',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'assets','asset-maintenance','record.update');await requireFeature(db,p,'maintenance');const maintenanceId=String((req.params as any).id),input=parse(z.object({completedOn:date,condition,version}).strict(),req.body),row=await db.transaction(async tx=>{const record=(await tx.query<any>('SELECT * FROM asset_maintenance_records WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,maintenanceId])).rows[0];if(!record)throw new ApiError('MAINTENANCE_NOT_FOUND','Maintenance record not found.',404);if(record.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Maintenance record changed. Reload before completing it.',409);if(record.status!=='Open')throw new ApiError('MAINTENANCE_ALREADY_CLOSED','This maintenance record is already closed.',409);dates(String(record.opened_on).slice(0,10),input.completedOn);const updated=(await tx.query<any>("UPDATE asset_maintenance_records SET completed_on=$1,status='Completed',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$2 AND id=$3 RETURNING id,asset_id AS \"assetId\",completed_on AS \"completedOn\",status,version",[input.completedOn,p.schoolId,maintenanceId])).rows[0];await tx.query("UPDATE school_assets SET status='Available',condition=$1,version=version+1,updated_by=$2,updated_at=CURRENT_TIMESTAMP WHERE school_id=$3 AND id=$4",[input.condition,p.userId,p.schoolId,record.asset_id]);await audit(tx,req,'ASSET_MAINTENANCE_COMPLETED','Asset Maintenance',maintenanceId,{assetId:record.asset_id});return updated});return{data:row}});
 app.post('/api/v1/specialist-operations/card-templates',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'idcards','id-card-template','record.create');await requireFeature(db,p,'idCards');const input=parse(templateInput,req.body),row=await db.transaction(async tx=>{const created=(await tx.query<any>('INSERT INTO id_card_templates(id,school_id,name,holder_type,design,active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7) RETURNING id,name,holder_type AS "holderType",design,active,version',[randomUUID(),p.schoolId,input.name,input.holderType,JSON.stringify(input.design),input.active,p.userId])).rows[0];await audit(tx,req,'ID_CARD_TEMPLATE_CREATED','I-Card Template',created.id);return created});return reply.code(201).send({data:row})});
 app.post('/api/v1/specialist-operations/cards',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'idcards','digital-id-card','record.create');await requireFeature(db,p,'idCards');const input=parse(issueInput,req.body),row=await db.transaction(async tx=>{const active=(await tx.query('SELECT id FROM id_card_issues WHERE school_id=$1 AND holder_type=$2 AND (student_id=$3 OR (student_id IS NULL AND $3 IS NULL)) AND (staff_id=$4 OR (staff_id IS NULL AND $4 IS NULL)) AND status=$5',[p.schoolId,input.holderType,input.holderType==='Student'?input.holderId:null,input.holderType==='Staff'?input.holderId:null,'Active'])).rows[0];if(active)throw new ApiError('ACTIVE_CARD_EXISTS','Revoke or replace the current active card first.',409);const issued=await issueCard(tx,p,input);await audit(tx,req,'ID_CARD_ISSUED','Digital I-Card',issued.id,{cardNumber:issued.cardNumber,holderType:input.holderType});return issued});return reply.code(201).send({data:row})});
 app.post('/api/v1/specialist-operations/cards/bulk',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'idcards','digital-id-card','record.create');await requireFeature(db,p,'bulkIssue');const input=parse(bulkInput,req.body);dates(input.issuedOn,input.expiresOn);if(input.holderType==='Staff'&&(input.classId||input.sectionId))throw new ApiError('VALIDATION_FAILED','Class and section filters apply only to students.',422);const result=await db.transaction(async tx=>{const params:any[]=[p.schoolId];let where="school_id=$1 AND status='Active'";if(input.holderType==='Student'&&input.classId){params.push(input.classId);where+=' AND class_id=$'+params.length}if(input.holderType==='Student'&&input.sectionId){params.push(input.sectionId);where+=' AND section_id=$'+params.length}const query='SELECT id FROM '+(input.holderType==='Student'?'students':'staff')+' WHERE '+where+' ORDER BY id LIMIT 500',people=(await tx.query<any>(query,params)).rows;let issued=0,skipped=0;const cards:any[]=[];for(const person of people){const active=(await tx.query('SELECT id FROM id_card_issues WHERE school_id=$1 AND holder_type=$2 AND (student_id=$3 OR (student_id IS NULL AND $3 IS NULL)) AND (staff_id=$4 OR (staff_id IS NULL AND $4 IS NULL)) AND status=$5',[p.schoolId,input.holderType,input.holderType==='Student'?person.id:null,input.holderType==='Staff'?person.id:null,'Active'])).rows[0];if(active){skipped++;continue}cards.push(await issueCard(tx,p,{holderType:input.holderType,holderId:person.id,templateId:input.templateId,issuedOn:input.issuedOn,expiresOn:input.expiresOn}));issued++}await audit(tx,req,'ID_CARDS_BULK_ISSUED','Digital I-Card',undefined,{holderType:input.holderType,issued,skipped});return{issued,skipped,cards}});return{data:result}});
 app.post('/api/v1/specialist-operations/cards/:id/revoke',{preHandler:auth(db,config,true)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'idcards','digital-id-card','record.archive');await requireFeature(db,p,'idCards');const cardId=String((req.params as any).id),input=parse(z.object({version,reason:z.string().trim().min(1).max(500)}).strict(),req.body),row=await db.transaction(async tx=>{const updated=(await tx.query<any>("UPDATE id_card_issues SET status='Revoked',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$1 AND id=$2 AND status='Active' AND version=$3 RETURNING id,status,version",[p.schoolId,cardId,input.version])).rows[0];if(!updated)throw new ApiError('RECORD_VERSION_CONFLICT','Card is no longer active or changed. Reload before revoking.',409);await audit(tx,req,'ID_CARD_REVOKED','Digital I-Card',cardId,{reason:input.reason});return updated});return{data:row}});
 app.post('/api/v1/specialist-operations/cards/:id/replace',{preHandler:auth(db,config,true)},async(req,reply)=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'idcards','digital-id-card','record.update');await authorizeWorkspaceAction(db,p,'idcards','digital-id-card','record.create');await requireFeature(db,p,'replacementCards');const cardId=String((req.params as any).id),input=parse(z.object({version,reason:z.string().trim().min(1).max(500),issuedOn:date,expiresOn:date.nullable().optional()}).strict(),req.body),row=await db.transaction(async tx=>{const old=(await tx.query<any>('SELECT * FROM id_card_issues WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,cardId])).rows[0];if(!old||old.status!=='Active'||old.version!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','Card is no longer active or changed. Reload before replacing.',409);await tx.query("UPDATE id_card_issues SET status='Replaced',version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$1 AND id=$2",[p.schoolId,cardId]);const issued=await issueCard(tx,p,{holderType:old.holder_type,holderId:old.student_id||old.staff_id,templateId:old.template_id,issuedOn:input.issuedOn,expiresOn:input.expiresOn},cardId);await audit(tx,req,'ID_CARD_REPLACED','Digital I-Card',issued.id,{replacedCardId:cardId,reason:input.reason});return issued});return reply.code(201).send({data:row})});
 app.get('/api/v1/specialist-operations/my-cards',{preHandler:auth(db,config)},async req=>{const p=principal(req);await authorizeWorkspaceAction(db,p,'idcards','digital-id-card','record.view');await requireFeature(db,p,'idCards');let rows:any[]=[];if(p.studentId)rows=(await db.query<any>('SELECT id,card_number AS "cardNumber",issued_on AS "issuedOn",expires_on AS "expiresOn",status,holder_snapshot AS "holderSnapshot" FROM id_card_issues WHERE school_id=$1 AND student_id=$2 ORDER BY created_at DESC',[p.schoolId,p.studentId])).rows;else if(p.teacherId)rows=(await db.query<any>('SELECT id,card_number AS "cardNumber",issued_on AS "issuedOn",expires_on AS "expiresOn",status,holder_snapshot AS "holderSnapshot" FROM id_card_issues WHERE school_id=$1 AND staff_id=$2 ORDER BY created_at DESC',[p.schoolId,p.teacherId])).rows;return{data:{items:rows}}});
 app.get('/api/v1/id-card-verify/:token',async req=>{const token=String((req.params as any).token||'');if(token.length<32||token.length>256)throw new ApiError('CARD_NOT_FOUND','Card verification failed.',404);const row=(await db.query<any>('SELECT c.card_number AS "cardNumber",c.issued_on AS "issuedOn",c.expires_on AS "expiresOn",c.status,c.holder_snapshot AS "holderSnapshot",c.school_id AS "schoolId",s.name AS "schoolName" FROM id_card_issues c JOIN schools s ON s.id=c.school_id WHERE c.verification_token_hash=$1',[digest(token)])).rows[0];if(!row)throw new ApiError('CARD_NOT_FOUND','Card verification failed.',404);const cfg=await configuration(db,row.schoolId);if(!cfg.enabled||!cfg.idCards||!cfg.verification)throw new ApiError('CARD_VERIFICATION_DISABLED','Card verification is disabled.',403);return{data:{cardNumber:row.cardNumber,status:row.status,issuedOn:row.issuedOn,expiresOn:row.expiresOn,name:row.holderSnapshot?.name||'',number:row.holderSnapshot?.number||'',schoolName:row.schoolName,valid:row.status==='Active'&&(!row.expiresOn||String(row.expiresOn).slice(0,10)>=new Date().toISOString().slice(0,10))}}});
}

