
import {registerNoticeWorkspaceRoutes} from './notice-workspace.js';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Database,Queryable} from '../database/types.js';
import type {AppConfig} from '../config/index.js';
import {authenticate} from '../auth/security.js';
import {requirePermission} from '../authorization/service.js';
import {authorizeArchivedLifecycle,authorizeCreate,authorizeRecord,authorizeWorkspaceAction} from '../authorization/policy-engine.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';
import {WorkspaceService} from '../services/workspace-service.js';
import {CoreRelationshipRepository} from '../repositories/core-relationship-repository.js';
import {readHomeworkPicklist} from '../services/homework-picklists.js';
const id=z.string().min(1).max(120),version=z.number().int().nonnegative();
const classInput=z.object({name:z.string().trim().min(1).max(120),status:z.enum(['Active','Inactive']),version,sections:z.array(z.object({id:id.optional(),name:z.string().trim().min(1).max(120),version:version.optional()}).strict()).min(1).max(100),teacherId:id.nullable().optional(),room:z.string().trim().max(120).optional(),academicGroup:z.string().trim().max(120).optional(),assignmentVersion:version.optional()}).strict();
function parse<T>(s:z.ZodType<T>,v:unknown){const r=s.safeParse(v);if(!r.success)throw new ApiError('VALIDATION_FAILED','Check the class and section fields.',422);return r.data}
async function references(tx:Queryable,schoolId:string,classId:string,sectionId?:string){const checks:Record<string,string>={students:'students',timetable:'timetable_entries',homework:'homework_records',exams:'exam_records',workLogs:'teacher_work_logs',history:'student_academic_history',assignments:'teacher_assignments'};for(const [label,table]of Object.entries(checks)){const r=await tx.query('SELECT id FROM '+table+' WHERE school_id=$1 AND class_id=$2'+(sectionId?' AND section_id=$3':'')+' LIMIT 1',sectionId?[schoolId,classId,sectionId]:[schoolId,classId]);if(r.rows.length)throw new ApiError('CLASS_HAS_REFERENCES','This '+(sectionId?'section':'class')+' is used by '+label+'. Keep it active or manage its references first.',409)}}
async function authorizeNestedClassChanges(db:Queryable,p:any,classId:string,input:z.infer<typeof classInput>,editing:boolean){
 const existing=editing?(await db.query<any>('SELECT id,name,active FROM sections WHERE school_id=$1 AND class_id=$2',[p.schoolId,classId])).rows:[];
 for(const section of input.sections){
  if(section.id)await authorizeRecord(db,p,'record.update',{schoolId:p.schoolId,workspaceKey:'sections',resourceType:'section',recordId:section.id});
  else{
   const inactive=existing.find((x:any)=>!x.active&&x.name.toLowerCase()===section.name.toLowerCase());
   if(inactive)await authorizeArchivedLifecycle(db,p,'record.restore',{schoolId:p.schoolId,workspaceKey:'sections',resourceType:'section',recordId:inactive.id,lifecycle:'Archived'});
   else await authorizeCreate(db,p,{schoolId:p.schoolId,workspaceKey:'sections',resourceType:'section'});
  }
 }
 for(const section of existing.filter((x:any)=>x.active&&!input.sections.some(next=>next.id===x.id)))await authorizeRecord(db,p,'record.archive',{schoolId:p.schoolId,workspaceKey:'sections',resourceType:'section',recordId:section.id});
 if(input.teacherId===undefined)return;
 const year=(await db.query<any>('SELECT id FROM academic_years WHERE school_id=$1 AND active=true',[p.schoolId])).rows[0];
 const assignment=year?(await db.query<any>("SELECT id,teacher_id FROM teacher_assignments WHERE school_id=$1 AND class_id=$2 AND academic_year_id=$3 AND assignment_type='ClassTeacher' AND section_id IS NULL AND active=true",[p.schoolId,classId,year.id])).rows[0]:null;
 if(assignment&&assignment.teacher_id!==input.teacherId)await authorizeRecord(db,p,'record.archive',{schoolId:p.schoolId,workspaceKey:'staff',resourceType:'teaching-assignment',recordId:assignment.id});
 if(input.teacherId&&assignment?.teacher_id!==input.teacherId)await authorizeCreate(db,p,{schoolId:p.schoolId,workspaceKey:'staff',resourceType:'teaching-assignment'});
}export async function registerStandardWorkspaceRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 await registerNoticeWorkspaceRoutes(app,db,config);
 const auth=(write=false)=>async(req:FastifyRequest)=>authenticate(req,db,config,write),core=new CoreRelationshipRepository(db);
 async function definition(p:any,key:string){const w=new WorkspaceService(db);await w.syncFactories(p,'standard-notice-class-ui');const row=(await db.query<any>('SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key=$2',[p.schoolId,key])).rows[0];return w.definition(db,p,row.id)}
 app.get('/api/v1/standard-workspaces/notices',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'notices:view');const files=(await db.query<any>('SELECT id,notice_id,name,type,size FROM notice_files WHERE school_id=$1 AND archived=false',[p.schoolId])).rows;const rows=(await db.query<any>("SELECT n.id,n.event_date AS date,n.title,n.audience,n.body AS text,n.publication_state AS status,n.expiry_date AS \"expiryDate\",n.priority,n.archived,n.version,n.created_at AS \"createdAt\",n.updated_at AS \"updatedAt\",n.created_by AS \"createdBy\",u.username AS \"createdByName\" FROM school_communications n JOIN users u ON u.id=n.created_by WHERE n.school_id=$1 AND n.status='Published' ORDER BY n.event_date DESC,n.id",[p.schoolId])).rows;return{data:{items:rows.filter(x=>x.status!=='Draft'||x.createdBy===p.userId||p.systemRecovery===true||p.permissions.includes('notices:update')).map(x=>({...x,status:x.archived?'Inactive':x.status,attachments:files.filter(f=>f.notice_id===x.id)})),definition:await definition(p,'notices'),audiences:await readHomeworkPicklist(db,p.schoolId,'noticeAudience'),statuses:await readHomeworkPicklist(db,p.schoolId,'noticeStatus'),priorities:await readHomeworkPicklist(db,p.schoolId,'noticePriority')}}});
 app.get('/api/v1/standard-workspaces/classes',{preHandler:auth()},async req=>{const p=req.principal!;await authorizeWorkspaceAction(db,p,'classes','class','record.view');const [classes,sections,teachers,assignments,years]=await Promise.all([core.list(p,'classes'),core.list(p,'sections'),core.list(p,'staff'),core.list(p,'teacher_assignments'),core.list(p,'academic_years')]),counts=(await db.query<any>("SELECT class_id AS \"classId\",count(*)::int AS count FROM students WHERE school_id=$1 AND status='Active' GROUP BY class_id",[p.schoolId])).rows,year=years.items.find(x=>x.active),extra=(await db.query<any>('SELECT id,room,academic_group FROM classes WHERE school_id=$1',[p.schoolId])).rows;return{data:{items:classes.items.map(c=>({...c,room:extra.find(x=>x.id===c.id)?.room||'',academicGroup:extra.find(x=>x.id===c.id)?.academic_group||'',status:c.active?'Active':'Inactive',sections:sections.items.filter(s=>s.classId===c.id&&s.active).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name)),assignments:assignments.items.filter(a=>a.classId===c.id&&a.assignmentType==='ClassTeacher'&&a.active&&a.academicYearId===year?.id),studentCount:counts.find(x=>x.classId===c.id)?.count||0})),teachers:teachers.items.filter(t=>t.status==='Active').map(t=>({id:t.id,name:t.name})),academicYearId:year?.id,definition:await definition(p,'classes'),statuses:await readHomeworkPicklist(db,p.schoolId,'classStatus')}}});
 for(const method of ['POST','PATCH'] as const)app.route({method,url:'/api/v1/standard-workspaces/classes'+(method==='PATCH'?'/:id':''),preHandler:auth(true),handler:async(req,reply)=>{const p=req.principal!,input=parse(classInput,req.body),editing=method==='PATCH',classId=editing?String((req.params as any).id):randomUUID();if(editing)await authorizeRecord(db,p,'record.update',{schoolId:p.schoolId,workspaceKey:'classes',resourceType:'class',recordId:classId});else await authorizeCreate(db,p,{schoolId:p.schoolId,workspaceKey:'classes',resourceType:'class',recordId:classId});await authorizeNestedClassChanges(db,p,classId,input,editing);const result=await db.transaction(async tx=>{
  await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);
  const old=editing?(await tx.query<any>('SELECT * FROM classes WHERE school_id=$1 AND id=$2 FOR UPDATE',[p.schoolId,classId])).rows[0]:null;if(editing&&!old)throw new ApiError('NOT_FOUND','Class not found.',404);if((old?.version||0)!==input.version)throw new ApiError('RECORD_VERSION_CONFLICT','This class changed. Reload before saving.',409);
  const statusValues=await readHomeworkPicklist(tx,p.schoolId,'classStatus');if(!statusValues.some(x=>x.active&&x.value===input.status))throw new ApiError('INVALID_STATUS','Choose an active Class Status value.',422);
  if(input.status==='Inactive'&&old?.active)await references(tx,p.schoolId,classId);
  const normalized=input.sections.map(s=>s.name.toLowerCase());if(new Set(normalized).size!==normalized.length)throw new ApiError('DUPLICATE_SECTION','Section names must be unique.',422);
  const existing=editing?(await tx.query<any>('SELECT id,name,version,active FROM sections WHERE school_id=$1 AND class_id=$2',[p.schoolId,classId])).rows:[];
  for(const s of input.sections)if(s.id){const prev=existing.find(x=>x.id===s.id);if(!prev||prev.version!==s.version)throw new ApiError('RECORD_VERSION_CONFLICT','A section changed or belongs to another class. Reload before saving.',409)}
  for(const s of existing.filter(s=>s.active&&!input.sections.some(n=>n.id===s.id)))await references(tx,p.schoolId,classId,s.id);
  if(editing)await core.updateClass(tx,p,classId,{name:input.name,active:true,version:input.version});else await tx.query('INSERT INTO classes(id,school_id,name,active) VALUES($1,$2,$3,true)',[classId,p.schoolId,input.name]);
  await tx.query('UPDATE classes SET room=$1,academic_group=$2 WHERE school_id=$3 AND id=$4',[input.room??old?.room??'',input.academicGroup??old?.academic_group??'',p.schoolId,classId]);
  for(const [i,s]of input.sections.entries()){if(s.id)await core.updateSection(tx,p,s.id,{name:s.name,version:s.version,sortOrder:i,active:true});else{const inactive=existing.find(x=>!x.active&&x.name.toLowerCase()===s.name.toLowerCase());if(inactive)await core.updateSection(tx,p,inactive.id,{name:s.name,version:inactive.version,active:true,sortOrder:i});else await core.createSection(tx,p,{classId,name:s.name,sortOrder:i})}}
  for(const s of existing.filter(s=>s.active&&!input.sections.some(n=>n.id===s.id)))await core.deactivateSection(tx,p,s.id,s.version);
  if(input.teacherId!==undefined){const year=(await tx.query<any>('SELECT id FROM academic_years WHERE school_id=$1 AND active=true',[p.schoolId])).rows[0];const assignments=year?(await tx.query<any>("SELECT id,teacher_id,version FROM teacher_assignments WHERE school_id=$1 AND class_id=$2 AND academic_year_id=$3 AND assignment_type='ClassTeacher' AND section_id IS NULL AND active=true",[p.schoolId,classId,year.id])).rows:[];if(assignments.length>1)throw new ApiError('ASSIGNMENT_AMBIGUOUS','Manage multiple class-teacher assignments in Teachers & Staff.',409);const a=assignments[0];if((a?.version||0)!==(input.assignmentVersion||0))throw new ApiError('RECORD_VERSION_CONFLICT','Class teacher assignment changed. Reload before saving.',409);if(input.teacherId&&!year)throw new ApiError('ACADEMIC_YEAR_REQUIRED','Select an active academic year before assigning a class teacher.',422);if(a&&a.teacher_id!==input.teacherId)await core.deactivateAssignment(tx,p,a.id,a.version);if(input.teacherId&&a?.teacher_id!==input.teacherId)await core.createAssignment(tx,p,{teacherId:input.teacherId,academicYearId:year.id,classId,assignmentType:'ClassTeacher'})}
  if(input.status==='Inactive'){await references(tx,p.schoolId,classId);await tx.query('UPDATE classes SET active=false WHERE id=$1 AND school_id=$2',[classId,p.schoolId])}
  await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:editing?'CLASS_WORKSPACE_UPDATED':'CLASS_WORKSPACE_CREATED',entityType:'Class',entityId:classId,outcome:'SUCCESS',correlationId:req.correlationId});return{id:classId};
 });return reply.code(editing?200:201).send({data:result})}});
 app.post('/api/v1/standard-workspaces/classes/:id/archive',{preHandler:auth(true)},async req=>{const p=req.principal!,input=parse(z.object({version}).strict(),req.body),classId=String((req.params as any).id);await authorizeRecord(db,p,'record.archive',{schoolId:p.schoolId,workspaceKey:'classes',resourceType:'class',recordId:classId});await db.transaction(async tx=>{await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);await references(tx,p.schoolId,classId);await core.deactivateClass(tx,p,classId,input.version);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'CLASS_ARCHIVED',entityType:'Class',entityId:classId,outcome:'SUCCESS',correlationId:req.correlationId})});return{data:{archived:true}}});
}

