import type {FastifyInstance,FastifyRequest} from 'fastify';
import {z} from 'zod';
import type {Database} from '../database/types.js';
import type {AppConfig} from '../config/index.js';
import {authenticate} from '../auth/security.js';
import {requirePermission,type Principal} from '../authorization/service.js';
import {resolveEffectiveGrants} from '../authorization/policy-engine.js';
import {resourceForTab} from '../authorization/workspace-tab-resources.js';
import {OPERATIONAL_WORKSPACE_KEYS,WorkspaceService,isOperationalWorkspaceDefinition} from '../services/workspace-service.js';
import {operationalDefinition} from './operational-workspaces.js';
import {ApiError} from '../errors/api-error.js';
import {workspaceLayoutSchema,readWorkspaceLayout,validateLayoutFields,projectLayout} from '../services/workspace-layout.js';
import {UNIVERSAL_TAB_KEYS,UNIVERSAL_SPECIAL_PERMISSIONS,UNIVERSAL_PERMISSION_DEFINITIONS} from '../authorization/universal-workspace-permissions.js';

const sources:Record<string,{path:string;collection?:string}>={students:{path:'students?page=1&pageSize=100'},staff:{path:'staff'},classes:{path:'classes'},sections:{path:'sections'},subjects:{path:'subjects'},'academic-years':{path:'academic-years'},attendance:{path:'academic/attendance'},timetable:{path:'academic/timetable'},homework:{path:'homework-workspace'},'teacher-work-log':{path:'work-log-workspace'},'exams-results':{path:'academic/exams'},'fees-payments':{path:'fees',collection:'payments'},'leave-requests':{path:'leave-workspace'},notices:{path:'standard-workspaces/notices'},'calendar-holidays':{path:'calendar-workspace'},documents:{path:'document-workspace'},certificates:{path:'certificates',collection:'certificates'},transport:{path:'transport',collection:'routes'},uniform:{path:'resource-catalogs/uniform'},curriculum:{path:'resource-catalogs/curriculum'},'rules-regulations':{path:'school-content/rules'},assets:{path:'specialist-operations',collection:'assets'},idcards:{path:'specialist-operations',collection:'cards'},users:{path:'users'},'homework-acknowledgements':{path:'homework-workspace',collection:'acknowledgements'}};

function feeLedgerRows(data:any){
 const students=Array.isArray(data?.students)?data.students:[],structures=Array.isArray(data?.structures)?data.structures:[],assignments=Array.isArray(data?.assignments)?data.assignments:[],payments=Array.isArray(data?.payments)?data.payments:[];
 return students.filter((student:any)=>student.status==='Active').map((student:any)=>{
  const applicable=structures.filter((structure:any)=>structure.status!=='Inactive'&&((structure.applicableClass===student.class&&(!structure.applicableSection||structure.applicableSection===student.section))||assignments.some((assignment:any)=>assignment.studentId===student.id&&assignment.feeStructureId===structure.id)));
  const ownPayments=payments.filter((payment:any)=>payment.student===student.admission),totalDue=applicable.reduce((sum:number,structure:any)=>sum+Number(structure.totalAmount||0),0),totalPaid=ownPayments.reduce((sum:number,payment:any)=>sum+Number(payment.amount||0),0),outstanding=Math.max(0,totalDue-totalPaid),last=ownPayments.reduce((current:any,payment:any)=>(!current||String(payment.date||'')>String(current.date||''))?payment:current,null);
  return{id:student.id,studentId:student.id,studentName:student.name,admission:student.admission,className:student.class,sectionName:student.section,totalDue,totalPaid,outstanding,paymentStatus:outstanding<=0?'Paid':totalPaid>0?'Partial':'Unpaid',lastPaymentDate:last?.date||'',receipt:last?.receipt||'',date:last?.date||'',head:last?.head||'',mode:last?.mode||'',amount:last?.amount??null};
 });
}
const tabs=['MAIN','GRID_1','GRID_2','GRID_3'] as const;
const who=(req:FastifyRequest)=>{if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Sign in first.',401);return req.principal};
const manager=(principal:Principal)=>principal.systemRecovery===true||principal.permissions.includes('workspaces:configure');
export async function hasDashboardView(db:Database,principal:Principal,workspaceId:string){if(principal.systemRecovery===true)return true;return !!(await db.query(`SELECT 1 FROM access_group_memberships gm JOIN access_groups g ON g.id=gm.group_id AND g.school_id=gm.school_id AND g.active=true JOIN access_group_roles agr ON agr.group_id=g.id AND agr.school_id=g.school_id JOIN access_roles ar ON ar.id=agr.role_id AND ar.school_id=g.school_id AND ar.workspace_id=$3 AND ar.status='Active' JOIN access_role_universal_permissions up ON up.role_id=ar.id AND up.school_id=ar.school_id AND up.tab_key='DASHBOARD' AND up.permission_key='VIEW' WHERE gm.school_id=$1 AND gm.user_id=$2 LIMIT 1`,[principal.schoolId,principal.userId,workspaceId])).rows[0]}
const parse=(schema:z.ZodType<any>,body:any)=>{const result=schema.safeParse(body);if(!result.success)throw new ApiError('VALIDATION_FAILED',result.error.issues.map(issue=>issue.message).join(' '),422);return result.data};


/** Dashboard VIEW gates only the dashboard components; tab access and standard actions never depend on it. */
export function dashboardScoped<T extends {components:unknown[]}>(value:{dashboardVisible:boolean;canManage:boolean},layout:T):T{return value.dashboardVisible||value.canManage?layout:{...layout,components:[]}}
export async function registerWorkspaceLayoutRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const auth=(csrf=false)=>(req:FastifyRequest)=>authenticate(req,db,config,csrf),service=new WorkspaceService(db);
 async function context(req:FastifyRequest){
  const principal=who(req),workspaceKey=String((req.params as any).workspaceKey),row=(await db.query<any>("SELECT id,system,workspace_key AS \"workspaceKey\" FROM workspace_definitions WHERE school_id=$1 AND workspace_key=$2 AND status<>'Archived'",[principal.schoolId,workspaceKey])).rows[0];
  if(!row||!isOperationalWorkspaceDefinition(row))throw new ApiError('WORKSPACE_NOT_FOUND','Operational workspace not found.',404);
  const definition=await service.definition(db,principal,row.id),canManage=manager(principal),administratorOverride=principal.systemRecovery===true,dashboardVisible=await hasDashboardView(db,principal,row.id);
  let operation:any=null;
  if(!administratorOverride)try{operation=await operationalDefinition(db,principal,workspaceKey,'record')}catch(error){if(!dashboardVisible)throw error}
  const visibleTabs:string[]=administratorOverride?[...tabs]:(operation?.visibleTabKeys||[]),fullAccess={visibleTabKeys:[...UNIVERSAL_TAB_KEYS],addableTabKeys:[...UNIVERSAL_TAB_KEYS],editableTabKeys:[...UNIVERSAL_TAB_KEYS],deletableTabKeys:[...UNIVERSAL_TAB_KEYS],printableTabKeys:[...UNIVERSAL_TAB_KEYS],specialPermissionKeys:[...UNIVERSAL_SPECIAL_PERMISSIONS]},noAccess={visibleTabKeys:[],addableTabKeys:[],editableTabKeys:[],deletableTabKeys:[],printableTabKeys:[],specialPermissionKeys:[]},actionAccess=administratorOverride?fullAccess:operation?{visibleTabKeys:operation.visibleTabKeys,addableTabKeys:operation.addableTabKeys,editableTabKeys:operation.editableTabKeys,deletableTabKeys:operation.deletableTabKeys,printableTabKeys:operation.printableTabKeys,specialPermissionKeys:operation.specialPermissionKeys}:noAccess,fields:any[]=[];
  for(const section of definition.sections){
   const roleRule=section.roleVisibility?.find((rule:any)=>rule.roleId===principal.roleId);
   if(!canManage&&(section.enabled===false||section.screenVisible===false||section.layouts?.record?.visible===false||roleRule?.screenVisible===false))continue;
   const tabKey=section.tabKey||'MAIN';if(!canManage&&!visibleTabs.includes(tabKey))continue;
   const resource=resourceForTab(workspaceKey,tabKey),grants=canManage||!resource?[]:await resolveEffectiveGrants(db,principal,workspaceKey,resource.resourceType,tabKey);
   fields.push(...section.fields.filter((field:any)=>!field.archived&&(canManage||(field.screenVisible!==false&&field.configuration?.visibility!=='hidden'&&grants.some(grant=>(grant.action==='record.view'||grant.action==='report.view'||grant.action==='submission.view')&&(!grant.constraints.readableFields||grant.constraints.readableFields.includes(field.fieldKey)))))).map((field:any)=>({fieldKey:field.fieldKey,label:field.label,fieldType:field.fieldType,tabKey,sectionId:section.id,sectionName:section.name})));
  }
  if(canManage)fields.push(...definition.unassignedFields.filter((field:any)=>!field.archived).map((field:any)=>({fieldKey:field.fieldKey,label:field.label,fieldType:field.fieldType,tabKey:field.tabKey||'MAIN'})));
  return{principal,workspaceKey,definition,canManage,administratorOverride,dashboardVisible,fields,visibleTabs,actionAccess,layout:readWorkspaceLayout(definition.layoutConfiguration)};
 }
 app.get('/api/v1/workspace-layouts',{preHandler:auth()},async req=>{const principal=who(req),items=(await db.query<any>("SELECT id,workspace_key AS \"workspaceKey\",plural_name AS name,icon,system FROM workspace_definitions WHERE school_id=$1 AND status='Active' AND (system=false OR workspace_key=ANY($2::text[])) ORDER BY plural_name",[principal.schoolId,[...OPERATIONAL_WORKSPACE_KEYS]])).rows,result=[];for(const item of items)if(await hasDashboardView(db,principal,item.id))result.push({workspaceKey:item.workspaceKey,name:item.name,icon:item.icon,system:item.system});return{data:{items:result}}});
 app.get('/api/v1/workspace-layouts/:workspaceKey',{preHandler:auth()},async req=>{const value=await context(req),roles=value.canManage?(await db.query<any>('SELECT name FROM roles WHERE school_id=$1 ORDER BY name',[value.principal.schoolId])).rows.map(row=>row.name):[],permissionOptions=[...UNIVERSAL_PERMISSION_DEFINITIONS.normal.map(item=>({value:item.key,label:item.label,kind:'normal'})),{value:'INHERIT',label:'Inherit Add or Edit context',kind:'context'},...UNIVERSAL_PERMISSION_DEFINITIONS.special.filter(item=>item.key!=='WORKSPACE_ADMINISTRATOR').map(item=>({value:'SPECIAL:'+item.key,label:item.label,kind:'special'}))];return{data:{workspaceId:value.definition.id,workspaceKey:value.workspaceKey,name:value.definition.pluralName,workspaceVersion:value.definition.version,canManage:value.canManage,administratorOverride:value.administratorOverride,currentRole:value.principal.roleName,roles,fields:value.fields,tabs:value.definition.tabConfiguration,dashboardVisible:value.dashboardVisible,visibleTabs:value.visibleTabs,actionAccess:value.actionAccess,permissionOptions,layout:dashboardScoped(value,projectLayout(value.layout,value.fields,value.canManage?[...tabs]:value.visibleTabs,value.canManage?undefined:value.principal.roleName,value.canManage?undefined:value.actionAccess))}}});
 app.put('/api/v1/workspace-layouts/:workspaceKey',{preHandler:auth(true)},async req=>{const value=await context(req);requirePermission(value.principal,'workspaces:configure');const body=parse(z.object({version:z.number().int().min(0),layout:workspaceLayoutSchema}).strict(),req.body);validateLayoutFields(body.layout,value.fields);const updated=await service.update(value.principal,value.definition.id,{version:body.version,layoutConfiguration:body.layout},req.correlationId);return{data:{workspaceVersion:updated.version,layout:readWorkspaceLayout(updated.layoutConfiguration)}}});
 app.get('/api/v1/workspace-layouts/:workspaceKey/records/:tabKey',{preHandler:auth()},async req=>{
  const value=await context(req),tabKey=z.enum(tabs).parse((req.params as any).tabKey);if(!value.dashboardVisible&&!value.canManage)throw new ApiError('DASHBOARD_VIEW_REQUIRED','Dashboard View permission is required for dashboard data.',403,{workspaceKey:value.workspaceKey});await operationalDefinition(db,value.principal,value.workspaceKey,'record',tabKey);
  const source=tabKey==='MAIN'?sources[value.workspaceKey]:null;if(!source&&tabKey==='MAIN'&&value.definition.system!==false)return{data:{items:[],coverage:'No native record adapter is available for this workspace.',complete:false,total:0}};
  const path=source?source.path:'operational-workspaces/'+encodeURIComponent(value.workspaceKey)+'/tabs/'+tabKey+'/grid-records',response=await app.inject({method:'GET',url:'/api/v1/'+path,headers:{cookie:req.headers.cookie||'',...(req.headers.authorization?{authorization:req.headers.authorization}:{})}});
  if(response.statusCode>=400){let body:any={};try{body=response.json()}catch{}throw new ApiError('LAYOUT_SOURCE_UNAVAILABLE',body.error?.message||'The authorized record source could not be loaded.',response.statusCode)}
  const data=response.json().data,raw=value.workspaceKey==='fees-payments'&&tabKey==='MAIN'?feeLedgerRows(data):source?.collection?data?.[source.collection]:data?.items||data?.records||[],rows=Array.isArray(raw)?raw:[],allowed=value.fields.filter(field=>field.tabKey===tabKey),items=rows.map((record:any)=>{const values={...record,...record.data,...record.values,...record.extra?.workspaceCustomFields};return{id:record.id,values:Object.fromEntries(allowed.filter(field=>Object.prototype.hasOwnProperty.call(values,field.fieldKey)).map(field=>[field.fieldKey,values[field.fieldKey]]))}});
  return{data:{items,complete:!data?.hasNext&&!(source?.path.startsWith('students?')&&rows.length===100),coverage:'Authorized records returned by the existing source',total:data?.total??items.length}};
 });
}
