import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import type {Database,Queryable} from '../database/types.js';
import type {AppConfig} from '../config/index.js';
import {authenticate} from '../auth/security.js';
import {requirePermission,type Principal} from '../authorization/service.js';
import {ApiError} from '../errors/api-error.js';
import {writeAudit} from '../audit/service.js';
import {WorkspaceService} from '../services/workspace-service.js';
import {ensureHomeworkPicklists,readHomeworkPicklist} from '../services/homework-picklists.js';
import {validateAttachmentFile} from './work-logs.js';
const id=z.string().min(1).max(120),version=z.number().int().nonnegative();
const record=z.object({academicYear:id,date:z.string().date(),class:id,section:id,period:id,subject:id,scheduledTeacherId:id,teacherId:id,substitute:z.boolean(),substitutionReason:z.string().max(200).nullable().optional(),topic:z.string().trim().min(1).max(500),details:z.string().max(20000),homeworkGiven:z.string().max(10000),remarks:z.string().max(10000),status:z.string().min(1).max(200)}).strict();
const save=z.object({record,version,retainIds:z.array(id).max(5),newFiles:z.array(z.object({name:z.string().min(1).max(240),content:z.string().max(14*1024*1024)}).strict()).max(5)}).strict();
function parse<T>(s:z.ZodType<T>,v:unknown):T{const r=s.safeParse(v);if(!r.success)throw new ApiError('VALIDATION_FAILED','Check the Work Log fields.',422,{fields:r.error.issues.map(x=>x.path.join('.'))});return r.data}
const stale=()=>new ApiError('RECORD_VERSION_CONFLICT','This Work Log changed. Refresh and review before saving.',409);
const date=(v:any)=>v instanceof Date?v.toISOString().slice(0,10):String(v||'').slice(0,10);
const weekday=(v:string)=>['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][new Date(v+'T12:00:00Z').getUTCDay()];
function own(p:Principal,teacherId:string){if(!!p.teacherId&&(!p.teacherId||p.teacherId!==teacherId))throw new ApiError('FORBIDDEN','Only your own teaching logs are available.',403)}
async function row(db:Queryable,p:Principal,id:string){const r=(await db.query<any>('SELECT * FROM teacher_work_logs WHERE school_id=$1 AND id=$2 AND archived=false FOR UPDATE',[p.schoolId,id])).rows[0];if(!r)throw new ApiError('NOT_FOUND','Work Log not found.',404);own(p,r.teacher_id);return r}
async function definition(db:Database,p:Principal,view:string){const service=new WorkspaceService(db);await service.syncFactories(p,'work-log-workspace');const w=(await db.query<any>("SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key='teacher-work-log' AND status='Active'",[p.schoolId])).rows[0];if(!w)throw new ApiError('WORKSPACE_UNAVAILABLE','Work Log workspace is unavailable.',409);const d=await service.definition(db,p,w.id);return{...d,sections:d.sections.filter((s:any)=>{const r=s.roleVisibility.find((x:any)=>x.roleId===p.roleId);return s.enabled!==false&&s.layouts?.[view]?.visible!==false&&(view==='print'?s.printVisible!==false&&r?.printVisible!==false:s.screenVisible!==false&&r?.screenVisible!==false&&(!['create','edit'].includes(view)||r?.editVisible!==false))}).map((s:any)=>({...s,fields:s.fields.filter((f:any)=>!f.archived&&(view==='print'?f.printVisible!==false:f.screenVisible!==false))}))}}
function dto(r:any){const d=r.data||{};return{...d,id:r.id,academicYear:r.academic_year_id,class:r.class_id,section:r.section_id,subject:r.subject_id||'',period:r.period_key||d.period||'',date:date(r.log_date||d.date),scheduledTeacherId:r.scheduled_teacher_id||'',teacherId:r.teacher_id,substitute:r.is_substitute,substitutionReason:r.substitution_reason||'',status:r.log_status,timetableEntryId:r.timetable_entry_id,createdBy:r.created_by,createdByName:r.creator||'',createdAt:r.created_at,updatedAt:r.updated_at,version:r.version,legacy:!r.log_date}}
async function refs(db:Queryable,p:Principal){const result:any={};for(const [key,table]of Object.entries({years:'academic_years',classes:'classes',sections:'sections',subjects:'subjects',teachers:'staff'}))result[key]=(await db.query('SELECT id,name,'+(table==='sections'?'class_id AS "classId",':'')+(table==='staff'?"status='Active'":'active')+' AS active FROM '+table+' WHERE school_id=$1 ORDER BY name',[p.schoolId])).rows;result.periods=(await db.query('SELECT id,name,start_time AS "startTime",end_time AS "endTime",period_type AS "periodType" FROM school_periods WHERE school_id=$1 AND active=true ORDER BY sort_order',[p.schoolId])).rows;result.timetable=(await db.query<any>('SELECT t.id,t.academic_year_id AS "academicYear",t.class_id AS class,t.section_id AS section,t.subject_id AS subject,t.teacher_id AS "scheduledTeacherId",t.period_key AS period,t.day_of_week AS day,t.start_time AS "startTime",t.end_time AS "endTime",t.version FROM timetable_entries t WHERE school_id=$1 AND active=true',[p.schoolId])).rows;return result}
function minutes(v:any){const [h,m]=String(v).split(':').map(Number);return h*60+m}
function overlaps(a:any,b:any){if(a.period===b.period)return true;return a.startTime&&a.endTime&&b.startTime&&b.endTime&&minutes(a.startTime)<minutes(b.endTime)&&minutes(b.startTime)<minutes(a.endTime)}
async function checkScope(tx:Queryable,p:Principal,r:z.infer<typeof record>){own(p,r.teacherId);if(!p.teacherId)return;const found=await tx.query('SELECT id FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$2 AND class_id=$3 AND (section_id IS NULL OR section_id=$4) AND (subject_id IS NULL OR subject_id=$5) AND (academic_year_id IS NULL OR academic_year_id=$6) AND active=true AND (valid_from IS NULL OR valid_from<=CURRENT_DATE) AND (valid_until IS NULL OR valid_until>=CURRENT_DATE)',[p.schoolId,p.teacherId,r.class,r.section,r.subject,r.academicYear]);if(!found.rows.length)throw new ApiError('FORBIDDEN','This class or subject is outside your teaching assignment.',403)}
export async function registerWorkLogWorkspaceRoutes(app:FastifyInstance,db:Database,config:AppConfig){
 const auth=(write=false)=>async(req:FastifyRequest)=>authenticate(req,db,config,write);
 const audit=(tx:Queryable,p:Principal,req:FastifyRequest,action:string,id:string)=>writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action,entityType:'Teacher Work Log',entityId:id,outcome:'SUCCESS',correlationId:req.correlationId});
 app.get('/api/v1/work-log-workspace',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'teacherlog:view');const d=await definition(db,p,'record'),items=(await db.query<any>('SELECT w.*,u.username AS creator FROM teacher_work_logs w JOIN users u ON u.id=w.created_by WHERE w.school_id=$1 AND w.archived=false'+(!!p.teacherId?' AND teacher_id=$2':'')+' ORDER BY w.created_at DESC',!!p.teacherId?[p.schoolId,p.teacherId]:[p.schoolId])).rows,files=(await db.query<any>('SELECT id,work_log_id,name,type,size FROM teacher_work_log_files WHERE school_id=$1 AND archived=false',[p.schoolId])).rows;await db.transaction(tx=>ensureHomeworkPicklists(tx,p.schoolId));const has=(a:string)=>p.systemRecovery===true||p.permissions.includes('teacherlog:'+a);return{data:{items:items.map(r=>({...dto(r),attachments:files.filter(f=>f.work_log_id===r.id).map(({work_log_id,...f})=>f)})),refs:await refs(db,p),definition:d,reasons:await readHomeworkPicklist(db,p.schoolId,'teacherSubstitutionReason'),statuses:await readHomeworkPicklist(db,p.schoolId,'workLogStatus'),teacherId:p.teacherId,permissions:{create:has('create'),edit:has('update'),delete:has('delete'),print:has('print'),manual:has('create')||has('update')}}}});
 app.get('/api/v1/work-log-workspace/definition',{preHandler:auth()},async req=>{const p=req.principal!;requirePermission(p,'teacherlog:view');const view=String((req.query as any).view||'record');if(!['record','create','edit','print'].includes(view))throw new ApiError('VALIDATION_FAILED','Invalid view.',422);if(view==='print')requirePermission(p,'teacherlog:print');return{data:await definition(db,p,view)}});
 for(const method of ['POST','PATCH'] as const)app.route({method,url:'/api/v1/work-log-workspace'+(method==='PATCH'?'/:id':''),bodyLimit:72*1024*1024,preHandler:auth(true),handler:async(req,reply)=>{const p=req.principal!,editing=method==='PATCH';requirePermission(p,editing?'teacherlog:update':'teacherlog:create');const input=parse(save,req.body),r=input.record,id=editing?String((req.params as any).id):randomUUID(),d=await definition(db,p,editing?'edit':'create');if(input.retainIds.length+input.newFiles.length>5||new Set(input.retainIds).size!==input.retainIds.length||(!editing&&input.retainIds.length))throw new ApiError('INVALID_ATTACHMENTS','Choose at most five attachments.',422);const uploads=input.newFiles.map(validateAttachmentFile);
 const result=await db.transaction(async tx=>{
  // Serialize new log allocations within a school, including concurrent substitute saves.
  await tx.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[p.schoolId]);
  const old=editing?await row(tx,p,id):null;if((old?.version||0)!==input.version)throw stale();await checkScope(tx,p,r);
  const visible=new Set(d.sections.flatMap((s:any)=>s.fields.map((f:any)=>f.fieldKey)));for(const [key,value]of Object.entries(r))if(!visible.has(key)&&(!old||JSON.stringify(dto(old)[key])!==JSON.stringify(value)))throw new ApiError('FIELD_NOT_EDITABLE','A required Work Log field is hidden in Workspace Manager.',422);
  const sources=await refs(tx,p),get=(key:string,value:string)=>sources[key].find((x:any)=>x.id===value&&x.active!==false),cls=get('classes',r.class),section=get('sections',r.section),year=get('years',r.academicYear),subject=get('subjects',r.subject),scheduled=get('teachers',r.scheduledTeacherId),actual=get('teachers',r.teacherId);
  if(!cls||!section||section.classId!==cls.id||!year||!subject||!scheduled||!actual)throw new ApiError('INVALID_REFERENCE','Select active school references and a section belonging to the class.',422);
  const unchanged=old&&old.log_date&&date(old.log_date)===r.date&&old.class_id===r.class&&old.section_id===r.section&&old.academic_year_id===r.academicYear&&old.period_key===r.period;
  const matches=sources.timetable.filter((t:any)=>t.academicYear===r.academicYear&&t.class===r.class&&(!t.section||t.section===r.section)&&t.day===weekday(r.date)&&t.period===r.period);
  if(!unchanged&&matches.length>1)throw new ApiError('AMBIGUOUS_TIMETABLE','Multiple timetable assignments exist for this period. Correct the timetable first.',409);
  const selected=matches[0],period=sources.periods.find((x:any)=>x.id===r.period),legacyPeriod=sources.timetable.find((x:any)=>x.period===r.period);
  if(!unchanged&&!period&&!legacyPeriod)throw new ApiError('INVALID_PERIOD','Select a period from the school timetable or period structure.',422);
  if(!unchanged&&period&&['Assembly','Short Break','Lunch'].includes(period.periodType))throw new ApiError('INVALID_PERIOD','Choose a teaching or activity period.',422);
  if(unchanged){if(r.subject!==old.subject_id||r.scheduledTeacherId!==old.scheduled_teacher_id)throw new ApiError('HISTORICAL_CONTEXT_LOCKED','The saved subject and scheduled teacher are historical facts. Change the lesson context explicitly to select another assignment.',409)}
  else if(selected&&(selected.subject!==r.subject||selected.scheduledTeacherId!==r.scheduledTeacherId))throw new ApiError('TIMETABLE_CHANGED','Subject or scheduled teacher differs from the timetable. Reload this period.',409);
  if(!r.substitute&&r.teacherId!==r.scheduledTeacherId)throw new ApiError('INVALID_ACTUAL_TEACHER','Actual teacher must match the scheduled teacher unless Substitute is selected.',422);
  if(r.substitute&&r.teacherId===r.scheduledTeacherId)throw new ApiError('INVALID_SUBSTITUTE','Choose the teacher who substituted for the scheduled teacher.',422);
  await ensureHomeworkPicklists(tx,p.schoolId);const reasons=await readHomeworkPicklist(tx,p.schoolId,'teacherSubstitutionReason'),statuses=await readHomeworkPicklist(tx,p.schoolId,'workLogStatus');if(!['Draft','Saved'].includes(r.status)||!statuses.some(x=>x.value===r.status&&x.active))throw new ApiError('INVALID_STATUS','Choose an available Work Log status.',422);if(r.substitute&&!reasons.some(x=>x.value===r.substitutionReason&&x.active))throw new ApiError('REASON_REQUIRED','Select an active substitution reason.',422);
  const context=unchanged?old.data.scheduleSnapshot:{period:r.period,startTime:selected?.startTime||period?.startTime||null,endTime:selected?.endTime||period?.endTime||null};
  if(r.substitute){const conflict=sources.timetable.find((t:any)=>t.academicYear===r.academicYear&&t.day===weekday(r.date)&&t.scheduledTeacherId===r.teacherId&&(t.class!==r.class||t.section!==r.section)&&overlaps(context||{period:r.period},t));if(conflict){const c=sources.classes.find((x:any)=>x.id===conflict.class),s=sources.sections.find((x:any)=>x.id===conflict.section);throw new ApiError('SUBSTITUTE_CONFLICT',actual.name+' is already assigned to '+(c?.name||'another class')+(s?' - '+s.name:'')+' during this period.',409)}
   const logs=(await tx.query<any>('SELECT id,class_id,section_id,data,period_key FROM teacher_work_logs WHERE school_id=$1 AND teacher_id=$2 AND log_date=$3 AND archived=false AND id<>$4',[p.schoolId,r.teacherId,r.date,id])).rows;const booked=logs.find(x=>(x.class_id!==r.class||x.section_id!==r.section)&&overlaps(context||{period:r.period},x.data.scheduleSnapshot||{period:x.period_key}));if(booked)throw new ApiError('SUBSTITUTE_CONFLICT',actual.name+' already has a work log for another class in this period.',409);
  }
  const previous=old?.data||{},data={...r,className:unchanged?previous.className:cls.name,sectionName:unchanged?previous.sectionName:section.name,academicYearName:unchanged?previous.academicYearName:year.name,subjectName:unchanged?previous.subjectName:subject.name,scheduledTeacherName:unchanged?previous.scheduledTeacherName:scheduled.name,teacherName:old?.teacher_id===r.teacherId?previous.teacherName||actual.name:actual.name,periodName:unchanged?previous.periodName:(period?.name||r.period),scheduleSnapshot:context,substitutionReasonLabel:r.substitute?reasons.find(x=>x.value===r.substitutionReason)?.label:null};
  const existing=(await tx.query<any>('SELECT id FROM teacher_work_log_files WHERE school_id=$1 AND work_log_id=$2 AND archived=false',[p.schoolId,id])).rows;if(input.retainIds.some(id=>!existing.some(f=>f.id===id)))throw new ApiError('INVALID_ATTACHMENTS','An attachment does not belong to this work log.',422);
  if(!visible.has('attachments')&&(uploads.length||input.retainIds.length!==existing.length))throw new ApiError('FIELD_NOT_EDITABLE','Attachments are hidden in Workspace Manager.',422);
  const vals=[r.teacherId,r.class,r.section,r.academicYear,JSON.stringify(data),p.userId,r.subject,r.scheduledTeacherId,unchanged?old.timetable_entry_id:selected?.id||null,r.period,r.date,r.substitute,r.substitute?r.substitutionReason:null,r.status];
  if(old){const changed=await tx.query('UPDATE teacher_work_logs SET teacher_id=$1,class_id=$2,section_id=$3,academic_year_id=$4,data=$5,updated_by=$6,subject_id=$7,scheduled_teacher_id=$8,timetable_entry_id=$9,period_key=$10,log_date=$11,is_substitute=$12,substitution_reason=$13,log_status=$14,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE school_id=$15 AND id=$16 AND version=$17 RETURNING id',[...vals,p.schoolId,id,input.version]);if(!changed.rows.length)throw stale()}
  else await tx.query('INSERT INTO teacher_work_logs(teacher_id,class_id,section_id,academic_year_id,data,updated_by,subject_id,scheduled_teacher_id,timetable_entry_id,period_key,log_date,is_substitute,substitution_reason,log_status,school_id,id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$6)',[...vals,p.schoolId,id]);
  for(const f of existing)if(!input.retainIds.includes(f.id))await tx.query('UPDATE teacher_work_log_files SET archived=true WHERE school_id=$1 AND id=$2',[p.schoolId,f.id]);for(const f of uploads)await tx.query('INSERT INTO teacher_work_log_files(id,school_id,work_log_id,name,type,size,content) VALUES($1,$2,$3,$4,$5,$6,$7)',[f.id,p.schoolId,id,f.name,f.type,f.size,f.content]);await audit(tx,p,req,editing?'WORK_LOG_UPDATED':'WORK_LOG_CREATED',id);return{id,version:input.version+1};
 });return reply.code(editing?200:201).send({data:result})}});
 app.post('/api/v1/work-log-workspace/:id/remove',{preHandler:auth(true)},async req=>{const p=req.principal!,id=String((req.params as any).id),input=parse(z.object({version}).strict(),req.body);requirePermission(p,'teacherlog:delete');await db.transaction(async tx=>{const r=await row(tx,p,id);if(r.version!==input.version)throw stale();await tx.query('UPDATE teacher_work_logs SET archived=true,version=version+1,updated_at=CURRENT_TIMESTAMP,updated_by=$1 WHERE school_id=$2 AND id=$3',[p.userId,p.schoolId,id]);await audit(tx,p,req,'WORK_LOG_REMOVED',id)});return{data:{removed:true}}});
 app.post('/api/v1/work-log-workspace/:id/print-event',{preHandler:auth(true)},async req=>{const p=req.principal!,id=String((req.params as any).id);requirePermission(p,'teacherlog:print');await row(db,p,id);await audit(db,p,req,'WORK_LOG_PRINTED',id);return{data:{recorded:true}}});
}

