import {workspaceLayoutSchema} from '../services/workspace-layout.js';
import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AppConfig } from '../config/index.js';
import type { Database } from '../database/types.js';
import { authenticate } from '../auth/security.js';
import { requirePermission,type Principal } from '../authorization/service.js';
import { ApiError } from '../errors/api-error.js';
import { WorkspaceService,WORKSPACE_FIELD_TYPES } from '../services/workspace-service.js';

const tabKey=z.enum(['MAIN','GRID_1','GRID_2','GRID_3']),tabConfiguration=z.object({MAIN:z.string().trim().min(1).max(80),GRID_1:z.string().trim().min(1).max(80),GRID_2:z.string().trim().min(1).max(80),GRID_3:z.string().trim().min(1).max(80)}).strict();
const key=z.string().regex(/^[a-z][a-z0-9-]{1,79}$/),fieldKey=z.string().regex(/^[a-z][A-Za-z0-9_]{1,79}$/),version=z.number().int().positive(),scalar=z.union([z.string().max(2000),z.number(),z.boolean(),z.null()]);
const jsonValue:z.ZodType<any>=z.lazy(()=>z.union([scalar,z.array(jsonValue).max(500),z.record(z.string().max(120),jsonValue)]));
const layoutView=z.object({order:z.number().int().min(0).max(10000).optional(),columns:z.number().int().min(1).max(3).optional(),visible:z.boolean().optional(),fieldOrder:z.array(z.string().max(120)).max(500).optional(),pageBreak:z.enum(['none','before','after']).optional()}).strict();
const layouts=z.object({create:layoutView.optional(),edit:layoutView.optional(),record:layoutView.optional(),print:layoutView.optional()}).strict();
const printConfiguration=z.object({paperSize:z.enum(['A4','Letter','Legal']).optional(),orientation:z.enum(['portrait','landscape']).optional(),margins:z.object({top:z.number().min(5).max(40),right:z.number().min(5).max(40),bottom:z.number().min(5).max(40),left:z.number().min(5).max(40)}).strict().optional(),showPageNumbers:z.boolean().optional(),repeatTableHeaders:z.boolean().optional(),includeFutureTemplates:z.boolean().optional(),templateCategories:z.record(z.enum(['certificate','form','receipt','other']),z.boolean()).optional(),branding:z.object({mode:z.literal('global'),headerStyle:z.enum(['classic','modern','formal','minimal']).optional()}).strict().optional(),watermark:z.object({enabled:z.boolean(),type:z.enum(['text','image']),text:z.string().max(120).optional(),opacity:z.number().int().min(3).max(50),position:z.enum(['center','diagonal','top','bottom']),rotation:z.number().int().min(-90).max(90),size:z.number().int().min(20).max(90)}).strict().optional()}).strict();
const numberingFormat=z.string().trim().min(3).max(80).refine(value=>{const tokens=value.match(/\{0{2,12}\}/g)||[];return tokens.length===1&&!value.replace(/\{0{2,12}\}/g,'').includes('{')&&!value.replace(/\{0{2,12}\}/g,'').includes('}')},{message:'Use exactly one zero placeholder, for example STU-{00000}.'});
const recordNumberConfiguration=z.object({enabled:z.boolean(),format:numberingFormat}).strict();
const navigationConfiguration=z.object({showInMainMenu:z.boolean(),parentMenu:z.string().trim().max(80),menuPosition:z.number().int().min(0).max(10000)}).strict();
const behaviorConfiguration=z.object({search:z.boolean(),filtering:z.boolean(),import:z.boolean(),export:z.boolean(),auditHistory:z.boolean(),duplicateRecords:z.boolean(),print:z.boolean(),archive:z.boolean(),bulkActions:z.boolean(),attachments:z.boolean()}).strict();
const workspaceCreate=z.object({workspaceKey:key,name:z.string().trim().min(2).max(120),pluralName:z.string().trim().min(2).max(120),description:z.string().max(500).optional(),category:z.string().trim().min(1).max(80).optional(),icon:z.string().max(80).nullable().optional()}).strict();
const workspaceUpdate=z.object({workspaceKey:key.optional(),name:z.string().trim().min(2).max(120).optional(),pluralName:z.string().trim().min(2).max(120).optional(),description:z.string().max(500).optional(),category:z.string().trim().min(1).max(80).optional(),icon:z.string().max(80).nullable().optional(),status:z.enum(['Draft','Active','Archived']).optional(),printConfiguration:printConfiguration.optional(),recordNumberConfiguration:recordNumberConfiguration.optional(),navigationConfiguration:navigationConfiguration.optional(),behaviorConfiguration:behaviorConfiguration.optional(),tabConfiguration:tabConfiguration.optional(),layoutConfiguration:workspaceLayoutSchema.optional(),version}).strict();
const sectionBase={tabKey:tabKey.optional(),sectionKey:key,name:z.string().trim().min(1).max(120),description:z.string().max(500).optional(),order:z.number().int().min(0).max(10000).optional(),enabled:z.boolean().optional(),screenVisible:z.boolean().optional(),printVisible:z.boolean().optional(),layoutColumns:z.number().int().min(1).max(3).optional(),layouts:layouts.optional()};
const sectionCreate=z.object({...sectionBase,workspaceVersion:version}).strict(),sectionUpdate=z.object({sectionKey:key.optional(),name:sectionBase.name.optional(),description:sectionBase.description,order:sectionBase.order,enabled:sectionBase.enabled,screenVisible:sectionBase.screenVisible,printVisible:sectionBase.printVisible,layoutColumns:sectionBase.layoutColumns,layouts:sectionBase.layouts,version}).strict();
const option=z.object({value:z.string().trim().min(1).max(120),label:z.string().trim().min(1).max(120)}).strict();
const fieldProps={tabKey:tabKey.optional(),sectionId:z.string().max(120).nullable().optional(),fieldKey,label:z.string().trim().min(1).max(120),description:z.string().max(500).optional(),fieldType:z.string().min(1).max(40),required:z.boolean().optional(),defaultValue:jsonValue.optional(),helpText:z.string().max(500).optional(),placeholder:z.string().max(200).optional(),width:z.enum(['full','half','third','twoThirds']).optional(),order:z.number().int().min(0).max(10000).optional(),screenVisible:z.boolean().optional(),previewVisible:z.boolean().optional(),printVisible:z.boolean().optional(),searchable:z.boolean().optional(),filterable:z.boolean().optional(),configuration:z.record(z.string().max(120),jsonValue).optional(),options:z.array(option).max(100).optional()};
const fieldCreate=z.object({...fieldProps,workspaceVersion:version}).strict();
const fieldUpdate=z.object({tabKey:fieldProps.tabKey,sectionId:fieldProps.sectionId,fieldKey:fieldKey.optional(),label:fieldProps.label.optional(),description:fieldProps.description,fieldType:fieldProps.fieldType.optional(),required:fieldProps.required,defaultValue:fieldProps.defaultValue,helpText:fieldProps.helpText,placeholder:fieldProps.placeholder,width:fieldProps.width,order:fieldProps.order,screenVisible:fieldProps.screenVisible,previewVisible:fieldProps.previewVisible,printVisible:fieldProps.printVisible,searchable:fieldProps.searchable,filterable:fieldProps.filterable,archived:z.boolean().optional(),configuration:fieldProps.configuration,options:fieldProps.options,version}).strict();
const visibilityRule=z.object({sectionId:z.string().max(120),roleId:z.string().max(120),screenVisible:z.boolean(),editVisible:z.boolean(),printVisible:z.boolean()}).strict();
const visibilityUpdate=z.object({workspaceVersion:version,rules:z.array(visibilityRule).max(5000)}).strict();
const confirmedVersion=z.object({version,confirmed:z.literal(true)}).strict();
function parsed<T>(schema:z.ZodType<T>,value:unknown):T{const r=schema.safeParse(value);if(!r.success)throw new ApiError('VALIDATION_FAILED','The request contains invalid or protected fields.',422,{fields:r.error.issues.map(x=>x.path.join('.'))});return r.data}
function auth(db:Database,config:AppConfig,csrf=false){return async(req:FastifyRequest)=>authenticate(req,db,config,csrf)}
function principal(req:FastifyRequest):Principal{if(!req.principal)throw new ApiError('AUTHENTICATION_REQUIRED','Authentication is required.',401);return req.principal}
function page(q:any){return{page:Math.max(1,Number(q?.page)||1),pageSize:Math.max(1,Math.min(100,Number(q?.pageSize)||25)),search:String(q?.search||'').slice(0,120)}}
export async function registerWorkspaceRoutes(app:FastifyInstance,db:Database,config:AppConfig){const service=new WorkspaceService(db);
 app.get('/api/v1/workspace-field-types',{preHandler:auth(db,config)},async req=>{const p=principal(req);requirePermission(p,'workspaces:view');return{data:{items:WORKSPACE_FIELD_TYPES,deferred:['formula','calculatedField']}}});
 app.get('/api/v1/workspaces',{preHandler:auth(db,config)},async req=>({data:await service.list(principal(req),page(req.query),req.correlationId)}));
 app.get('/api/v1/workspaces/:id',{preHandler:auth(db,config)},async req=>({data:await service.get(principal(req),String((req.params as any).id),req.correlationId)}));
 app.get('/api/v1/workspaces/:id/versions',{preHandler:auth(db,config)},async req=>({data:await service.versions(principal(req),String((req.params as any).id))}));
 app.post('/api/v1/workspaces',{preHandler:auth(db,config,true)},async(req,reply)=>reply.code(201).send({data:await service.create(principal(req),parsed(workspaceCreate,req.body),req.correlationId)}));
 app.patch('/api/v1/workspaces/:id',{preHandler:auth(db,config,true)},async req=>({data:await service.update(principal(req),String((req.params as any).id),parsed(workspaceUpdate,req.body),req.correlationId)}));
 app.post('/api/v1/workspaces/:id/sections',{preHandler:auth(db,config,true)},async(req,reply)=>reply.code(201).send({data:await service.addSection(principal(req),String((req.params as any).id),parsed(sectionCreate,req.body),req.correlationId)}));
 app.patch('/api/v1/workspace-sections/:id',{preHandler:auth(db,config,true)},async req=>({data:await service.updateSection(principal(req),String((req.params as any).id),parsed(sectionUpdate,req.body),req.correlationId)}));
 app.get('/api/v1/workspaces/:id/role-visibility',{preHandler:auth(db,config)},async req=>({data:await service.roleVisibility(principal(req),String((req.params as any).id))}));
 app.put('/api/v1/workspaces/:id/role-visibility',{preHandler:auth(db,config,true)},async req=>({data:await service.saveRoleVisibility(principal(req),String((req.params as any).id),parsed(visibilityUpdate,req.body),req.correlationId)}));
 app.post('/api/v1/workspaces/:id/fields',{preHandler:auth(db,config,true)},async(req,reply)=>reply.code(201).send({data:await service.addField(principal(req),String((req.params as any).id),parsed(fieldCreate,req.body),req.correlationId)}));
 app.patch('/api/v1/workspace-fields/:id',{preHandler:auth(db,config,true)},async req=>({data:await service.updateField(principal(req),String((req.params as any).id),parsed(fieldUpdate,req.body),req.correlationId)}));
 app.get('/api/v1/workspace-fields/:id/delete-preview',{preHandler:auth(db,config)},async req=>({data:await service.fieldDeletePreview(principal(req),String((req.params as any).id))}));
 app.post('/api/v1/workspace-fields/:id/unassign',{preHandler:auth(db,config,true)},async req=>({data:await service.unassignField(principal(req),String((req.params as any).id),parsed(z.object({version}).strict(),req.body),req.correlationId)}));
 app.post('/api/v1/workspace-fields/:id/delete',{preHandler:auth(db,config,true)},async req=>({data:await service.deleteField(principal(req),String((req.params as any).id),parsed(confirmedVersion,req.body),req.correlationId)}));
 app.get('/api/v1/workspace-sections/:id/delete-preview',{preHandler:auth(db,config)},async req=>({data:await service.sectionDeletePreview(principal(req),String((req.params as any).id))}));
 app.post('/api/v1/workspace-sections/:id/delete',{preHandler:auth(db,config,true)},async req=>({data:await service.deleteSection(principal(req),String((req.params as any).id),parsed(confirmedVersion,req.body),req.correlationId)}));
 app.get('/api/v1/workspaces/:id/reset-preview',{preHandler:auth(db,config)},async req=>({data:await service.resetPreview(principal(req),String((req.params as any).id),req.correlationId)}));
 app.post('/api/v1/workspaces/:id/reset',{preHandler:auth(db,config,true)},async req=>({data:await service.reset(principal(req),String((req.params as any).id),parsed(z.object({version,confirmed:z.literal(true)}).strict(),req.body),req.correlationId)}));
}
