import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {describe,expect,it} from 'vitest';
import {permissionContract} from '../../src/authorization/policy-registry.js';
function sourceFiles(root:string):string[]{return readdirSync(root,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?sourceFiles(join(root,entry.name)):entry.name.endsWith('.ts')?[join(root,entry.name)]:[])}
describe('authorization integration coverage',()=>{
 it('registers every literal permission used by server handlers',()=>{const missing=new Set<string>();for(const file of sourceFiles(join(process.cwd(),'src'))){const text=readFileSync(file,'utf8'),pattern=/requirePermission\([^,]+,\s*['"]([^'"]+)['"]\)/g;for(const match of text.matchAll(pattern))if(!permissionContract(match[1]))missing.add(match[1])}expect([...missing]).toEqual([])});
 it('uses linked identities and central record decisions in the Homework reference route',()=>{const text=readFileSync(join(process.cwd(),'src/routes/homework-workspace.ts'),'utf8');expect(text).not.toContain("roleName==='Teacher'");expect(text).not.toContain("roleName==='Student'");expect(text).toContain('authorizeRecord');expect(text).toContain('authorizeCreate');expect(text).toContain('authorizeUpdate');expect(text).toContain('attachment.view');expect(text).toContain('record.acknowledge')});
 it('ships normalized grant storage as a forward-only migration',()=>{const text=readFileSync(join(process.cwd(),'src/database/migrations.ts'),'utf8');expect(text).toContain("version:40,name:'normalized_authorization_grants'");expect(text).toContain('CREATE TABLE IF NOT EXISTS access_role_grants');expect(text).toContain('authorization_version bigint')});
 it('keeps legacy permission stores outside runtime authorization',()=>{const access=readFileSync(join(process.cwd(),'src/authorization/access-control.ts'),'utf8'),security=readFileSync(join(process.cwd(),'src/auth/security.ts'),'utf8'),api=readFileSync(join(process.cwd(),'src/routes/api.ts'),'utf8'),roles=readFileSync(join(process.cwd(),'src/routes/production-authority.ts'),'utf8'),imports=readFileSync(join(process.cwd(),'src/services/import-service.ts'),'utf8');expect(access).toContain('access_role_grants');expect(access).not.toContain('access_group_workspace_roles');expect(access).not.toContain('access_role_permissions');for(const text of [security,api,roles,imports])expect(text).not.toContain('role_permissions')});
 it('disables direct legacy assignment and rollout-mode bypasses',()=>{const route=readFileSync(join(process.cwd(),'src/routes/access-management.ts'),'utf8'),academic=readFileSync(join(process.cwd(),'src/services/academic-service.ts'),'utf8'),portal=readFileSync(join(process.cwd(),'src/services/portal-service.ts'),'utf8'),homework=readFileSync(join(process.cwd(),'src/routes/homework-workspace.ts'),'utf8');expect(route).not.toContain('/rollout');expect(route).not.toContain('accessMode');expect(route).not.toContain('LEGACY_AUTHORIZATION_ACTIVE');expect(academic).not.toContain("accessControlMode!=='Enforced'");expect(portal).not.toContain('linkedTeacherCompatibility');expect(homework).not.toContain('enforced')});
 it('synchronizes built-in workspaces before the central permission UI is returned',()=>{const route=readFileSync(join(process.cwd(),'src/routes/access-management-standard.ts'),'utf8'),sync=route.indexOf('syncFactories(p,req.correlationId)'),query=route.indexOf('const workspaces=');expect(sync).toBeGreaterThan(-1);expect(query).toBeGreaterThan(sync)});
});