import {describe,expect,it} from 'vitest';
import {grantMatches,LEGACY_RUNTIME_AUTHORIZATION_ENABLED,type EffectiveGrant,type RecordSecurityContext} from '../../src/authorization/policy-engine.js';
import {serverPermissionKeysForGrant,validateGrantDefinition,workspaceManifest} from '../../src/authorization/policy-registry.js';
import {permissionsForUser} from '../../src/authorization/access-control.js';
import {requirePermission,type Principal} from '../../src/authorization/service.js';

const principal:Principal={userId:'u1',schoolId:'s1',roleId:'r1',roleName:'Teacher',teacherId:'t1',studentId:null,guardianId:null,permissions:[],username:'teacher'};
const baseGrant:EffectiveGrant={workspaceKey:'homework',resourceType:'homework',action:'record.view',scope:'CLASS',constraints:{},groupId:'g1',groupName:'Teachers',roleId:'role1',roleName:'Teacher homework',provenance:'universal'};
const baseRecord:RecordSecurityContext={schoolId:'s1',workspaceKey:'homework',resourceType:'homework',classId:'c1',sectionId:'sec1',subjectId:'sub1',academicYearId:'y1',audienceType:'CLASS',lifecycle:'Published',published:true};
const relationships={groupIds:new Set<string>(),classIds:new Set(['c1']),sectionIds:new Set(['sec1']),childStudentIds:new Set<string>(),assignments:[{academicYearId:'y1',classId:'c1',sectionId:'sec1',subjectId:'sub1'}]};

describe('central authorization policy',()=>{
 it('publishes a typed manifest and fails closed for unknown combinations',()=>{expect(workspaceManifest('homework').map(x=>x.resourceType)).toContain('homework');expect(validateGrantDefinition('homework','homework','record.view','ASSIGNED_TEACHING_CONTEXT')).toBe(true);expect(validateGrantDefinition('homework','unknown','record.view','CLASS')).toBe(false);expect(validateGrantDefinition('unknown','homework','record.view','CLASS')).toBe(false)});
 it('keeps class and section audiences exact',()=>{expect(grantMatches(baseGrant,principal,baseRecord,relationships as any)).toBe(true);expect(grantMatches({...baseGrant,scope:'SECTION'},principal,baseRecord,relationships as any)).toBe(false);expect(grantMatches({...baseGrant,scope:'SECTION'},principal,{...baseRecord,audienceType:'SECTION'},relationships as any)).toBe(true)});
 it('requires one composite teaching assignment',()=>{const grant={...baseGrant,scope:'ASSIGNED_TEACHING_CONTEXT' as const};expect(grantMatches(grant,principal,baseRecord,relationships as any)).toBe(true);const split={...relationships,assignments:[{academicYearId:'y1',classId:'c1',sectionId:'other',subjectId:'sub1'},{academicYearId:'y1',classId:'other',sectionId:'sec1',subjectId:'sub1'}]};expect(grantMatches(grant,principal,baseRecord,split as any)).toBe(false)});
 it('does not let ALL_WORKSPACE bypass lifecycle and sensitivity constraints',()=>{const grant={...baseGrant,scope:'ALL_WORKSPACE' as const};expect(grantMatches(grant,principal,{...baseRecord,lifecycle:'Archived'},relationships as any)).toBe(false);expect(grantMatches({...grant,constraints:{viewArchived:true}},principal,{...baseRecord,lifecycle:'Archived'},relationships as any)).toBe(true);expect(grantMatches(grant,principal,{...baseRecord,sensitivity:'Confidential'},relationships as any)).toBe(false)});
 it('has no teacher role-name permission bypass and rejects unknown permissions',()=>{expect(()=>requirePermission(principal,'students:view')).toThrow();expect(()=>requirePermission({...principal,permissions:['students:view']},'students:view')).not.toThrow();expect(()=>requirePermission(principal,'not-registered:anything')).toThrow()});
 it('keeps legacy runtime authority disabled and excludes ambiguous manage permissions',()=>{expect(LEGACY_RUNTIME_AUTHORIZATION_ENABLED).toBe(false);expect(serverPermissionKeysForGrant('homework','homework','record.view')).toContain('homework:view');expect(serverPermissionKeysForGrant('homework','homework','record.update')).not.toContain('homework:manage')});
 it('derives route permissions only from universal workspace permissions',async()=>{const sql:string[]=[];const db={query:async(text:string)=>{sql.push(text);if(text.includes('access_role_universal_permissions'))return{rows:[{workspaceKey:'homework',roleId:'r1',tabKey:'MAIN',permissionKey:'VIEW'},{workspaceKey:'homework',roleId:'r1',tabKey:'SPECIAL',permissionKey:'VIEW_ASSIGNED_RECORDS'}]};return{rows:[]}}} as any;const result=await permissionsForUser(db,{schoolId:'s1',userId:'u1',roleName:'Teacher',permissions:['students:view']});expect(result.permissions).toEqual(['homework:view']);expect(sql.some(x=>x.includes('access_role_grants'))).toBe(false);expect(sql.some(x=>x.includes('role_permissions'))).toBe(false)});
 it('automatically assigns every workspace capability to the System Administrator backend authority',async()=>{
  const db={query:async(text:string)=>text.includes('workspace_definitions')?{rows:[{key:'students'},{key:'fees-payments'}]}:{rows:[]}} as any;
  const result=await permissionsForUser(db,{schoolId:'s1',userId:'admin',roleName:'System Administrator',systemRecovery:true,permissions:[]});
  expect(result.authority).toBe('SYSTEM_RECOVERY_ROLE');
  for(const workspace of ['students','fees-payments'])for(const action of ['view','create','update','delete','manage','print','permanent-delete'])expect(result.permissions).toContain(workspace+':'+action);
 });
});