param([string]$ConfigPath,[switch]$ValidateOnly,[switch]$NoBrowser,[switch]$NoStart,[switch]$SkipTests)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'SchoolHub.Common.ps1')
$root=Get-SchoolHubRoot;if(-not $ConfigPath){$ConfigPath=Join-Path $root 'schoolhub.config.env'}
$logDirectory=Join-Path $root 'logs';New-Item -ItemType Directory -Path $logDirectory -Force|Out-Null;$logPath=Join-Path $logDirectory ('schoolhub-setup-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.log');$step='Configuration validation';Start-Transcript -LiteralPath $logPath|Out-Null
try{
 if(-not (Test-Path -LiteralPath $ConfigPath)){Copy-Item -LiteralPath (Join-Path $root 'schoolhub.config.env.example') -Destination $ConfigPath;throw "CONFIG_CREATED: Edit $ConfigPath, replace CHANGE_ME, then run setup again."}
 $config=Read-SchoolHubConfig $ConfigPath
 $step='Prerequisite checks';foreach($commandName in @('node','npm.cmd','python')){if(-not (Get-Command $commandName -ErrorAction SilentlyContinue)){throw "PREREQUISITE_MISSING: $commandName was not found."}};if(-not (Enable-SchoolHubPostgresTools ([int]$config.POSTGRES_PORT))){throw 'PREREQUISITE_MISSING: PostgreSQL client tools psql, pg_dump, and pg_restore were not found in PATH or the installed PostgreSQL service directory.'};$major=[int]((& node --version).TrimStart('v').Split('.')[0]);if($major -lt 22){throw 'NODE_VERSION: Node.js 22 or newer is required.'}
 $step='Configuration protection';if(-not (Protect-SchoolHubConfig $ConfigPath)){Write-Warning 'Could not restrict configuration ACLs automatically. Protect this file manually.'}
 $step='PostgreSQL connection';$oldPassword=$env:PGPASSWORD;try{$env:PGPASSWORD=$config.POSTGRES_PASSWORD;& psql -h $config.POSTGRES_HOST -p $config.POSTGRES_PORT -U $config.POSTGRES_USER -d $config.POSTGRES_DATABASE -v ON_ERROR_STOP=1 -tAc 'SELECT 1'|Out-Null;if($LASTEXITCODE -ne 0){throw 'DATABASE_CONNECTION: PostgreSQL connection failed.'}}finally{$env:PGPASSWORD=$oldPassword}
 if($ValidateOnly){Write-Host 'SchoolHub configuration and database connection are valid.' -ForegroundColor Green;exit 0}
 $step='Port conflict checks';$managedRunning=$false;$portChecks=@([pscustomobject]@{Port=[int]$config.FRONTEND_PORT;Kind='static'});if($config.START_API -eq 'true'){$portChecks+=,[pscustomobject]@{Port=[int]$config.API_PORT;Kind='api'}};foreach($check in $portChecks){$owner=Get-SchoolHubPortOwner $check.Port;if($owner -and -not (Test-SchoolHubProcess $owner.OwningProcess $check.Kind)){throw "PORT_IN_USE: Port $($check.Port) belongs to process $($owner.OwningProcess)."};if($owner){$managedRunning=$true}}
 if($managedRunning){$step='Safe service stop before dependency update';& (Join-Path $PSScriptRoot 'Stop-SchoolHub.ps1') -RuntimeDirectory $logDirectory}
 $step='Public runtime configuration';Write-SchoolHubRuntimeConfig $config (Join-Path $root 'schoolhub-runtime-config.json')
 $step='Dependency installation';Push-Location (Join-Path $root 'schoolhub-server');try{& npm.cmd ci;if($LASTEXITCODE -ne 0){throw 'NPM_INSTALL_FAILED: npm ci failed.'};$step='Production build';& npm.cmd run build;if($LASTEXITCODE -ne 0){throw 'BUILD_FAILED: TypeScript build failed.'};if(-not $SkipTests){$step='Automated server tests';& npm.cmd test;if($LASTEXITCODE -ne 0){throw 'TEST_FAILED: Server tests failed.'}}
  $step='Pre-migration database backup';$backupDirectory=Join-Path $root 'backups';New-Item -ItemType Directory -Path $backupDirectory -Force|Out-Null;$backupPath=Join-Path $backupDirectory ('schoolhub-pre-migration-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.dump');$oldPassword=$env:PGPASSWORD;try{$env:PGPASSWORD=$config.POSTGRES_PASSWORD;& pg_dump -h $config.POSTGRES_HOST -p $config.POSTGRES_PORT -U $config.POSTGRES_USER -d $config.POSTGRES_DATABASE --format=custom --no-owner --file=$backupPath;if($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $backupPath) -or (Get-Item -LiteralPath $backupPath).Length -le 0){throw 'DATABASE_BACKUP_FAILED: PostgreSQL backup failed.'};& pg_restore --list $backupPath|Out-Null;if($LASTEXITCODE -ne 0){throw 'DATABASE_BACKUP_INVALID: The PostgreSQL backup catalogue could not be verified.'}}finally{$env:PGPASSWORD=$oldPassword}
  $step='Forward-only database migrations';Set-SchoolHubEnvironment $config $root;& npm.cmd run migrate;if($LASTEXITCODE -ne 0){throw 'MIGRATION_FAILED: Database migration failed. Existing data was not reset.'}
 }finally{Pop-Location}
 if(-not $NoStart){$step='Service startup and health checks';& (Join-Path $PSScriptRoot 'Start-SchoolHub.ps1') -ConfigPath $ConfigPath -NoBrowser:$NoBrowser;if($LASTEXITCODE -ne 0){throw 'STARTUP_FAILED: SchoolHub did not become healthy.'}}
 Write-Host 'SchoolHub setup completed successfully.' -ForegroundColor Green;Write-Host "Setup log: $logPath";Write-Host 'No administrator or operational record was created automatically.'
}catch{Write-SchoolHubSafeFailure $step $_ $logPath;exit 1}finally{try{Stop-Transcript|Out-Null}catch{}}
