import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { Database, Queryable } from '../database/types.js';
import type { Principal } from '../authorization/service.js';
import { ApiError } from '../errors/api-error.js';
import { hashPassword } from '../auth/password.js';
import { writeAudit } from '../audit/service.js';
import { BUILT_IN_WORKSPACES, WORKSPACE_FIELD_TYPE_NAMES } from './workspace-service.js';

const skippedCollections=['teacherWorkLogs','teacherLogs','leaves','notices','calendar','calendarEvents','documents','certificates','generatedDocuments','uniformCategories','curriculumEntries','workflowDefinitions','workflowInstances','coScholasticRatings','transportAssignments','buses'];
const demoStudents=[['STU001','Aarav Sharma'],['STU002','Ananya Singh'],['STU003','Vivaan Gupta']];
const demoTeachers=[['EMP001','Neha Sharma'],['EMP002','Rahul Verma'],['EMP003','Shalini Mehta']];
const arr=(v:any,k:string)=>Array.isArray(v?.[k])?v[k]:[];
const normalized=(v:any)=>String(v??'').trim().replace(/\s+/g,' ').toLowerCase();
const stable=(prefix:string,value:string)=>prefix+createHash('sha256').update(value).digest('hex').slice(0,20);
const dayName=(value:any)=>({mon:'Monday',tue:'Tuesday',wed:'Wednesday',thu:'Thursday',fri:'Friday',sat:'Saturday',sun:'Sunday'} as any)[normalized(value).slice(0,3)]||String(value||'');
const workspaceMetadata=(d:any)=>{const raw=d?.workspaceMetadata&&typeof d.workspaceMetadata==='object'?d.workspaceMetadata:{};return{schemaVersion:Number(raw.schemaVersion||1),workspaces:arr(raw,'workspaces'),sections:arr(raw,'sections'),fields:arr(raw,'fields'),options:arr(raw,'options')}};
function prepare(source:any){
 const d=structuredClone(source),withIds=(records:any[],prefix:string,key:(x:any)=>string)=>records.forEach(x=>{if(!x.id)x.id=stable(prefix,key(x))});
 withIds(arr(d,'roles'),'rol_',x=>normalized(x.name));withIds(arr(d,'teachers'),'tch_',x=>normalized(x.emp)+'|'+normalized(x.name));withIds(arr(d,'academicYears'),'ay_',x=>normalized(x.name));withIds(arr(d,'classes'),'cls_',x=>normalized(x.name));withIds(arr(d,'subjects'),'sub_',x=>normalized(x.name));withIds(arr(d,'users'),'usr_',x=>normalized(x.username));withIds(arr(d,'students'),'stu_',x=>normalized(x.admission)+'|'+normalized(x.name));withIds(arr(d,'feeStructures'),'fee_structure_',x=>[normalized(x.name),normalized(x.academicYear),normalized(x.applicableClass),normalized(x.applicableSection)].join('|'));withIds(arr(d,'fees'),'fee_payment_',x=>[normalized(x.receipt),normalized(x.student),x.date,normalized(x.head)].join('|'));
 const classes=arr(d,'classes'),years=arr(d,'academicYears'),subjects=arr(d,'subjects'),staff=arr(d,'teachers'),students=arr(d,'students'),sections=arr(d,'classSections');
 if(!sections.length)for(const c of classes)String(c.sections||'').split(',').map((x:string)=>x.trim()).filter(Boolean).forEach((name:string,index:number)=>sections.push({id:stable('sec_',c.id+'|'+normalized(name)),classId:c.id,name,active:true,sortOrder:index}));
 withIds(sections,'sec_',x=>String(x.classId)+'|'+normalized(x.name));d.classSections=sections;
 const by=(records:any[],key:(x:any)=>any)=>new Map(records.map(x=>[normalized(key(x)),x])),classBy=by(classes,x=>x.name),yearBy=by(years,x=>x.name),subjectBy=by(subjects,x=>x.name),staffByName=by(staff,x=>x.name),staffByEmp=by(staff,x=>x.emp),studentByAdmission=by(students,x=>x.admission),studentByName=by(students,x=>x.name),activeYear=yearBy.get(normalized(d.settings?.year))||years.find((x:any)=>x.status==='Active'||x.active===true)||null;
 const sectionFor=(classId:any,value:any)=>sections.find((x:any)=>String(x.classId)===String(classId)&&normalized(x.name)===normalized(value));
 for(const s of students){const cls=s.classId?classes.find((x:any)=>x.id===s.classId):classBy.get(normalized(s.class));if(cls){s.classId=cls.id;const sec=s.sectionId?sections.find((x:any)=>x.id===s.sectionId&&x.classId===cls.id):sectionFor(cls.id,s.section);if(sec)s.sectionId=sec.id}if(!s.academicYearId&&activeYear)s.academicYearId=activeYear.id}
 const attendance=arr(d,'attendance');for(const a of attendance){const stu=a.studentId?students.find((x:any)=>x.id===a.studentId):studentByAdmission.get(normalized(a.student))||studentByName.get(normalized(a.student));if(stu)a.studentId=stu.id;a.date=a.date||a.attendanceDate;a.period=a.period||'Full Day';if(!a.id)a.id=stable('att_',[a.studentId||a.student,a.date,a.period].join('|'))}
 const homework=arr(d,'homework');for(const h of homework){const cls=h.classId?classes.find((x:any)=>x.id===h.classId):classBy.get(normalized(h.class));if(cls){h.classId=cls.id;const sec=h.sectionId?sections.find((x:any)=>x.id===h.sectionId):sectionFor(cls.id,h.section);if(sec)h.sectionId=sec.id}h.subjectId=h.subjectId||(subjectBy.get(normalized(h.subject))?.id);h.teacherId=h.teacherId||(staffByEmp.get(normalized(h.teacher))||staffByName.get(normalized(h.teacher)))?.id;h.academicYearId=h.academicYearId||(yearBy.get(normalized(h.academicYear))||activeYear)?.id;h.title=h.title||String(h.text||'Homework').slice(0,200);h.instructions=h.instructions??h.text??'';h.assignedDate=h.assignedDate||h.date;h.dueDate=h.dueDate||h.due||null;if(!h.id)h.id=stable('hw_',[h.classId,h.sectionId,h.subjectId,h.assignedDate,h.title].join('|'))}
 const exams=arr(d,'exams');for(const e of exams){const cls=e.classId?classes.find((x:any)=>x.id===e.classId):classBy.get(normalized(e.class));if(cls){e.classId=cls.id;const sec=e.sectionId?sections.find((x:any)=>x.id===e.sectionId):sectionFor(cls.id,e.section);if(sec)e.sectionId=sec.id}e.subjectId=e.subjectId||(subjectBy.get(normalized(e.subject))?.id);e.academicYearId=e.academicYearId||(yearBy.get(normalized(e.academicYear))||activeYear)?.id;e.examDate=e.examDate||e.date||null;e.maxMarks=Number(e.maxMarks??e.max);e.passingMarks=e.passingMarks==null?null:Number(e.passingMarks);e.state=e.state||(e.published?'Published':'Draft');if(!e.id)e.id=stable('ex_',[e.name,e.classId,e.sectionId,e.subjectId,e.examDate].join('|'))}
 const examById=new Map(exams.map((x:any)=>[String(x.id),x])),marks=arr(d,'marks');for(const m of marks){const stu=m.studentId?students.find((x:any)=>x.id===m.studentId):studentByAdmission.get(normalized(m.student))||studentByName.get(normalized(m.student));if(stu)m.studentId=stu.id;if(!m.id)m.id=stable('mk_',[m.examId,m.studentId||m.student].join('|'));const exam=examById.get(String(m.examId));if(exam)m.maxMarks=exam.maxMarks}
 let timetable=arr(d,'timetableRelationships').filter((x:any)=>x.subjectId&&x.classId);
 if(!timetable.length&&d.timetableEntries&&typeof d.timetableEntries==='object')for(const [key,periods] of Object.entries<any>(d.timetableEntries)){const [className,...sectionParts]=key.split('|'),cls=classBy.get(normalized(className)),sec=cls?sectionFor(cls.id,sectionParts.join('|')):null;for(const [periodKey,days] of Object.entries<any>(periods||{}))for(const [day,value] of Object.entries<any>(days||{})){const subject=subjectBy.get(normalized(value));if(cls&&subject&&!/break/i.test(String(value)))timetable.push({id:stable('tt_',[key,periodKey,day].join('|')),academicYearId:activeYear?.id,classId:cls.id,sectionId:sec?.id||null,subjectId:subject.id,teacherId:null,day:dayName(day),periodKey,room:null})}}
 for(const x of timetable){x.academicYearId=x.academicYearId||activeYear?.id;x.day=dayName(x.day);if(!x.id)x.id=stable('tt_',[x.academicYearId,x.classId,x.sectionId,x.day,x.periodKey].join('|'))}d.timetableRelationships=timetable;
 const history=arr(d,'studentAcademicHistory');withIds(history,'hist_',x=>[x.studentId,x.academicYearId||x.yearId].join('|'));
 return d
}

async function batchInsert(tx:Queryable,table:string,columns:string[],rows:any[][]){
 const size=200;for(let start=0;start<rows.length;start+=size){const chunk=rows.slice(start,start+size),values:any[]=[],tuples=chunk.map((row,i)=>'('+row.map((v,j)=>{values.push(v);return '$'+(i*columns.length+j+1)}).join(',')+')');await tx.query('INSERT INTO '+table+'('+columns.join(',')+') VALUES '+tuples.join(',')+' ON CONFLICT DO NOTHING',values)}
}

export class ImportService{
 constructor(private db:Database){}
 private dupes(values:string[]){const seen=new Set<string>(),dupes=new Set<string>();for(const v of values){if(!v)continue;if(seen.has(v))dupes.add(v);seen.add(v)}return[...dupes]}
 preview(backup:any){
  const data=prepare(backup?.data||backup);if(!data||typeof data!=='object'||!data.settings)throw new ApiError('INVALID_IMPORT','Select a valid SchoolHub backup.',422);
  const collections={roles:arr(data,'roles'),users:arr(data,'users'),staff:arr(data,'teachers'),academicYears:arr(data,'academicYears'),classes:arr(data,'classes'),sections:arr(data,'classSections'),subjects:arr(data,'subjects'),assignments:arr(data,'teacherAssignments'),students:arr(data,'students'),attendance:arr(data,'attendance'),homework:arr(data,'homework'),timetable:arr(data,'timetableRelationships'),exams:arr(data,'exams'),marks:arr(data,'marks'),academicHistory:arr(data,'studentAcademicHistory'),feeStructures:arr(data,'feeStructures'),feeAssignments:arr(data,'feeAssignments'),fees:arr(data,'fees')};
  const metadata=workspaceMetadata(data);
  const ids=(records:any[])=>new Set(records.map(x=>String(x.id||'')).filter(Boolean)),sets={staff:ids(collections.staff),years:ids(collections.academicYears),classes:ids(collections.classes),sections:ids(collections.sections),subjects:ids(collections.subjects),students:ids(collections.students),exams:ids(collections.exams)},errors:string[]=[],warnings:string[]=[];
  if(Number(data._schoolHub?.dataSchemaVersion||0)>5)errors.push('The backup uses an unsupported future data schema.');
  const demo={students:collections.students.filter((s:any)=>demoStudents.some(x=>x[0]===s.admission&&x[1]===s.name)).length,teachers:collections.staff.filter((t:any)=>demoTeachers.some(x=>x[0]===t.emp&&x[1]===t.name)).length};
  const duplicates={usernames:this.dupes(collections.users.map((x:any)=>normalized(x.username))),admissions:this.dupes(collections.students.map((x:any)=>String(x.admission||''))),employees:this.dupes(collections.staff.map((x:any)=>String(x.emp||''))),ids:Object.fromEntries(Object.entries(collections).map(([k,v])=>[k,this.dupes((v as any[]).map(x=>String(x.id||'')))])),attendance:this.dupes(collections.attendance.map((x:any)=>[x.studentId,x.date,x.period].join('|'))),marks:this.dupes(collections.marks.map((x:any)=>[x.examId,x.studentId].join('|'))),timetable:this.dupes(collections.timetable.map((x:any)=>[x.academicYearId,x.classId,x.sectionId||'',x.day,x.periodKey].join('|')))};
  for(const [name,list] of Object.entries(duplicates.ids))if((list as string[]).length)errors.push('Duplicate stable IDs in '+name+'.');if(duplicates.usernames.length)errors.push('Duplicate usernames.');if(duplicates.admissions.length)errors.push('Duplicate admission numbers.');if(duplicates.employees.length)errors.push('Duplicate employee IDs.');if(duplicates.attendance.length)errors.push('Duplicate attendance identity.');if(duplicates.marks.length)errors.push('Duplicate marks identity.');if(duplicates.timetable.length)errors.push('Duplicate timetable slot.');if(demo.students||demo.teachers)errors.push('Confirmed demo records require cleanup before server import.');
  let ambiguous=0;for(const u of collections.users)if(u.teacherId&&!sets.staff.has(String(u.teacherId))){ambiguous++;errors.push('A user references a missing teacher.')}
  for(const s of collections.sections)if(!sets.classes.has(String(s.classId)))errors.push('A section references a missing class.');
  for(const s of collections.students){if(!s.classId||!sets.classes.has(String(s.classId)))errors.push('A student references a missing class.');if((s.section||s.sectionId)&&(!s.sectionId||!sets.sections.has(String(s.sectionId))))errors.push('A student references a missing section.');if(!s.academicYearId||!sets.years.has(String(s.academicYearId)))errors.push('A student references a missing academic year.')}
  const activeAssignments=new Set<string>();for(const a of collections.assignments){if(!sets.staff.has(String(a.teacherId))||!sets.years.has(String(a.academicYearId))||!sets.classes.has(String(a.classId))||(a.sectionId&&!sets.sections.has(String(a.sectionId)))||(a.subjectId&&!sets.subjects.has(String(a.subjectId))))errors.push('A teacher assignment contains a missing relationship.');if(a.validFrom&&a.validUntil&&a.validUntil<a.validFrom)errors.push('A teacher assignment has an invalid date range.');if(a.active!==false){const key=[a.teacherId,a.academicYearId,a.classId,a.sectionId||'',a.subjectId||'',a.assignmentType].join('|');if(activeAssignments.has(key))errors.push('Duplicate active teacher assignment.');activeAssignments.add(key)}}
  for(const a of collections.attendance)if(!sets.students.has(String(a.studentId))||!a.date)errors.push('Attendance contains a missing student or date.');
  for(const h of collections.homework)if(!sets.classes.has(String(h.classId))||!sets.years.has(String(h.academicYearId))||(h.sectionId&&!sets.sections.has(String(h.sectionId)))||(h.subjectId&&!sets.subjects.has(String(h.subjectId)))||(h.teacherId&&!sets.staff.has(String(h.teacherId)))||!h.assignedDate)errors.push('Homework contains a missing academic relationship.');
  for(const x of collections.timetable)if(!sets.classes.has(String(x.classId))||!sets.years.has(String(x.academicYearId))||(x.sectionId&&!sets.sections.has(String(x.sectionId)))||(x.subjectId&&!sets.subjects.has(String(x.subjectId)))||(x.teacherId&&!sets.staff.has(String(x.teacherId)))||!x.day||!x.periodKey)errors.push('Timetable contains a missing academic relationship.');
  for(const e of collections.exams)if(!sets.classes.has(String(e.classId))||!sets.years.has(String(e.academicYearId))||(e.sectionId&&!sets.sections.has(String(e.sectionId)))||(e.subjectId&&!sets.subjects.has(String(e.subjectId)))||!(e.maxMarks>0)||(e.passingMarks!=null&&e.passingMarks>e.maxMarks))errors.push('Exam contains an invalid relationship or marks configuration.');
  for(const m of collections.marks)if(!sets.exams.has(String(m.examId))||!sets.students.has(String(m.studentId))||(!m.absent&&(m.marks==null||Number(m.marks)<0||Number(m.marks)>Number(m.maxMarks))))errors.push('Marks contain an invalid exam, student, or value.');
  for(const h of collections.academicHistory)if(!sets.students.has(String(h.studentId))||!sets.years.has(String(h.academicYearId||h.yearId))||!sets.classes.has(String(h.classId)))errors.push('Academic history contains a missing relationship.');
  if(metadata.schemaVersion>1)errors.push('The backup uses an unsupported future Workspace metadata version.');if(metadata.workspaces.some((x:any)=>!x.id||!x.workspaceKey||!x.name||!x.pluralName)||metadata.sections.some((x:any)=>!x.id||!x.workspaceId||!x.sectionKey||!x.name)||metadata.fields.some((x:any)=>!x.id||!x.workspaceId||!x.fieldKey||!x.label||!x.fieldType))errors.push('Workspace metadata contains missing stable identities.');const workspaceIds=ids(metadata.workspaces),sectionIds=ids(metadata.sections),fieldIds=ids(metadata.fields);if(this.dupes(metadata.workspaces.map((x:any)=>String(x.id||''))).length||this.dupes(metadata.sections.map((x:any)=>String(x.id||''))).length||this.dupes(metadata.fields.map((x:any)=>String(x.id||''))).length)errors.push('Duplicate Workspace metadata IDs.');if(this.dupes(metadata.workspaces.map((x:any)=>normalized(x.workspaceKey))).length)errors.push('Duplicate Workspace keys.');if(metadata.workspaces.some((x:any)=>x.system||x.workspaceType==='BuiltIn'||BUILT_IN_WORKSPACES.some(b=>b.key===x.workspaceKey)))errors.push('Backups cannot overwrite built-in Workspace identities.');for(const s of metadata.sections)if(!workspaceIds.has(String(s.workspaceId)))errors.push('Workspace section references a missing Workspace.');for(const f of metadata.fields){if(!workspaceIds.has(String(f.workspaceId))||(f.sectionId&&!sectionIds.has(String(f.sectionId))))errors.push('Workspace field references missing metadata.');if(!WORKSPACE_FIELD_TYPE_NAMES.includes(f.fieldType))errors.push('Workspace field uses an unsupported type.')}for(const o of metadata.options)if(!fieldIds.has(String(o.fieldId)))errors.push('Workspace option references a missing field.');
  if(!collections.academicYears.length)warnings.push('No academic years are present.');
  const skipped=skippedCollections.map(collection=>({collection,count:arr(data,collection).length,reason:'No silent partial migration'})),skippedWithData=skipped.filter(x=>x.count>0);if(skippedWithData.length)errors.push('Migration is blocked because this backup contains data in collections that are not yet supported: '+skippedWithData.map(x=>x.collection+' ('+x.count+')').join(', ')+'.');const uniqueErrors=[...new Set(errors)],hash=createHash('sha256').update(JSON.stringify(data)).digest('hex'),counts={...Object.fromEntries(Object.entries(collections).map(([k,v])=>[k,v.length])),workspaceDefinitions:metadata.workspaces.length,workspaceSections:metadata.sections.length,workspaceFields:metadata.fields.length,workspaceOptions:metadata.options.length};
  return{hash,valid:!uniqueErrors.length,errors:uniqueErrors,warnings:[...new Set(warnings)],school:{name:data.settings.school||'',academicYear:data.settings.year||''},counts,teacherLinks:{ambiguous},duplicates,demoRecords:demo,workspaceMetadata:{schemaVersion:metadata.schemaVersion,counts:{workspaces:metadata.workspaces.length,sections:metadata.sections.length,fields:metadata.fields.length,options:metadata.options.length}},localOnly:skipped.map(x=>({collection:x.collection,count:x.count,imported:false})),reconciliation:{imported:Object.entries(counts).map(([collection,count])=>({collection,count})),skipped,rejected:uniqueErrors}}
 }
 async commit(p:Principal,backup:any,expectedHash:string,correlationId:string){
  const preview=this.preview(backup);if(!preview.valid)throw new ApiError('INVALID_IMPORT','The import preview contains blocking identity or demo-data problems.',422,preview);if(preview.hash!==expectedHash)throw new ApiError('IMPORT_HASH_MISMATCH','The selected backup changed after preview.',409);const data=prepare(backup?.data||backup),exists=await this.db.query('SELECT id FROM import_jobs WHERE school_id=$1 AND backup_hash=$2',[p.schoolId,preview.hash]);if(exists.rows.length)throw new ApiError('DUPLICATE_IMPORT','This backup was already imported.',409);
  return this.db.transaction(async tx=>{const id=randomUUID(),tables={roles:'roles',users:'users',staff:'staff',academicYears:'academic_years',classes:'classes',sections:'sections',subjects:'subjects',assignments:'teacher_assignments',students:'students',attendance:'attendance_records',homework:'homework_records',timetable:'timetable_entries',exams:'exam_records',marks:'mark_records',academicHistory:'student_academic_history',feeStructures:'school_fee_structures',feeAssignments:'school_fee_assignments',fees:'school_fee_payments',workspaceDefinitions:'workspace_definitions',workspaceSections:'workspace_sections',workspaceFields:'workspace_fields',workspaceOptions:'workspace_field_options'} as const,before:Record<string,number>={};for(const [name,table] of Object.entries(tables)){const r=await tx.query<{count:string}>('SELECT count(*)::text count FROM '+table+' WHERE school_id=$1',[p.schoolId]);before[name]=Number(r.rows[0]?.count||0)}await tx.query('INSERT INTO import_jobs(id,school_id,backup_hash,status,counts,created_by) VALUES($1,$2,$3,$4,$5,$6)',[id,p.schoolId,preview.hash,'Running',JSON.stringify(preview.counts),p.userId]);await this.insertCollections(tx,p.schoolId,data);const imported=[],matched=[];for(const [name,table] of Object.entries(tables)){const r=await tx.query<{count:string}>('SELECT count(*)::text count FROM '+table+' WHERE school_id=$1',[p.schoolId]),count=Number(r.rows[0]?.count||0)-before[name],accepted=Number((preview.counts as any)[name]||0);imported.push({collection:name,count});if(accepted>count)matched.push({collection:name,count:accepted-count,reason:'Matched an existing server record'})}const reconciliation={imported,skipped:[...preview.reconciliation.skipped,...matched],rejected:[] as string[]};await tx.query("UPDATE import_jobs SET status='Completed',counts=$2,completed_at=CURRENT_TIMESTAMP WHERE id=$1",[id,JSON.stringify({source:preview.counts,imported})]);await writeAudit(tx,{schoolId:p.schoolId,actorUserId:p.userId,action:'IMPORT_COMMIT',entityType:'Import',entityId:id,outcome:'SUCCESS',correlationId,summary:{hash:preview.hash,counts:preview.counts,reconciliation}});return{id,hash:preview.hash,status:'Completed',counts:preview.counts,reconciliation}})
 }
 private async insertCollections(tx:Queryable,schoolId:string,d:any){
  const roleIds=new Map<string,string>();for(const r of arr(d,'roles')){await tx.query('INSERT INTO roles(id,school_id,name,system,active) VALUES($1,$2,$3,$4,true) ON CONFLICT DO NOTHING',[r.id,schoolId,r.name,r.name==='System Administrator']);const stored=await tx.query<any>('SELECT id FROM roles WHERE school_id=$1 AND name=$2',[schoolId,r.name]),serverId=stored.rows[0]?.id;if(!serverId)throw new ApiError('INVALID_IMPORT','A role could not be imported.',422);roleIds.set(String(r.id),serverId);}
  for(const t of arr(d,'teachers'))await tx.query('INSERT INTO staff(id,school_id,employee_number,name,role_name,subject_snapshot,status) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING',[t.id,schoolId,t.emp||null,t.name,t.role||'Teacher',t.subject||null,t.status||'Active']);
  for(const y of arr(d,'academicYears'))await tx.query('INSERT INTO academic_years(id,school_id,name,start_date,end_date,active) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING',[y.id,schoolId,y.name,y.start||y.startDate||null,y.end||y.endDate||null,y.active!==false]);
  const source=d.settings&&typeof d.settings==='object'?d.settings:{},shared=Object.fromEntries(['phone','email','website','address','studentPrefix','employeePrefix','receiptPrefix','currency'].filter(k=>source[k]!==undefined).map(k=>[k==='phone'?'contactPhone':k,source[k]])),activeYear=arr(d,'academicYears').find((y:any)=>y.status==='Active'||y.active===true)||null,current=await tx.query<any>('SELECT name,settings FROM schools WHERE id=$1',[schoolId]);await tx.query('UPDATE schools SET name=$1,settings=$2,active_academic_year_id=$3,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$4',[String(source.school||'').trim()||current.rows[0]?.name||'SchoolHub',JSON.stringify({...current.rows[0]?.settings,...shared}),activeYear?.id||null,schoolId]);
  for(const c of arr(d,'classes'))await tx.query('INSERT INTO classes(id,school_id,name,active) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[c.id,schoolId,c.name,c.active!==false]);
  for(const s of arr(d,'classSections'))await tx.query('INSERT INTO sections(id,school_id,class_id,name,active,sort_order) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING',[s.id,schoolId,s.classId,s.name,s.active!==false,s.sortOrder||0]);
  for(const s of arr(d,'subjects'))await tx.query('INSERT INTO subjects(id,school_id,name,code,active) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[s.id,schoolId,s.name,s.code||null,s.active!==false]);
  const roleRows=await tx.query<any>('SELECT id,name FROM roles WHERE school_id=$1',[schoolId]),roleMap=new Map(roleRows.rows.map(x=>[x.name,x.id]));for(const u of arr(d,'users')){const existing=await tx.query('SELECT id FROM users WHERE school_id=$1 AND lower(username)=lower($2)',[schoolId,u.username]);if(existing.rows.length)continue;const password=await hashPassword(randomBytes(32).toString('hex')),roleId=roleIds.get(String(u.roleId||''))||roleMap.get(u.role);if(!roleId)throw new ApiError('INVALID_IMPORT','A user role reference is invalid.',422);await tx.query('INSERT INTO users(id,school_id,role_id,teacher_id,username,password_hash,must_change_password,status) VALUES($1,$2,$3,$4,$5,$6,true,$7)',[u.id,schoolId,roleId,u.teacherId||null,u.username,password,'PendingPassword'])}
  for(const a of arr(d,'teacherAssignments'))await tx.query('INSERT INTO teacher_assignments(id,school_id,teacher_id,academic_year_id,class_id,section_id,subject_id,assignment_type,valid_from,valid_until,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT DO NOTHING',[a.id,schoolId,a.teacherId,a.academicYearId,a.classId,a.sectionId||null,a.subjectId||null,a.assignmentType||'ClassTeacher',a.validFrom||null,a.validUntil||null,a.active!==false]);
  for(const s of arr(d,'students'))await tx.query('INSERT INTO students(id,school_id,admission_number,name,class_id,section_id,academic_year_id,status,father_name,email,phone,address,date_of_birth,extra) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT DO NOTHING',[s.id,schoolId,s.admission,s.name,s.classId,s.sectionId||null,s.academicYearId||null,s.status||'Active',s.father||null,s.email||null,s.phone||null,s.address||null,s.dob||null,JSON.stringify(s.customFields||{})]);
  await batchInsert(tx,'attendance_records',['id','school_id','student_id','attendance_date','period','status','remark','recorded_by'],arr(d,'attendance').map((a:any)=>[a.id,schoolId,a.studentId,a.date,a.period||'Full Day',a.status,a.remark||null,null]));
  await batchInsert(tx,'homework_records',['id','school_id','academic_year_id','class_id','section_id','subject_id','teacher_id','title','instructions','assigned_date','due_date','status','attachment_metadata'],arr(d,'homework').map((h:any)=>[h.id,schoolId,h.academicYearId,h.classId,h.sectionId||null,h.subjectId||null,h.teacherId||null,h.title,h.instructions,h.assignedDate,h.dueDate||null,h.status||'Draft',JSON.stringify((h.attachments||[]).map((x:any)=>({name:x.name||'attachment',size:Number(x.size)||0,type:x.type||''})))]));
  await batchInsert(tx,'timetable_entries',['id','school_id','academic_year_id','class_id','section_id','subject_id','teacher_id','day_of_week','period_key','room','start_time','end_time'],arr(d,'timetableRelationships').map((x:any)=>[x.id,schoolId,x.academicYearId,x.classId,x.sectionId||null,x.subjectId||null,x.teacherId||null,x.day,x.periodKey,x.room||null,x.startTime||null,x.endTime||null]));
  await batchInsert(tx,'exam_records',['id','school_id','academic_year_id','class_id','section_id','subject_id','name','exam_date','max_marks','passing_marks','state','published','published_at','locked_at'],arr(d,'exams').map((e:any)=>[e.id,schoolId,e.academicYearId,e.classId,e.sectionId||null,e.subjectId||null,e.name,e.examDate||null,e.maxMarks,e.passingMarks,e.state,e.state==='Published',e.state==='Published'?new Date().toISOString():null,e.state==='Published'?new Date().toISOString():null]));
  await batchInsert(tx,'mark_records',['id','school_id','exam_id','student_id','marks','absent','recorded_by'],arr(d,'marks').map((m:any)=>[m.id,schoolId,m.examId,m.studentId,m.absent?null:Number(m.marks),!!m.absent,null]));
  await batchInsert(tx,'student_academic_history',['id','school_id','student_id','academic_year_id','class_id','section_id','outcome','destination_academic_year_id','destination_class_id','destination_section_id','snapshot','promotion_job_id'],arr(d,'studentAcademicHistory').map((h:any)=>[h.id,schoolId,h.studentId,h.academicYearId||h.yearId,h.classId,h.sectionId||null,h.outcome||h.status||'Historical',h.destinationAcademicYearId||null,h.destinationClassId||null,h.destinationSectionId||null,JSON.stringify(h.snapshot||h),null]));
  for(const f of arr(d,'feeStructures')){const components=arr(f,'components').map((c:any)=>({name:String(c.name||c.component||'').trim(),amount:Number(c.amount||c.applicableAmount||0)})).filter((c:any)=>c.name),data={name:String(f.name||'Migrated Fee Structure'),academicYear:String(f.academicYear||d.settings?.year||''),applicableClass:String(f.applicableClass||f.class||''),applicableSection:String(f.applicableSection||f.section||''),components,dueDate:String(f.dueDate||''),status:f.status==='Inactive'?'Inactive':'Active',totalAmount:components.reduce((n:number,c:any)=>n+Number(c.amount||0),0)};await tx.query('INSERT INTO school_fee_structures(id,school_id,data) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[f.id,schoolId,JSON.stringify(data)])}
  const importedStudents=await tx.query<any>('SELECT id,admission_number FROM students WHERE school_id=$1',[schoolId]),studentIdByAdmission=new Map(importedStudents.rows.map(x=>[normalized(x.admission_number),x.id]));
  for(const a of arr(d,'feeAssignments')){const studentId=studentIdByAdmission.get(normalized(a.student||a.admission));if(studentId&&a.feeStructureId)await tx.query('INSERT INTO school_fee_assignments(school_id,student_id,structure_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[schoolId,studentId,a.feeStructureId])}
  for(const f of arr(d,'fees')){const studentId=studentIdByAdmission.get(normalized(f.student||f.admission));if(!studentId)continue;const amount=Number(f.amount||0),receipt=String(f.receipt||('MIG-'+f.id)).trim(),components=(Array.isArray(f.components)&&f.components.length?f.components:[{component:f.head,applicableAmount:amount,paidAmount:amount}]).map((c:any)=>({component:String(c.component||c.head||f.head||'Legacy Fee').trim(),applicableAmount:Number(c.applicableAmount||c.amount||amount),paidAmount:Number(c.paidAmount||c.amount||amount)})),data={...f,receipt,date:String(f.date||new Date().toISOString().slice(0,10)),student:String(f.student||f.admission),head:components.length>1?'Multiple Fee Components':components[0].component,mode:['Cash','UPI','Bank','Card','Online'].includes(f.mode)?f.mode:'Cash',amount,components};const fingerprint=createHash('sha256').update(JSON.stringify(data)).digest('hex');await tx.query('INSERT INTO school_fee_payments(id,school_id,student_id,receipt_key,data,amount_minor,mutation_key,request_fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING',[f.id,schoolId,studentId,receipt.toLowerCase(),JSON.stringify(data),Math.round(amount*100),stable('fee_import_',f.id),fingerprint])}
  const wm=workspaceMetadata(d);for(const w of wm.workspaces){const occupied=await tx.query('SELECT id FROM workspace_definitions WHERE school_id=$1 AND workspace_key=$2',[schoolId,w.workspaceKey]);if(occupied.rows[0])throw new ApiError('WORKSPACE_IMPORT_CONFLICT','A Workspace key already exists on the server.',409)}for(const w of wm.workspaces)await tx.query("INSERT INTO workspace_definitions(id,school_id,workspace_key,name,plural_name,description,category,icon,workspace_type,status,system,factory_version,definition_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'Custom','Draft',false,0,1)",[w.id,schoolId,w.workspaceKey,w.name,w.pluralName,w.description||'',w.category||'Imported',w.icon||null]);for(const s of wm.sections)await tx.query('INSERT INTO workspace_sections(id,school_id,workspace_id,section_key,name,description,sort_order,enabled,screen_visible,print_visible,layout_columns,system) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,false)',[s.id,schoolId,s.workspaceId,s.sectionKey,s.name,s.description||'',s.order||0,s.enabled!==false,s.screenVisible!==false,s.printVisible!==false,s.layoutColumns||2]);for(const f of wm.fields)await tx.query('INSERT INTO workspace_fields(id,school_id,workspace_id,section_id,field_key,label,description,field_type,required,default_value,help_text,placeholder,width,sort_order,screen_visible,preview_visible,print_visible,searchable,filterable,archived,system,configuration) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,false,$21)',[f.id,schoolId,f.workspaceId,f.sectionId||null,f.fieldKey,f.label,f.description||'',f.fieldType,!!f.required,JSON.stringify(f.defaultValue??null),f.helpText||'',f.placeholder||'',f.width||'full',f.order||0,f.screenVisible!==false,!!f.previewVisible,f.printVisible!==false,!!f.searchable,!!f.filterable,!!f.archived,JSON.stringify(f.configuration||{})]);for(const o of wm.options)await tx.query('INSERT INTO workspace_field_options(id,school_id,field_id,value,label,sort_order,active) VALUES($1,$2,$3,$4,$5,$6,$7)',[o.id,schoolId,o.fieldId,o.value,o.label,o.order||0,o.active!==false]);for(const w of wm.workspaces)await tx.query('INSERT INTO workspace_definition_versions(id,school_id,workspace_id,workspace_version,definition_snapshot,change_reason) VALUES($1,$2,$3,1,$4,$5)',[randomUUID(),schoolId,w.id,JSON.stringify({workspace:w,sections:wm.sections.filter((s:any)=>s.workspaceId===w.id),fields:wm.fields.filter((f:any)=>f.workspaceId===w.id)}),'Imported Workspace metadata'])
 }
}

