import {pathToFileURL} from 'node:url';
import {loadConfig} from '../config/index.js';
import {createPostgresDatabase} from '../database/postgres.js';
import type {Database,Queryable} from '../database/types.js';
import {DATABASE_SCHEMA_VERSION} from '../database/migrations.js';
import {hashPassword,validatePassword} from '../auth/password.js';
import {WorkspaceService} from '../services/workspace-service.js';
import {workspaceAuthorizationCatalog} from '../authorization/permission-catalog.js';
import type {Principal} from '../authorization/service.js';

export const AUTHORIZATION_QA_FIXTURE_VERSION=1;
const QA_SCHOOL_SLUG='qa-school';

export function assertAuthorizationQaSeedEnvironment(env:NodeJS.ProcessEnv){
 const nodeEnv=String(env.NODE_ENV||'').trim().toLowerCase();
 if(nodeEnv==='production')throw new Error('Authorization QA fixtures are blocked in production.');
 if(!['development','test','staging'].includes(nodeEnv))throw new Error('Authorization QA fixtures require NODE_ENV=development, test, or staging.');
 if(env.AUTHORIZATION_QA_SEED!=='ALLOW')throw new Error('Set AUTHORIZATION_QA_SEED=ALLOW to confirm this development/staging-only QA seed.');
 if(nodeEnv==='staging'&&env.AUTHORIZATION_QA_STAGING!=='ALLOW')throw new Error('Set AUTHORIZATION_QA_STAGING=ALLOW to confirm the approved staging target.');
 if(!env.QA_TEST_PASSWORD)throw new Error('QA_TEST_PASSWORD is required and is never stored in source control or logs.');
 if(!validatePassword(env.QA_TEST_PASSWORD))throw new Error('QA_TEST_PASSWORD must satisfy the normal SchoolHub password policy.');
 if(!env.DATABASE_URL)throw new Error('DATABASE_URL is required.');
}

async function one<T>(db:Queryable,sql:string,values:unknown[]):Promise<T>{const row=(await db.query<T>(sql,values)).rows[0];if(!row)throw new Error('QA fixture reconciliation did not return the expected record.');return row}
async function school(db:Queryable,name:string,slug:string,id:string){return one<{id:string}>(db,'INSERT INTO schools(id,name,slug,settings) VALUES($1,$2,$3,$4) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,updated_at=CURRENT_TIMESTAMP,version=schools.version+1 RETURNING id',[id,name,slug,JSON.stringify({qaFixture:true,qaFixtureVersion:AUTHORIZATION_QA_FIXTURE_VERSION})])}
async function accountRole(db:Queryable,schoolId:string,name:string,id:string){return one<{id:string}>(db,'INSERT INTO roles(id,school_id,name,system,active) VALUES($1,$2,$3,false,true) ON CONFLICT(school_id,name) DO UPDATE SET active=true RETURNING id',[id,schoolId,name])}
async function group(db:Queryable,schoolId:string,name:string,kind:string,creator:string,id:string){return one<{id:string}>(db,'INSERT INTO access_groups(id,school_id,name,description,group_kind,system,active,created_by) VALUES($1,$2,$3,$4,$5,false,true,$6) ON CONFLICT(school_id,lower(name)) DO UPDATE SET description=EXCLUDED.description,group_kind=EXCLUDED.group_kind,active=true,updated_at=CURRENT_TIMESTAMP,version=access_groups.version+1 RETURNING id',[id,schoolId,name,'Persistent authorization QA fixture.',kind,creator])}
async function accessRole(db:Queryable,schoolId:string,workspaceId:string,name:string,creator:string,id:string){return one<{id:string}>(db,'INSERT INTO access_roles(id,school_id,name,description,workspace_id,status,system,created_by) VALUES($1,$2,$3,$4,$5,\'Active\',false,$6) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,workspace_id=EXCLUDED.workspace_id,status=\'Active\',updated_at=CURRENT_TIMESTAMP,version=access_roles.version+1 RETURNING id',[id,schoolId,name,'Authorization QA role; managed by seed:authorization-qa.',workspaceId,creator])}
async function user(db:Queryable,input:{id:string;schoolId:string;roleId:string;username:string;firstName:string;lastName:string;passwordHash:string;teacherId?:string|null;studentId?:string|null}){return one<{id:string}>(db,'INSERT INTO users(id,school_id,role_id,teacher_id,student_id,username,password_hash,must_change_password,status,first_name,last_name) VALUES($1,$2,$3,$4,$5,$6,$7,false,\'Active\',$8,$9) ON CONFLICT(school_id,lower(username)) DO UPDATE SET role_id=EXCLUDED.role_id,teacher_id=EXCLUDED.teacher_id,student_id=EXCLUDED.student_id,password_hash=EXCLUDED.password_hash,must_change_password=false,status=\'Active\',first_name=EXCLUDED.first_name,last_name=EXCLUDED.last_name,updated_at=CURRENT_TIMESTAMP,version=users.version+1 RETURNING id',[input.id,input.schoolId,input.roleId,input.teacherId||null,input.studentId||null,input.username,input.passwordHash,input.firstName,input.lastName])}

async function reconcileCore(db:Database,passwordHash:string){
 return db.transaction(async tx=>{
  const a=await school(tx,'QA School',QA_SCHOOL_SLUG,'qa-school-a');
  await school(tx,'QA School B','qa-school-b','qa-school-b');
  const roleAdmin=await accountRole(tx,a.id,'[QA] School Administrator','qa-account-role-admin');
  const roleTeacher=await accountRole(tx,a.id,'Teacher','qa-account-role-teacher');
  const roleStudent=await accountRole(tx,a.id,'Student','qa-account-role-student');
  const roleParent=await accountRole(tx,a.id,'Parent','qa-account-role-parent');
  const year=await one<{id:string}>(tx,'INSERT INTO academic_years(id,school_id,name,start_date,end_date,active) VALUES($1,$2,$3,$4,$5,true) ON CONFLICT(school_id,name) DO UPDATE SET start_date=EXCLUDED.start_date,end_date=EXCLUDED.end_date,active=true,updated_at=CURRENT_TIMESTAMP,version=academic_years.version+1 RETURNING id',['qa-year-current',a.id,'QA 2026-2027','2026-04-01','2027-03-31']);
  await tx.query('UPDATE schools SET active_academic_year_id=$1 WHERE id=$2',[year.id,a.id]);
  const klass=await one<{id:string}>(tx,'INSERT INTO classes(id,school_id,name,active) VALUES($1,$2,$3,true) ON CONFLICT(school_id,name) DO UPDATE SET active=true RETURNING id',['qa-class-viii',a.id,'VIII']);
  const sectionA=await one<{id:string}>(tx,'INSERT INTO sections(id,school_id,class_id,name,active,sort_order) VALUES($1,$2,$3,$4,true,1) ON CONFLICT(school_id,class_id,name) DO UPDATE SET active=true,sort_order=1 RETURNING id',['qa-section-viii-a',a.id,klass.id,'A']);
  const sectionB=await one<{id:string}>(tx,'INSERT INTO sections(id,school_id,class_id,name,active,sort_order) VALUES($1,$2,$3,$4,true,2) ON CONFLICT(school_id,class_id,name) DO UPDATE SET active=true,sort_order=2 RETURNING id',['qa-section-viii-b',a.id,klass.id,'B']);
  const subject=await one<{id:string}>(tx,'INSERT INTO subjects(id,school_id,name,code,active) VALUES($1,$2,$3,$4,true) ON CONFLICT(school_id,name) DO UPDATE SET code=EXCLUDED.code,active=true RETURNING id',['qa-subject-science',a.id,'Science','SCI']);
  const teacher=await one<{id:string}>(tx,'INSERT INTO staff(id,school_id,employee_number,name,role_name,subject_snapshot,status) VALUES($1,$2,$3,$4,\'Teacher\',\'Science\',\'Active\') ON CONFLICT(school_id,employee_number) DO UPDATE SET name=EXCLUDED.name,role_name=\'Teacher\',subject_snapshot=\'Science\',status=\'Active\',updated_at=CURRENT_TIMESTAMP,version=staff.version+1 RETURNING id',['qa-teacher-science',a.id,'QA-T-001','[QA] Science Teacher']);
  const studentA=await one<{id:string}>(tx,'INSERT INTO students(id,school_id,admission_number,name,class_id,section_id,academic_year_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,\'Active\') ON CONFLICT(school_id,admission_number) DO UPDATE SET name=EXCLUDED.name,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,academic_year_id=EXCLUDED.academic_year_id,status=\'Active\',updated_at=CURRENT_TIMESTAMP,version=students.version+1 RETURNING id',['qa-student-a',a.id,'QA-S-001','[QA] Student A',klass.id,sectionA.id,year.id]);
  const studentB=await one<{id:string}>(tx,'INSERT INTO students(id,school_id,admission_number,name,class_id,section_id,academic_year_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,\'Active\') ON CONFLICT(school_id,admission_number) DO UPDATE SET name=EXCLUDED.name,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,academic_year_id=EXCLUDED.academic_year_id,status=\'Active\',updated_at=CURRENT_TIMESTAMP,version=students.version+1 RETURNING id',['qa-student-b',a.id,'QA-S-002','[QA] Student B',klass.id,sectionB.id,year.id]);
  const studentPeer=await one<{id:string}>(tx,'INSERT INTO students(id,school_id,admission_number,name,class_id,section_id,academic_year_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,\'Active\') ON CONFLICT(school_id,admission_number) DO UPDATE SET name=EXCLUDED.name,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,academic_year_id=EXCLUDED.academic_year_id,status=\'Active\',updated_at=CURRENT_TIMESTAMP,version=students.version+1 RETURNING id',['qa-student-a-peer',a.id,'QA-S-003','[QA] Student A Peer',klass.id,sectionA.id,year.id]);
  const guardian=await one<{id:string}>(tx,'INSERT INTO guardian_profiles(id,school_id,name,status) VALUES($1,$2,$3,\'Active\') ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,status=\'Active\',updated_at=CURRENT_TIMESTAMP,version=guardian_profiles.version+1 RETURNING id',['qa-parent-a',a.id,'[QA] Parent A']);
  const adminUser=await user(tx,{id:'qa-user-admin',schoolId:a.id,roleId:roleAdmin.id,username:'qa.admin',firstName:'[QA] School',lastName:'Administrator',passwordHash});
  const teacherUser=await user(tx,{id:'qa-user-teacher',schoolId:a.id,roleId:roleTeacher.id,username:'qa.teacher',firstName:'[QA] Science',lastName:'Teacher',passwordHash,teacherId:teacher.id});
  const studentUserA=await user(tx,{id:'qa-user-student-a',schoolId:a.id,roleId:roleStudent.id,username:'qa.student.a',firstName:'[QA] Student',lastName:'A',passwordHash,studentId:studentA.id});
  const studentUserB=await user(tx,{id:'qa-user-student-b',schoolId:a.id,roleId:roleStudent.id,username:'qa.student.b',firstName:'[QA] Student',lastName:'B',passwordHash,studentId:studentB.id});
  const parentUser=await user(tx,{id:'qa-user-parent-a',schoolId:a.id,roleId:roleParent.id,username:'qa.parent.a',firstName:'[QA] Parent',lastName:'A',passwordHash});
  await tx.query('INSERT INTO user_guardian_links(user_id,guardian_id,school_id) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET guardian_id=EXCLUDED.guardian_id,school_id=EXCLUDED.school_id',[parentUser.id,guardian.id,a.id]);
  await tx.query('INSERT INTO guardian_student_links(id,school_id,guardian_id,student_id,relationship,active) VALUES($1,$2,$3,$4,\'Guardian\',true) ON CONFLICT(school_id,guardian_id,student_id) DO UPDATE SET relationship=\'Guardian\',active=true',['qa-link-parent-a-student-a',a.id,guardian.id,studentA.id]);
  await tx.query('DELETE FROM guardian_student_links WHERE school_id=$1 AND guardian_id=$2 AND student_id<>$3 AND id LIKE \'qa-%\'',[a.id,guardian.id,studentA.id]);
  await tx.query('INSERT INTO teacher_assignments(id,school_id,teacher_id,academic_year_id,class_id,section_id,subject_id,assignment_type,active) VALUES($1,$2,$3,$4,$5,$6,$7,\'SubjectTeacher\',true) ON CONFLICT(id) DO UPDATE SET academic_year_id=EXCLUDED.academic_year_id,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,subject_id=EXCLUDED.subject_id,active=true,updated_at=CURRENT_TIMESTAMP,version=teacher_assignments.version+1',['qa-assignment-science-viii-a',a.id,teacher.id,year.id,klass.id,sectionA.id,subject.id]);
  await tx.query('DELETE FROM teacher_assignments WHERE school_id=$1 AND teacher_id=$2 AND id LIKE \'qa-%\' AND id<>$3',[a.id,teacher.id,'qa-assignment-science-viii-a']);
  for(const attendance of [{id:'qa-attendance-a',studentId:studentA.id,status:'Present'},{id:'qa-attendance-b',studentId:studentB.id,status:'Absent'}])await tx.query('INSERT INTO attendance_records(id,school_id,student_id,attendance_date,period,status,remark,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(school_id,student_id,attendance_date,period) DO UPDATE SET status=EXCLUDED.status,remark=EXCLUDED.remark,recorded_by=EXCLUDED.recorded_by,updated_at=CURRENT_TIMESTAMP,version=attendance_records.version+1',[attendance.id,a.id,attendance.studentId,'2026-09-01','Full Day',attendance.status,'Authorization QA fixture.',adminUser.id]);
  await tx.query('INSERT INTO classes(id,school_id,name,active) VALUES($1,$2,$3,true) ON CONFLICT(school_id,name) DO UPDATE SET active=true',['qa-school-b-class', 'qa-school-b','Control Class']);
  for(const period of [{id:'qa-period-1',name:'[QA] Period 1',start:'09:00',end:'09:45',order:1},{id:'qa-period-2',name:'[QA] Period 2',start:'10:00',end:'10:45',order:2}])await tx.query('INSERT INTO school_periods(id,school_id,name,period_type,start_time,end_time,duration_minutes,sort_order,active) VALUES($1,$2,$3,\'Teaching Period\',$4,$5,45,$6,true) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,start_time=EXCLUDED.start_time,end_time=EXCLUDED.end_time,duration_minutes=45,sort_order=EXCLUDED.sort_order,active=true,updated_at=CURRENT_TIMESTAMP,version=school_periods.version+1',[period.id,a.id,period.name,period.start,period.end,period.order]);
  for(const entry of [{id:'qa-timetable-a',sectionId:sectionA.id,period:'qa-period-1'},{id:'qa-timetable-b',sectionId:sectionB.id,period:'qa-period-2'}])await tx.query('INSERT INTO timetable_entries(id,school_id,academic_year_id,class_id,section_id,subject_id,teacher_id,day_of_week,period_key,room,start_time,end_time,notes,active) VALUES($1,$2,$3,$4,$5,$6,$7,\'Monday\',$8,\'QA Room\',\'09:00\',\'09:45\',\'Authorization QA fixture.\',true) ON CONFLICT(id) DO UPDATE SET academic_year_id=EXCLUDED.academic_year_id,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,subject_id=EXCLUDED.subject_id,teacher_id=EXCLUDED.teacher_id,day_of_week=EXCLUDED.day_of_week,period_key=EXCLUDED.period_key,room=EXCLUDED.room,notes=EXCLUDED.notes,active=true,updated_at=CURRENT_TIMESTAMP,version=timetable_entries.version+1',[entry.id,a.id,year.id,klass.id,entry.sectionId,subject.id,teacher.id,entry.period]);  for(const exam of [{id:'qa-exam-a',sectionId:sectionA.id,name:'[QA] VIII-A Science Exam'},{id:'qa-exam-b',sectionId:sectionB.id,name:'[QA] VIII-B Science Exam'}])await tx.query('INSERT INTO exam_records(id,school_id,academic_year_id,class_id,section_id,subject_id,name,exam_date,max_marks,passing_marks,state,published,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,\'2026-09-15\',100,40,\'Published\',true,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET academic_year_id=EXCLUDED.academic_year_id,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,subject_id=EXCLUDED.subject_id,name=EXCLUDED.name,state=\'Published\',published=true,published_at=CURRENT_TIMESTAMP,locked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,version=exam_records.version+1',[exam.id,a.id,year.id,klass.id,exam.sectionId,subject.id,exam.name]);
  for(const mark of [{id:'qa-mark-a',examId:'qa-exam-a',studentId:studentA.id,value:80},{id:'qa-mark-b',examId:'qa-exam-b',studentId:studentB.id,value:70}])await tx.query('INSERT INTO mark_records(id,school_id,exam_id,student_id,marks,absent,recorded_by) VALUES($1,$2,$3,$4,$5,false,$6) ON CONFLICT(school_id,exam_id,student_id) DO UPDATE SET marks=EXCLUDED.marks,absent=false,recorded_by=EXCLUDED.recorded_by,updated_at=CURRENT_TIMESTAMP,version=mark_records.version+1',[mark.id,a.id,mark.examId,mark.studentId,mark.value,adminUser.id]);  const feeStructureData={name:'[QA] Standard Fee',academicYear:'QA 2026-2027',applicableClass:'VIII',applicableSection:'',components:[{name:'Tuition',amount:1000}],dueDate:'2026-10-31',status:'Active',totalAmount:1000};
  await tx.query('INSERT INTO school_fee_structures(id,school_id,data,archived) VALUES($1,$2,$3,false) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,archived=false,updated_at=CURRENT_TIMESTAMP,version=school_fee_structures.version+1',['qa-fee-structure',a.id,JSON.stringify(feeStructureData)]);
  for(const studentId of [studentA.id,studentB.id])await tx.query('INSERT INTO school_fee_assignments(school_id,student_id,structure_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[a.id,studentId,'qa-fee-structure']);
  for(const payment of [{id:'qa-fee-payment-a',studentId:studentA.id,student:'QA-S-001',receipt:'QA-REC-A'},{id:'qa-fee-payment-b',studentId:studentB.id,student:'QA-S-002',receipt:'QA-REC-B'}]){const data={id:payment.id,receipt:payment.receipt,date:'2026-09-20',student:payment.student,feeStructureId:'qa-fee-structure',head:'Tuition',mode:'Cash',amount:1000,components:[{component:'Tuition',applicableAmount:1000,paidAmount:1000}]};await tx.query('INSERT INTO school_fee_payments(id,school_id,student_id,receipt_key,data,amount_minor,voided,mutation_key,request_fingerprint) VALUES($1,$2,$3,$4,$5,100000,false,$6,$7) ON CONFLICT(id) DO UPDATE SET student_id=EXCLUDED.student_id,receipt_key=EXCLUDED.receipt_key,data=EXCLUDED.data,amount_minor=EXCLUDED.amount_minor,voided=false,mutation_key=EXCLUDED.mutation_key,request_fingerprint=EXCLUDED.request_fingerprint,updated_at=CURRENT_TIMESTAMP,version=school_fee_payments.version+1',[payment.id,a.id,payment.studentId,payment.receipt.toLowerCase(),JSON.stringify(data),'qa-fee-mutation-'+payment.id,'qa-fee-fingerprint-'+payment.id]);}
  for(const leave of [{id:'qa-leave-a',studentId:studentA.id,applicant:'[QA] Student A',submitter:studentUserA.id,submitterName:'qa.student.a'},{id:'qa-leave-b',studentId:studentB.id,applicant:'[QA] Student B',submitter:studentUserB.id,submitterName:'qa.student.b'}]){const data={applicant:leave.applicant,applicantType:'Student',studentId:leave.studentId,staffId:null,type:'Medical Leave',from:'2026-10-10',to:'2026-10-11',reason:'Authorization QA fixture.',priority:'Normal',status:'Pending',decisionNote:'',submittedBy:leave.submitter,submittedByName:leave.submitterName,submittedAt:'2026-10-01T00:00:00.000Z'};await tx.query('INSERT INTO school_leave_requests(id,school_id,data,archived) VALUES($1,$2,$3,false) ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data,archived=false,updated_at=CURRENT_TIMESTAMP,version=school_leave_requests.version+1',[leave.id,a.id,JSON.stringify(data)]);}
  return{schoolId:a.id,yearId:year.id,classId:klass.id,sectionAId:sectionA.id,sectionBId:sectionB.id,subjectId:subject.id,teacherId:teacher.id,studentAId:studentA.id,studentBId:studentB.id,studentPeerId:studentPeer.id,guardianId:guardian.id,adminUserId:adminUser.id,teacherUserId:teacherUser.id,studentAUserId:studentUserA.id,studentBUserId:studentUserB.id,parentUserId:parentUser.id};
 });
}

async function reconcileAuthorization(db:Database,ids:Awaited<ReturnType<typeof reconcileCore>>){
 const principal:Principal={userId:ids.adminUserId,schoolId:ids.schoolId,roleId:'qa-account-role-admin',roleName:'[QA] School Administrator',teacherId:null,studentId:null,guardianId:null,permissions:[],username:'qa.admin'};
 await new WorkspaceService(db).syncFactories(principal,'authorization-qa-seed');
 return db.transaction(async tx=>{
  const groups={
   admin:await group(tx,ids.schoolId,'[QA] School Administrators','Administration',ids.adminUserId,'qa-group-admin'),
   teacher:await group(tx,ids.schoolId,'[QA] Teachers','Teachers',ids.adminUserId,'qa-group-teachers'),
   student:await group(tx,ids.schoolId,'[QA] Students','Students',ids.adminUserId,'qa-group-students'),
   parent:await group(tx,ids.schoolId,'[QA] Parents','Parents',ids.adminUserId,'qa-group-parents')
  };
  const memberships=[[groups.admin.id,ids.adminUserId],[groups.teacher.id,ids.teacherUserId],[groups.student.id,ids.studentAUserId],[groups.student.id,ids.studentBUserId],[groups.parent.id,ids.parentUserId]];
  for(const [groupId,userId] of memberships)await tx.query('INSERT INTO access_group_memberships(school_id,group_id,user_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,user_id) DO NOTHING',[ids.schoolId,groupId,userId,ids.adminUserId]);
  await tx.query('DELETE FROM access_group_memberships WHERE school_id=$1 AND group_id=ANY($2::text[]) AND user_id LIKE \'qa-%\' AND NOT ((group_id=$3 AND user_id=$4) OR (group_id=$5 AND user_id=$6) OR (group_id=$7 AND user_id=ANY($8::text[])) OR (group_id=$9 AND user_id=$10))',[ids.schoolId,Object.values(groups).map(x=>x.id),groups.admin.id,ids.adminUserId,groups.teacher.id,ids.teacherUserId,groups.student.id,[ids.studentAUserId,ids.studentBUserId],groups.parent.id,ids.parentUserId]);
  await tx.query('INSERT INTO access_group_global_roles(school_id,group_id,role_key,created_by) VALUES($1,$2,\'Setup Administration\',$3) ON CONFLICT(group_id,role_key) DO NOTHING',[ids.schoolId,groups.admin.id,ids.adminUserId]);
  const workspaces=(await tx.query<{id:string;workspaceKey:string}>('SELECT id,workspace_key AS "workspaceKey" FROM workspace_definitions WHERE school_id=$1 AND status<>\'Archived\'',[ids.schoolId])).rows;
  const byKey=new Map(workspaces.map(x=>[x.workspaceKey,x.id])),catalog=workspaceAuthorizationCatalog();
  const administrationWorkspaceKeys=new Set(['users','reports','access','school','portal','diagnostics','imports','workflows']);
  for(const workspaceKey of administrationWorkspaceKeys){
   const roleId='qa-role-admin-'+workspaceKey;
   await tx.query('DELETE FROM access_group_roles WHERE school_id=$1 AND group_id=$2 AND role_id=$3',[ids.schoolId,groups.admin.id,roleId]);
   await tx.query("UPDATE access_roles SET status='Archived',updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE school_id=$1 AND id=$2 AND status<>'Archived'",[ids.schoolId,roleId]);
  }
  for(const [workspaceKey,resources] of Object.entries(catalog)){
   if(administrationWorkspaceKeys.has(workspaceKey))continue;
   const workspaceId=byKey.get(workspaceKey);if(!workspaceId)continue;
   const role=await accessRole(tx,ids.schoolId,workspaceId,'[QA] Workspace Access '+workspaceKey,ids.adminUserId,'qa-role-admin-'+workspaceKey);
   await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);
   for(const resource of resources)for(const item of [...resource.actions,...resource.workflowPermissions])if(item.scopes.includes('ALL_WORKSPACE'))await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,$3,$4,\'ALL_WORKSPACE\',$5,\'System template\',$6) ON CONFLICT(role_id,resource_type,action_key,scope_key) DO UPDATE SET constraints=EXCLUDED.constraints,grant_source=EXCLUDED.grant_source',[ids.schoolId,role.id,resource.resourceType,item.action,JSON.stringify({viewDrafts:true,viewArchived:true,viewDeleted:true,viewHistoricalYears:true,viewConfidential:true,viewInternalNotes:true}),ids.adminUserId]);
   await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,groups.admin.id,role.id,ids.adminUserId]);
  }
  const homeworkWorkspaceId=byKey.get('homework');if(!homeworkWorkspaceId)throw new Error('Homework workspace factory is unavailable.');
  const roleSpecs=[
   {id:'qa-role-homework-teacher',name:'[QA] Access Set H1',groupId:groups.teacher.id,grants:[['record.view','ASSIGNED_TEACHING_CONTEXT'],['record.create','ASSIGNED_TEACHING_CONTEXT'],['record.update','ASSIGNED_TEACHING_CONTEXT'],['record.publish','ASSIGNED_TEACHING_CONTEXT'],['record.print','ASSIGNED_TEACHING_CONTEXT']]},
   {id:'qa-role-homework-student',name:'[QA] Access Set H2',groupId:groups.student.id,grants:[['record.view','DIRECT_RECIPIENT'],['record.acknowledge','DIRECT_RECIPIENT']]},
   {id:'qa-role-homework-parent',name:'[QA] Access Set H3',groupId:groups.parent.id,grants:[['record.view','CHILD_RECIPIENT']]}
  ] as const;
  for(const spec of roleSpecs){const role=await accessRole(tx,ids.schoolId,homeworkWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const [action,scope] of spec.grants)await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,\'homework\',$3,$4,\'{}\',\'System template\',$5)',[ids.schoolId,role.id,action,scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}
  for(const [roleId,scope] of [['qa-role-homework-teacher','ASSIGNED_TEACHING_CONTEXT'],['qa-role-homework-student','SELF'],['qa-role-homework-parent','CHILD_PERSONAL']] as const)await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,\'homework-acknowledgement\',\'acknowledgement.view_status\',$3,\'{}\',\'Explicit\',$4)',[ids.schoolId,roleId,scope,ids.adminUserId]);
  const studentsWorkspaceId=byKey.get('students');if(!studentsWorkspaceId)throw new Error('Students workspace factory is unavailable.');
  const studentRoleSpecs=[
   {id:'qa-role-students-assigned',name:'[QA] Access Set S1',groupId:groups.teacher.id,scope:'ASSIGNED_STUDENT'},
   {id:'qa-role-students-self',name:'[QA] Access Set S2',groupId:groups.student.id,scope:'SELF'},
   {id:'qa-role-students-child',name:'[QA] Access Set S3',groupId:groups.parent.id,scope:'CHILD_PERSONAL'}
  ] as const;
  for(const spec of studentRoleSpecs){const role=await accessRole(tx,ids.schoolId,studentsWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,\'student\',\'record.view\',$3,\'{}\',\'Explicit\',$4)',[ids.schoolId,role.id,spec.scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}  const relationshipRoleSpecs=[
   {id:'qa-role-core-staff',name:'[QA] Access Set C1',workspace:'staff',grants:[['staff','record.view','SELF'],['teaching-assignment','record.view','SELF']]},
   {id:'qa-role-core-classes',name:'[QA] Access Set C2',workspace:'classes',grants:[['class','record.view','ASSIGNED_CLASS']]},
   {id:'qa-role-core-sections',name:'[QA] Access Set C3',workspace:'sections',grants:[['section','record.view','ASSIGNED_SECTION']]},
   {id:'qa-role-core-subjects',name:'[QA] Access Set C4',workspace:'subjects',grants:[['subject','record.view','ASSIGNED_TEACHING_CONTEXT']]},
   {id:'qa-role-core-years',name:'[QA] Access Set C5',workspace:'academic-years',grants:[['academic-year','record.view','ASSIGNED_TEACHING_CONTEXT']]}
  ] as const;
  for(const spec of relationshipRoleSpecs){const workspaceId=byKey.get(spec.workspace);if(!workspaceId)throw new Error(spec.workspace+' workspace factory is unavailable.');const role=await accessRole(tx,ids.schoolId,workspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const [resource,action,scope] of spec.grants)await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,$3,$4,$5,\'{}\',\'Explicit\',$6)',[ids.schoolId,role.id,resource,action,scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,groups.teacher.id,role.id,ids.adminUserId])}
  const attendanceWorkspaceId=byKey.get('attendance');if(!attendanceWorkspaceId)throw new Error('Attendance workspace factory is unavailable.');
  const attendanceRoleSpecs=[
   {id:'qa-role-attendance-teacher',name:'[QA] Access Set A1',groupId:groups.teacher.id,grants:[['record.view','ASSIGNED_SECTION'],['record.create','ASSIGNED_SECTION'],['record.update','ASSIGNED_SECTION'],['record.print','ASSIGNED_SECTION']]},
   {id:'qa-role-attendance-student',name:'[QA] Access Set A2',groupId:groups.student.id,grants:[['record.view','SELF']]},
   {id:'qa-role-attendance-parent',name:'[QA] Access Set A3',groupId:groups.parent.id,grants:[['record.view','CHILD_PERSONAL']]}
  ] as const;
  for(const spec of attendanceRoleSpecs){const role=await accessRole(tx,ids.schoolId,attendanceWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const [action,scope] of spec.grants)await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,\'attendance-entry\',$3,$4,\'{}\',\'Explicit\',$5)',[ids.schoolId,role.id,action,scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}
  const timetableWorkspaceId=byKey.get('timetable');if(!timetableWorkspaceId)throw new Error('Timetable workspace factory is unavailable.');
  const timetableRoleSpecs=[
   {id:'qa-role-timetable-teacher',name:'[QA] Access Set T1',groupId:groups.teacher.id,entryGrants:[['record.view','ASSIGNED_TEACHING_CONTEXT'],['record.create','ASSIGNED_TEACHING_CONTEXT'],['record.update','ASSIGNED_TEACHING_CONTEXT'],['record.archive','ASSIGNED_TEACHING_CONTEXT'],['record.print','ASSIGNED_TEACHING_CONTEXT']]},
   {id:'qa-role-timetable-student',name:'[QA] Access Set T2',groupId:groups.student.id,entryGrants:[['record.view','SECTION']]},
   {id:'qa-role-timetable-parent',name:'[QA] Access Set T3',groupId:groups.parent.id,entryGrants:[['record.view','SECTION']]}
  ] as const;
  for(const spec of timetableRoleSpecs){const role=await accessRole(tx,ids.schoolId,timetableWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const [action,scope] of spec.entryGrants)await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,\'timetable-entry\',$3,$4,\'{}\',\'Explicit\',$5)',[ids.schoolId,role.id,action,scope,ids.adminUserId]);await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,\'timetable-period\',\'record.view\',\'ALL_WORKSPACE\',\'{}\',\'Explicit\',$3)',[ids.schoolId,role.id,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}  const examsWorkspaceId=byKey.get('exams-results');if(!examsWorkspaceId)throw new Error('Exams & Results workspace factory is unavailable.');
  const examRoleSpecs=[
   {id:'qa-role-exams-teacher',name:'[QA] Access Set E1',groupId:groups.teacher.id,grants:[['exam','record.view','ASSIGNED_TEACHING_CONTEXT'],['exam','record.create','ASSIGNED_TEACHING_CONTEXT'],['exam','record.update','ASSIGNED_TEACHING_CONTEXT'],['exam','record.archive','ASSIGNED_TEACHING_CONTEXT'],['exam','assessment.publish_results','ASSIGNED_TEACHING_CONTEXT'],['mark','record.view','ASSIGNED_TEACHING_CONTEXT'],['mark','assessment.enter_marks','ASSIGNED_TEACHING_CONTEXT'],['report-card','report.view','ASSIGNED_TEACHING_CONTEXT'],['report-card','assessment.publish_results','ASSIGNED_TEACHING_CONTEXT']]},
   {id:'qa-role-exams-student',name:'[QA] Access Set E2',groupId:groups.student.id,grants:[['exam','record.view','SECTION'],['mark','record.view','SELF'],['report-card','report.view','SELF']]},
   {id:'qa-role-exams-parent',name:'[QA] Access Set E3',groupId:groups.parent.id,grants:[['exam','record.view','SECTION'],['mark','record.view','CHILD_PERSONAL'],['report-card','report.view','CHILD_PERSONAL']]}
  ] as const;
  for(const spec of examRoleSpecs){const role=await accessRole(tx,ids.schoolId,examsWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const [resource,action,scope] of spec.grants)await tx.query('INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,$3,$4,$5,\'{}\',\'Explicit\',$6)',[ids.schoolId,role.id,resource,action,scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}  const feesWorkspaceId=byKey.get('fees-payments');if(!feesWorkspaceId)throw new Error('Fees & Payments workspace factory is unavailable.');
  const feeRoleSpecs=[
   {id:'qa-role-fees-student',name:'[QA] Access Set F1',groupId:groups.student.id,scope:'SELF'},
   {id:'qa-role-fees-parent',name:'[QA] Access Set F2',groupId:groups.parent.id,scope:'CHILD_PERSONAL'}
  ] as const;
  for(const spec of feeRoleSpecs){const role=await accessRole(tx,ids.schoolId,feesWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const resource of ['fee-payment','fee-assignment'])await tx.query("INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,$3,'record.view',$4,'{}','Explicit',$5)",[ids.schoolId,role.id,resource,spec.scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}
  const leaveWorkspaceId=byKey.get('leave-requests');if(!leaveWorkspaceId)throw new Error('Leave Requests workspace factory is unavailable.');
  const leaveRoleSpecs=[
   {id:'qa-role-leave-student',name:'[QA] Access Set L1',groupId:groups.student.id,scope:'SELF'},
   {id:'qa-role-leave-parent',name:'[QA] Access Set L2',groupId:groups.parent.id,scope:'CHILD_PERSONAL'}
  ] as const;
  for(const spec of leaveRoleSpecs){const role=await accessRole(tx,ids.schoolId,leaveWorkspaceId,spec.name,ids.adminUserId,spec.id);await tx.query('DELETE FROM access_role_grants WHERE school_id=$1 AND role_id=$2',[ids.schoolId,role.id]);for(const action of ['record.view','record.create','record.update','record.archive','attachment.view','attachment.download'])await tx.query("INSERT INTO access_role_grants(school_id,role_id,resource_type,action_key,scope_key,constraints,grant_source,created_by) VALUES($1,$2,'leave-request',$3,$4,'{}','Explicit',$5)",[ids.schoolId,role.id,action,spec.scope,ids.adminUserId]);await tx.query('INSERT INTO access_group_roles(school_id,group_id,role_id,created_by) VALUES($1,$2,$3,$4) ON CONFLICT(group_id,role_id) DO NOTHING',[ids.schoolId,spec.groupId,role.id,ids.adminUserId])}
  await tx.query('INSERT INTO specialist_operations_configuration(school_id,configuration,updated_by) VALUES($1,$2,$3) ON CONFLICT(school_id) DO UPDATE SET configuration=EXCLUDED.configuration,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP,version=specialist_operations_configuration.version+1',[ids.schoolId,JSON.stringify({enabled:true,assetRegister:true,assignments:true,maintenance:true,idCards:true,bulkIssue:true,replacementCards:true,verification:false}),ids.adminUserId]);
await tx.query('INSERT INTO access_control_settings(school_id,mode,authorization_version,updated_by) VALUES($1,\'Enforced\',2,$2) ON CONFLICT(school_id) DO UPDATE SET mode=\'Enforced\',authorization_version=access_control_settings.authorization_version+1,updated_by=$2,updated_at=CURRENT_TIMESTAMP,version=access_control_settings.version+1',[ids.schoolId,ids.adminUserId]);
  for(const homework of [
   {id:'qa-homework-a',sectionId:ids.sectionAId,title:'[QA] VIII-A Science Homework',teacherId:ids.teacherId,creator:ids.teacherUserId},
   {id:'qa-homework-b',sectionId:ids.sectionBId,title:'[QA] VIII-B Science Homework',teacherId:null,creator:ids.adminUserId}
  ]){await tx.query('INSERT INTO homework_records(id,school_id,academic_year_id,class_id,section_id,subject_id,teacher_id,title,instructions,assigned_date,due_date,status,created_by,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,CURRENT_DATE,CURRENT_DATE+7,\'Published\',$10,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET academic_year_id=EXCLUDED.academic_year_id,class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,subject_id=EXCLUDED.subject_id,teacher_id=EXCLUDED.teacher_id,title=EXCLUDED.title,instructions=EXCLUDED.instructions,status=\'Published\',created_by=EXCLUDED.created_by,published_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,version=homework_records.version+1',[homework.id,ids.schoolId,ids.yearId,ids.classId,homework.sectionId,ids.subjectId,homework.teacherId,homework.title,'Authorization QA fixture. Acknowledgement workflow is enabled; submissions are not implemented in the current server.',homework.creator]);await tx.query('INSERT INTO record_access_controls(school_id,workspace_id,record_id,owner_user_id,assigned_user_id,audience_type,class_id,section_id,created_by) VALUES($1,$2,$3,$4,$5,\'Section\',$6,$7,$8) ON CONFLICT(school_id,workspace_id,record_id) DO UPDATE SET owner_user_id=EXCLUDED.owner_user_id,assigned_user_id=EXCLUDED.assigned_user_id,audience_type=\'Section\',class_id=EXCLUDED.class_id,section_id=EXCLUDED.section_id,archived=false,updated_at=CURRENT_TIMESTAMP,version=record_access_controls.version+1',[ids.schoolId,homeworkWorkspaceId,homework.id,homework.creator,homework.id==='qa-homework-a'?ids.teacherUserId:null,ids.classId,homework.sectionId,ids.adminUserId])}
  for(const acknowledgement of [{id:'qa-ack-a',homeworkId:'qa-homework-a',studentId:ids.studentAId,status:'SEEN'},{id:'qa-ack-a-peer',homeworkId:'qa-homework-a',studentId:ids.studentPeerId,status:'COMPLETED'},{id:'qa-ack-b',homeworkId:'qa-homework-b',studentId:ids.studentBId,status:'SEEN'}])await tx.query('INSERT INTO homework_acknowledgements(id,school_id,homework_id,student_id,status_code,student_note,acknowledged_at) VALUES($1,$2,$3,$4,$5,\'Authorization QA fixture.\',CURRENT_TIMESTAMP) ON CONFLICT(school_id,homework_id,student_id) DO UPDATE SET status_code=EXCLUDED.status_code,student_note=EXCLUDED.student_note,acknowledged_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,version=homework_acknowledgements.version+1',[acknowledgement.id,ids.schoolId,acknowledgement.homeworkId,acknowledgement.studentId,acknowledgement.status]);
  return{groups:Object.fromEntries(Object.entries(groups).map(([key,value])=>[key,value.id])),homework:{a:'qa-homework-a',b:'qa-homework-b'}};
 });
}

export async function seedAuthorizationQa(env:NodeJS.ProcessEnv=process.env){
 assertAuthorizationQaSeedEnvironment(env);const config=loadConfig(env),db=createPostgresDatabase(config.databaseUrl);
 try{
  const version=Number((await db.query<{version:number}>('SELECT COALESCE(max(version),0)::int AS version FROM migration_history')).rows[0]?.version||0);
  if(version!==DATABASE_SCHEMA_VERSION)throw new Error('Authorization QA seed requires schema '+DATABASE_SCHEMA_VERSION+'; current schema is '+version+'. Run the normal migration process in the QA database first.');
  const passwordHash=await hashPassword(env.QA_TEST_PASSWORD!);
  const ids=await reconcileCore(db,passwordHash),authorization=await reconcileAuthorization(db,ids);
  return{mode:process.argv.includes('--reconcile')?'reconcile':'seed',fixtureVersion:AUTHORIZATION_QA_FIXTURE_VERSION,schoolId:ids.schoolId,users:{admin:ids.adminUserId,teacher:ids.teacherUserId,studentA:ids.studentAUserId,studentB:ids.studentBUserId,parentA:ids.parentUserId},relationships:{teacherAssignment:'qa-assignment-science-viii-a',parentStudent:'qa-link-parent-a-student-a'},authorization,...authorization};
 }finally{await db.close()}
}

const entry=process.argv[1]?pathToFileURL(process.argv[1]).href:'';
if(import.meta.url===entry)seedAuthorizationQa().then(result=>{console.log(JSON.stringify(result,null,2))}).catch(error=>{console.error('Authorization QA seed failed: '+(error instanceof Error?error.message:String(error)));process.exitCode=1});
