import {pathToFileURL} from 'node:url';
import {assertAuthorizationQaSeedEnvironment} from './seed-authorization-qa.js';

type Identity={username:string;visible:string[];allowed:string[];denied:string[];visibleStudents:string[];allowedStudents:string[];deniedStudents:string[];coreAllowed:boolean};
const identities:Identity[]=[
 {username:'qa.admin',visible:['[QA] VIII-A Science Homework','[QA] VIII-B Science Homework'],allowed:['qa-homework-a','qa-homework-b'],denied:[],visibleStudents:['[QA] Student A','[QA] Student A Peer','[QA] Student B'],allowedStudents:['qa-student-a','qa-student-b'],deniedStudents:[],coreAllowed:true},
 {username:'qa.teacher',visible:['[QA] VIII-A Science Homework'],allowed:['qa-homework-a'],denied:['qa-homework-b'],visibleStudents:['[QA] Student A','[QA] Student A Peer'],allowedStudents:['qa-student-a'],deniedStudents:['qa-student-b'],coreAllowed:true},
 {username:'qa.student.a',visible:['[QA] VIII-A Science Homework'],allowed:['qa-homework-a'],denied:['qa-homework-b'],visibleStudents:['[QA] Student A'],allowedStudents:['qa-student-a'],deniedStudents:['qa-student-b'],coreAllowed:false},
 {username:'qa.student.b',visible:['[QA] VIII-B Science Homework'],allowed:['qa-homework-b'],denied:['qa-homework-a'],visibleStudents:['[QA] Student B'],allowedStudents:['qa-student-b'],deniedStudents:['qa-student-a'],coreAllowed:false},
 {username:'qa.parent.a',visible:['[QA] VIII-A Science Homework'],allowed:['qa-homework-a'],denied:['qa-homework-b'],visibleStudents:['[QA] Student A'],allowedStudents:['qa-student-a'],deniedStudents:['qa-student-b'],coreAllowed:false}
];

async function json(url:string,init:RequestInit={}){
 const response=await fetch(url,init),body=await response.json().catch(()=>({}));
 return{response,body};
}
function same(left:string[],right:string[]){return [...left].sort().join('|')===[...right].sort().join('|')}

export async function verifyAuthorizationQa(env:NodeJS.ProcessEnv=process.env){
 assertAuthorizationQaSeedEnvironment(env);
 const base=String(env.QA_BASE_URL||'http://127.0.0.1:4010').replace(/\/$/,'')+'/api/v1';
 const schoolSlug=String(env.QA_SCHOOL_SLUG||'qa-school'),password=env.QA_TEST_PASSWORD!;
 let scenarios=0;
 const results=[] as Array<{username:string;role:string;permissions:number;visible:string[];visibleStudents:string[]}>;
 for(const identity of identities){
  const login=await json(base+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({schoolSlug,username:identity.username,password})});
  if(!login.response.ok)throw new Error(identity.username+' authentication failed with HTTP '+login.response.status);
  scenarios++;
  const cookie=login.response.headers.get('set-cookie')?.split(';')[0];
  if(!cookie)throw new Error(identity.username+' login did not return a session cookie.');
  const headers={cookie},writeHeaders={...headers,'content-type':'application/json','x-csrf-token':String((login.body as any)?.data?.csrfToken||'')};
  const list=await json(base+'/homework-workspace',{headers});
  if(!list.response.ok)throw new Error(identity.username+' Homework list failed with HTTP '+list.response.status);
  const visible=(list.body as any)?.data?.items?.map((item:any)=>String(item.title))||[];
  if(!same(visible,identity.visible))throw new Error(identity.username+' Homework visibility mismatch: '+visible.join(', '));
  scenarios++;
  const acknowledgementExpected:Record<string,Record<string,string[]>>={'qa.admin':{'qa-homework-a':['qa-ack-a','qa-ack-a-peer'],'qa-homework-b':['qa-ack-b']},'qa.teacher':{'qa-homework-a':['qa-ack-a','qa-ack-a-peer']},'qa.student.a':{'qa-homework-a':['qa-ack-a']},'qa.student.b':{'qa-homework-b':['qa-ack-b']},'qa.parent.a':{'qa-homework-a':['qa-ack-a']}};for(const recordId of identity.allowed){const result=await json(base+'/homework-workspace/'+encodeURIComponent(recordId),{headers});if(!result.response.ok)throw new Error(identity.username+' expected access to '+recordId+' but received HTTP '+result.response.status);const acknowledgementIds=((result.body as any)?.data?.acknowledgements||[]).map((item:any)=>String(item.id));if(!same(acknowledgementIds,acknowledgementExpected[identity.username]?.[recordId]||[]))throw new Error(identity.username+' acknowledgement status visibility mismatch for '+recordId+': '+acknowledgementIds.join(', '));scenarios++}
  for(const recordId of identity.denied){const result=await json(base+'/homework-workspace/'+encodeURIComponent(recordId),{headers});if(![403,404].includes(result.response.status))throw new Error(identity.username+' expected denial for '+recordId+' but received HTTP '+result.response.status);scenarios++}
  const studentList=await json(base+'/students?page=1&pageSize=20',{headers});if(!studentList.response.ok)throw new Error(identity.username+' Students list failed with HTTP '+studentList.response.status);const visibleStudents=(studentList.body as any)?.data?.items?.map((item:any)=>String(item.name))||[];if(!same(visibleStudents,identity.visibleStudents))throw new Error(identity.username+' Student visibility mismatch: '+visibleStudents.join(', '));scenarios++;
  for(const recordId of identity.allowedStudents){const result=await json(base+'/students/'+encodeURIComponent(recordId),{headers});if(!result.response.ok)throw new Error(identity.username+' expected Student access to '+recordId+' but received HTTP '+result.response.status);scenarios++}
  for(const recordId of identity.deniedStudents){const result=await json(base+'/students/'+encodeURIComponent(recordId),{headers});if(![403,404].includes(result.response.status))throw new Error(identity.username+' expected Student denial for '+recordId+' but received HTTP '+result.response.status);scenarios++}
  const attendanceExpected:Record<string,string[]>={'qa.admin':['qa-attendance-a','qa-attendance-b'],'qa.teacher':['qa-attendance-a'],'qa.student.a':['qa-attendance-a'],'qa.student.b':['qa-attendance-b'],'qa.parent.a':['qa-attendance-a']};const attendance=await json(base+'/academic/attendance?date=2026-09-01&period=Full%20Day',{headers});if(!attendance.response.ok)throw new Error(identity.username+' Attendance list failed with HTTP '+attendance.response.status);const attendanceIds=((attendance.body as any)?.data?.items||[]).map((item:any)=>String(item.id));if(!same(attendanceIds,attendanceExpected[identity.username]||[]))throw new Error(identity.username+' Attendance visibility mismatch: '+attendanceIds.join(', '));scenarios++;
  const ownAttendance=(attendance.body as any)?.data?.items?.[0];if(identity.username==='qa.admin'||identity.username==='qa.teacher'){const update=await json(base+'/academic/attendance',{method:'PUT',headers:writeHeaders,body:JSON.stringify({date:'2026-09-01',period:'Full Day',rows:[{studentId:'qa-student-a',status:'Present',remark:'Authorization QA fixture.',version:Number(ownAttendance?.version)}]})});if(!update.response.ok)throw new Error(identity.username+' expected Attendance update access but received HTTP '+update.response.status);scenarios++}else{const studentId=identity.username==='qa.student.b'?'qa-student-b':'qa-student-a',update=await json(base+'/academic/attendance',{method:'PUT',headers:writeHeaders,body:JSON.stringify({date:'2026-09-01',period:'Full Day',rows:[{studentId,status:studentId==='qa-student-b'?'Absent':'Present',remark:'Authorization QA fixture.',version:Number(ownAttendance?.version)}]})});if(update.response.status!==403)throw new Error(identity.username+' expected Attendance update denial but received HTTP '+update.response.status);scenarios++}const print=await json(base+'/academic/attendance/print-event',{method:'POST',headers:writeHeaders,body:'{}'}),printAllowed=identity.username==='qa.admin'||identity.username==='qa.teacher';if(printAllowed&&!print.response.ok)throw new Error(identity.username+' expected Attendance print access but received HTTP '+print.response.status);if(!printAllowed&&print.response.status!==403)throw new Error(identity.username+' expected Attendance print denial but received HTTP '+print.response.status);scenarios++;
  const timetableExpected:Record<string,string[]>={'qa.admin':['qa-timetable-a','qa-timetable-b'],'qa.teacher':['qa-timetable-a'],'qa.student.a':['qa-timetable-a'],'qa.student.b':['qa-timetable-b'],'qa.parent.a':['qa-timetable-a']};
  const timetable=await json(base+'/academic/timetable',{headers});if(!timetable.response.ok)throw new Error(identity.username+' Timetable list failed with HTTP '+timetable.response.status);const timetableIds=((timetable.body as any)?.data?.items||[]).map((item:any)=>String(item.id));if(!same(timetableIds,timetableExpected[identity.username]||[]))throw new Error(identity.username+' Timetable visibility mismatch: '+timetableIds.join(', '));scenarios++;
  const periods=await json(base+'/academic/timetable-periods',{headers});if(!periods.response.ok)throw new Error(identity.username+' Timetable period reference failed with HTTP '+periods.response.status);const periodIds=((periods.body as any)?.data?.items||[]).map((item:any)=>String(item.id));if(!same(periodIds,['qa-period-1','qa-period-2']))throw new Error(identity.username+' Timetable period visibility mismatch: '+periodIds.join(', '));scenarios++;
  const timetablePrint=await json(base+'/academic/timetable/print-event',{method:'POST',headers:writeHeaders,body:'{}'}),timetablePrintAllowed=identity.username==='qa.admin'||identity.username==='qa.teacher';if(timetablePrintAllowed&&!timetablePrint.response.ok)throw new Error(identity.username+' expected Timetable print access but received HTTP '+timetablePrint.response.status);if(!timetablePrintAllowed&&timetablePrint.response.status!==403)throw new Error(identity.username+' expected Timetable print denial but received HTTP '+timetablePrint.response.status);scenarios++;
  if(identity.username==='qa.teacher'){
   const own=((timetable.body as any)?.data?.items||[]).find((item:any)=>item.id==='qa-timetable-a');const update=await json(base+'/academic/timetable/qa-timetable-a',{method:'PATCH',headers:writeHeaders,body:JSON.stringify({notes:'Authorization QA verified.',version:Number(own?.version)})});if(!update.response.ok)throw new Error('qa.teacher expected Timetable update access but received HTTP '+update.response.status);scenarios++;
   const move=await json(base+'/academic/timetable/qa-timetable-a',{method:'PATCH',headers:writeHeaders,body:JSON.stringify({sectionId:'qa-section-viii-b',version:Number((update.body as any)?.data?.version)})});if(move.response.status!==403)throw new Error('qa.teacher expected Timetable cross-section update denial but received HTTP '+move.response.status);scenarios++;
   const create=await json(base+'/academic/timetable',{method:'POST',headers:writeHeaders,body:JSON.stringify({academicYearId:'qa-year-current',classId:'qa-class-viii',sectionId:'qa-section-viii-a',subjectId:'qa-subject-science',teacherId:'qa-teacher-science',day:'Tuesday',periodKey:'qa-period-1',room:'QA Room',notes:'Temporary authorization verification.'})});if(!create.response.ok)throw new Error('qa.teacher expected Timetable create access but received HTTP '+create.response.status);scenarios++;const created=(create.body as any)?.data;
   const archive=await json(base+'/academic/timetable/'+encodeURIComponent(String(created?.id))+'/deactivate',{method:'POST',headers:writeHeaders,body:JSON.stringify({version:Number(created?.version)})});if(!archive.response.ok)throw new Error('qa.teacher expected Timetable archive access but received HTTP '+archive.response.status);scenarios++;
   const deniedCreate=await json(base+'/academic/timetable',{method:'POST',headers:writeHeaders,body:JSON.stringify({academicYearId:'qa-year-current',classId:'qa-class-viii',sectionId:'qa-section-viii-b',subjectId:'qa-subject-science',teacherId:'qa-teacher-science',day:'Wednesday',periodKey:'qa-period-1',room:'QA Room'})});if(deniedCreate.response.status!==403)throw new Error('qa.teacher expected Timetable VIII-B create denial but received HTTP '+deniedCreate.response.status);scenarios++;
  }  const examExpected:Record<string,string[]>={'qa.admin':['qa-exam-a','qa-exam-b'],'qa.teacher':['qa-exam-a'],'qa.student.a':['qa-exam-a'],'qa.student.b':['qa-exam-b'],'qa.parent.a':['qa-exam-a']};const exams=await json(base+'/academic/exams',{headers});if(!exams.response.ok)throw new Error(identity.username+' Exams list failed with HTTP '+exams.response.status);const examIds=((exams.body as any)?.data?.items||[]).map((item:any)=>String(item.id)).filter((id:string)=>id==='qa-exam-a'||id==='qa-exam-b');if(!same(examIds,examExpected[identity.username]||[]))throw new Error(identity.username+' Exams visibility mismatch: '+examIds.join(', '));scenarios++;
  const reportStudent=identity.username==='qa.student.b'?'qa-student-b':'qa-student-a',report=await json(base+'/academic/report-cards/'+reportStudent+'?academicYearId=qa-year-current',{headers}),teacherReportDenied=identity.username==='qa.teacher';if(teacherReportDenied&&![403,404].includes(report.response.status))throw new Error('qa.teacher subject assignment must not expose a whole report card.');if(!teacherReportDenied&&!report.response.ok)throw new Error(identity.username+' expected own/authorized report-card access but received HTTP '+report.response.status);scenarios++;const deniedReportStudent=reportStudent==='qa-student-a'?'qa-student-b':'qa-student-a',deniedReport=await json(base+'/academic/report-cards/'+deniedReportStudent+'?academicYearId=qa-year-current',{headers});const reportAll=identity.username==='qa.admin';if(reportAll&&!deniedReport.response.ok)throw new Error('qa.admin expected both report cards but received HTTP '+deniedReport.response.status);if(!reportAll&&![403,404].includes(deniedReport.response.status))throw new Error(identity.username+' expected unrelated report-card denial but received HTTP '+deniedReport.response.status);scenarios++;
  const examA=((exams.body as any)?.data?.items||[]).find((item:any)=>item.id==='qa-exam-a');
  if(identity.username==='qa.admin'){
   const correction=await json(base+'/academic/exams/qa-exam-a/correction',{method:'POST',headers:writeHeaders,body:JSON.stringify({version:Number(examA?.version),reason:'Authorization QA correction verification.'})});if(!correction.response.ok)throw new Error('qa.admin expected Exam correction access but received HTTP '+correction.response.status);scenarios++;
   const publish=await json(base+'/academic/exams/qa-exam-a/publish',{method:'POST',headers:writeHeaders,body:JSON.stringify({version:Number((correction.body as any)?.data?.version)})});if(!publish.response.ok)throw new Error('qa.admin expected Exam publish access but received HTTP '+publish.response.status);scenarios++;
  }
  if(identity.username==='qa.teacher'){
   const correction=await json(base+'/academic/exams/qa-exam-a/correction',{method:'POST',headers:writeHeaders,body:JSON.stringify({version:Number(examA?.version),reason:'Authorization QA denied correction check.'})});if(correction.response.status!==403)throw new Error('qa.teacher expected Exam correction denial but received HTTP '+correction.response.status);scenarios++;
  }
  if(identity.username==='qa.teacher'){
   const createdExam=await json(base+'/academic/exams',{method:'POST',headers:writeHeaders,body:JSON.stringify({academicYearId:'qa-year-current',classId:'qa-class-viii',sectionId:'qa-section-viii-a',subjectId:'qa-subject-science',name:'[QA] Temporary Exam',examDate:'2026-10-01',maxMarks:100,passingMarks:40})});if(!createdExam.response.ok)throw new Error('qa.teacher expected Exam create access but received HTTP '+createdExam.response.status);scenarios++;let created=(createdExam.body as any)?.data;
   const updatedExam=await json(base+'/academic/exams/'+encodeURIComponent(String(created?.id)),{method:'PATCH',headers:writeHeaders,body:JSON.stringify({name:'[QA] Temporary Exam Updated',version:Number(created?.version)})});if(!updatedExam.response.ok)throw new Error('qa.teacher expected Exam update access but received HTTP '+updatedExam.response.status);scenarios++;created=(updatedExam.body as any)?.data;
   const marks=await json(base+'/academic/marks',{method:'PUT',headers:writeHeaders,body:JSON.stringify({examId:created.id,examVersion:created.version,rows:[{studentId:'qa-student-a',marks:75,absent:false}]})});if(!marks.response.ok)throw new Error('qa.teacher expected Marks entry access but received HTTP '+marks.response.status+': '+JSON.stringify(marks.body));scenarios++;
   const archivedExam=await json(base+'/academic/exams/'+encodeURIComponent(String(created.id))+'/archive',{method:'POST',headers:writeHeaders,body:JSON.stringify({version:Number(created.version)})});if(!archivedExam.response.ok)throw new Error('qa.teacher expected Exam archive access but received HTTP '+archivedExam.response.status);scenarios++;
   const deniedExam=await json(base+'/academic/exams',{method:'POST',headers:writeHeaders,body:JSON.stringify({academicYearId:'qa-year-current',classId:'qa-class-viii',sectionId:'qa-section-viii-b',subjectId:'qa-subject-science',name:'[QA] Denied Exam',examDate:'2026-10-02',maxMarks:100,passingMarks:40})});if(deniedExam.response.status!==403)throw new Error('qa.teacher expected VIII-B Exam create denial but received HTTP '+deniedExam.response.status);scenarios++;
  }
  const fees=await json(base+'/fees',{headers}),feesAllowed=identity.username!=='qa.teacher';
  if(!feesAllowed){if(fees.response.status!==403)throw new Error('qa.teacher expected Fees denial but received HTTP '+fees.response.status)}
  else{
   if(!fees.response.ok)throw new Error(identity.username+' Fees list failed with HTTP '+fees.response.status);
   const feeData=(fees.body as any)?.data||{},paymentIds=(feeData.payments||[]).map((item:any)=>String(item.id)).filter((id:string)=>id==='qa-fee-payment-a'||id==='qa-fee-payment-b'),studentIds=(feeData.students||[]).map((item:any)=>String(item.id)).filter((id:string)=>id==='qa-student-a'||id==='qa-student-b'),assignmentIds=(feeData.assignments||[]).map((item:any)=>String(item.id)).filter((id:string)=>id.startsWith('qa-student-')),expectedFees=identity.username==='qa.admin'?['qa-fee-payment-a','qa-fee-payment-b']:identity.username==='qa.student.b'?['qa-fee-payment-b']:['qa-fee-payment-a'],expectedStudents=identity.username==='qa.admin'?['qa-student-a','qa-student-b']:identity.username==='qa.student.b'?['qa-student-b']:['qa-student-a'];
   if(!same(paymentIds,expectedFees))throw new Error(identity.username+' Fees payment visibility mismatch: '+paymentIds.join(', '));
   if(!same(studentIds,expectedStudents))throw new Error(identity.username+' Fees student visibility mismatch: '+studentIds.join(', '));
   if(assignmentIds.length!==expectedStudents.length||!assignmentIds.every((id:string)=>expectedStudents.some(studentId=>id.startsWith(studentId+':'))))throw new Error(identity.username+' Fees assignment visibility mismatch: '+assignmentIds.join(', '));
   const structureIds=(feeData.structures||[]).map((item:any)=>String(item.id)).filter((id:string)=>id==='qa-fee-structure');if(identity.username==='qa.admin'?!same(structureIds,['qa-fee-structure']):structureIds.length!==0)throw new Error(identity.username+' Fees structure visibility mismatch: '+structureIds.join(', '));
  }
  scenarios++;
  const leave=await json(base+'/leave-workspace',{headers}),leaveAllowed=identity.username!=='qa.teacher';
  if(!leaveAllowed){if(leave.response.status!==403)throw new Error('qa.teacher expected Leave denial but received HTTP '+leave.response.status)}
  else{
   if(!leave.response.ok)throw new Error(identity.username+' Leave list failed with HTTP '+leave.response.status);
   const leaveData=(leave.body as any)?.data||{},leaveIds=(leaveData.items||[]).map((item:any)=>String(item.id)).filter((id:string)=>id==='qa-leave-a'||id==='qa-leave-b'),expectedLeaves=identity.username==='qa.admin'?['qa-leave-a','qa-leave-b']:identity.username==='qa.student.b'?['qa-leave-b']:['qa-leave-a'];
   if(!same(leaveIds,expectedLeaves))throw new Error(identity.username+' Leave visibility mismatch: '+leaveIds.join(', '));
   const refIds=(leaveData.refs||[]).map((item:any)=>String(item.id)).filter((id:string)=>id==='qa-student-a'||id==='qa-student-b'),expectedRefs=identity.username==='qa.admin'?['qa-student-a','qa-student-b']:identity.username==='qa.student.b'?['qa-student-b']:['qa-student-a'];if(!same(refIds,expectedRefs))throw new Error(identity.username+' Leave applicant choices mismatch: '+refIds.join(', '));
  }
  scenarios++;
  const specialist=await json(base+'/specialist-operations',{headers}),specialistAllowed=identity.username==='qa.admin';if(specialistAllowed&&!specialist.response.ok)throw new Error('qa.admin expected Assets and ID Cards access but received HTTP '+specialist.response.status);if(!specialistAllowed&&specialist.response.status!==403)throw new Error(identity.username+' expected Assets and ID Cards denial but received HTTP '+specialist.response.status);scenarios++;
  const corePaths=['staff','classes','sections','subjects','academic-years','teacher-assignments'];for(const path of corePaths){const result=await json(base+'/'+path,{headers});if(identity.coreAllowed&&!result.response.ok)throw new Error(identity.username+' expected '+path+' access but received HTTP '+result.response.status);if(!identity.coreAllowed&&![403,404].includes(result.response.status))throw new Error(identity.username+' expected '+path+' denial but received HTTP '+result.response.status);if(identity.username==='qa.teacher'&&result.response.ok){const ids=((result.body as any)?.data?.items||[]).map((item:any)=>String(item.id)),expected:Record<string,string[]>={staff:['qa-teacher-science'],classes:['qa-class-viii'],sections:['qa-section-viii-a'],subjects:['qa-subject-science'],'academic-years':['qa-year-current'],'teacher-assignments':['qa-assignment-science-viii-a']};if(!same(ids,expected[path]))throw new Error('qa.teacher '+path+' relationship scope mismatch: '+ids.join(', '))}scenarios++}  results.push({username:identity.username,role:String((login.body as any)?.data?.user?.role||''),permissions:Array.isArray((login.body as any)?.data?.user?.permissions)?(login.body as any).data.user.permissions.length:0,visible,visibleStudents});
 }
 return{baseUrl:base,schoolSlug,scenarioCount:scenarios,passed:scenarios,identities:results};
}

const entry=process.argv[1]?pathToFileURL(process.argv[1]).href:'';
if(import.meta.url===entry)verifyAuthorizationQa().then(result=>console.log(JSON.stringify(result,null,2))).catch(error=>{console.error('Authorization QA verification failed: '+(error instanceof Error?error.message:String(error)));process.exitCode=1});